### ISSUE TITLE
KeyError: 'dsInfo'，but indicater“INFO Two factor authentication cookie generated. Sync should now be successful”

### ISSUE THREAD

**Issue by micawberism1** [boredazfcuk/docker-icloudpd#117]
root@Tuzi:~# docker exec -it iCloud_Tuzi sync-icloud.sh --Initialise

2021-12-09 19:54:11 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2021-12-09 19:54:11 INFO     ***** https://github.com/boredazfcuk/docker-icloudpd *****
2021-12-09 19:54:11 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/11/26_16:44 *****
2021-12-09 19:54:11 INFO     ***** /usr/local/bin/sync-icloud.sh hash: 46d834fef2282db929063a297c893740 *****
2021-12-09 19:54:11 INFO     Alpine Linux 3.13.5
2021-12-09 19:54:11 INFO     Python version: 3.8.10
2021-12-09 19:54:11 INFO     icloudpd version: 1.7.2
2021-12-09 19:54:13 INFO     pyicloud-ipd version: 0.10.1
2021-12-09 19:54:16 INFO     Running user id: 0
2021-12-09 19:54:16 INFO     Running group id: 0
2021-12-09 19:54:16 INFO     Local user: Tuzi:1026
2021-12-09 19:54:16 INFO     Local group: users:100
2021-12-09 19:54:16 INFO     Force GID: False
2021-12-09 19:54:16 INFO     LAN IP Address: 172.17.0.4
2021-12-09 19:54:16 INFO     Default gateway: 172.17.0.1
2021-12-09 19:54:16 INFO     DNS server: 192.168.50.1
2021-12-09 19:54:16 INFO     DNS lookup for icloud.com: 17.253.144.10
2021-12-09 19:54:27 INFO     Route check to icloud.com successful
2021-12-09 19:54:27 INFO     Apple ID: micawberism@live.com
2021-12-09 19:54:27 INFO     Authentication Type: 2FA
2021-12-09 19:54:27 INFO     Cookie path: /config/micawberismlivecom
2021-12-09 19:54:27 INFO     Cookie expiry notification period: 7
2021-12-09 19:54:27 INFO     Download destination directory: /mnt/Photos/iCloud
2021-12-09 19:54:27 INFO     Folder structure: {:%Y/%m}
2021-12-09 19:54:27 INFO     Directory permissions: 750
2021-12-09 19:54:27 INFO     File permissions: 640
2021-12-09 19:54:27 INFO     Synchronisation interval: 43200
2021-12-09 19:54:27 INFO     Synchronisation delay (minutes): 0
2021-12-09 19:54:27 INFO     Time zone: Asia/Shanghai
2021-12-09 19:54:27 INFO     Set EXIF date/time: False
2021-12-09 19:54:27 INFO     Auto delete: False
2021-12-09 19:54:27 INFO     Photo size: original
2021-12-09 19:54:27 INFO     Skip download check: False
2021-12-09 19:54:27 INFO     Skip live photos: False
2021-12-09 19:54:27 INFO     Number of most recently added photos to download: Download All Photos
2021-12-09 19:54:27 INFO     Stop downloading when prexisiting files count is: Download All Photos
2021-12-09 19:54:27 INFO     Live photo size: original
2021-12-09 19:54:27 INFO     Skip videos: False
2021-12-09 19:54:27 INFO     Convert HEIC to JPEG: False
2021-12-09 19:54:27 INFO     JPEG conversion quality: 90
2021-12-09 19:54:27 INFO     Downloading from: icloud.com
2021-12-09 19:54:28 INFO     Script launch parameters: --Initialise
2021-12-09 19:54:28 INFO     Group, users:100, already created
2021-12-09 19:54:28 INFO     User, Tuzi:1026, already created
2021-12-09 19:54:28 INFO     Set owner, Tuzi, on iCloud directory, if required
2021-12-09 19:54:28 INFO     Set group, users, on iCloud directory, if required
2021-12-09 19:54:28 INFO     Correct owner on icloudpd temp directory, if required
2021-12-09 19:54:28 INFO     Correct group on icloudpd temp directory, if required
2021-12-09 19:54:28 INFO     Correct owner on config directory, if required
2021-12-09 19:54:28 INFO     Correct group on config directory, if required
2021-12-09 19:54:28 INFO     Correct owner on keyring directory, if required
2021-12-09 19:54:28 INFO     Correct group on keyring directory, if required
2021-12-09 19:54:28 INFO     Set 750 permissions on iCloud directories, if required
2021-12-09 19:54:28 INFO     Set 640 permissions on iCloud files, if required
2021-12-09 19:54:28 INFO     Configure password
2021-12-09 19:54:28 INFO     Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for micawberism@live.com:
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
2021-12-09 19:54:52 INFO     Correct owner on config directory, if required
2021-12-09 19:54:52 INFO     Correct group on config directory, if required
2021-12-09 19:54:52 INFO     Generate 2FA cookie using password stored in keyring file.
iCloud Password:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for micawberism@live.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
2021-12-09 19:55:14 INFO     Two factor authentication cookie generated. Sync should now be successful.

**Comment by boredazfcuk** [comment]
Are you based in mainland China? If yes, then you are likely running into this issue: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/392

Set the variable `icloud_china=True` which will use icloud.com.cn for authentication, instead of icloud.com.

**Comment by micawberism1** [comment]
Thank you very much for your reply, my problem has been solved. But my other Apple IDs in China were not changed to icloud.com.cn,I was able to use it before, but I don't know what the reason is. Also, it asks me to escalate the issues: WARNING Downloading from icloud.com.cn is untested.

Thank you again for your answers!

**Comment by boredazfcuk** [comment]
Hi.

I put the warning in, as I had no way of testing this fix (I'm a long way from China!). I'm also not sure if there would be any other issues arise because of this. It's very much an experimental feature at this point in time.

I'm not aware of the reason why icloud.com.cn has replaced icloud.com either. It seems that not all accounts are affected. Some Apple IDs still need to be authenticated via icloud.com, but some don't. I don't know how Apple have decided which accounts need authenticating via icloud.com.cn. The only thing that can really be done is to use icloud.com as standard, but change to icloud.com.cn if you run into problems.

**Comment by micawberism1** [comment]
Thank you, if you find other problems in use, I will promptly inform you. 

Welcome to China and feel the Chinese culture, I believe you can become a good friend with us.
