### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike

### ISSUE THREAD

**Issue by brbeaird** [boredazfcuk/docker-icloudpd#12]
Recently updated, tried to go interactive and refresh my token. Now getting this:

```
2020-04-29 21:21:35 INFO     Great, you're all set up. The script can now be run without user interaction until 2SA expires.
You can set up email notifications for when the two-step authentication expires.
(Use --help to view information about SMTP options.)
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    load_entry_point('icloudpd==1.5.0', 'console_scripts', 'icloudpd')()
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.5.0-py3.8.egg/icloudpd/base.py", line 292, in main
  File "/usr/lib/python3.8/posixpath.py", line 336, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

Any ideas?

**Comment by brbeaird** [comment]
Nevermind - figured it out. I forgot to start up a totally different container instance when running interactively. Will have to save that command for next time.

**Comment by boredazfcuk** [comment]
Hi,

Unfortunately the error is generated by the icloudpd application and I don't know anything about Python to attempt to fix it.

I'm not sure why you're seeing this though as it should send errors to the bit bucket when running icloudpd.

Thanks.
