### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by z886** [boredazfcuk/docker-icloudpd#122]
Hi, 
   When running this command “docker exec -it xxx sync-icloud.sh --Initialise”, the following error is reported. 
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})

**Comment by boredazfcuk** [comment]
Hi,

Are you based in China by any chance? If you are, please see the `icloud_china` variable in the ReadMe.md.

Thanks

**Comment by z886** [comment]
Thank you!

**Comment by boredazfcuk** [comment]
I'll close this off, as I guess that's sorted it.
