### ISSUE TITLE
Error during download - Exit code: 1

### ISSUE THREAD

**Issue by SyngnathZ** [boredazfcuk/docker-icloudpd#135]
After successfully fully backup the photos on iCloud for the very first time. Error occurred during the automatic backup schedule.

`docker logs iCloudPD`

2022-02-13 21:54:40 INFO     Check for new files using password stored in keyring file
2022-02-13 21:54:40 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
/iCloud/2022/02/IMG_9181.JPG
/iCloud/2022/02/IMG_9180.PNG
/iCloud/2022/02/IMG_9179.PNG
/iCloud/2022/01/2022-01-31--tail-23000449.mov
/iCloud/2022/01/IMG_8771.PNG
/iCloud/2020/12/IMG_2881-8089257.JPG
2022-02-13 22:03:02 INFO     Check successful
2022-02-13 22:03:02 INFO     New files detected: 6
2022-02-13 22:03:02 INFO     Starting download of new files for user: user
2022-02-13 22:03:02 INFO     Downloading new files using password stored in keyring file...
2022-02-13 22:03:02 INFO     iCloudPD launch command: /usr/bin/icloudpd --directory /iCloud --cookie-directory /config --folder-structure {:%Y/%m} --username xxxxx@qq.com  2>/tmp/icloudpd/icloudpd_download_error
2022-02-13 22:03:03 DEBUG    Authenticating...
2022-02-13 22:03:13 ERROR    Error during download - Exit code: 1
2022-02-13 22:03:13 ERROR    Error debugging info:
2022-02-13 22:03:13 ERROR    
2022-02-13 22:03:13 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by boredazfcuk** [comment]
Can you connect in to the container with:
```
docker exec -it icloudpd /bin/ash
```
(assuming your container is named icloudpd)

and then check the contents of the file with: `more /tmp/icloudpd/icloudpd_download_error`

The error info should be displayed in the log above, so I'm not sure why it isn't, or if the file is actually empty.

**Comment by SyngnathZ** [comment]
The error info:

```
[~] # docker exec -it iCloudPD /bin/sh
/ # more /tmp/icloudpd/icloudpd_download_error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for 978900487@qq.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
```

**Comment by SyngnathZ** [comment]
The error info:

```
[~] # docker exec -it iCloudPD /bin/sh
/ # more /tmp/icloudpd/icloudpd_download_error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for xxxxx@qq.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
```

Seems like it was the password information problem?

**Comment by boredazfcuk** [comment]
Can you try re-initialising the container?

I see this error for users who are based in China, but have not set the `icloud_china` variable. Could this apply to you?

**Comment by shaoj0013** [comment]
icloud_china 变量我设置了

**Comment by shaoj0013** [comment]
host='setup.icloud.com.cn', port=443): Max retries exceeded with url: /setup/ws/1/login?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=DDA3F994-908F-11EC-A330-0242AC110006 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1cea84a4c0>: Failed to establish a new connection: [Errno 110] Operation timed out'))
2022-02-18 15:55:39 INFO     Two factor authentication cookie generated. Sync should now be successful.

**Comment by boredazfcuk** [comment]
@SyngnathZ I'm assuming that worked as you've not got back to me. If not just re-open the issue.

@shaoj0013 Please open your own issue as your error is different. Yours appears to be network related as it's failing to connect to the servers.
