### ISSUE TITLE
No new files detected. Nothing to download

### ISSUE THREAD

**Issue by aLAN-LDZ** [boredazfcuk/docker-icloudpd#138]
Hello. I have the following problem with this container, unfortunately I cannot run it

`
2022-02-18 22:29:42 INFO     Check download directory mounted correctly
2022-02-18 22:29:42 INFO     Failsafe file /home/Alan/iCloud/.mounted exists, continuing
2022-02-18 22:29:43 INFO     Check for new files using password stored in keyring file
2022-02-18 22:29:43 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
No passwd entry for user 'Alan'
cat: /tmp/icloudpd/icloud_check_exit_code: No such file or directory
ash: out of range
2022-02-18 22:29:43 INFO     Check successful
grep: /tmp/icloudpd/icloudpd_check.log: No such file or directory
ash: out of range
2022-02-18 22:29:43 INFO     No new files detected. Nothing to download
ash: out of range
2022-02-18 22:29:43 INFO     Web cookie expires: 2022-04-19 @ 22:27:49
2022-02-18 22:29:43 INFO     Two factor authentication cookie expires: 2022-05-19 @ 22:28:09
2022-02-18 22:29:43 INFO     Days remaining until expiration: 89
2022-02-18 22:29:43 INFO     iCloud login counter = 1
2022-02-18 22:29:43 INFO     Synchronisation ended at 22:29:43
2022-02-18 22:29:43 INFO     Total time taken: 00:00:01
2022-02-18 22:29:43 INFO     Next synchronisation at 22:29:42

`

**Comment by boredazfcuk** [comment]
Hi, Alan!

I can see what the issue is, it's a pretty simple fix... but, I'm currently overhauling the notifications system on my local beta version.

I don't want to push the fix and find I break notifications for a bunch of people.

So... To get you up and kicking, we'll need to run a couple of commands to fix this just on your machine until I'm ready to push the new version.

Connect to your container like this (assuming it's called icloudpd):
```
docker exec -it icloudpd /bin/ash
```
then run:
```
sed -i '#icloudpd/icloud_#icloudpd/icloudpd_#' /usr/local/bin/.sync-icloud.sh
```

and then restart your container. I think that should fix it.

**Comment by aLAN-LDZ** [comment]
I got an error that there is no such file, I decided to set everything up again and unfortunately now I got stuck a step earlier.

Although I run

`docker exec -it icloudpd sync-icloud.sh --Initialise
`
Console says:

`
2022-02-19 06:09:10 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2022-02-19 06:09:10 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2022-02-19 06:09:10 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2022/02/11_18:46 *****
2022-02-19 06:09:10 INFO     ***** /usr/local/bin/sync-icloud.sh hash: e801648a13038e92c819b41ef9eeda99 *****
2022-02-19 06:09:10 INFO     Alpine Linux 3.13.5
2022-02-19 06:09:10 INFO     Python version: 3.8.10
2022-02-19 06:09:13 INFO     icloudpd version: 1.7.2
2022-02-19 06:09:15 INFO     pyicloud-ipd version: 0.10.1
2022-02-19 06:09:15 INFO     Running user id: 0
2022-02-19 06:09:15 INFO     Running group id: 0
2022-02-19 06:09:15 INFO     Local user: Alan:1000
2022-02-19 06:09:15 INFO     Local group: group:1000
2022-02-19 06:09:15 INFO     Force GID: False
2022-02-19 06:09:15 INFO     LAN IP Address: 10.0.5.1 10.0.3.1 10.0.7.1 192.168.50.76 10.2.0.1
2022-02-19 06:09:15 INFO     Default gateway: 192.168.50.1
2022-02-19 06:09:15 INFO     DNS server: 10.0.3.1
2022-02-19 06:09:15 INFO     DNS lookup for icloud.com: 17.253.144.10
2022-02-19 06:09:18 INFO     Route check to icloud.com successful
2022-02-19 06:09:18 INFO     Apple ID: alan.joz@me.com
2022-02-19 06:09:18 INFO     Authentication Type: 2FA
2022-02-19 06:09:18 INFO     Cookie path: /config/alanjozmecom
2022-02-19 06:09:18 INFO     Cookie expiry notification period: 7
2022-02-19 06:09:18 INFO     Download destination directory: /home/Alan/iCloud
2022-02-19 06:09:18 INFO     Folder structure: {:%Y/%m/%d}
2022-02-19 06:09:18 INFO     Directory permissions: 750
2022-02-19 06:09:18 INFO     File permissions: 640
2022-02-19 06:09:18 INFO     Synchronisation interval: 86400
2022-02-19 06:09:18 INFO     Synchronisation delay (minutes): 0
2022-02-19 06:09:18 INFO     Time zone: UTC
2022-02-19 06:09:18 INFO     Set EXIF date/time: False
2022-02-19 06:09:18 INFO     Auto delete: False
2022-02-19 06:09:18 INFO     Photo size: original
2022-02-19 06:09:18 INFO     Skip download check: False
2022-02-19 06:09:18 INFO     Skip live photos: False
2022-02-19 06:09:18 INFO     Number of most recently added photos to download: Download All Photos
2022-02-19 06:09:18 INFO     Stop downloading when prexisiting files count is: Download All Photos
2022-02-19 06:09:18 INFO     Live photo size: original
2022-02-19 06:09:18 INFO     Skip videos: False
2022-02-19 06:09:18 INFO     Convert HEIC to JPEG: False
2022-02-19 06:09:18 INFO     JPEG conversion quality: 90
2022-02-19 06:09:18 INFO     Downloading from: icloud.com
2022-02-19 06:09:19 INFO     Creating directory: /home/Alan/.local/share/
2022-02-19 06:09:19 INFO     Creating symbolic link: /home/Alan/.local/share/python_keyring/ to: /config/python_keyring/ directory
2022-02-19 06:09:19 INFO     Creating group group:1000
2022-02-19 06:09:19 INFO     Creating user Alan:1000
useradd: invalid user name 'Alan'
2022-02-19 06:09:19 INFO     Set owner, Alan, on iCloud directory, if required
find: unknown user Alan
2022-02-19 06:09:19 INFO     Set group, group, on iCloud directory, if required
2022-02-19 06:09:19 INFO     Correct owner on icloudpd temp directory, if required
find: unknown user Alan
2022-02-19 06:09:19 INFO     Correct group on icloudpd temp directory, if required
2022-02-19 06:09:19 INFO     Correct owner on config directory, if required
find: unknown user Alan
2022-02-19 06:09:19 INFO     Correct group on config directory, if required
2022-02-19 06:09:19 INFO     Correct owner on keyring directory, if required
find: unknown user Alan
2022-02-19 06:09:19 INFO     Correct group on keyring directory, if required
2022-02-19 06:09:19 INFO     Set 750 permissions on iCloud directories, if required
2022-02-19 06:09:19 INFO     Set 640 permissions on iCloud files, if required
2022-02-19 06:09:19 INFO     Configure password
2022-02-19 06:09:19 ERROR    Keyring file /config/python_keyring/keyring_pass.cfg does not exist
2022-02-19 06:09:19 INFO      - Please add the your password to the system keyring using the --Initialise script command line option
2022-02-19 06:09:19 INFO      - Syntax: docker exec -it <container name> sync-icloud.sh --Initialise
2022-02-19 06:09:19 INFO      - Example: docker exec -it icloudpd sync-icloud.sh --Initialise
2022-02-19 06:09:19 INFO     Waiting for keyring file to be created...

`

I'm sorry, I don't know much about containers, but I can see that something that should take me 5 minutes and I'm struggling with it for a few days xD

**Comment by aLAN-LDZ** [comment]
I think I have some trash left from the previous attempt. At the time of the change and not creating a special folder for / config everything worked.

**Comment by aLAN-LDZ** [comment]
can i automatically convert files to jpg / png? Is HEIC downloaded first and only then the conversion takes place ??

**Comment by aLAN-LDZ** [comment]
after some time 

2022-02-19 12:30:46 INFO     Downloading /home/user/iCloud/2019/WFS01444.JPG
2022-02-19 12:30:49 INFO     Downloading /home/user/iCloud/2019/WFS01440.JPG
2022-02-19 12:30:51 INFO     Downloading /home/user/iCloud/2019/WFS01433.jpg
2022-02-19 12:30:52 ERROR    Error during download - Exit code: 1
2022-02-19 12:30:52 ERROR    Error debugging info:
2022-02-19 12:30:52 ERROR    
2022-02-19 12:30:52 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by boredazfcuk** [comment]
> can i automatically convert files to jpg / png? Is HEIC downloaded first and only then the conversion takes place ?? so that no HEIC files are left

Hi,

Not that's not possible. The files on the iCloud server are only in HEIC format. If you remove them from the local filesystem, the application will recognise that they are missing, and re-download them.

**Comment by boredazfcuk** [comment]
> after some time
> 
> 2022-02-19 12:30:46 INFO Downloading /home/user/iCloud/2019/WFS01444.JPG 2022-02-19 12:30:49 INFO Downloading /home/user/iCloud/2019/WFS01440.JPG 2022-02-19 12:30:51 INFO Downloading /home/user/iCloud/2019/WFS01433.jpg 2022-02-19 12:30:52 ERROR Error during download - Exit code: 1 2022-02-19 12:30:52 ERROR Error debugging info: 2022-02-19 12:30:52 ERROR 2022-02-19 12:30:52 ERROR ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

I've pushed a new version of the container this morning which should hopefully print the debugging info that is missing from the above log snip. Can you update and re-post please?

**Comment by aLAN-LDZ** [comment]
Hello

I have updated the container as requested and I am uploading a new log

2022-02-20 11:00:41 INFO     Downloading /home/user/iCloud/2019/WFS01430.jpg
2022-02-20 11:00:42 ERROR    Failed to download new files
2022-02-20 11:00:42 ERROR    Error debugging info:
2022-02-20 11:00:42 ERROR    /usr/lib/python3.8/site-packages/tzlocal/unix.py:158: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn('Can not find any timezone configuration, defaulting to UTC.')
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 562, in main
    download_photo(consecutive_files_found, item)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 489, in download_photo
    (".jpg", ".jpeg")) and not exif_datetime.get_photo_exif(download_path):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/exif_datetime.py", line 11, in get_photo_exif
    exif_dict = piexif.load(path)
  File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 49, in load
    exif_dict["Interop"] = exifReader.get_ifd_dict(pointer, "Interop")
  File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 108, in get_ifd_dict
    tag_count = struct.unpack(self.endian_mark + "H",
struct.error: unpack requires a buffer of 2 bytes
2022-02-20 11:00:42 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2022-02-20 11:00:42 INFO     Sending  failure notification
ash: out of range
2022-02-20 11:00:42 ERROR     failure notification failed with status code:

**Comment by boredazfcuk** [comment]
Hi.

Can I ask what notification method you are using? I've given the notifications feature a big update recently, and yours has failed, so it looks like I've broken something.

**Comment by aLAN-LDZ** [comment]
Hi

I don't use any - I mean I haven't configured any :p

**Comment by boredazfcuk** [comment]
Cool. I've amended the script to get rid of test to check if the sending of the notification was successful... Don't want to do that if you're not actually sending notifications!

Can you update to the latest container and try again? It is complaining that the time zone isn't configured, so I've set this to default to UTC. It could be related, but the time zone thing should just be a warning.

You are setting the TZ variable, right?

**Comment by aLAN-LDZ** [comment]
Yes, I have UTC set - unfortunately, the error continues

2022-02-21 07:09:31 INFO     /home/user/iCloud/2019/WFS01430.jpg already exists.
2022-02-21 07:09:31 INFO     Downloading /home/user/iCloud/2019/WFS01434.jpg
2022-02-21 07:09:32 ERROR    Failed to download new files
2022-02-21 07:09:32 ERROR    Error debugging info:
2022-02-21 07:09:32 ERROR    Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 562, in main
    download_photo(consecutive_files_found, item)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 489, in download_photo
    (".jpg", ".jpeg")) and not exif_datetime.get_photo_exif(download_path):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/exif_datetime.py", line 11, in get_photo_exif
    exif_dict = piexif.load(path)
  File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 49, in load
    exif_dict["Interop"] = exifReader.get_ifd_dict(pointer, "Interop")
  File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 108, in get_ifd_dict
    tag_count = struct.unpack(self.endian_mark + "H",
struct.error: unpack requires a buffer of 2 bytes
2022-02-21 07:09:32 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2022-02-21 07:09:32 INFO     Web cookie expires: 2022-04-20 @ 07:30:35
2022-02-21 07:09:32 INFO     Two factor authentication cookie expires: 2022-05-20 @ 07:31:02
2022-02-21 07:09:32 INFO     Days remaining until expiration: 88
2022-02-21 07:09:32 INFO     iCloud login counter = 2
2022-02-21 07:09:32 INFO     Synchronisation ended at 07:09:32
2022-02-21 07:09:32 INFO     Total time taken: 00:13:09
2022-02-21 07:09:32 INFO     Next synchronisation at 06:56:23

**Comment by boredazfcuk** [comment]
Well it looks like the change has fixed the time zone warning as that no longer appears.

You're definitely not setting the `set_exif_datetime` variable? I can see in the log file that it's attempting to read the EXIF data.

Also, how are the WFSxxxxx.JPG files being created? The camera on iDevices saves it's photos as IMG_0000.HEIC. Whatever app is generating these WFSxxxxx.JPG files may be saving incorrect (or possibly omitting) data that the downloading application needs. For example, if you have your folder structure set to year/month, but these files don't contain that information in their EXIF data, then that might be causing the problem.

**Comment by aLAN-LDZ** [comment]
I had it set! After deleting the variable, set_exif_datetime downloaded without a problem :)!

**Comment by boredazfcuk** [comment]
Cool. This is the second time I've been made aware of this issue. I'll report it upstream to see if they can take a look at it.
