### ISSUE TITLE
Failed to download new files

### ISSUE THREAD

**Issue by URBANsUNITED** [boredazfcuk/docker-icloudpd#142]
Hi!

I am getting the below error while downloading my files.
Using the latest docker and have ca. 200GB downloaded from my ca. 800GB

```
2022-02-27 04:15:04 ERROR    Failed to download new files
2022-02-27 04:15:04 ERROR    Error debugging info:
2022-02-27 04:15:04 ERROR    Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 562, in main
    download_photo(consecutive_files_found, item)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 489, in download_photo
    (".jpg", ".jpeg")) and not exif_datetime.get_photo_exif(download_path):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/exif_datetime.py", line 11, in get_photo_exif
    exif_dict = piexif.load(path)
  File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 49, in load
    exif_dict["Interop"] = exifReader.get_ifd_dict(pointer, "Interop")
  File "/usr/lib/python3.8/site-packages/piexif/_load.py", line 108, in get_ifd_dict
    tag_count = struct.unpack(self.endian_mark + "H",
struct.error: unpack requires a buffer of 2 bytes

```

Started the docker again to see if the error comes again.

**edit:**
Same error after restart. New try without

set_exif_datetime=true

--

<br class="Apple-interchange-newline">

Best regards

URBANsUNITED

**Comment by boredazfcuk** [comment]
Hi,

This is likely due to setting `set_exif_datetime` to `True`. It seems that recently, some people's photos have something stored in their EXIF data which is making the script crash.

see the two issues here:

https://github.com/boredazfcuk/docker-icloudpd/issues?q=is%3Aissue+struct.error+is%3Aclosed

**Comment by URBANsUNITED** [comment]
Indeed!

set_exif_datetime=false

is the key to make it work. It's still downloading my files :) without any issue.
It would be got to know which file is the problematic one btw...

Thanks!
