### ISSUE TITLE
Troble to login my iCloud 

### ISSUE THREAD

**Issue by Hawkenm** [boredazfcuk/docker-icloudpd#146]
**### When I try to log in to this icloud account, the program reports an error. The log is displayed as follows:**

``/` # /usr/local/bin/sync-icloud.sh --Initialise

2022-03-12 13:50:20 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2022-03-12 13:50:20 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2022-03-12 13:50:20 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2022/03/05_07:21 *****
2022-03-12 13:50:20 INFO     ***** /usr/local/bin/sync-icloud.sh hash: **************e84d72f0deda316 *****
2022-03-12 13:50:20 INFO     Alpine Linux 3.13.5
2022-03-12 13:50:20 INFO     Python version: 3.8.10
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2022-03-12 13:50:21 INFO     icloudpd version: 1.7.2
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2022-03-12 13:50:22 INFO     pyicloud-ipd version: 0.10.1
2022-03-12 13:50:22 INFO     Running user id: 0
2022-03-12 13:50:22 INFO     Running group id: 0
2022-03-12 13:50:22 INFO     Local user: icloud:1001
2022-03-12 13:50:22 INFO     Local group: icloud:1002
2022-03-12 13:50:22 INFO     Force GID: true
2022-03-12 13:50:22 INFO     LAN IP Address: 172.16.0.5
2022-03-12 13:50:22 INFO     Default gateway: 172.16.0.1
2022-03-12 13:50:22 INFO     DNS server: 172.17.0.10
2022-03-12 13:50:29 INFO     Route check to icloud.com.cn successful
2022-03-12 13:50:29 INFO     Apple ID: 2698********@qq.com
2022-03-12 13:50:29 INFO     Authentication Type: 2FA
2022-03-12 13:50:29 INFO     Cookie path: /config/269*******qqcom
2022-03-12 13:50:29 INFO     Cookie expiry notification period: 7
2022-03-12 13:50:29 INFO     Download destination directory: /downloads
2022-03-12 13:50:29 INFO     Folder structure: {:%Y/%m}
2022-03-12 13:50:29 INFO     Directory permissions: 750
2022-03-12 13:50:29 INFO     File permissions: 640
2022-03-12 13:50:29 INFO     Synchronisation interval: 43200
2022-03-12 13:50:29 INFO     Synchronisation delay (minutes): 0
2022-03-12 13:50:29 INFO     Set EXIF date/time: False
2022-03-12 13:50:29 INFO     Auto delete: True
2022-03-12 13:50:29 INFO     Photo size: original
2022-03-12 13:50:29 INFO     Skip download check: False
2022-03-12 13:50:29 INFO     Skip live photos: False
2022-03-12 13:50:29 INFO     Number of most recently added photos to download: Download All Photos
2022-03-12 13:50:29 INFO     Stop downloading when prexisiting files count is: Download All Photos
2022-03-12 13:50:29 INFO     Live photo size: original
2022-03-12 13:50:29 INFO     Skip videos: False
2022-03-12 13:50:29 INFO     Convert HEIC to JPEG: False
2022-03-12 13:50:29 INFO     JPEG conversion quality: 90
2022-03-12 13:50:29 INFO     Downloading from: icloud.com.cn
2022-03-12 13:50:29 WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues
2022-03-12 13:50:29 INFO     Script launch parameters: --Initialise
2022-03-12 13:50:29 INFO     Group, icloud:1002, already created
2022-03-12 13:50:29 INFO     User, icloud:1001, already created
2022-03-12 13:50:29 INFO     Set owner, icloud, on iCloud directory, if required
2022-03-12 13:50:29 INFO     Set group, icloud, on iCloud directory, if required
2022-03-12 13:50:29 INFO     Correct owner on icloudpd temp directory, if required
2022-03-12 13:50:29 INFO     Correct group on icloudpd temp directory, if required
2022-03-12 13:50:29 INFO     Correct owner on config directory, if required
2022-03-12 13:50:29 INFO     Correct group on config directory, if required
2022-03-12 13:50:29 INFO     Correct owner on keyring directory, if required
2022-03-12 13:50:29 INFO     Correct group on keyring directory, if required
2022-03-12 13:50:29 INFO     Set 750 permissions on iCloud directories, if required
2022-03-12 13:50:29 INFO     Set 640 permissions on iCloud files, if required
2022-03-12 13:50:29 INFO     Configure password
2022-03-12 13:50:29 INFO     Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for 269**********@qq.com: 
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
2022-03-12 13:50:36 INFO     Correct owner on config directory, if required
2022-03-12 13:50:36 INFO     Correct group on config directory, if required
2022-03-12 13:50:36 INFO     Generate 2FA cookie using password stored in keyring file
iCloud Password: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for 269*************@qq.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
grep: /config/2698723602qqcom: No such file or directory
ash: out of range
2022-03-12 13:50:43 ERROR    2FA information missing from cookie. Authentication has failed
2022-03-12 13:50:43 ERROR     - Was the correct password entered?
2022-03-12 13:50:43 ERROR     - Was the 2FA code mistyped?
2022-03-12 13:50:43 ERROR     - Are you based in China? You may need to set the icloud_china `variable``

**### I have tried on three different computers and two different IP addresses, but this problem still reappears.**

**Comment by GeorgeUgly** [comment]
Same as yours

**Comment by boredazfcuk** [comment]
Hi,
Do you have special characters in your e-mail address? The script removes all characters which are not:
```
a-z
0-9
_
```
the script is complaining that it cannot find a config file which matches your e-mail address, so my guess is that something is being stripped out somewhere.

Thanks.

**Comment by boredazfcuk** [comment]
> Hi, I have the same problem, but when I first do it, I forgot to stick the volume, so the path is "/homes/..." rather than "/volume1/homes/..." and I finished all the program without error, but in the case of wrong address, all the photos were stored in the "/home/.../Photos/iCloud". But after I change the volume destination, the error came out. My QQ is 1220519124, and any help is grateful.

The download destination shouldn't really matter. If the download destination doesn't have anything in it (maybe because it was changed), the script will just re-download your entire photo stream again (provided the `.mounted` file exists).

**Comment by boredazfcuk** [comment]
No worries. If you have any further problems, please create a new issue.

I'm closing this on off as OP hasn't responded in over a month.
