### ISSUE TITLE
ERROR Failed check for new files files

### ISSUE THREAD

**Issue by kotori912** [boredazfcuk/docker-icloudpd#150]
Hi,
After I reconfigured, this great tool made strange mistakes and it didn't work properly
I don't know how to describe it

I installed it in UNRAID OS 6.9.2. Anyone can help me? 

Error message are:

```
2022-03-26 23:36:24 WARNING Additional command line options supplied: icloud_china

2022-03-26 23:36:24 WARNING Additional command line options is depreciated. Please specify all options using the dedicated variables

2022-03-26 23:36:24 INFO Convert HEIC to JPEG: False
2022-03-26 23:36:24 INFO JPEG conversion quality: 90
2022-03-26 23:36:24 INFO Downloading from: icloud.com
2022-03-26 23:36:26 INFO Group, group:1000, already created
2022-03-26 23:36:26 INFO User, user:1000, already created
2022-03-26 23:36:26 INFO Set owner, user, on iCloud directory, if required
2022-03-26 23:36:26 INFO Set group, group, on iCloud directory, if required
2022-03-26 23:36:26 INFO Correct owner on icloudpd temp directory, if required
2022-03-26 23:36:26 INFO Correct group on icloudpd temp directory, if required
2022-03-26 23:36:26 INFO Correct owner on config directory, if required
2022-03-26 23:36:26 INFO Correct group on config directory, if required
2022-03-26 23:36:26 INFO Correct owner on keyring directory, if required
2022-03-26 23:36:26 INFO Correct group on keyring directory, if required
2022-03-26 23:36:26 INFO Set 777 permissions on iCloud directories, if required
2022-03-26 23:36:26 INFO Set 666 permissions on iCloud files, if required
2022-03-26 23:36:26 INFO Configure password
2022-03-26 23:36:26 INFO Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2022-03-26 23:36:26 INFO Check download directory mounted correctly
2022-03-26 23:36:26 INFO Failsafe file /home/user/iCloud/.mounted exists, continuing
2022-03-26 23:36:26 INFO Set owner, user, on iCloud directory, if required
2022-03-26 23:36:26 INFO Set group, group, on iCloud directory, if required
2022-03-26 23:36:26 INFO Correct owner on icloudpd temp directory, if required
2022-03-26 23:36:26 INFO Correct group on icloudpd temp directory, if required
2022-03-26 23:36:26 INFO Correct owner on config directory, if required
2022-03-26 23:36:26 INFO Correct group on config directory, if required
2022-03-26 23:36:26 INFO Correct owner on keyring directory, if required
2022-03-26 23:36:26 INFO Correct group on keyring directory, if required
2022-03-26 23:36:26 INFO Set 777 permissions on iCloud directories, if required
2022-03-26 23:36:26 INFO Set 666 permissions on iCloud files, if required
2022-03-26 23:36:26 INFO Sync user user
2022-03-26 23:36:27 INFO Synchronisation starting at 23:36:27
2022-03-26 23:36:27 INFO Check 2FA Cookie
2022-03-26 23:36:27 INFO Cookie exists, check expiry date
2022-03-26 23:36:27 INFO Valid two factor authentication cookie found. Days until expiration: 89
2022-03-26 23:36:27 INFO Check download directory mounted correctly
2022-03-26 23:36:27 INFO Failsafe file /home/user/iCloud/.mounted exists, continuing
2022-03-26 23:36:27 INFO Check for new files using password stored in keyring file
2022-03-26 23:36:27 INFO Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2022-03-26 23:36:32 ERROR Failed check for new files files

2022-03-26 23:36:32 ERROR Error debugging info:

2022-03-26 23:36:32 ERROR Traceback (most recent call last):

File "/usr/bin/icloudpd", line 33, in <module>
sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
icloud = authenticate(
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
icloud = pyicloud_ipd.PyiCloudService(
File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
self.authenticate()
File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
2022-03-26 23:36:32 ERROR ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

2022-03-26 23:36:32 INFO Web cookie expires: 2022-05-25 @ 14:43:48
2022-03-26 23:36:32 INFO Two factor authentication cookie expires: 2022-06-24 @ 14:44:17
2022-03-26 23:36:32 INFO Days remaining until expiration: 89
2022-03-26 23:36:32 INFO iCloud login counter = 1
2022-03-26 23:36:32 INFO Synchronisation ended at 23:36:32
2022-03-26 23:36:32 INFO Total time taken: 00:00:05
2022-03-26 23:36:32 INFO Next synchronisation at 23:36:27
```

**Comment by laiquan** [comment]
same problem

**Comment by kotori912** [comment]
> same problem

Have you solved it?

**Comment by boredazfcuk** [comment]
Hi,

I can see from this line:
```
2022-03-26 23:36:24 WARNING Additional command line options supplied: icloud_china
```
...that the `icloud_china` variable is not being set correctly.

I think you are creating your container with:
`additional_command_line_options=icloud_china`

when it should just be:
`icloud_china=True`

Can you give that a go and let me know?

Thanks.

**Comment by kotori912** [comment]
> Hi,
> 
> I can see from this line:
> 
> ```
> 2022-03-26 23:36:24 WARNING Additional command line options supplied: icloud_china
> ```
> 
> ...that the `icloud_china` variable is not being set correctly.
> 
> I think you are creating your container with: `additional_command_line_options=icloud_china`
> 
> when it should just be: `icloud_china=True`
> 
> Can you give that a go and let me know?
> 
> Thanks.

First of all, I'm sorry to reply to you for such a long time. I was busy some time ago
I tried this method. It's very effective


> same problem

To solve this problem, you need to add another variable
on there
![image](https://user-images.githubusercontent.com/46342352/164445612-df4aab78-3032-429c-91a5-ef9b7cf83d9c.png)
Same as the one below
![image](https://user-images.githubusercontent.com/46342352/164445474-fbd6693e-29e9-4249-acf6-a8cf2c47f391.png)
