### ISSUE TITLE
Error information on the blow,anyone solve it?

### ISSUE THREAD

**Issue by laiquan** [boredazfcuk/docker-icloudpd#152]
2022-03-27 13:06:43.457810+00:00/downloads/2021/08/31/IMG_0130.HEIC
2022-03-27 13:06:43.457818+00:00/downloads/2021/08/31/IMG_0130_HEVC.MOV
2022-03-27 13:06:46.303086+00:00/downloads/2021/08/31/IMG_0129.HEIC
2022-03-27 13:06:46.303159+00:00/downloads/2021/08/31/IMG_0129_HEVC.MOV
2022-03-27 13:06:46.367335+00:002022-03-27 13:06:46 ERROR    Failed check for new files files
2022-03-27 13:06:46.367988+00:002022-03-27 13:06:46 ERROR    Error debugging info:
2022-03-27 13:06:46.369857+00:002022-03-27 13:06:46 ERROR    Traceback (most recent call last):
2022-03-27 13:06:46.369891+00:00File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
2022-03-27 13:06:46.369898+00:00httplib_response = self._make_request(
2022-03-27 13:06:46.369903+00:00File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
2022-03-27 13:06:46.369908+00:00six.raise_from(e, None)
2022-03-27 13:06:46.369912+00:00File "<string>", line 3, in raise_from
2022-03-27 13:06:46.369916+00:00File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
2022-03-27 13:06:46.369920+00:00httplib_response = conn.getresponse()
2022-03-27 13:06:46.369924+00:00File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
2022-03-27 13:06:46.369928+00:00response.begin()
2022-03-27 13:06:46.369932+00:00File "/usr/lib/python3.8/http/client.py", line 307, in begin
2022-03-27 13:06:46.369936+00:00version, status, reason = self._read_status()
2022-03-27 13:06:46.369940+00:00File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
2022-03-27 13:06:46.369944+00:00raise RemoteDisconnected("Remote end closed connection without"
2022-03-27 13:06:46.369948+00:00http.client.RemoteDisconnected: Remote end closed connection without response
2022-03-27 13:06:46.369952+00:002022-03-27T13:06:46.369952057Z
2022-03-27 13:06:46.369955+00:00During handling of the above exception, another exception occurred:
2022-03-27 13:06:46.369959+00:002022-03-27T13:06:46.369959765Z
2022-03-27 13:06:46.369963+00:00Traceback (most recent call last):
2022-03-27 13:06:46.369967+00:00File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
2022-03-27 13:06:46.369971+00:00resp = conn.urlopen(
2022-03-27 13:06:46.369975+00:00File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
2022-03-27 13:06:46.369978+00:00retries = retries.increment(
2022-03-27 13:06:46.369982+00:00File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
2022-03-27 13:06:46.369986+00:00raise six.reraise(type(error), error, _stacktrace)
2022-03-27 13:06:46.369990+00:00File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
2022-03-27 13:06:46.369994+00:00raise value.with_traceback(tb)
2022-03-27 13:06:46.369998+00:00File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
2022-03-27 13:06:46.370002+00:00httplib_response = self._make_request(
2022-03-27 13:06:46.370005+00:00File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
2022-03-27 13:06:46.370009+00:00six.raise_from(e, None)
2022-03-27 13:06:46.370013+00:00File "<string>", line 3, in raise_from
2022-03-27 13:06:46.370017+00:00File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
2022-03-27 13:06:46.370021+00:00httplib_response = conn.getresponse()
2022-03-27 13:06:46.370025+00:00File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
2022-03-27 13:06:46.370029+00:00response.begin()
2022-03-27 13:06:46.370033+00:00File "/usr/lib/python3.8/http/client.py", line 307, in begin
2022-03-27 13:06:46.370038+00:00version, status, reason = self._read_status()
2022-03-27 13:06:46.370042+00:00File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
2022-03-27 13:06:46.370046+00:00raise RemoteDisconnected("Remote end closed connection without"
2022-03-27 13:06:46.370050+00:00urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-03-27 13:06:46.370054+00:002022-03-27T13:06:46.370054724Z
2022-03-27 13:06:46.370058+00:00During handling of the above exception, another exception occurred:
2022-03-27 13:06:46.370062+00:002022-03-27T13:06:46.370062315Z
2022-03-27 13:06:46.370068+00:00Traceback (most recent call last):
2022-03-27 13:06:46.370073+00:00File "/usr/bin/icloudpd", line 33, in <module>
2022-03-27 13:06:46.370077+00:00sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
2022-03-27 13:06:46.370081+00:00File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
2022-03-27 13:06:46.370084+00:00return self.main(*args, **kwargs)
2022-03-27 13:06:46.370088+00:00File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
2022-03-27 13:06:46.370092+00:00rv = self.invoke(ctx)
2022-03-27 13:06:46.370096+00:00File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
2022-03-27 13:06:46.370100+00:00return ctx.invoke(self.callback, **ctx.params)
2022-03-27 13:06:46.370104+00:00File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
2022-03-27 13:06:46.370108+00:00return callback(*args, **kwargs)
2022-03-27 13:06:46.370111+00:00File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 561, in main
2022-03-27 13:06:46.370115+00:00item = next(photos_iterator)
2022-03-27 13:06:46.370119+00:00File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 295, in photos
2022-03-27 13:06:46.370123+00:00request = self.photos_request(offset)
2022-03-27 13:06:46.370127+00:00File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 276, in photos_request
2022-03-27 13:06:46.370130+00:00return self.service.session.post(
2022-03-27 13:06:46.370134+00:00File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
2022-03-27 13:06:46.370138+00:00return self.request('POST', url, data=data, json=json, **kwargs)
2022-03-27 13:06:46.370142+00:00File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 68, in request
2022-03-27 13:06:46.370146+00:00response = super(PyiCloudSession, self).request(*args, **kwargs)
2022-03-27 13:06:46.370150+00:00File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
2022-03-27 13:06:46.370153+00:00resp = self.send(prep, **send_kwargs)
2022-03-27 13:06:46.370157+00:00File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
2022-03-27 13:06:46.370161+00:00r = adapter.send(request, **kwargs)
2022-03-27 13:06:46.370166+00:00File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
2022-03-27 13:06:46.370169+00:00raise ConnectionError(err, request=request)
2022-03-27 13:06:46.370173+00:00requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-03-27 13:06:46.370454+00:002022-03-27 13:06:46 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2022-03-27 13:06:46.372865+00:002022-03-27 13:06:46 INFO     Web cookie expires: 2022-05-26 @ 13:00:33
2022-03-27 13:06:46.372963+00:002022-03-27 13:06:46 INFO     Two factor authentication cookie expires: 2022-06-25 @ 13:00:56
2022-03-27 13:06:46.373461+00:002022-03-27 13:06:46 INFO     Days remaining until expiration: 89
2022-03-27 13:06:46.374026+00:002022-03-27 13:06:46 INFO     iCloud login counter = 1
2022-03-27 13:06:46.376157+00:002022-03-27 13:06:46 INFO     Synchronisation ended at 13:06:46
2022-03-27 13:06:46.377122+00:002022-03-27 13:06:46 INFO     Total time taken: 00:00:47
2022-03-27 13:06:46.378205+00:002022-03-27 13:06:46 INFO     Next synchronisation at 13:05:59

**Comment by boredazfcuk** [comment]
Hi,
This suggests that the Apple servers are disconnecting your session.

Can you grab me the first half of the logs so I can see what variables are being set? Please remove any identifying information, such as AppleID/e-mail/username etc

**Comment by boredazfcuk** [comment]
Hi,

I'm closing this off as I've not has a response in over two weeks. Please reply with requested information and I'll re-open the issue.

Thanks.
