### ISSUE TITLE
failed to download new files after check successful

### ISSUE THREAD

**Issue by pstreem** [boredazfcuk/docker-icloudpd#159]
new deployment for docker-icloudpd , feedback error. the log as below:

```
2022-05-04 22:33:19 INFO     Check successful
2022-05-04 22:33:19 INFO     New files detected: 5431
2022-05-04 22:33:19 INFO     Starting download of new files for user: user
2022-05-04 22:33:19 INFO     Downloading new files using password stored in keyring file...
2022-05-04 22:33:19 INFO     iCloudPD launch command: /usr/bin/icloudpd --directory /iCloud --cookie-directory /config --folder-structure {:%Y/%m/%d} --username pstreem@xx**xx.com --auto-delete  2>/tmp/icloudpd/icloudpd_download_error
2022-05-04 22:33:20 DEBUG    Authenticating...
2022-05-04 22:33:23 ERROR    Failed to download new files
2022-05-04 22:33:23 ERROR    Error debugging info:
2022-05-04 22:33:23 ERROR    Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Bad Gateway (502)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Bad Gateway (502)'))
2022-05-04 22:33:23 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2022-05-04 22:33:23 INFO     Web cookie expires: 2022-07-03 @ 14:16:33
2022-05-04 22:33:23 INFO     Two factor authentication cookie expires: 2022-08-02 @ 14:16:54
2022-05-04 22:33:23 INFO     Days remaining until expiration: 89
```

could you can help check how to fix this ? thanks.

**Comment by pstreem** [comment]
I don't know how.  restart several times. it's ok now. sorry for this.
