### ISSUE TITLE
Invalid email / password combination

### ISSUE THREAD

**Issue by gregbert42** [boredazfcuk/docker-icloudpd#17]
No changes to configuration. Now getting the following error. Gives "No Reason"

2020-06-13 17:21:53 INFO     Set 750 permissions on iCloud directories, if required
2020-06-13 17:21:53 INFO     Set 640 permissions on iCloud files, if required
2020-06-13 17:21:53 INFO     Sync user remote_fs_user
2020-06-13 17:21:53 INFO     Check 2FA Cookie
2020-06-13 17:21:53 INFO     Cookie exists, check expiry date
2020-06-13 17:21:53 INFO     Valid two factor authentication cookie found. Days until expiration: 89
2020-06-13 17:21:53 INFO     Check download directory mounted correctly
2020-06-13 17:21:53 INFO     Checking for new files using insecure password method. Please store password in the iCloud keyring to prevent password leaks
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    load_entry_point('icloudpd==1.5.0', 'console_scripts', 'icloudpd')()
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.5.0-py3.8.egg/icloudpd/base.py", line 253, in main
  File "/usr/lib/python3.8/site-packages/icloudpd-1.5.0-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2020-06-13 17:21:55 ERROR    Check failed - Exit code: 1
2020-06-13 17:21:55 INFO     Web cookie expires: 2020-08-12 @ 15:18:48

**Comment by gregbert42** [comment]
I changed to use the key ring. This works.

**Comment by boredazfcuk** [comment]
Says it’s an email/password issue in your error text.

Password handling is a bit of a pain to be honest, due to handling of special characters.

You’ve pointed out a benefit that’s I’d not considered before though, that the keyring authentication should handle special characters better than my script does.

Thanks for letting me know. I like these issues that resolve themselves 😂

**Comment by gregbert42** [comment]
There actually were no special characters in this password...
it was the equivalent of: superPassword123
i hadnt made any changes. i went back to refresh the cookie and that worked fine as well..
sorry i cant offer more! obviously a rather sensitive place. But all working well with the keyring - much better process anyway.
