### ISSUE TITLE
can't initialise the iCloudPD

### ISSUE THREAD

**Issue by fzxvvc** [boredazfcuk/docker-icloudpd#171]
Hi! I tried to build the iCloudPD on my docker, everything is ok but this come out:

```
Enter iCloud password for f********@icloud.com: 
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
2022-06-16 15:33:22 INFO     Correct owner on config directory, if required
2022-06-16 15:33:22 INFO     Correct group on config directory, if required
2022-06-16 15:33:22 INFO     Generate 2FA cookie using password stored in keyring file
iCloud Password: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for f*****@icloud.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
grep: /config/f*****icloudcom: No such file or directory
ash: out of range
2022-06-16 15:33:48 ERROR    2FA information missing from cookie. Authentication has failed
2022-06-16 15:33:48 ERROR     - Was the correct password entered?
2022-06-16 15:33:48 ERROR     - Was the 2FA code mistyped?
2022-06-16 15:33:48 ERROR     - Are you based in China? You may need to set the icloud_china variable
```

my iCloud account is based in China,I tried the US account, everything is ok.Whats the problem?

**Comment by boredazfcuk** [comment]
Hi,

This error occurs when attempting to authenticate against the wrong icloud website.

Have you tried with `icloud_china=True` and also without it? There's no way to determine where your account is located so you'll just need to try both.

Thanks.

**Comment by fzxvvc** [comment]
Hi,
First of all, thank you
I have set it successfully. The command should be   

> --env icloud_china=True \

What I have been using is

> > --env icloud_china
Thanks

**Comment by boredazfcuk** [comment]
No problem. Enjoy,
