### ISSUE TITLE
Failed check for new files files

### ISSUE THREAD

**Issue by bluesmilery** [boredazfcuk/docker-icloudpd#172]
Hi,

This is the error info. Please help me.

```
2022-06-20 04:39:40 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
/iCloud/2022/06/IMG_5313.MOV
/iCloud/2022/06/IMG_5312.MOV
/iCloud/2022/06/IMG_5311.HEIC
/iCloud/2022/06/IMG_5311_HEVC.MOV
/iCloud/2022/06/IMG_5310.HEIC
/iCloud/2022/06/IMG_5310_HEVC.MOV
/iCloud/2022/06/IMG_5309.JPG
/iCloud/2022/06/IMG_5308.HEIC
/iCloud/2022/06/IMG_5308_HEVC.MOV
/iCloud/2022/06/IMG_5307.HEIC
/iCloud/2022/06/IMG_5628.heic
/iCloud/2022/06/IMG_5305.HEIC
/iCloud/2022/06/IMG_5304.HEIC
/iCloud/2022/06/IMG_5304_HEVC.MOV
/iCloud/2022/06/IMG_5303.JPG
/iCloud/2022/06/IMG_5302.JPG
/iCloud/2022/06/IMG_5301.JPG
/iCloud/2022/06/IMG_5300.MOV
/iCloud/2022/06/IMG_5299.MOV
2022-06-20 04:47:40 ERROR    Failed check for new files files
2022-06-20 04:47:40 ERROR    Error debugging info:
2022-06-20 04:47:40 ERROR    Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 701, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 561, in main
    item = next(photos_iterator)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 295, in photos
    request = self.photos_request(offset)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 276, in photos_request
    return self.service.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 68, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 756, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
2022-06-20 04:47:40 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
```

**Comment by DrRobertDoback** [comment]
I had the exact same error and came across your post while searching for a fix.  I was ultimately able to trace my problem back to a DNS issue (I recently setup pihole on my network).  I changed the icloudpd docker config to point to Google's public DNS instead of my local DNS and it fixed the issue.

**Comment by boredazfcuk** [comment]
Hi,

The `Connection broken` part of your error suggests that the network connection had an issue while downloading.

Are you still seeing this issue?

Thanks.

**Comment by boredazfcuk** [comment]
You could also disable the new files check by setting `skip_check=True`, as I've seen issues with this when people have a large number of files.

**Comment by bluesmilery** [comment]
> Hi,
> 
> The `Connection broken` part of your error suggests that the network connection had an issue while downloading.
> 
> Are you still seeing this issue?
> 
> Thanks.

The problem was solved. I find a solution: modify the `urllib3/response.py` file and add one line code `line = (len(line)>0 and line or "0")`

Ref. https://github.com/psf/requests/issues/4248#issuecomment-408666274

**Comment by boredazfcuk** [comment]
No, it doesn't download photos every time, it will only download a photo if it does not exist on the disk.

I just find that if I have `skip_check=True` and restart my container a few times in quick succession, I get throttled by Apple. Having the check means I can restart a fair few more times before they get arsey, so it helps when I'm testing.

**Comment by boredazfcuk** [comment]
Hi, I'm going to assume that no news is good news and that `skip_check=True` resolved your issue.

**Comment by zarkfly** [comment]
kip_check=True 设置无效，还是会检查文件怎么办
