### ISSUE TITLE
[Resolved] Error when trying to download photos (please see logs)

### ISSUE THREAD

**Issue by FadingArabChristians** [boredazfcuk/docker-icloudpd#178]
2022-07-04 05:11:29 ERROR    Failed to download new files
2022-07-04 05:11:29 ERROR    Error debugging info:
2022-07-04 05:11:29 ERROR    Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2635)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='p35-ckdatabasews.icloud.com', port=443): Max retries exceeded with url: /database/1/com.apple.photos.cloud/production/private/records/query?clientBuildNumber=REDACTED clientMasteringNumber=REDACTED ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=REDACTED&dsid=REDACTED&remapEnums=True&getCurrentSyncToken=True (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2635)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 561, in main
    item = next(photos_iterator)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 295, in photos
    request = self.photos_request(offset)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 276, in photos_request
    return self.service.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 68, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='p35-ckdatabasews.icloud.com', port=443): Max retries exceeded with url: /database/1/com.apple.photos.cloud/production/private/records/query?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=REDACTED&dsid=REDACTED&remapEnums=True&getCurrentSyncToken=True (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2635)')))
2022-07-04 05:11:29 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2022-07-04 05:11:29 INFO     Sending Prowl failure notification
2022-07-04 05:11:30 INFO     Prowl failure notification sent successfully
2022-07-04 05:11:30 INFO     Web cookie expires: 2022-08-24 @ 16:36:42
2022-07-04 05:11:30 INFO     Two factor authentication cookie expires: 2022-09-23 @ 16:37:02
2022-07-04 05:11:30 INFO     Days remaining until expiration: 81
2022-07-04 05:11:30 INFO     iCloud login counter = 2
2022-07-04 05:11:30 INFO     Synchronisation ended at 05:11:30
2022-07-04 05:11:30 INFO     Total time taken: 00:10:25
2022-07-04 05:11:30 INFO     Next synchronisation at 05:01:05

** Press ANY KEY to close this window **

**Comment by FadingArabChristians** [comment]
I'm running unRaid 6.10.3 and the latest docker/container as of 7/5/22

**Comment by FadingArabChristians** [comment]
I ended up force updating the container/docker and it seems to be working as of right now.

I'm gonna mark this post as resolved for the time being.
