### ISSUE TITLE
run Initialise failed 

### ISSUE THREAD

**Issue by Lzxingyang** [boredazfcuk/docker-icloudpd#179]
when my cookes expired, then I rerun  Initialise command again then it give below error informations.
Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg

But the file was not exist " /config/python_keyring/keyring_pass.cfg" 

2022-07-09 12:04:38 INFO     Configure password
2022-07-09 12:04:38 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2022-07-09 12:04:38 INFO     Correct owner on config directory, if required
2022-07-09 12:04:38 INFO     Correct group on config directory, if required
2022-07-09 12:04:38 INFO     Generate 2FA cookie using password stored in keyring file
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
grep: /config/yangshoudonggmailcom: No such file or directory
ash: out of range
2022-07-09 12:04:45 ERROR    2FA information missing from cookie. Authentication has failed
2022-07-09 12:04:45 ERROR     - Was the correct password entered?
2022-07-09 12:04:45 ERROR     - Was the 2FA code mistyped?
2022-07-09 12:04:45 ERROR     - Are you based in China? You may need to set the icloud_china variable

**Comment by boredazfcuk** [comment]
This error:

`grep: /config/yangshoudonggmailcom: No such file or directory`

is because it cannot find your cookie file. It could be a permissions issue. Try deleting it, and then reinitialising the container.

**Comment by boredazfcuk** [comment]
Hi,

I'm going to assume that no news is good news and that this issue is now resolved.

Thanks.
