### ISSUE TITLE
fail to create keyring file

### ISSUE THREAD

**Issue by Amar-amo** [boredazfcuk/docker-icloudpd#198]
Save password in keyring?  [y/N]: y
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/usr/lib/python3.10/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3.10/site-packages/keyrings/alt/file_base.py", line 90, in set_password
    password_base64 = base64.encodestring(password_encrypted).decode()
AttributeError: module 'base64' has no attribute 'encodestring'

I am running the latest dockerhub version on unRaid 6.10.3

**Comment by jonsego** [comment]
Same here.
Enter iCloud password for *********:
Save password in keyring?  [y/N]: y
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/usr/lib/python3.10/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3.10/site-packages/keyrings/alt/file_base.py", line 90, in set_password
    password_base64 = base64.encodestring(password_encrypted).decode()
AttributeError: module 'base64' has no attribute 'encodestring'
2022-08-25 13:31:21 INFO     Correct owner on config directory, if required
2022-08-25 13:31:21 INFO     Correct group on config directory, if required
2022-08-25 13:31:21 INFO     Generate 2FA cookie using password stored in keyring file
iCloud Password:
  0: SMS to *******90
  1: Enter two-factor authentication code
Please choose an option: [0]: 1
Please enter two-factor authentication code: ******
iCloud Photo Library not finished indexing.  Please try again in a few minutes
2022-08-25 13:31:53 INFO     Two factor authentication cookie generated. Sync should now be successful

And no keyring file created.

**Comment by boredazfcuk** [comment]
Hi,

Please update to the latest version I've just released.

I've not been able to upgrade the container for quite a while due to the underlying application not being compatible with Python 3.9+

I managed to fix the broken bits of code and got it retrieving the password from the keystore and downloading files again. I never thought to check the container initialisation process though... The fix was very similar to the one for adding the password to the keystore though, which is why I've been able to push this fix already.

Any further problems, please re-open the issue.

Thanks.
