### ISSUE TITLE
doesnt work since roughly three weeks - python error

### ISSUE THREAD

**Issue by felixg3** [boredazfcuk/docker-icloudpd#21]
Hey there, I am getting the following error message in my log. Do you have any troubleshooting suggestions? Thank you!

Traceback (most recent call last):
File "/usr/bin/icloudpd", line 11, in <module>
load_entry_point('icloudpd==1.5.0', 'console_scripts', 'icloudpd')()
File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/icloudpd-1.5.0-py3.8.egg/icloudpd/base.py", line 276, in main
File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 194, in albums
folder['fields']['albumNameEnc']['value']).decode('utf-8')
KeyError: 'albumNameEnc'
2020-08-19 20:33:26 ERROR Check failed - Exit code: 1

**Comment by boredazfcuk** [comment]
Hi,

This is a fault with the underlying application. There is an open issue for it here: https://github.com/ndbroadbent/icloud_photos_downloader/issues/150

In the latest version of my container, I have applied the workaround here: https://github.com/ndbroadbent/icloud_photos_downloader/issues/150#issuecomment-668433279

However, this "fix" will only skip the album with the bad/blank name, rather than download the photos in the album correctly.

I'm not a Python coder so I don't know how to fix it properly, unfortunately.

**Comment by boredazfcuk** [comment]
I’ll close this off now as it’s nearly a week old and presumably the fix worked.

**Comment by felixg3** [comment]
Sorry for the late reply, but thanks @boredazfcuk.
