### ISSUE TITLE
Failed to initialize, unable to create cookie file

### ISSUE THREAD

**Issue by ProphetRush** [boredazfcuk/docker-icloudpd#211]
Hi, I tried for a whole night but I just can't let it run
The keyring file can be successfully generated but the 2FA cookie cannot be create and raise these error
The version of the script is 0923, so it should be the newest version already

the log stack trace: 

2022-09-24 19:08:29 INFO     Generate 2FA cookie using password stored in keyring file
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
grep: /config/631607XXXqqcom: No such file or directory
ash: out of range
2022-09-24 19:08:32 ERROR    2FA information missing from cookie. Authentication has failed
2022-09-24 19:08:32 ERROR     - Was the correct password entered?
2022-09-24 19:08:32 ERROR     - Was the 2FA code mistyped?
2022-09-24 19:08:32 ERROR     - Are you based in China? You may need to set the icloud_china variable

**Comment by ProphetRush** [comment]
problem solved. It come from a bug of pyicloud.

When I migrate docker from my previous NAS, I manually copied the env variables from QNAP Container station pages, and the front end has strangly add a whitespace before all my env value, so apple_id field is also infected.

When I start initalize the icloudpd docker, it call icloud login service with stripped username, but raw username stored in the keyring. As what I can see, login is always successful but error keep happens when generating cookies using the data stored in the keyring.

here is the responsible code of pyicloud
<img width="524" alt="image" src="https://user-images.githubusercontent.com/26762116/192356695-7b1a3627-a5bc-4326-9d96-4341a3c679d6.png">

**Comment by boredazfcuk** [comment]
Thanks for logging this. I’ve amended the code to remove the white space from the Apple ID variable. I should probably do it for all variables, but a lot of my checks are for if the variable is set or not, rather than caring about if it’s actually “True” like the documentation says.
