### ISSUE TITLE
Failed to check for new files after Unraid upgrade

### ISSUE THREAD

**Issue by B0rax** [boredazfcuk/docker-icloudpd#212]
Hi!

This docker has been working fine for me for a long time now. I decided to upgrade Unraid (the OS which manages my docker containers) from 6.9.2 to 6.11.0.

Now this docker container crashes. 2FA seems to be still valid. Discord notifications (at least the notification that the docker has started) still work. This is the log file I get when I try to start it:

```
[snip]
2022-09-26 14:43:38 INFO     Check 2FA Cookie
2022-09-26 14:43:38 INFO     Cookie exists, check expiry date
2022-09-26 14:43:38 INFO     Valid two factor authentication cookie found. Days until expiration: 67
2022-09-26 14:43:38 INFO     Check download directory mounted correctly
2022-09-26 14:43:38 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2022-09-26 14:43:38 INFO     Check for new files using password stored in keyring file
2022-09-26 14:43:38 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2022-09-26 14:43:44 ERROR    Failed check for new files files
2022-09-26 14:43:44 ERROR    Error debugging info:
2022-09-26 14:43:44 ERROR    Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1471d6f15960>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: /setup/ws/1/login?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=D87CB9B0-3D98-11ED-85FA-0242AC11000C (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1471d6f15960>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 68, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: /setup/ws/1/login?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=D87CB9B0-3D98-11ED-85FA-0242AC11000C (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1471d6f15960>: Failed to establish a new connection: [Errno -3] Try again'))
2022-09-26 14:43:44 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2022-09-26 14:43:44 INFO     Sending Discord failure notification
2022-09-26 14:43:49 ERROR    Discord failure notification failed with status code: 000
2022-09-26 14:43:49 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
```

**Comment by B0rax** [comment]
Seems to be fixed now. I updated the container to the version released yesterday.
I also signed in to iCloud through a browser (independent of this container), I don’t know which of those two actions fixed it.

**Comment by boredazfcuk** [comment]
The app which runs inside the container basically connects to the iCloud.com website and downloads the files it finds in there. Same way as you would if you were downloading the files in your web browser.

This is problematic because if the website changes at all, then it throws the downloader out. I see this issues quite a lot with my Mrs' iCloud account. I think she may have been a victim of a password leak in the past, so malicious actors discover these credentials and attempt to access the account. Multiple incorrect password attempts then lock the account.

When you log into iCloud.com after that, you get prompted with "You need to unlock your account... blah, blah, blah" and then have to go through and answer the security questions and once that's complete, it lets you in. When the app in my container connects to iCloud.com, it can't handle these prompts, so errors out.

I've also seen it where iCloud.com popped up a message about enabling 2FA on her account as well (should probably do that lol). That broke the downloader too. It's just one of those things that people need to be aware of, so I'll update the README at some point soon.
