### ISSUE TITLE
Docker in Windows 10: Telegram startup notification failed with status code: 000

### ISSUE THREAD

**Issue by pulsedriver74** [boredazfcuk/docker-icloudpd#224]
Hello everybody,

i'm a newbie in docker creation.
I've configured boredazfcuk under Windows 10, but i've got an error message when i‘ve started the docker - please see below.

In Addition, i’ve tried the command 
https://api.telegram.org/botXXXXXX/sendMessage?chat_id=-XXXXX in WebBrowser and it was successful - in Telegram Chat the Message was shown, but not with docker.

Thanks for your support and best regards!

2022-10-30 19:11:08 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2022-10-30 19:11:08 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2022-10-30 19:11:08 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2022/10/23_17:37 *****
2022-10-30 19:11:08 INFO     ***** /usr/local/bin/sync-icloud.sh hash: XXX
*****
2022-10-30 19:11:08 INFO     Alpine Linux 3.16.1
2022-10-30 19:11:08 INFO     Python version: 3.10.5
2022-10-30 19:11:09 INFO     icloudpd version: 1.7.2
2022-10-30 19:11:10 INFO     pyicloud-ipd version: 0.10.1
2022-10-30 19:11:10 INFO     Interactive session:  \(False\)
2022-10-30 19:11:10 INFO     Running user id: 0
2022-10-30 19:11:10 INFO     Running group id: 0
2022-10-30 19:11:10 INFO     Local user: boredazfcuk:1000
2022-10-30 19:11:10 INFO     Local group: admins:1010
2022-10-30 19:11:10 INFO     Force GID: False
2022-10-30 19:11:10 INFO     LAN IP Address: 192.168.2.2
2022-10-30 19:11:10 INFO     Default gateway: 192.168.2.1
2022-10-30 19:11:10 INFO     DNS server: 127.0.0.11
2022-10-30 19:11:10 INFO     IP address for icloud.com: 17.253.144.10
2022-10-30 19:11:39 INFO     Route check to icloud.com successful
2022-10-30 19:11:39 INFO     Apple ID: userid@gmx.net
2022-10-30 19:11:39 INFO     Authentication Type: 2FA
2022-10-30 19:11:39 INFO     Cookie path: /config/userid
2022-10-30 19:11:39 INFO     Cookie expiry notification period: 14
2022-10-30 19:11:39 INFO     Download destination directory: /home/boredazfcuk/iCloud
2022-10-30 19:11:39 INFO     Folder structure: {:%Y}
2022-10-30 19:11:39 INFO     Directory permissions: 750
2022-10-30 19:11:39 INFO     File permissions: 640
2022-10-30 19:11:39 INFO     Synchronisation interval: 43200
2022-10-30 19:11:39 INFO     Synchronisation delay (minutes): 0
2022-10-30 19:11:39 INFO     Set EXIF date/time: False
2022-10-30 19:11:39 INFO     Auto delete: True
2022-10-30 19:11:39 INFO     Photo size: original
2022-10-30 19:11:39 INFO     Single pass mode: False
2022-10-30 19:11:39 INFO     Skip download check: False
2022-10-30 19:11:39 INFO     Skip live photos: False
2022-10-30 19:11:39 INFO     Number of most recently added photos to download: Download All Photos
2022-10-30 19:11:39 INFO     Downloading photos from album: Download All Photos
2022-10-30 19:11:39 INFO     Stop downloading when prexisiting files count is: Download All Photos
2022-10-30 19:11:39 INFO     Live photo size: original
2022-10-30 19:11:39 INFO     Skip videos: False
2022-10-30 19:11:39 INFO     Convert HEIC to JPEG: False
2022-10-30 19:11:39 INFO     JPEG conversion quality: 90
2022-10-30 19:11:39 INFO     Notification title: boredazfcuk/iCloudPD
2022-10-30 19:11:39 INFO     Telegram notifications enabled
2022-10-30 19:11:39 INFO     Telegram token: XXXXXx
2022-10-30 19:11:39 INFO     Telegram chat id: -XXXXXX
2022-10-30 19:11:39 INFO     Telegram notification URL: https://api.telegram.org/botXXXXXXXXXXXXXXXXXX
2022-10-30 19:11:39 INFO     Telegram silent file notifications: False
2022-10-30 19:11:39 INFO     Sending Telegram startup notification
2022-10-30 19:11:39 ERROR    Telegram startup notification failed with status code: 000
2022-10-30 19:11:39 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by boredazfcuk** [comment]
Hi,

Error code 000 is basically an "Unknown error" issue. Usually a network problem at the client end. If you don't configure Telegram notifications, does it let you authenticate and download the photos?

Is there a firewall on the host machine which is blocking http(s) traffic to the Internet?

Have you configured a network for this? The default bridge doesn't operate in the same way as a named network, so it could be something to do with that.

Thanks.

**Comment by pulsedriver74** [comment]
Hi,

thanks for your answers!
Yes, i assume it's a firewall issue with my host here.

I have removed the Telegram section, but i'm getting now following errors (see below).

Many thanks for your support & best regards


 
2022-11-27 22:07:53 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2022-11-27 22:07:53 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2022-11-27 22:07:53 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2022/10/23_17:37 *****
2022-11-27 22:07:53 INFO     ***** /usr/local/bin/sync-icloud.sh hash: eb2e7819882bd52340890f1742cfdcf8 *****
2022-11-27 22:07:54 INFO     Alpine Linux 3.16.1
2022-11-27 22:07:54 INFO     Python version: 3.10.5

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
2022-11-27 22:07:54 INFO     icloudpd version: 1.7.2

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
2022-11-27 22:07:55 INFO     pyicloud-ipd version: 0.10.1
2022-11-27 22:07:55 INFO     Interactive session:  \(False\)
2022-11-27 22:07:55 INFO     Running user id: 0
2022-11-27 22:07:55 INFO     Running group id: 0
2022-11-27 22:07:55 INFO     Local user: boredazfcuk:1000
2022-11-27 22:07:55 INFO     Local group: admins:1010
2022-11-27 22:07:55 INFO     Force GID: False
2022-11-27 22:07:55 INFO     LAN IP Address: 192.168.2.2
2022-11-27 22:07:55 INFO     Default gateway: 192.168.2.1
2022-11-27 22:07:55 INFO     DNS server: 127.0.0.11
2022-11-27 22:07:55 INFO     IP address for icloud.com: 17.253.144.10
2022-11-27 22:08:26 INFO     Route check to icloud.com successful
2022-11-27 22:08:26 INFO     Apple ID: XXXXXXXXXXXX
2022-11-27 22:08:26 INFO     Authentication Type: 2FA
2022-11-27 22:08:26 INFO     Cookie path: /config/XXXXXXXXXXX
2022-11-27 22:08:26 INFO     Cookie expiry notification period: 14
2022-11-27 22:08:26 INFO     Download destination directory: /home/boredazfcuk/iCloud
2022-11-27 22:08:26 INFO     Folder structure: {:%Y}
2022-11-27 22:08:26 INFO     Directory permissions: 750
2022-11-27 22:08:26 INFO     File permissions: 640
2022-11-27 22:08:26 INFO     Synchronisation interval: 43200
2022-11-27 22:08:26 INFO     Synchronisation delay (minutes): 0
2022-11-27 22:08:26 INFO     Set EXIF date/time: False
2022-11-27 22:08:26 INFO     Auto delete: True
2022-11-27 22:08:26 INFO     Photo size: original
2022-11-27 22:08:26 INFO     Single pass mode: False
2022-11-27 22:08:26 INFO     Skip download check: False
2022-11-27 22:08:26 INFO     Skip live photos: False
2022-11-27 22:08:26 INFO     Number of most recently added photos to download: Download All Photos
2022-11-27 22:08:26 INFO     Downloading photos from album: Download All Photos
2022-11-27 22:08:26 INFO     Stop downloading when prexisiting files count is: Download All Photos
2022-11-27 22:08:26 INFO     Live photo size: original
2022-11-27 22:08:26 INFO     Skip videos: False
2022-11-27 22:08:26 INFO     Convert HEIC to JPEG: False
2022-11-27 22:08:26 INFO     JPEG conversion quality: 90
2022-11-27 22:08:26 INFO     Downloading from: icloud.com
2022-11-27 22:08:26 INFO     Nextcloud synchronisation trigger: Enabled
2022-11-27 22:08:26 INFO     Group, admins:1010, already created
2022-11-27 22:08:26 INFO     User, boredazfcuk:1000, already created
2022-11-27 22:08:26 INFO     Set owner, boredazfcuk, on iCloud directory, if required
2022-11-27 22:08:26 INFO     Set group, admins, on iCloud directory, if required
2022-11-27 22:08:26 INFO     Correct owner on icloudpd temp directory, if required
2022-11-27 22:08:26 INFO     Correct group on icloudpd temp directory, if required
2022-11-27 22:08:26 INFO     Correct owner on config directory, if required
2022-11-27 22:08:26 INFO     Correct group on config directory, if required
2022-11-27 22:08:26 INFO     Correct owner on keyring directory, if required
2022-11-27 22:08:26 INFO     Correct group on keyring directory, if required
2022-11-27 22:08:26 INFO     Set 750 permissions on iCloud directories, if required
2022-11-27 22:08:26 INFO     Set 640 permissions on iCloud files, if required
2022-11-27 22:08:26 INFO     Configure password
2022-11-27 22:08:26 ERROR    Keyring file /config/python_keyring/keyring_pass.cfg does not exist
2022-11-27 22:08:26 INFO      - Please add the your password to the system keyring using the --Initialise script command line option
2022-11-27 22:08:26 INFO      - Syntax: docker exec -it <container name> sync-icloud.sh --Initialise
2022-11-27 22:08:26 INFO      - Example: docker exec -it icloudpd sync-icloud.sh --Initialise
2022-11-27 22:08:26 INFO     Waiting for keyring file to be created...

--------------------------------------------------------------------

When i now try to add my password in the keyring, following ERROR occurs:


PS C:\WINDOWS\system32> docker exec -it iCloudPD_frank sync-icloud.sh --Initialise                                      
2022-11-27 22:04:09 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2022-11-27 22:04:09 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2022-11-27 22:04:09 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2022/10/23_17:37 *****
2022-11-27 22:04:09 INFO     ***** /usr/local/bin/sync-icloud.sh hash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*****
2022-11-27 22:04:09 INFO     Alpine Linux 3.16.1
2022-11-27 22:04:09 INFO     Python version: 3.10.5

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
2022-11-27 22:04:10 INFO     icloudpd version: 1.7.2

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
2022-11-27 22:04:11 INFO     pyicloud-ipd version: 0.10.1
2022-11-27 22:04:11 INFO     Interactive session:  \(False\)
2022-11-27 22:04:11 INFO     Running user id: 0
2022-11-27 22:04:11 INFO     Running group id: 0
2022-11-27 22:04:11 INFO     Local user: boredazfcuk:1000
2022-11-27 22:04:11 INFO     Local group: admins:1010
2022-11-27 22:04:11 INFO     Force GID: False
2022-11-27 22:04:11 INFO     LAN IP Address: 192.168.2.2
2022-11-27 22:04:11 INFO     Default gateway: 192.168.2.1
2022-11-27 22:04:11 INFO     DNS server: 127.0.0.11
2022-11-27 22:04:11 INFO     IP address for icloud.com: 17.253.144.10
2022-11-27 22:04:41 INFO     Route check to icloud.com successful
2022-11-27 22:04:41 INFO     Apple ID: xxxxxxxxxxxxxxxxxxxxxxxxxxx
2022-11-27 22:04:41 INFO     Authentication Type: 2FA
2022-11-27 22:04:41 INFO     Cookie path: /config/xxxxxxxxxxxxxxxxxxxxxxxx
2022-11-27 22:04:41 INFO     Cookie expiry notification period: 14
2022-11-27 22:04:41 INFO     Download destination directory: /home/boredazfcuk/iCloud
2022-11-27 22:04:41 INFO     Folder structure: {:%Y}
2022-11-27 22:04:41 INFO     Directory permissions: 750
2022-11-27 22:04:41 INFO     File permissions: 640
2022-11-27 22:04:41 INFO     Synchronisation interval: 43200
2022-11-27 22:04:41 INFO     Synchronisation delay (minutes): 0
2022-11-27 22:04:41 INFO     Set EXIF date/time: False
2022-11-27 22:04:41 INFO     Auto delete: True
2022-11-27 22:04:41 INFO     Photo size: original
2022-11-27 22:04:41 INFO     Single pass mode: False
2022-11-27 22:04:41 INFO     Skip download check: False
2022-11-27 22:04:41 INFO     Skip live photos: False
2022-11-27 22:04:41 INFO     Number of most recently added photos to download: Download All Photos
2022-11-27 22:04:41 INFO     Downloading photos from album: Download All Photos
2022-11-27 22:04:41 INFO     Stop downloading when prexisiting files count is: Download All Photos
2022-11-27 22:04:41 INFO     Live photo size: original
2022-11-27 22:04:41 INFO     Skip videos: False
2022-11-27 22:04:41 INFO     Convert HEIC to JPEG: False
2022-11-27 22:04:41 INFO     JPEG conversion quality: 90
2022-11-27 22:04:41 INFO     Downloading from: icloud.com
2022-11-27 22:04:42 INFO     Nextcloud synchronisation trigger: Enabled
2022-11-27 22:04:42 INFO     Script launch parameters: --Initialise
2022-11-27 22:04:42 INFO     Group, admins:1010, already created
2022-11-27 22:04:42 INFO     User, boredazfcuk:1000, already created
2022-11-27 22:04:42 INFO     Set owner, boredazfcuk, on iCloud directory, if required
2022-11-27 22:04:42 INFO     Set group, admins, on iCloud directory, if required
2022-11-27 22:04:42 INFO     Correct owner on icloudpd temp directory, if required
2022-11-27 22:04:42 INFO     Correct group on icloudpd temp directory, if required
2022-11-27 22:04:42 INFO     Correct owner on config directory, if required
2022-11-27 22:04:42 INFO     Correct group on config directory, if required
2022-11-27 22:04:42 INFO     Correct owner on keyring directory, if required
2022-11-27 22:04:42 INFO     Correct group on keyring directory, if required
2022-11-27 22:04:42 INFO     Set 750 permissions on iCloud directories, if required
2022-11-27 22:04:42 INFO     Set 640 permissions on iCloud files, if required
2022-11-27 22:04:42 INFO     Configure password
2022-11-27 22:04:42 INFO     Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for XXXXXXXXXXXXXXXXXXXX:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: /setup/ws/1/login?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=8963AAED-6E9F-11ED-9C70-0242C0A80202 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 68, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: /setup/ws/1/login?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=8963AAED-6E9F-11ED-9C70-0242C0A80202 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
2022-11-27 22:05:00 INFO     Correct owner on config directory, if required
2022-11-27 22:05:00 INFO     Correct group on config directory, if required
2022-11-27 22:05:00 INFO     Generate 2FA cookie using password stored in keyring file
iCloud Password:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for XXXXXXXXXXXXXXXXXXXX@gmx.net could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: /setup/ws/1/login?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=9945FB65-6E9F-11ED-BF0D-0242C0A80202 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 68, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: /setup/ws/1/login?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=9945FB65-6E9F-11ED-BF0D-0242C0A80202 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
grep: /config/XXXXXXXXXXXXXXXXXXX: No such file or directory
ash: out of range
2022-11-27 22:05:27 ERROR    2FA information missing from cookie. Authentication has failed
2022-11-27 22:05:27 ERROR     - Was the correct password entered?
2022-11-27 22:05:27 ERROR     - Was the 2FA code mistyped?
2022-11-27 22:05:27 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2022-11-27 22:05:27 ERROR     - Are you based in China? You may need to set the icloud_china variable

**Comment by boredazfcuk** [comment]
`
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain `

This suggests something is intercepting your traffic (Squid cache proxy server, maybe?). There should not be any self-signed certificates in the cert chain from Apple.

**Comment by boredazfcuk** [comment]
Closing due to inactivity.
