### ISSUE TITLE
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, Failed to resolve 'accountservice.p00.prod.me.com' after 6 queries `

### ISSUE THREAD

**Issue by china31** [boredazfcuk/docker-icloudpd#241]
2022-12-05 18:22:56 DEBUG    Authenticating...
2022-12-05 18:22:59 INFO     Two-step/two-factor authentication is required!
Traceback (most recent call last):
  File "/usr/local/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/local/lib/python3.8/dist-packages/icloudpd/authentication.py", line 47, in authenticate
    request_2sa(icloud, logger)
  File "/usr/local/lib/python3.8/dist-packages/icloudpd/authentication.py", line 53, in request_2sa
    devices = icloud.trusted_devices
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py", line 249, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, Failed to resolve 'accountservice.p00.prod.me.com' after 6 queries

**Comment by bbiagent** [comment]
一样的情况

**Comment by michaelin1208** [comment]
Same issue

**Comment by boredazfcuk** [comment]
Duplicate
