### ISSUE TITLE
See that the error is still reported after today's update

### ISSUE THREAD

**Issue by china31** [boredazfcuk/docker-icloudpd#251]
Two-step authentication required. Your trusted devices are:
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 216, in main
    devices = api.trusted_devices
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 249, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, Failed to resolve 'accountservice.p00.prod.me.com' after 6 queries 
2022-12-30 00:11:28 INFO     Correct owner on config directory, if required
2022-12-30 00:11:28 INFO     Correct group on config directory, if required
2022-12-30 00:11:28 INFO     Generate 2FA cookie using password stored in keyring file
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/authentication.py", line 47, in authenticate
    request_2sa(icloud, logger)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/authentication.py", line 53, in request_2sa
    devices = icloud.trusted_devices
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 249, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, Failed to resolve 'accountservice.p00.prod.me.com' after 6 queries 
2022-12-30 00:11:32 ERROR    2FA information missing from cookie. Authentication has failed
2022-12-30 00:11:32 ERROR     - Was the correct password entered?
2022-12-30 00:11:32 ERROR     - Was the 2FA code mistyped?
2022-12-30 00:11:32 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?

**Comment by tokyoqiang** [comment]
same error for me, we really appreciate that boredazfcuk can help to update the coding for docker after his happy & busy holiday :-)

**Comment by yanghano** [comment]
pjoc/docker-icloudpd:master 用这个docker相同的设置，跑一下两步验证，成功后可以换回原版的

**Comment by china31** [comment]
> pjoc/docker-iCloudPD：Master 用这个 docker 相同的设置，跑一下两步验证，成功后可以换回原版的

如何换回原版呢

**Comment by tokyoqiang** [comment]
1. docker里下载镜像 pjoc/docker-icloudpd；
2. 在portainer里，点击你icloud的容器，选择复制，镜像填pjoc/docker-icloudpd，此时会自动创建新容器（配置和之前一样）；
3. 在新容器里运行 sync-icloud.sh --Initialise，等2步验证成功；
4. 在portainer里，点击你icloud的容器，选择复制，镜像填boredazfcuk/icloudpd
5. 这时下载应该就好了。

**Comment by yanghano** [comment]
> > pjoc/docker-iCloudPD：Master 用这个 docker 相同的设置，跑一下两步验证，成功后可以换回原版的
> 
> 如何换回原版呢

原版和pjoc版本用一个挂载路径就行了，pjoc设置完关掉再启动原版的就行，直接启动不用初始化。

**Comment by china31** [comment]
> 1. docker里下载镜像 pjoc/docker-icloudpd；
> 2. 在portainer里，点击你icloud的容器，选择复制，镜像填pjoc/docker-icloudpd，此时会自动创建新容器（配置和之前一样）；
> 3. 在新容器里运行 sync-icloud.sh --Initialise，等2步验证成功；
> 4. 在portainer里，点击你icloud的容器，选择复制，镜像填boredazfcuk/icloudpd
> 5. 这时下载应该就好了。

感谢，其实只需要复制pjoc/docker-icloudpd产生的新cookie的内容覆盖以前的即可恢复使用。

**Comment by china31** [comment]
> > > pjoc/docker-iCloudPD：Master 用这个 docker 相同的设置，跑一下两步验证，成功后可以换回原版的
> > 
> > 
> > 如何换回原版呢
> 
> 原版和pjoc版本用一个挂载路径就行了，pjoc设置完关掉再启动原版的就行，直接启动不用初始化。

已解决，感谢您

**Comment by AlexaAmaya** [comment]
> 1. docker里下载镜像 pjoc/docker-icloudpd；
> 2. 在portainer里，点击你icloud的容器，选择复制，镜像填pjoc/docker-icloudpd，此时会自动创建新容器（配置和之前一样）；
> 3. 在新容器里运行 sync-icloud.sh --Initialise，等2步验证成功；
> 4. 在portainer里，点击你icloud的容器，选择复制，镜像填boredazfcuk/icloudpd
> 5. 这时下载应该就好了。

目前显示docker无法下载这个镜像。

**Comment by Aiaiioi** [comment]
> > 1. docker里下载镜像 pjoc/docker-icloudpd；
> > 2. 在portainer里，点击你icloud的容器，选择复制，镜像填pjoc/docker-icloudpd，此时会自动创建新容器（配置和之前一样）；
> > 3. 在新容器里运行 sync-icloud.sh --Initialise，等2步验证成功；
> > 4. 在portainer里，点击你icloud的容器，选择复制，镜像填boredazfcuk/icloudpd
> > 5. 这时下载应该就好了。
> 
> 目前显示docker无法下载这个镜像。

pjoc/docker-icloudpd:sha-0c2060f
拉这个试试看。

**Comment by AlexaAmaya** [comment]
> 



> > > 1. docker里下载镜像 pjoc/docker-icloudpd；
> > > 2. 在portainer里，点击你icloud的容器，选择复制，镜像填pjoc/docker-icloudpd，此时会自动创建新容器（配置和之前一样）；
> > > 3. 在新容器里运行 sync-icloud.sh --Initialise，等2步验证成功；
> > > 4. 在portainer里，点击你icloud的容器，选择复制，镜像填boredazfcuk/icloudpd
> > > 5. 这时下载应该就好了。
> > 
> > 
> > 目前显示docker无法下载这个镜像。
> 
> pjoc/docker-icloudpd:sha-0c2060f 拉这个试试看。

我发现好像也拉不下来，日志报了个错说无法下载。sad

**Comment by AlexaAmaya** [comment]
首先，感谢各位大佬。

1. 根据https://github.com/boredazfcuk/docker-icloudpd/issues/251#issuecomment-1416857406，下载新的img。（之前家里的nas一直下载不了，倒腾了很久也不行，昨晚重启了下，好了）；
2. 导出“容器设置”，并替换 "image" : "pjoc/docker-icloudpd:sha-0c2060f"；
3. 导入刚导出的json，建立新的容器；
4. sync-icloud.sh --Initialise
5. 熟悉的2fa又回来了

但是日志也报错了，不知道是什么原因。
![231676853670_ pic](https://user-images.githubusercontent.com/109637800/219985769-34bb6095-3a9f-48c3-aaf8-c93bd2a2a112.jpg)

**Comment by AlexaAmaya** [comment]
> 首先，感谢各位大佬。
> 
> 1. 根据[See that the error is still reported after today's update #251 (comment)](https://github.com/boredazfcuk/docker-icloudpd/issues/251#issuecomment-1416857406)    -- 下载新的img。（之前家里的nas一直下载不了，倒腾了很久也不行，昨晚重启了下，好了）；
> 2. 导出“容器设置”，并替换 "image" : "pjoc/docker-icloudpd:sha-0c2060f"；
> 3. 导入刚导出的json，建立新的容器；
> 4. sync-icloud.sh --Initialise
> 5. 熟悉的2fa又回来了
> 6. 但是日志也报错了，不知道是什么原因。
>    ![231676853670_ pic](https://user-images.githubusercontent.com/109637800/219985769-34bb6095-3a9f-48c3-aaf8-c93bd2a2a112.jpg)
> 7. 这个状态等了很久了，看之前回复好像再运行之前的img就行了。
>    ![241676854145_ pic](https://user-images.githubusercontent.com/109637800/219986241-c138811c-9fce-4980-a6f5-f00976ab09c4.jpg)

更新下，关闭pjoc/docker-icloudpd:sha-0c2060f（他解决了2fa，完成了使命），重新打开旧的img就行了。
![251676859516_ pic](https://user-images.githubusercontent.com/109637800/219994703-dbb0d087-5be2-4d6c-a9df-97cb73197343.jpg)

**Comment by alienwow** [comment]
> > 首先，感谢各位大佬。
> > 
> > 1. 根据[See that the error is still reported after today's update #251 (comment)](https://github.com/boredazfcuk/docker-icloudpd/issues/251#issuecomment-1416857406)    -- 下载新的img。（之前家里的nas一直下载不了，倒腾了很久也不行，昨晚重启了下，好了）；
> > 2. 导出“容器设置”，并替换 "image" : "pjoc/docker-icloudpd:sha-0c2060f"；
> > 3. 导入刚导出的json，建立新的容器；
> > 4. sync-icloud.sh --Initialise
> > 5. 熟悉的2fa又回来了
> > 6. 但是日志也报错了，不知道是什么原因。
> >    ![231676853670_ pic](https://user-images.githubusercontent.com/109637800/219985769-34bb6095-3a9f-48c3-aaf8-c93bd2a2a112.jpg)
> > 7. 这个状态等了很久了，看之前回复好像再运行之前的img就行了。
> >    ![241676854145_ pic](https://user-images.githubusercontent.com/109637800/219986241-c138811c-9fce-4980-a6f5-f00976ab09c4.jpg)
> 
> 更新下，关闭pjoc/docker-icloudpd:sha-0c2060f（他解决了2fa，完成了使命），重新打开旧的img就行了。 ![251676859516_ pic](https://user-images.githubusercontent.com/109637800/219994703-dbb0d087-5be2-4d6c-a9df-97cb73197343.jpg)

Wow, great job, mine can be synchronized too！ thx！

**Comment by boredazfcuk** [comment]
New version pushed to Dockerhub which may resolve this issue.
