### ISSUE TITLE
2FA ERROR

### ISSUE THREAD

**Issue by hayhaps** [boredazfcuk/docker-icloudpd#257]
Two-step authentication required. Your trusted devices are:
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 216, in main
    devices = api.trusted_devices
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 249, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, Failed to resolve 'accountservice.p00.prod.me.com' after 6 queries 
2023-01-05 21:54:28 INFO     Correct owner on config directory, if required
2023-01-05 21:54:28 INFO     Correct group on config directory, if required
2023-01-05 21:54:28 INFO     Generate 2FA cookie using password stored in keyring file
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/authentication.py", line 47, in authenticate
    request_2sa(icloud, logger)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/authentication.py", line 53, in request_2sa
    devices = icloud.trusted_devices
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 249, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, Failed to resolve 'accountservice.p00.prod.me.com' after 6 queries 
2023-01-05 21:54:32 ERROR    2FA information missing from cookie. Authentication has failed
2023-01-05 21:54:32 ERROR     - Was the correct password entered?
2023-01-05 21:54:32 ERROR     - Was the 2FA code mistyped?
2023-01-05 21:54:32 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?

**Comment by ysslang** [comment]
I got the same error.

**Comment by lenzhang** [comment]
same error

**Comment by li77leprince** [comment]
same error

**Comment by alienwow** [comment]
how to fix it?

**Comment by alienwow** [comment]
I got the same error.
how to fix it?

**Comment by AlexaAmaya** [comment]
> 首先，感谢各位大佬。
> 
> 1. 根据[See that the error is still reported after today's update #251 (comment)](https://github.com/boredazfcuk/docker-icloudpd/issues/251#issuecomment-1416857406)    -- 下载新的img。（之前家里的nas一直下载不了，倒腾了很久也不行，昨晚重启了下，好了）；
> 2. 导出“容器设置”，并替换 "image" : "pjoc/docker-icloudpd:sha-0c2060f"；
> 3. 导入刚导出的json，建立新的容器；
> 4. sync-icloud.sh --Initialise
> 5. 熟悉的2fa又回来了
> 6. 但是日志也报错了，不知道是什么原因。
>    ![231676853670_ pic](https://user-images.githubusercontent.com/109637800/219985769-34bb6095-3a9f-48c3-aaf8-c93bd2a2a112.jpg)
> 7. 这个状态等了很久了，看之前回复好像再运行之前的img就行了。
>    ![241676854145_ pic](https://user-images.githubusercontent.com/109637800/219986241-c138811c-9fce-4980-a6f5-f00976ab09c4.jpg)

更新下，关闭pjoc/docker-icloudpd:sha-0c2060f（他解决了2fa，完成了使命），重新打开旧的img就行了。
![251676859516_ pic](https://user-images.githubusercontent.com/109637800/219994703-dbb0d087-5be2-4d6c-a9df-97cb73197343.jpg)

**Comment by boredazfcuk** [comment]
New version pushed to Dockerhub which should fix this issue.
