### ISSUE TITLE
recent three days each breakdown with this error 

### ISSUE THREAD

**Issue by QXmastEr** [boredazfcuk/docker-icloudpd#260]
2023-01-13 23:12:25 ERROR    Failed to download new files
2023-01-13 23:12:25 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-01-13 23:12:25 ERROR    Error debugging info:
2023-01-13 23:12:25 ERROR    Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 562, in main
    download_photo(consecutive_files_found, item)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 489, in download_photo
    (".jpg", ".jpeg")) and not exif_datetime.get_photo_exif(download_path):
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/exif_datetime.py", line 11, in get_photo_exif
    exif_dict = piexif.load(path)
  File "/usr/lib/python3.10/site-packages/piexif/_load.py", line 53, in load
    exif_dict["1st"] = exifReader.get_ifd_dict(pointer, "1st")
  File "/usr/lib/python3.10/site-packages/piexif/_load.py", line 108, in get_ifd_dict
    tag_count = struct.unpack(self.endian_mark + "H",
struct.error: unpack requires a buffer of 2 bytes
2023-01-13 23:12:25 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by boredazfcuk** [comment]
This is usually due to a file/folder with a bad name. Please check the file/folder names for non-standard characters.

**Comment by boredazfcuk** [comment]
Closing due to inactivity.
