### ISSUE TITLE
Failed check for new files files

### ISSUE THREAD

**Issue by yong-lionheart** [boredazfcuk/docker-icloudpd#261]
I am using the docker：pjoc/docker-icloudpd:master  to fix the 2FA issue in China,
so far I can create the key-ring, but after that I met below issue. 
Can you help me?

2023-01-14 18:06:42 INFO     Check for new files using password stored in keyring file                                                                                                                                                      
2023-01-14 18:06:42 INFO     Generating list of files in iCloud. This may take a             
 long time if you have a large photo collection. Please be patient. Nothing is b                                                                            
eing downloaded at this time                                                                                                                                
2023-01-14 18:06:49 ERROR    Failed check for new files files                                                                                               
2023-01-14 18:06:49 ERROR     - Can you log into iCloud.com without receiving po                                                                            
p-up notifications?                                                                                                                                         
2023-01-14 18:06:49 ERROR    Error debugging info:                                                                                                          
2023-01-14 18:06:49 ERROR    Traceback (most recent call last):                                                                                             
  File "/usr/bin/icloudpd", line 33, in <module>                                                                                                            
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')(                                                                            
))                                                                                                                                                          
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__                                                                            
    return self.main(*args, **kwargs)                                                                                                                       
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main                                                                                
    rv = self.invoke(ctx)                                                                                                                                   
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke                                                                              
    return ctx.invoke(self.callback, **ctx.params)                                                                                                          
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke                                                                               
    return __callback(*args, **kwargs)                                                                                                                      
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/bas                                                                            
e.py", line 563, in main                                                                                                                                    
    download_photo(consecutive_files_found, item)                                                                                                           
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/bas                                                                            
e.py", line 392, in download_photo                                                                                                                          
    date_path = folder_structure.format(created_date)                                                                                                       
KeyError: ' '                                                                                                                                               
2023-01-14 18:06:49 ERROR    ***** Please report problems here: https://github.c                                                                            
om/boredazfcuk/docker-icloudpd/issues *****

**Comment by eflylab** [comment]
+1

**Comment by Yob42** [comment]
Same

2023-01-20 16:22:45 INFO     Synchronisation starting at 16:22:45
2023-01-20 16:22:45 INFO     Check 2FA Cookie
2023-01-20 16:22:45 INFO     Cookie exists, check expiry date
2023-01-20 16:22:45 INFO     Valid two factor authentication cookie found. Days until expiration: 89
2023-01-20 16:22:45 INFO     Check download directory mounted correctly
2023-01-20 16:22:45 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-01-20 16:22:45 INFO     Check for new files using password stored in keyring file
2023-01-20 16:22:45 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
iCloud Photo Library not finished indexing.  Please try again later. This process may take hours.
2023-01-20 16:22:50 ERROR    Failed check for new files files
2023-01-20 16:22:50 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-01-20 16:22:50 ERROR    Error debugging info:
2023-01-20 16:22:50 ERROR    
2023-01-20 16:22:50 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by boredazfcuk** [comment]
Please upgrade to latest version of the container and try again.
