### ISSUE TITLE
Failed check for new files files & AttributeError: 'PhotoAsset' object has no attribute 'item_type'

### ISSUE THREAD

**Issue by ProphetRush** [boredazfcuk/docker-icloudpd#269]
2023-01-24 20:12:36 INFO     Failsafe file /home/Prophet/iCloud/.mounted exists, continuing
2023-01-24 20:12:36 INFO     Check for new files using password stored in keyring file
2023-01-24 20:12:36 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-01-24 20:12:41 ERROR    Failed check for new files files
2023-01-24 20:12:41 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-01-24 20:12:41 ERROR    Error debugging info:
2023-01-24 20:12:41 ERROR    Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 565, in main
    download_photo(consecutive_files_found, item)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 379, in download_photo
    if photo.item_type not in ("image", "movie"):
AttributeError: 'PhotoAsset' object has no attribute 'item_type'
2023-01-24 20:12:41 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by JinhanM** [comment]
how did you solved this problem? I encontered the same question.
I didnt see "two step authentication required" when I set my password in terminal.
please help
