### ISSUE TITLE
前段时间qzchenwl修改icloudpd的暂时可用，但是现在中国区用户，又无法使用了！请问有办法修复么？

### ISSUE THREAD

**Issue by shaoj0013** [boredazfcuk/docker-icloudpd#289]
2023-03-11 21:07:38 INFO     Correct group on keyring directory, if required
2023-03-11 21:07:38 INFO     Configure password
2023-03-11 21:07:38 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2023-03-11 21:07:38 INFO     Check download directory mounted correctly
2023-03-11 21:07:38 INFO     Failsafe file /mnt/admin/Photos/iCloud/dengss0214/.mounted exists, continuing
2023-03-11 21:07:38 INFO     Correct owner on icloudpd temp directory, if required
2023-03-11 21:07:38 INFO     Correct group on icloudpd temp directory, if required
2023-03-11 21:07:38 INFO     Correct owner on config directory, if required
2023-03-11 21:07:38 INFO     Correct group on config directory, if required
2023-03-11 21:07:38 INFO     Correct owner on keyring directory, if required
2023-03-11 21:07:38 INFO     Correct group on keyring directory, if required
2023-03-11 21:07:38 INFO     Sync user admin
2023-03-11 21:07:38 INFO     Synchronisation starting at 21:07:38
2023-03-11 21:07:38 INFO     Check 2FA Cookie
2023-03-11 21:07:38 INFO     Cookie exists, check expiry date
2023-03-11 21:07:38 INFO     Valid two factor authentication cookie found. Days until expiration: 82
2023-03-11 21:07:38 INFO     Check download directory mounted correctly
2023-03-11 21:07:38 INFO     Failsafe file /mnt/admin/Photos/iCloud/dengss0214/.mounted exists, continuing
2023-03-11 21:07:38 INFO     Check for new files using password stored in keyring file
2023-03-11 21:07:38 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-03-11 21:11:53 ERROR    Failed check for new files files
2023-03-11 21:11:53 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-03-11 21:11:53 ERROR    Error debugging info:
2023-03-11 21:11:53 ERROR    Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f73f6240610>, 'Connection to setup.icloud.com.cn timed out. (connect timeout=None)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='setup.icloud.com.cn', port=443): Max retries exceeded with url: /setup/ws/1/validate (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f73f6240610>, 'Connection to setup.icloud.com.cn timed out. (connect timeout=None)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 8, in <module>
sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 260, in main
    icloud = authenticate(
  File "/usr/lib/python3.10/site-packages/icloudpd/authentication.py", line 31, in authenticate
    icloud = pyicloud.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 279, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 295, in authenticate
    self.data = self._validate_token()
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 389, in _validate_token
    req = self.session.post("%s/validate" % self.SETUP_ENDPOINT, data="null")
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 78, in request
    response = super().request(method, url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
  raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='setup.icloud.com.cn', port=443): Max retries exceeded with url: /setup/ws/1/validate (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f73f6240610>, 'Connection to setup.icloud.com.cn timed out. (connect timeout=None)'))
2023-03-11 21:11:53 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-03-11 21:11:53 INFO     Web cookie expires: 2023-05-03 @ 07:00:10
2023-03-11 21:11:53 INFO     Two factor authentication cookie expires: 2023-06-02 @ 07:00:44
2023-03-11 21:11:53 INFO     Days remaining until expiration: 82
2023-03-11 21:11:53 INFO     iCloud login counter = 1
2023-03-11 21:11:53 INFO     Synchronisation ended at 21:11:53
2023-03-11 21:11:53 INFO     Total time taken: 00:04:15
2023-03-11 21:11:53 INFO     Next synchronisation at 09:07:38

**Comment by boredazfcuk** [comment]
Connection timeout suggests network/firewall issues.
