### ISSUE TITLE
icloudpy update，fixed region china login

### ISSUE THREAD

**Issue by jiaoting** [boredazfcuk/docker-icloudpd#290]
https://github.com/mandarons/icloudpy/releases

**Comment by AndreyNikiforov** [comment]
@jiaoting how is your work helps/related to this project? It is a wrapper around pyicloud only, right?

**Comment by jiaoting** [comment]
2023-03-16 20:34:16 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2023-03-16 20:34:16 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-03-16 20:34:16 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2023/03/16_05:23 *****
2023-03-16 20:34:16 INFO     ***** /usr/local/bin/sync-icloud.sh hash: caed431192b8c6326aa1ed119d14fbb8 *****
2023-03-16 20:34:16 INFO     Alpine Linux 3.17.2
2023-03-16 20:34:16 INFO     Python version: 3.10.10
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
2023-03-16 20:34:18 INFO     icloudpd version: 1.12.0
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
2023-03-16 20:34:19 INFO     pyicloud-ipd version: 
2023-03-16 20:34:19 INFO     Running user id: 0
2023-03-16 20:34:19 INFO     Running group id: 0
2023-03-16 20:34:19 INFO     Local user: user:1000
2023-03-16 20:34:19 INFO     Local group: group:1000
2023-03-16 20:34:19 INFO     Force GID: False
2023-03-16 20:34:19 INFO     LAN IP Address: 172.17.0.7
2023-03-16 20:34:19 INFO     Default gateway: 172.17.0.1
2023-03-16 20:34:19 INFO     DNS server: 192.168.111.1
2023-03-16 20:34:19 INFO     IP address for icloud.com: 103.115.248.1
2023-03-16 20:34:43 INFO     Route check to icloud.com.cn successful
2023-03-16 20:34:43 INFO     Apple ID: jiaoting@126.com
2023-03-16 20:34:43 INFO     Authentication Type: 2FA
2023-03-16 20:34:43 INFO     Cookie path: /config/jiaoting126com
2023-03-16 20:34:43 INFO     Cookie expiry notification period: 7
2023-03-16 20:34:43 INFO     Download destination directory: /home/user/iCloud
2023-03-16 20:34:43 INFO     Folder structure: {:%Y/%m/%d}
2023-03-16 20:34:43 INFO     Directory permissions: 777
2023-03-16 20:34:43 INFO     File permissions: 666
2023-03-16 20:34:43 INFO     Synchronisation interval: 86400
2023-03-16 20:34:43 INFO     Synchronisation delay (minutes): 0
2023-03-16 20:34:43 INFO     Set EXIF date/time: False
2023-03-16 20:34:43 INFO     Auto delete: true
2023-03-16 20:34:43 INFO     Delete after download: False
2023-03-16 20:34:43 INFO     Photo size: original
2023-03-16 20:34:43 INFO     Single pass mode: False
2023-03-16 20:34:43 INFO     Skip download check: False
2023-03-16 20:34:43 INFO     Skip live photos: False
2023-03-16 20:34:43 INFO     Number of most recently added photos to download: Download All Photos
2023-03-16 20:34:43 INFO     Downloading photos from album: Download All Photos
2023-03-16 20:34:43 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-03-16 20:34:43 INFO     Live photo size: original
2023-03-16 20:34:43 INFO     Skip videos: False
2023-03-16 20:34:43 INFO     Convert HEIC to JPEG: False
2023-03-16 20:34:43 INFO     JPEG conversion quality: 90
2023-03-16 20:34:43 INFO     Nextcloud synchronisation trigger: Disabled
2023-03-16 20:34:43 INFO     Script launch parameters: --Initialise
2023-03-16 20:34:43 INFO     Group, group:1000, already created
2023-03-16 20:34:43 INFO     User, user:1000, already created
2023-03-16 20:34:43 INFO     Correct owner on icloudpd temp directory, if required
2023-03-16 20:34:43 INFO     Correct group on icloudpd temp directory, if required
2023-03-16 20:34:43 INFO     Correct owner on config directory, if required
2023-03-16 20:34:43 INFO     Correct group on config directory, if required
2023-03-16 20:34:43 INFO     Correct owner on keyring directory, if required
2023-03-16 20:34:43 INFO     Correct group on keyring directory, if required
2023-03-16 20:34:43 INFO     Configure password
2023-03-16 20:34:43 INFO     Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for jiaoting@126.com: 
Traceback (most recent call last):
  File "/usr/bin/icloud", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 234, in authenticate
    raise PyiCloudConnectionException(msg)
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter
2023-03-16 20:35:20 INFO     Correct owner on config directory, if required
2023-03-16 20:35:20 INFO     Correct group on config directory, if required
2023-03-16 20:35:20 INFO     Generate 2FA cookie using password stored in keyring file
iCloud Password: 
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 571, in core
    icloud = authenticator(domain)(
  File "/usr/lib/python3.10/site-packages/icloudpd/authentication.py", line 31, in authenticate_
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 234, in authenticate
    raise PyiCloudConnectionException(msg)
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter
grep: /config/jiaoting126com: No such file or directory
ash: out of range
2023-03-16 20:35:27 ERROR    2FA information missing from cookie. Authentication has failed
2023-03-16 20:35:27 ERROR     - Was the correct password entered?
2023-03-16 20:35:27 ERROR     - Was the 2FA code mistyped?
2023-03-16 20:35:27 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?

**Comment by boredazfcuk** [comment]
Fixed in latest version of the container.
