### ISSUE TITLE
Exception on Initialise

### ISSUE THREAD

**Issue by timvanmeurs** [boredazfcuk/docker-icloudpd#300]
With the latest version I'm getting the following exception when doing an Initialise:

```
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.12.0', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 572, in core
    icloud = authenticator(domain)(
  File "/usr/lib/python3.10/site-packages/icloudpd/authentication.py", line 35, in authenticate_
    icloud = pyicloud.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 279, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 345, in authenticate
    self._webservices = self.data["webservices"]
KeyError: 'webservices'
```

Version info:
```
2023-04-01 08:10:04 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2023/04/01_01:40 *****
2023-04-01 08:10:04 INFO     ***** /usr/local/bin/sync-icloud.sh hash: 961362b82c760eb5feb3629e629eb166 *****
2023-04-01 08:10:04 INFO     Alpine Linux 3.17.2
2023-04-01 08:10:04 INFO     Python version: 3.10.10
2023-04-01 08:10:05 INFO     icloudpd version: 1.12.0
2023-04-01 08:10:07 INFO     pyicloud version: 1.0.0
```

**Comment by boredazfcuk** [comment]
Hi, I pushed a new version out with a patch incorporated which was supposed fix the iCloud China authentication issue... It didn't though, so I've now reverted to an older version of the container.

**Comment by timvanmeurs** [comment]
thanks, update worked indeed!
