### ISSUE TITLE
Failed check for new files files

### ISSUE THREAD

**Issue by mikmil48** [boredazfcuk/docker-icloudpd#301]
023-04-04 00:27:40 ERROR    Failed check for new files files
2023-04-04 00:27:40 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-04 00:27:40 ERROR    Error debugging info:
2023-04-04 00:27:40 ERROR    Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 563, in main
    download_photo(consecutive_files_found, item)
  File "/usr/lib/python3.10/site-packages/icloudpd-1.7.2-py3.10.egg/icloudpd/base.py", line 381, in download_photo
    created_date = photo.created.astimezone(get_localzone())
  File "/usr/lib/python3.10/site-packages/tzlocal/unix.py", line 209, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/lib/python3.10/site-packages/tzlocal/unix.py", line 167, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/usr/lib/python3.10/site-packages/tzlocal/utils.py", line 124, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like New York/New York. \nPlease use a timezone in the form of Continent/City'
2023-04-04 00:27:40 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-04-04 00:27:40 INFO     Web cookie expires: 2023-05-26 @ 23:23:20
2023-04-04 00:27:40 INFO     Two factor authentication cookie expires: 2023-06-25 @ 23:23:41
2023-04-04 00:27:40 INFO     Days remaining until expiration: 82
2023-04-04 00:27:40 INFO     Synchronisation ended at 00:27:40
2023-04-04 00:27:40 INFO     Total time taken: 00:00:06
2023-04-04 00:27:40 INFO     Next synchronisation at 00:27:34

**Comment by captainbarf** [comment]
having the exact same issue!

**Comment by tfpiaoyang** [comment]
Same here.

**Comment by JoshuaLiew** [comment]
me too

**Comment by michaelin1208** [comment]
Mark, same issue

**Comment by swapfun** [comment]
The same issue with yours

**Comment by boredazfcuk** [comment]
I can't tell where the problem has occurred as the log snip is too short. This bit suggests your time zone is incorrect though:
```
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like New York/New York. \nPlease use a timezone in the form of Continent/City'
```

**Comment by boredazfcuk** [comment]
Please update to latest version of container, set the time zone correctly and test again. Please reopen the issue if you still have a problem.

**Comment by captainbarf** [comment]
Still seem to be having the same problem after update 

 File "/opt/icloudpd_v1.12.0/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 728, in core
    download_photo(consecutive_files_found, item)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 361, in download_photo_
    created_date = photo.created.astimezone(get_localzone())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/tzlocal/unix.py", line 209, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/tzlocal/unix.py", line 167, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/tzlocal/utils.py", line 124, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like america/new york. \nPlease use a timezone in the form of Continent/City'

**Comment by mikmil48** [comment]
2023-04-10 19:47:32 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.280 started *****
2023-04-10 19:47:32 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-04-10 19:47:32 INFO     Alpine Linux 3.17.3
2023-04-10 19:47:32 INFO     Python version: 3.10.11
2023-04-10 19:47:32 INFO     Apple ID: jmillercrnp@gmail.com
2023-04-10 19:47:32 INFO     Authentication Type: 2FA
2023-04-10 19:47:32 INFO     Cookie path: /config/jmillercrnpgmailcom
2023-04-10 19:47:32 INFO     Cookie expiry notification period: 7
2023-04-10 19:47:32 INFO     Download destination directory: /home/user/iCloud
2023-04-10 19:47:32 INFO     Folder structure: {:%Y/%m/%d}
2023-04-10 19:47:32 INFO     Synchronisation interval: 86400
2023-04-10 19:47:32 INFO     Synchronisation delay (minutes): 0
2023-04-10 19:47:32 INFO     Set EXIF date/time: false
2023-04-10 19:47:32 INFO     Auto delete: false
2023-04-10 19:47:32 INFO     Photo size: original
2023-04-10 19:47:32 INFO     Single pass mode: false
2023-04-10 19:47:32 INFO     Skip download check: false
2023-04-10 19:47:32 INFO     Skip live photos: false
2023-04-10 19:47:32 INFO     Number of most recently added photos to download: Download All Photos
2023-04-10 19:47:32 INFO     Downloading photos from album: Download All Photos
2023-04-10 19:47:32 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-04-10 19:47:32 INFO     Live photo size: original
2023-04-10 19:47:32 INFO     Skip videos: false
2023-04-10 19:47:32 INFO     Convert HEIC to JPEG: false
2023-04-10 19:47:32 INFO     Downloading from: icloud.com
2023-04-10 19:47:33 INFO     Check download directory mounted correctly...
2023-04-10 19:47:33 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-04-10 19:47:33 INFO     Sync user: user
2023-04-10 19:47:33 INFO     Synchronisation starting at 19:47:33
2023-04-10 19:47:33 INFO     Check download directory mounted correctly...
2023-04-10 19:47:33 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-04-10 19:47:33 INFO     Check for new files using password stored in keyring file
2023-04-10 19:47:33 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
  0: SMS to ********81
  1: Enter two-factor authentication code
Please choose an option: [0]: 2023-04-10 19:47:37 ERROR    Failed check for new files files
2023-04-10 19:47:37 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-10 19:47:37 ERROR    Error debugging info:
2023-04-10 19:47:37 ERROR    Aborted!
2023-04-10 19:47:37 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-04-10 19:47:37 INFO     Web cookie expires: 2023-06-03 @ 23:51:09
2023-04-10 19:47:37 INFO     Two factor authentication cookie expires: 2023-06-25 @ 23:23:41
2023-04-10 19:47:37 INFO     Days remaining until expiration: 76
2023-04-10 19:47:37 INFO     Synchronisation ended at 19:47:37
2023-04-10 19:47:37 INFO     Total time taken: 00:00:04
2023-04-10 19:47:37 INFO     Next synchronisation at 19:47:33

**Comment by boredazfcuk** [comment]
> Still seem to be having the same problem after update


This isn't a problem with the container... Your time zone is invalid. It believe it should be America/New_York
