### ISSUE TITLE
docker container start failed

### ISSUE THREAD

**Issue by Blankdlh** [boredazfcuk/docker-icloudpd#302]
sort: cannot read: /config/icloudpd.conf.tmp: Operation not permitted
chmod: cannot access '/config/icloudpd.conf': No such file or directory
sed: /config/icloudpd.conf: No such file or directory
sed: /config/icloudpd.conf: No such file or directory
sed: /config/icloudpd.conf: No such file or directory
sed: /config/icloudpd.conf: No such file or directory
/usr/local/bin/sync-icloud.sh: source: line 76: can't open '/config/icloudpd.conf': No such file or directory

**Comment by boredazfcuk** [comment]
At a guess, you need to run the container in privileged mode. I can't really tell from such a small log snip.

**Comment by Blankdlh** [comment]
> At a guess, you need to run the container in privileged mode. I can't really tell from such a small log snip.

container can started with privileged mode ，bug Authentication failed.


2023-04-06 11:03:56 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.191 started *****
2023-04-06 11:03:56 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-04-06 11:03:56 INFO     Alpine Linux 3.17.3
2023-04-06 11:03:56 INFO     Python version: 3.10.10
2023-04-06 11:03:58 INFO     icloudpd version: 1.12.0
2023-04-06 11:03:58 INFO     pyicloud version: N/A
2023-04-06 11:03:58 INFO     pyicloud-ipd version: N/A
2023-04-06 11:04:26 INFO     Apple ID: xxx
2023-04-06 11:04:26 INFO     Authentication Type: 2FA
2023-04-06 11:04:26 INFO     Cookie path: /config/xxx
2023-04-06 11:04:26 INFO     Cookie expiry notification period: 7
2023-04-06 11:04:26 INFO     Download destination directory: /home/root/iCloud
2023-04-06 11:04:26 INFO     Folder structure: {:%Y/%Y-%m-%d}
2023-04-06 11:04:26 INFO     Synchronisation interval: 86400
2023-04-06 11:04:26 INFO     Synchronisation delay (minutes): 0
2023-04-06 11:04:26 INFO     Set EXIF date/time: false
2023-04-06 11:04:26 INFO     Auto delete: false
2023-04-06 11:04:26 INFO     Photo size: original
2023-04-06 11:04:26 INFO     Single pass mode: false
2023-04-06 11:04:26 INFO     Skip download check: false
2023-04-06 11:04:26 INFO     Skip live photos: false
2023-04-06 11:04:26 INFO     Number of most recently added photos to download: Download All Photos
2023-04-06 11:04:26 INFO     Downloading photos from album: Download All Photos
2023-04-06 11:04:26 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-04-06 11:04:26 INFO     Live photo size: original
2023-04-06 11:04:26 INFO     Skip videos: false
2023-04-06 11:04:26 INFO     Convert HEIC to JPEG: false
2023-04-06 11:04:26 INFO     Downloading from: icloud.com.cn
2023-04-06 11:04:26 WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues
2023-04-06 11:04:26 INFO     Script launch parameters: --Initialise
Enter iCloud password for xxx:
Save password in keyring?  [y/N]: y
Two-step authentication required. Your trusted devices are:
Traceback (most recent call last):
  File "/usr/bin/icloud", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 226, in main
    devices = api.trusted_devices
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 266, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 571, in core
    icloud = authenticator(domain)(
  File "/usr/lib/python3.10/site-packages/icloudpd/authentication.py", line 48, in authenticate_
    request_2sa(icloud, logger)
  File "/usr/lib/python3.10/site-packages/icloudpd/authentication.py", line 55, in request_2sa
    devices = icloud.trusted_devices
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 266, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com
2023-04-06 11:05:00 ERROR    2FA information missing from cookie. Authentication has failed
2023-04-06 11:05:00 ERROR     - Was the correct password entered?
2023-04-06 11:05:00 ERROR     - Was the 2FA code mistyped?
2023-04-06 11:05:00 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?

**Comment by boredazfcuk** [comment]
Upgrade to the latest version of the container and try again.

**Comment by boredazfcuk** [comment]
Fixed in latest version

**Comment by Blankdlh** [comment]
@boredazfcuk 
After completing the two-step verification, an error appeared in the log: "ERROR Keyring file does not exist. Please try again." I checked the config directory and found that only icloudpd.conf and python_keyring were created, and python_keyring is an empty directory.

2023-04-11 14:20:35 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.281 started *****
2023-04-11 14:20:35 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-04-11 14:20:35 INFO     Alpine Linux 3.17.3
2023-04-11 14:20:35 INFO     Python version: 3.10.11
2023-04-11 14:21:03 INFO     Apple ID: xxx
2023-04-11 14:21:03 INFO     Authentication Type: 2FA
2023-04-11 14:21:03 INFO     Cookie path: /config/dailhblankgmailcom
2023-04-11 14:21:03 INFO     Cookie expiry notification period: 7
2023-04-11 14:21:03 INFO     Download destination directory: /home/xxx/iCloud
2023-04-11 14:21:03 INFO     Folder structure: {:%Y/%Y-%m-%d}
2023-04-11 14:21:03 INFO     Synchronisation interval: 86400
2023-04-11 14:21:03 INFO     Synchronisation delay (minutes): 0
2023-04-11 14:21:03 INFO     Set EXIF date/time: false
2023-04-11 14:21:03 INFO     Auto delete: false
2023-04-11 14:21:03 INFO     Photo size: original
2023-04-11 14:21:03 INFO     Single pass mode: false
2023-04-11 14:21:03 INFO     Skip download check: false
2023-04-11 14:21:03 INFO     Skip live photos: false
2023-04-11 14:21:03 INFO     Number of most recently added photos to download: Download All Photos
2023-04-11 14:21:03 INFO     Downloading photos from album: Download All Photos
2023-04-11 14:21:03 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-04-11 14:21:03 INFO     Live photo size: original
2023-04-11 14:21:03 INFO     Skip videos: false
2023-04-11 14:21:03 INFO     Convert HEIC to JPEG: false
2023-04-11 14:21:03 INFO     Downloading from: icloud.com.cn
2023-04-11 14:21:03 WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues
2023-04-11 14:21:03 INFO     Script launch parameters: --Initialise
Enter iCloud password for xxxx:
Save password in keyring? [y/N]: y

Two-step authentication required.
Please enter validation code
(string) --> 111111

2023-04-11 14:21:44 ERROR    Keyring file does not exist. Please try again.

**Comment by boredazfcuk** [comment]
I believe you need to set **auth_china=true** in your `/config/icoudpd.conf` configuration file.
