### ISSUE TITLE
Why did I get an error after entering the password

### ISSUE THREAD

**Issue by JoshuaLiew** [boredazfcuk/docker-icloudpd#303]
/ # sync-icloud.sh --Initialise

2023-04-06 14:51:36 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.197 started *****
2023-04-06 14:51:36 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-04-06 14:51:36 INFO     Alpine Linux 3.17.3
2023-04-06 14:51:36 INFO     Python version: 3.10.10
2023-04-06 14:51:37 INFO     icloudpd version: 1.12.0
2023-04-06 14:51:37 INFO     pyicloud version: 1.0.0
2023-04-06 14:51:37 INFO     pyicloud-ipd version: N/A
2023-04-06 14:52:05 INFO     Apple ID: {apple_id}
2023-04-06 14:52:05 INFO     Authentication Type: 2FA
2023-04-06 14:52:05 INFO     Cookie path: /config/{apple_id}
2023-04-06 14:52:05 INFO     Cookie expiry notification period: 7
2023-04-06 14:52:05 INFO     Download destination directory: /downloads
2023-04-06 14:52:05 INFO     Folder structure: {:%Y/%m/%d}
2023-04-06 14:52:05 INFO     Synchronisation interval: 86400
2023-04-06 14:52:05 INFO     Synchronisation delay (minutes): 0
2023-04-06 14:52:05 INFO     Set EXIF date/time: false
2023-04-06 14:52:05 INFO     Auto delete: false
2023-04-06 14:52:05 INFO     Photo size: original
2023-04-06 14:52:05 INFO     Single pass mode: false
2023-04-06 14:52:05 INFO     Skip download check: false
2023-04-06 14:52:05 INFO     Skip live photos: false
2023-04-06 14:52:05 INFO     Number of most recently added photos to download: Download All Photos
2023-04-06 14:52:05 INFO     Downloading photos from album: Download All Photos
2023-04-06 14:52:05 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-04-06 14:52:05 INFO     Live photo size: original
2023-04-06 14:52:05 INFO     Skip videos: false
2023-04-06 14:52:05 INFO     Convert HEIC to JPEG: false
2023-04-06 14:52:05 INFO     Downloading from: icloud.com.cn
2023-04-06 14:52:05 WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues
2023-04-06 14:52:06 INFO     Script launch parameters: --Initialise
--directory or --list-albums are required
iCloud Password: 
Traceback (most recent call last):
  File "/opt/china_auth_fix/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 217, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.10/site-packages/pyicloud/utils.py", line 41, in get_password_from_keyring
    raise PyiCloudNoStoredPasswordAvailableException(
pyicloud.exceptions.PyiCloudNoStoredPasswordAvailableException: No pyicloud password for {apple_id} could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/china_auth_fix/icloudpd.py", line 5, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/china_auth_fix/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/opt/china_auth_fix/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 271, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 337, in authenticate
    self._webservices = self.data["webservices"]
KeyError: 'webservices'
2023-04-06 14:52:16 ERROR    2FA information missing from cookie. Authentication has failed
2023-04-06 14:52:16 ERROR     - Was the correct password entered?
2023-04-06 14:52:16 ERROR     - Was the 2FA code mistyped?
2023-04-06 14:52:16 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
/ #

**Comment by TheGitaly** [comment]
I think I'm getting the same error? Had to re-create my icloudpd container today, and pulled the latest image. I enter my password, get the 2FA prompt on my Apple device. But there's no where to type it in as the application seems to run into an exception.

```
~] # docker exec -it icloudpd sync-icloud.sh --Initialise

2023-04-07 23:54:49 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.202 started *****
2023-04-07 23:54:49 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-04-07 23:54:49 INFO     Alpine Linux 3.17.3
2023-04-07 23:54:49 INFO     Python version: 3.10.11
2023-04-07 23:54:49 INFO     icloudpd version: 1.12.0
2023-04-07 23:54:49 INFO     pyicloud version: 1.0.0
2023-04-07 23:54:49 INFO     pyicloud-ipd version: N/A
2023-04-07 23:55:03 INFO     Apple ID: redacted
2023-04-07 23:55:03 INFO     Authentication Type: 2FA
2023-04-07 23:55:03 INFO     Cookie path: /config/redacted
2023-04-07 23:55:03 INFO     Cookie expiry notification period: 7
2023-04-07 23:55:03 INFO     Download destination directory: /iCloud
2023-04-07 23:55:03 INFO     Folder structure: {:%Y/%m/%d}
2023-04-07 23:55:03 INFO     Synchronisation interval: 86400
2023-04-07 23:55:03 INFO     Synchronisation delay (minutes): 0
2023-04-07 23:55:03 INFO     Set EXIF date/time: false
2023-04-07 23:55:03 INFO     Auto delete: true
2023-04-07 23:55:03 INFO     Photo size: original
2023-04-07 23:55:03 INFO     Single pass mode: false
2023-04-07 23:55:03 INFO     Skip download check: false
2023-04-07 23:55:03 INFO     Skip live photos: false
2023-04-07 23:55:03 INFO     Number of most recently added photos to download: Download All Photos
2023-04-07 23:55:03 INFO     Downloading photos from album: Download All Photos
2023-04-07 23:55:03 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-04-07 23:55:03 INFO     Live photo size: original
2023-04-07 23:55:03 INFO     Skip videos: false
2023-04-07 23:55:03 INFO     Convert HEIC to JPEG: true
2023-04-07 23:55:03 INFO     Delete accompanying files (.JPG/.HEIC.MOV)
2023-04-07 23:55:03 WARNING  This feature deletes files from your local disk. Please use with caution. I am not responsible for any data loss.
2023-04-07 23:55:03 WARNING  This feature cannot be used if the 'folder_structure' variable is set to 'none' and also, 'set_exif_datetime' must be 'False'
2023-04-07 23:55:03 WARNING  These two settings will increase the chances of de-duplication happening, which could result in the wrong files being removed. Continuing in 2 minutes.
2023-04-07 23:57:03 INFO     Downloading from: icloud.com
2023-04-07 23:57:03 INFO     Script launch parameters: --Initialise
--directory or --list-albums are required
iCloud Password:
Traceback (most recent call last):
  File "/opt/china_auth_fix/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 217, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.10/site-packages/pyicloud/utils.py", line 41, in get_password_from_keyring
    raise PyiCloudNoStoredPasswordAvailableException(
pyicloud.exceptions.PyiCloudNoStoredPasswordAvailableException: No pyicloud password for redacted could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/china_auth_fix/icloudpd.py", line 5, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/china_auth_fix/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/opt/china_auth_fix/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud.PyiCloudService(
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 271, in __init__
    self.authenticate()
  File "/usr/lib/python3.10/site-packages/pyicloud/base.py", line 337, in authenticate
    self._webservices = self.data["webservices"]
KeyError: 'webservices'
2023-04-07 23:57:40 ERROR    2FA information missing from cookie. Authentication has failed
2023-04-07 23:57:40 ERROR     - Was the correct password entered?
2023-04-07 23:57:40 ERROR     - Was the 2FA code mistyped?
2023-04-07 23:57:40 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-07 23:57:40 ERROR     - Are you based in China? You will need to set the icloud_china variable

```

**Comment by wokaozws** [comment]
Same question

**Comment by TheGitaly** [comment]
I think somethings quite broken with the authentication method in this release. 

I've tried creating the keyring file using an earlier version of the docker image (tag 1.0.125), which is successful. Upon updating the container back to the latest tag and running --Initalise, I get a 2FA prompt on my IDevice without entering the password. Then the application spits out an exception without prompting me to enter the 2FA code.

**Comment by boredazfcuk** [comment]
I agree. When I was trying to get a fully working version that allows for authentication in China, globally, SMS 2FA (thus doesn't work in v1.0.125), downloads Live Photos correctly and also uses the latest version of the underlying application...

During my testing, I removed my keyring file so I could test everything from a clean environment and I noticed that it fails to save the password to the system keyring. If I restore the keying from a backup, it works. So something is broken in regard to saving the password. This issue goes back for multiple version of the containers, I've never noticed though as I haven't tested removing/changing my password in a long time. 

I've tried multiple versions of underlying apps, but haven't found a combination that works yet. I suspect it's an update to the keeping package which has broken it. Will keep testing tonight.

**Comment by MarcHagen** [comment]
icloud_photo_downloader v1.0.184 seems to work for me, not tested the newer versions but latest breaks indeed (not getting the `Save password in keyring? [y/N]:` question). Fails to write to keyring?

**Comment by boredazfcuk** [comment]
I've just pushed a new latest version... boredazfcuk/icloudpd:1.0.268

This should fix the keyring issue. Please re-open if it still doesn't work.

**Comment by DuncanTheFox** [comment]
@boredazfcuk I am having the same issue on the latest version.

pyicloud_ipd.exceptions.PyiCloudNoStoredPasswordAvailableException: No pyicloud password for

After providing pw no keyring question..

**Comment by petersuba** [comment]
Yes, it seems like a similar but slightly different error:

`Enter iCloud password for redacted@email: 
Traceback (most recent call last):
  File "starters/icloud.py", line 5, in <module>
  File "pyicloud_ipd/cmdline.py", line 202, in main
  File "pyicloud_ipd/base.py", line 63, in __init__
  File "pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
pyicloud_ipd.exceptions.PyiCloudNoStoredPasswordAvailableException: No pyicloud password for redactedpassword could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.
[677] Failed to execute script 'icloud' due to unhandled exception!`

Note that it seems like the script instead of the user, tries to look up the password. I mean it is like it confuses the password and the username.
