### ISSUE TITLE
2023-04-10 19:47:32 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.280 started *****

### ISSUE THREAD

**Issue by mikmil48** [boredazfcuk/docker-icloudpd#305]
2023-04-10 19:47:32 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.280 started *****
2023-04-10 19:47:32 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-04-10 19:47:32 INFO     Alpine Linux 3.17.3
2023-04-10 19:47:32 INFO     Python version: 3.10.11
2023-04-10 19:47:32 INFO     Apple ID: jmillercrnp@gmail.com
2023-04-10 19:47:32 INFO     Authentication Type: 2FA
2023-04-10 19:47:32 INFO     Cookie path: /config/jmillercrnpgmailcom
2023-04-10 19:47:32 INFO     Cookie expiry notification period: 7
2023-04-10 19:47:32 INFO     Download destination directory: /home/user/iCloud
2023-04-10 19:47:32 INFO     Folder structure: {:%Y/%m/%d}
2023-04-10 19:47:32 INFO     Synchronisation interval: 86400
2023-04-10 19:47:32 INFO     Synchronisation delay (minutes): 0
2023-04-10 19:47:32 INFO     Set EXIF date/time: false
2023-04-10 19:47:32 INFO     Auto delete: false
2023-04-10 19:47:32 INFO     Photo size: original
2023-04-10 19:47:32 INFO     Single pass mode: false
2023-04-10 19:47:32 INFO     Skip download check: false
2023-04-10 19:47:32 INFO     Skip live photos: false
2023-04-10 19:47:32 INFO     Number of most recently added photos to download: Download All Photos
2023-04-10 19:47:32 INFO     Downloading photos from album: Download All Photos
2023-04-10 19:47:32 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-04-10 19:47:32 INFO     Live photo size: original
2023-04-10 19:47:32 INFO     Skip videos: false
2023-04-10 19:47:32 INFO     Convert HEIC to JPEG: false
2023-04-10 19:47:32 INFO     Downloading from: icloud.com
2023-04-10 19:47:33 INFO     Check download directory mounted correctly...
2023-04-10 19:47:33 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-04-10 19:47:33 INFO     Sync user: user
2023-04-10 19:47:33 INFO     Synchronisation starting at 19:47:33
2023-04-10 19:47:33 INFO     Check download directory mounted correctly...
2023-04-10 19:47:33 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-04-10 19:47:33 INFO     Check for new files using password stored in keyring file
2023-04-10 19:47:33 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
  0: SMS to ********81
  1: Enter two-factor authentication code
Please choose an option: [0]: 2023-04-10 19:47:37 ERROR    Failed check for new files files
2023-04-10 19:47:37 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-10 19:47:37 ERROR    Error debugging info:
2023-04-10 19:47:37 ERROR    Aborted!
2023-04-10 19:47:37 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-04-10 19:47:37 INFO     Web cookie expires: 2023-06-03 @ 23:51:09
2023-04-10 19:47:37 INFO     Two factor authentication cookie expires: 2023-06-25 @ 23:23:41
2023-04-10 19:47:37 INFO     Days remaining until expiration: 76
2023-04-10 19:47:37 INFO     Synchronisation ended at 19:47:37
2023-04-10 19:47:37 INFO     Total time taken: 00:00:04
2023-04-10 19:47:37 INFO     Next synchronisation at 19:47:33

_Originally posted by @mikmil48 in https://github.com/boredazfcuk/docker-icloudpd/issues/301#issuecomment-1502239116_

**Comment by boredazfcuk** [comment]
You need to initialise the container using the `--Initialise` command line option.

**Comment by mikmil48** [comment]
2023-04-11 00:09:34 INFO     Sync user: user
2023-04-11 00:09:34 INFO     Synchronisation starting at 00:09:34
2023-04-11 00:09:34 INFO     Check download directory mounted correctly...
2023-04-11 00:09:34 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-04-11 00:09:34 INFO     Check for new files using password stored in keyring file
2023-04-11 00:09:34 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-04-11 00:09:43 ERROR    Failed check for new files files
2023-04-11 00:09:43 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-11 00:09:43 ERROR    Error debugging info:
2023-04-11 00:09:43 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 728, in core
    download_photo(consecutive_files_found, item)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 361, in download_photo_
    created_date = photo.created.astimezone(get_localzone())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/tzlocal/unix.py", line 209, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/tzlocal/unix.py", line 167, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/tzlocal/utils.py", line 124, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like America/New York. \nPlease use a timezone in the form of Continent/City'
2023-04-11 00:09:43 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-04-11 00:09:43 INFO     Web cookie expires: 2023-06-10 @ 00:08:34
2023-04-11 00:09:43 INFO     Two factor authentication cookie expires: 2023-07-10 @ 00:08:57
2023-04-11 00:09:43 INFO     Days remaining until expiration: 89
2023-04-11 00:09:43 INFO     Synchronisation ended at 00:09:43
2023-04-11 00:09:43 INFO     Total time taken: 00:00:09
2023-04-11 00:09:43 INFO     Next synchronisation at 00:09:34
