### ISSUE TITLE
2023-04-11 00:09:34 INFO     Sync user: user

### ISSUE THREAD

**Issue by mikmil48** [boredazfcuk/docker-icloudpd#307]
2023-04-11 00:09:34 INFO     Sync user: user
2023-04-11 00:09:34 INFO     Synchronisation starting at 00:09:34
2023-04-11 00:09:34 INFO     Check download directory mounted correctly...
2023-04-11 00:09:34 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-04-11 00:09:34 INFO     Check for new files using password stored in keyring file
2023-04-11 00:09:34 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-04-11 00:09:43 ERROR    Failed check for new files files
2023-04-11 00:09:43 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-11 00:09:43 ERROR    Error debugging info:
2023-04-11 00:09:43 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 728, in core
    download_photo(consecutive_files_found, item)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 361, in download_photo_
    created_date = photo.created.astimezone(get_localzone())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/tzlocal/unix.py", line 209, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/tzlocal/unix.py", line 167, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/tzlocal/utils.py", line 124, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like America/New York. \nPlease use a timezone in the form of Continent/City'
2023-04-11 00:09:43 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-04-11 00:09:43 INFO     Web cookie expires: 2023-06-10 @ 00:08:34
2023-04-11 00:09:43 INFO     Two factor authentication cookie expires: 2023-07-10 @ 00:08:57
2023-04-11 00:09:43 INFO     Days remaining until expiration: 89
2023-04-11 00:09:43 INFO     Synchronisation ended at 00:09:43
2023-04-11 00:09:43 INFO     Total time taken: 00:00:09
2023-04-11 00:09:43 INFO     Next synchronisation at 00:09:34

_Originally posted by @mikmil48 in https://github.com/boredazfcuk/docker-icloudpd/issues/305#issuecomment-1502497815_

**Comment by 0xJacky** [comment]
Same issue

**Comment by 0xJacky** [comment]
Try to use `-TZ=Asia/Shanghai` paramater to start your docker container.

**Comment by boredazfcuk** [comment]
>tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like America/New York. \nPlease use a timezone in the form of Continent/City'

It seems that your time zone is incorrect. Please see this list for valid time zones: https://timezonedb.com/time-zones

**Comment by mikmil48** [comment]
America/New_York fixed it smh
