### ISSUE TITLE
For some reasons that I am not aware of  (as stated in the log), iCloudpd is unable to download photos anymore

### ISSUE THREAD

**Issue by Suyknow** [boredazfcuk/docker-icloudpd#311]
```
2023-04-11 23:01:49 INFO     Check for new files using password stored in keyring file
2023-04-11 23:01:49 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-04-11 23:01:53 ERROR    Failed check for new files files
2023-04-11 23:01:53 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-11 23:01:53 ERROR    Error debugging info:
2023-04-11 23:01:53 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 571, in core
    icloud = authenticator(domain)(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/authentication.py", line 31, in authenticate_
    icloud = pyicloud_ipd.PyiCloudService(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 234, in authenticate
    raise PyiCloudConnectionException(msg)
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter
2023-04-11 23:01:53 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-04-11 23:01:53 INFO     Web cookie expires: 2023-06-10 @ 15:00:39
2023-04-11 23:01:53 INFO     Two factor authentication cookie expires: 2023-07-10 @ 15:00:50
2023-04-11 23:01:53 INFO     Days remaining until expiration: 89
2023-04-11 23:01:53 INFO     Synchronisation ended at 23:01:53
2023-04-11 23:01:53 INFO     Total time taken: 00:00:04
2023-04-11 23:01:53 INFO     Next synchronisation at 11:01:49
```

**Comment by Suyknow** [comment]
> > pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request.
> 
> This line means that your container is connecting to the global icloud servers to download the photos instead of the ones in China.
> 
> Check that **icloud_china** and **auth_china** are both set to **true** in your icloudpd.conf file.

After setting both values to true as instructed, it works fine.
My iCloudpd.conf was generated earlier with only the setting for iCloud_china. It's possible that auth_china was added in a later update and was not linked to iCloud_china in that particular version.
Anyway, it's now working properly and thanks for your help!
