### ISSUE TITLE
new problem in icloud.com.cn

### ISSUE THREAD

**Issue by jiaoting** [boredazfcuk/docker-icloudpd#314]
2023-04-12 15:45:17 INFO ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.283 started *****
2023-04-12 15:45:17 INFO ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-04-12 15:45:17 INFO Alpine Linux 3.17.3
2023-04-12 15:45:17 INFO Python version: 3.10.11
2023-04-12 15:45:39 INFO Apple ID: [jiaoting@126.com](mailto:jiaoting@126.com)
2023-04-12 15:45:39 INFO Authentication Type: 2FA
2023-04-12 15:45:39 INFO Cookie path: /config/jiaoting126com
2023-04-12 15:45:39 INFO Cookie expiry notification period: 7
2023-04-12 15:45:39 INFO Download destination directory: /home/user/iCloud
2023-04-12 15:45:39 INFO Folder structure: {:%Y/%m/%d}
2023-04-12 15:45:39 INFO Synchronisation interval: 86400
2023-04-12 15:45:39 INFO Synchronisation delay (minutes): 0
2023-04-12 15:45:39 INFO Set EXIF date/time: false
2023-04-12 15:45:39 INFO Auto delete: true
2023-04-12 15:45:39 INFO Photo size: original
2023-04-12 15:45:39 INFO Single pass mode: false
2023-04-12 15:45:39 INFO Skip download check: false
2023-04-12 15:45:39 INFO Skip live photos: false
2023-04-12 15:45:39 INFO Number of most recently added photos to download: Download All Photos
2023-04-12 15:45:39 INFO Downloading photos from album: Download All Photos
2023-04-12 15:45:39 INFO Stop downloading when prexisiting files count is: Download All Photos
2023-04-12 15:45:39 INFO Live photo size: original
2023-04-12 15:45:39 INFO Skip videos: false
2023-04-12 15:45:39 INFO Convert HEIC to JPEG: false
2023-04-12 15:45:40 INFO Downloading from: icloud.com.cn
2023-04-12 15:45:40 WARNING Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues
2023-04-12 15:45:40 INFO Check download directory mounted correctly...
2023-04-12 15:45:40 INFO Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-04-12 15:45:40 INFO Sync user: user
2023-04-12 15:45:40 INFO Synchronisation starting at 15:45:40
2023-04-12 15:45:40 INFO Check download directory mounted correctly...
2023-04-12 15:45:40 INFO Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-04-12 15:45:40 INFO Check for new files using password stored in keyring file
2023-04-12 15:45:40 INFO Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-04-12 15:45:42 ERROR Failed check for new files files
2023-04-12 15:45:42 ERROR - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-12 15:45:42 ERROR Error debugging info:
2023-04-12 15:45:42 ERROR Traceback (most recent call last):
File "/opt/icloudpd_v1.12.0/bin/icloudpd", line 8, in
sys.exit(main())
File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1130, in call
return self.main(*args, **kwargs)
File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke
return _callback(*args, **kwargs)
File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
core(
File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 571, in core
icloud = authenticator(domain)(
File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/authentication.py", line 31, in authenticate
icloud = pyicloud_ipd.PyiCloudService(
File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 204, in init
self.authenticate()
File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 234, in authenticate
raise PyiCloudConnectionException(msg)
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter
2023-04-12 15:45:42 ERROR ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-04-12 15:45:42 INFO Web cookie expires: 2023-06-11 @ 07:44:28
2023-04-12 15:45:42 INFO Two factor authentication cookie expires: 2023-07-11 @ 07:44:38
2023-04-12 15:45:42 INFO Days remaining until expiration: 89
2023-04-12 15:45:42 INFO Synchronisation ended at 15:45:42
2023-04-12 15:45:42 INFO Total time taken: 00:00:02
2023-04-12 15:45:42 INFO Next synchronisation at 15:45:40

**Comment by Alano-i** [comment]
This is likely because the `auth_china` and `icloud_china` parameters in the icloudpd.conf file (this file is in the /config directory) are not set to `true`, please check.

If the configuration is modified in the environment variable, it is best to update it to the .conf file synchronously. Can the author consider optimizing this place？

**Comment by jiaoting** [comment]
> icloud_china

I use icloud_china = true

**Comment by ilchann** [comment]
same
https://github.com/boredazfcuk/docker-icloudpd/issues/266

**Comment by q1067972249** [comment]
same

**Comment by MacArthurL** [comment]
各位，这个问题很好解决。按照 @Alano-i 大佬的解决办法，在docker映射的/config文件夹里有个名为icloudpd.conf的文件，用记事本等编辑器打开可以在第2行看到auth_china这个环境变量一直被设置为false，无论在创建容器时auth_china设置的是啥。只需要关闭容器，手动修改这个环境变量的值为true，保存后再重启容器即可。

**Comment by boredazfcuk** [comment]
> pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter

You need to set **auth_china=true** in your `/config/icloudpd.conf` configuration file.

Thanks.

**Comment by AlexaAmaya** [comment]
> 各位，这个问题很好解决。按照 @Alano-i 大佬的解决办法，在docker映射的/config文件夹里有个名为icloudpd.conf的文件，用记事本等编辑器打开可以在第2行看到auth_china这个环境变量一直被设置为false，无论在创建容器时auth_china设置的是啥。只需要关闭容器，手动修改这个环境变量的值为true，保存后再重启容器即可。

我没找到这个/config文件夹哎～

**Comment by aamplifier** [comment]
I have modified 'auth_china=true' and reboot,but still can't resolve.Is there anything else I haven't noticed
