### ISSUE TITLE
ERROR    Failed check for new files files - ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by freezah** [boredazfcuk/docker-icloudpd#315]
## Overview
Suddenly stopped syncing files. Redeployed container with latest image version and still hitting same issue.

## Expected Behavior
Download all new files from iCloud

## Actual Behavior
Crashing at new files few days old

## Context
Getting following log:

/xxx/2023-04/IMG_3806.PNG
/xxx/2023-04/IMG_3805.HEIC
/xxx/2023-04/IMG_3804.HEIC
/xxx/2023-04/IMG_3803.PNG
2023-04-15 11:07:50 ERROR    Failed check for new files files
2023-04-15 11:07:50 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-15 11:07:50 ERROR    Error debugging info:
2023-04-15 11:07:50 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 727, in core
    item = next(photos_iterator)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/services/photos.py", line 295, in photos
    request = self.photos_request(offset)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/services/photos.py", line 276, in photos_request
    return self.service.session.post(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 71, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Comment by boredazfcuk** [comment]
Your check is processing, as I can see files that it has listed. Please check you don't have files with non alpha-numeric characters in their names.

**Comment by boredazfcuk** [comment]
I've had a look into this and it appears that the Apple servers aren't correctly encoding one of the files. I suggest you remove if from your photo stream (if you can identify it).

It can be worked around in code from what this link suggests: https://stackoverflow.com/questions/58195791/python-requests-throws-connection-broken-chunkedencodingerror-with-http-client but that would need to be implemented in one of the upstream packages that is in the container.

I can see that you've already logged an issue for it in the upstream repo: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/623 but it has been closed. That's the only place that will be able to fix it, so I'm not sure what else to suggest.

**Comment by freezah** [comment]
I am not able to identify which file could this be (if any). I removed few next and previous photos and it now crashes on some previous one.

The iCloud_photos_downloader is closing my issue asking to post it in the project that I'm actually deploying from - meaning  https://github.com/boredazfcuk/docker-icloudpd :/
