### ISSUE TITLE
problem log when check for new files

### ISSUE THREAD

**Issue by MannyChen0507** [boredazfcuk/docker-icloudpd#317]
2023-04-18 02:56:19.940959+00:002023-04-18 02:56:19 ERROR    Failed check for new files files
2023-04-18 02:56:19.941507+00:002023-04-18 02:56:19 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-18 02:56:19.942017+00:002023-04-18 02:56:19 ERROR    Error debugging info:
2023-04-18 02:56:19.943073+00:002023-04-18 02:56:19 ERROR    Traceback (most recent call last):
2023-04-18 02:56:19.943095+00:00File "/opt/icloudpd_v1.12.0/bin/icloudpd", line 8, in <module>
2023-04-18 02:56:19.943102+00:00sys.exit(main())
2023-04-18 02:56:19.943105+00:00File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
2023-04-18 02:56:19.943115+00:00return self.main(*args, **kwargs)
2023-04-18 02:56:19.943118+00:00File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1055, in main
2023-04-18 02:56:19.943121+00:00rv = self.invoke(ctx)
2023-04-18 02:56:19.943124+00:00File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
2023-04-18 02:56:19.943129+00:00return ctx.invoke(self.callback, **ctx.params)
2023-04-18 02:56:19.943132+00:00File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke
2023-04-18 02:56:19.943135+00:00return __callback(*args, **kwargs)
2023-04-18 02:56:19.943140+00:00File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
2023-04-18 02:56:19.943143+00:00core(
2023-04-18 02:56:19.943146+00:00File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 571, in core
2023-04-18 02:56:19.943150+00:00icloud = authenticator(domain)(
2023-04-18 02:56:19.943154+00:00File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/authentication.py", line 31, in authenticate_
2023-04-18 02:56:19.943157+00:00icloud = pyicloud_ipd.PyiCloudService(
2023-04-18 02:56:19.943160+00:00File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 204, in __init__
2023-04-18 02:56:19.943163+00:00self.authenticate()
2023-04-18 02:56:19.943171+00:00File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 234, in authenticate
2023-04-18 02:56:19.943174+00:00raise PyiCloudConnectionException(msg)

base above lines ,I can't check new files, crying~

**Comment by boredazfcuk** [comment]
I can't tell what's happening with such a small snip of the log file. Set `debug_logging=true` in your `/config/icloudpd.conf` file, generate another log and post it.
