### ISSUE TITLE
Changing folder structure

### ISSUE THREAD

**Issue by Torashin** [boredazfcuk/docker-icloudpd#324]
I haven't been able to change the folder structure of downloads, and I hoped you could please elaborate on the rather vague description, which goes as follows:

folder_structure: This specifies the folder structure to use in your download destination directory. If this variable is not set, it will set {:%Y/%m/%d} as the default. Use none to download to a flat file structure. Use album to store in folders with same name as on iCloud.com

So I've tried album, {album}, {%album}, and %album, in addition to {:%Y/%m/%d}, :%Y/%m/%d, {%Y/%m/%d} and %Y/%m/%d and they all give me the same error:

2023-04-23 13:52:02 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-04-23 13:52:11 ERROR    Failed check for new files files
2023-04-23 13:52:11 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-23 13:52:11 ERROR    Error debugging info:
2023-04-23 13:52:11 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 728, in core
    download_photo(consecutive_files_found, item)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 372, in download_photo_
    date_path = folder_structure.format(created_date)
KeyError: 'album'

Edit: well now I've even getting the error with the Folder Structure parameter blank (which used to work), so the error must be due to something else. I could still do with the clarification though!

**Comment by boredazfcuk** [comment]
What does your `/config/icloudpd.conf` file say?

Mine is confiured:
```
folder_structure={:%Y/%m}
```
I've just created a new container, with it set to `folder_structure={:%Y/%m/%d}` and it worked fine.

I'm unsure about the album option, as I've never used it, personally.

**Comment by Torashin** [comment]
Ahh, that's intersting. My config had folder_structure={album}, despite unraids update container menu being set to {:%Y/%m}. Changing the config to the latter fixed the error - many thanks.

All that remains then is some clarification on the album option.

**Comment by boredazfcuk** [comment]
It could depend on what version of the container you are running. I wanted to move to using a config file for the settings, so made that the primary configuration method. Any environment variables would be ignored in favour of the config file.

Some people who use NAS devices complained though, as it made it more difficult for them to configure their containers. I then changed it so that it would write any environment variables it found into the config file before loading it. I will be phasing out environment variables in the future, just not so soon. 

Looking at the docs, folder-structure and album are unrelated parameters:
```
--folder-structure <folder_structure>
                                  Folder structure (default: {:%Y/%m/%d}). If
                                  set to 'none' all photos will just be placed
                                  into the download directory

--album <album>             Album to download (default: All Photos)
```
From what I have read in various issues that have been opened in the upstream repo, if you choose to download an album, it can only do one at a time. I did request that the option was changed to allow a comma separated list, or allow multiple `--album` parameters, but it was never implemented.

**Comment by Torashin** [comment]
Ahhhh, got you. By 'use album' it means the other sync method. Cheers for the help.

Also a quick heads up - I had to use the 1.0.349 tag instead of latest to get the docker install to complete. Nobody else seems to have this problem though, so ¯\_(ツ)_/¯

**Comment by boredazfcuk** [comment]
Please update to latest version. It should container a fix for the folder_structure issue.
