### ISSUE TITLE
Some strange error

### ISSUE THREAD

**Issue by JoaquinSun** [boredazfcuk/docker-icloudpd#342]
**_Can you log into icloud.com.cn without receiving pop-up notifications?_** : I can't.
And following is thre error part. Run in latest version of docker image.

```
2023-05-29 04:51:01.691377+00:002023-05-29 12:51:01 ERROR    Failed to download new files
2023-05-29 04:51:01.692365+00:002023-05-29 12:51:01 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-05-29 04:51:01.693272+00:002023-05-29 12:51:01 ERROR    Error debugging info:
2023-05-29 04:51:01.695632+00:002023-05-29 12:51:01 ERROR    Traceback (most recent call last):
2023-05-29 04:51:01.695659+00:00File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
2023-05-29 04:51:01.695669+00:00sys.exit(main())
2023-05-29 04:51:01.695677+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
2023-05-29 04:51:01.695685+00:00return self.main(*args, **kwargs)
2023-05-29 04:51:01.695693+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 1055, in main
2023-05-29 04:51:01.695701+00:00rv = self.invoke(ctx)
2023-05-29 04:51:01.695709+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
2023-05-29 04:51:01.695716+00:00return ctx.invoke(self.callback, **ctx.params)
2023-05-29 04:51:01.695724+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 760, in invoke
2023-05-29 04:51:01.695732+00:00return __callback(*args, **kwargs)
2023-05-29 04:51:01.695739+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/base.py", line 283, in main
2023-05-29 04:51:01.695747+00:00core(
2023-05-29 04:51:01.695754+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/base.py", line 727, in core
2023-05-29 04:51:01.695762+00:00if download_photo(
2023-05-29 04:51:01.695770+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/base.py", line 467, in download_photo_
2023-05-29 04:51:01.695777+00:00not exif_datetime.get_photo_exif(download_path):
2023-05-29 04:51:01.695785+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/exif_datetime.py", line 11, in get_photo_exif
2023-05-29 04:51:01.695793+00:00exif_dict = piexif.load(path)
2023-05-29 04:51:01.695801+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/piexif/_load.py", line 53, in load
2023-05-29 04:51:01.695809+00:00exif_dict["1st"] = exifReader.get_ifd_dict(pointer, "1st")
2023-05-29 04:51:01.695817+00:00File "/opt/icloudpd_latest/lib/python3.10/site-packages/piexif/_load.py", line 108, in get_ifd_dict
2023-05-29 04:51:01.695824+00:00tag_count = struct.unpack(self.endian_mark + "H",
2023-05-29 04:51:01.695832+00:00struct.error: unpack requires a buffer of 2 bytes
2023-05-29 04:51:01.696577+00:002023-05-29 12:51:01 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
```

**Comment by boredazfcuk** [comment]
>struct.error: unpack requires a buffer of 2 bytes

This is usually because you have an unsupported file somewhere in your photo stream. Sorry I can't help more than this but I've not encountered this error personally, so I don't know what to look for.

**Comment by boredazfcuk** [comment]
Also, if you have the **set_exif_datetime** variable set to `true` try disabling it and restarting the container.

**Comment by boredazfcuk** [comment]
Closing this as no response in over two weeks.
