### ISSUE TITLE
How to handle bugs，please ~~

### ISSUE THREAD

**Issue by hyw520sj** [boredazfcuk/docker-icloudpd#348]
2023-06-22 17:46:55 INFO     Sync user: user
2023-06-22 17:46:55 INFO     Synchronisation starting at 17:46:55
2023-06-22 17:46:55 INFO     Check download directory mounted correctly...
2023-06-22 17:46:55 INFO     Failsafe file /icloud/.mounted exists, continuing
2023-06-22 17:46:55 DEBUG    Authenticating...
2023-06-22 17:47:03 DEBUG    Looking up all photos and videos from album All Photos...
2023-06-22 17:47:03 INFO     Downloading 1264 original photos and videos to /icloud ...
2023-06-22 17:47:05 ERROR    Failed to download new files
2023-06-22 17:47:05 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-06-22 17:47:05 ERROR    Error debugging info:
2023-06-22 17:47:05 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/base.py", line 283, in main
    core(
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/base.py", line 727, in core
    if download_photo(
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/base.py", line 355, in download_photo_
    created_date = photo.created.astimezone(get_localzone())
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/tzlocal/unix.py", line 209, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/tzlocal/unix.py", line 167, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/tzlocal/utils.py", line 124, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like CST-8. \nPlease use a timezone in the form of Continent/City'
2023-06-22 17:47:05 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-06-22 17:47:05 INFO     Web cookie expires: 2023-08-21 @ 09:41:45
2023-06-22 17:47:05 INFO     Two factor authentication cookie expires: 2023-09-20 @ 09:41:40
2023-06-22 17:47:05 INFO     Days remaining until expiration: 89
2023-06-22 17:47:05 INFO     Synchronisation ended at 17:47:05
2023-06-22 17:47:05 INFO     Total time taken: 00:00:10
2023-06-22 17:47:05 INFO     Next synchronisation at 17:46:55

**Comment by boredazfcuk** [comment]
Your time zone is incorrect. The list of supported time zones can be found here: https://nodatime.org/TimeZones. The value you need to set is listed in the "Zone ID" column of the table.
