### ISSUE TITLE
Latest Build - Missing icloud bin

### ISSUE THREAD

**Issue by Roving-Ronin** [boredazfcuk/docker-icloudpd#358]
Hi @boredazfcuk 
FYI The :latest build (~11 July 2023 and all the way back it seems to 1.0.270) is based off icloudpd_version=1.14.5.
As per https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/594 this version is / still is MISSING the icloud binary, stopping being able to setup the icloud KeyRing.

Could you please update the docker latest image to icloudpd_version=1.15.1.   that is supposed to fix this issue?

**Comment by boredazfcuk** [comment]
FYI Adding the password to the keyring is mandatory in my container and has been for over two years:

>20210712
> - Change: Removed apple_password variable. Password must now be added to the system keyring.

There are actually two versions of the binary packaged in the container. One which allows saving the password for people in China (v.1.7.2) and one for the rest of the world.

My only guess is that you've logged this issue against the wrong repo.

**Comment by Roving-Ronin** [comment]
I'm using UNRAID as the host, but it definitely is using your docker image for icloudpd. Following the setup instructions fails with:


/ # /usr/local/bin/sync-icloud.sh --Initialise

2023-07-23 11:21:46 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.617 started *****
2023-07-23 11:21:46 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-07-23 11:21:46 INFO     Alpine Linux 3.18.2
2023-07-23 11:21:46 INFO     Python version: 3.11.4
2023-07-23 11:21:47 INFO     Loading configuration from: /config/icloudpd.conf
2023-07-23 11:22:08 INFO     Apple ID: justin@hobson-net.com
2023-07-23 11:22:08 INFO     Authentication Type: MFA
2023-07-23 11:22:08 INFO     Cookie path: /config/justinhobsonnetcom
2023-07-23 11:22:08 INFO     Cookie expiry notification period: 7
2023-07-23 11:22:08 INFO     Download destination directory: /home/user/iCloud
2023-07-23 11:22:08 INFO     Folder structure: {:%Y}
2023-07-23 11:22:08 INFO     Synchronisation interval: 43200
2023-07-23 11:22:08 INFO     Synchronisation delay (minutes): 0
2023-07-23 11:22:08 INFO     Set EXIF date/time: false
2023-07-23 11:22:08 INFO     Auto delete: false
2023-07-23 11:22:08 INFO     Delete after download: false
2023-07-23 11:22:08 INFO     Photo size: original
2023-07-23 11:22:08 INFO     Single pass mode: false
2023-07-23 11:22:08 INFO     Skip download check: false
2023-07-23 11:22:08 INFO     Skip live photos: false
2023-07-23 11:22:08 INFO     Number of most recently added photos to download: Download All Photos
2023-07-23 11:22:08 INFO     Downloading photos from album: Download All Photos
2023-07-23 11:22:08 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-07-23 11:22:08 INFO     Live photo size: original
2023-07-23 11:22:08 INFO     Skip videos: false
2023-07-23 11:22:08 INFO     Convert HEIC to JPEG: true
2023-07-23 11:22:08 INFO     Converted JPEGs path: /home/user/iCloud/jpeg
2023-07-23 11:22:08 INFO     Downloading from: icloud.com.cn
2023-07-23 11:22:08 WARNING  You have the icloud_china variable set, but auth_china is false. Are you sure this is correct?
2023-07-23 11:22:08 INFO     Authentication domain: com
2023-07-23 11:22:08 INFO     Ignore Synology extended attribute directories: Disabled
2023-07-23 11:22:08 INFO     Script launch parameters: --Initialise
Enter iCloud password for xxxxx@xxxxxxx.com: 
Traceback (most recent call last):
  File "/opt/icloudpd_v1.7.2_china/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud==1.0.0', 'console_scripts', 'icloud')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/cmdline.py", line 191, in main
    api = PyiCloudService(username.strip(), password.strip())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 271, in __init__
    self.authenticate()
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 337, in authenticate
    self._webservices = self.data["webservices"]
                        ~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'webservices'
2023-07-23 11:22:18 ERROR    Keyring file does not exist. Please try again.
______________________________________________________________________________________

iPhone does the whole verify ID 2FA thing, but as per above the script fails. No idea why above has reference to China as the icloud_china variable is set to FALSE.

**Comment by Roving-Ronin** [comment]
Running the container with 'Priviliged' enabled, gives the following errors:

/ # /usr/local/bin/sync-icloud.sh --Initialise

2023-07-23 11:28:22 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.617 started *****
2023-07-23 11:28:22 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-07-23 11:28:22 INFO     Alpine Linux 3.18.2
2023-07-23 11:28:22 INFO     Python version: 3.11.4
2023-07-23 11:28:22 INFO     Loading configuration from: /config/icloudpd.conf
2023-07-23 11:28:47 INFO     Apple ID: justin@hobson-net.com
2023-07-23 11:28:47 INFO     Authentication Type: MFA
2023-07-23 11:28:47 INFO     Cookie path: /config/justinhobsonnetcom
2023-07-23 11:28:47 INFO     Cookie expiry notification period: 7
2023-07-23 11:28:47 INFO     Download destination directory: /home/user/iCloud
2023-07-23 11:28:47 INFO     Folder structure: {:%Y}
2023-07-23 11:28:47 INFO     Synchronisation interval: 43200
2023-07-23 11:28:47 INFO     Synchronisation delay (minutes): 0
2023-07-23 11:28:47 INFO     Set EXIF date/time: false
2023-07-23 11:28:47 INFO     Auto delete: false
2023-07-23 11:28:47 INFO     Delete after download: false
2023-07-23 11:28:47 INFO     Photo size: original
2023-07-23 11:28:47 INFO     Single pass mode: false
2023-07-23 11:28:47 INFO     Skip download check: false
2023-07-23 11:28:47 INFO     Skip live photos: false
2023-07-23 11:28:47 INFO     Number of most recently added photos to download: Download All Photos
2023-07-23 11:28:47 INFO     Downloading photos from album: Download All Photos
2023-07-23 11:28:47 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-07-23 11:28:47 INFO     Live photo size: original
2023-07-23 11:28:47 INFO     Skip videos: false
2023-07-23 11:28:47 INFO     Convert HEIC to JPEG: true
2023-07-23 11:28:47 INFO     Converted JPEGs path: /home/user/iCloud/jpeg
2023-07-23 11:28:47 INFO     Downloading from: icloud.com.cn
2023-07-23 11:28:47 WARNING  You have the icloud_china variable set, but auth_china is false. Are you sure this is correct?
2023-07-23 11:28:47 INFO     Authentication domain: com
2023-07-23 11:28:47 INFO     Ignore Synology extended attribute directories: Disabled
2023-07-23 11:28:47 INFO     Script launch parameters: --Initialise
Enter iCloud password for xxxxx@xxxxxxx.com: 
Traceback (most recent call last):
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='setup.icloud.com.cn', port=443): Max retries exceeded with url: /setup/ws/1/accountLogin (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.7.2_china/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud==1.0.0', 'console_scripts', 'icloud')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/cmdline.py", line 191, in main
    api = PyiCloudService(username.strip(), password.strip())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 271, in __init__
    self.authenticate()
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 335, in authenticate
    self._authenticate_with_token()
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 351, in _authenticate_with_token
    req = self.session.post(
          ^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 78, in request
    response = super().request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='setup.icloud.com.cn', port=443): Max retries exceeded with url: /setup/ws/1/accountLogin (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)')))
2023-07-23 11:28:59 ERROR    Keyring file does not exist. Please try again.
^C
/ #

**Comment by boredazfcuk** [comment]
The log file shows that it's using the /opt/icloudpd_v1.7.2_china/bin/icloud binary to authenticate against Apple's servers. It will only use v1.7.2 if icloud_china is present.

Setting it to **FALSE** means the variable is present. I think you need to set it to **false** as I have a feeling that only lowercase variables are recognised as Boolean values in Linux.

**Comment by boredazfcuk** [comment]
I've a had a look into this a short while ago and setting *icloud_china* to `false` or `FALSE` will result it in being *true*.

For most variables, I just check whether they are configured or not. If they are configured, then they will be processed. If they are not configured, the script bypasses them. So, you could set *icloud_china=blahblahblah* and the script would configure itself to use the servers in China. 

I've updated the script so that it now checks the value of the variable. If it is set to *true* it will configure the script to use the servers in China. If it is set to anything else, it will use the global servers. if it is not set, it will configure it to *false*.

Update your container to the latest version and I think your issue should go away.

**Comment by Roving-Ronin** [comment]
Many thanks for updating the script, I had been trying with that set to false and encountering the problem. Updated to v1.0.621 and works fine now.

Well except for now getting the 'private db access disabled for this account' issue, from all the attempts to connect previously. LoL.

Many thanks for the assistance !

**Comment by boredazfcuk** [comment]
Ha! That should clear up after a while... I get it a lot in testing.

Sometimes I'll push 10-20 new versions to my private repo. Recreating my container that many times, results in a lot of repeated authentications. I normally get blocked after about 10-20 logins and have to give up for the night.
