### ISSUE TITLE
ERROR    Check failed - Exit code: 1

### ISSUE THREAD

**Issue by eleaner** [boredazfcuk/docker-icloudpd#36]
Hi

I started getting this sort of errors
any idea what might cause them?
```
/home/user/iCloud/2018/12/29/IMG_9490-2184363.JPG
/home/user/iCloud/2018/12/29/IMG_9489-2373439.JPG
/home/user/iCloud/2018/12/29/IMG_9488-2415572.JPG
/home/user/iCloud/2018/12/29/IMG_9485-2347916.JPG
/home/user/iCloud/2018/12/29/IMG_9484-2159835.JPG
/home/user/iCloud/2018/12/29/IMG_9483-2295044.JPG
/home/user/iCloud/2018/12/29/IMG_9482-2288166.JPG
/home/user/iCloud/2018/12/29/IMG_9481-1983629.JPG
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    load_entry_point('icloudpd==1.6.2', 'console_scripts', 'icloudpd')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.6.2-py3.8.egg/icloudpd/base.py", line 562, in main
  File "/usr/lib/python3.8/site-packages/icloudpd-1.6.2-py3.8.egg/icloudpd/base.py", line 456, in download_photo
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/iCloud/2018/12/29/IMG_9480.JPG'
2020-10-31 14:49:02 ERROR    Check failed - Exit code: 1
```

**Comment by boredazfcuk** [comment]
I'm not sure why that would appear. It looks like it's an issue with the underlying application not being able to verify a file which it thinks should be on disk. The `--only-print-filenames` option (which generates that list of files) shouldn't actually modify files on the disk. However, there were changes made upstream to it's operation in recently.

I've just pushed out an update to Dockerhub which upgrades the container downloader application from 1.6.x to 1.7. Try pulling the latest version form Dockerhub and then trying again.

If it doesn't work then it'll be an issue with the option upstream.

**Comment by eleaner** [comment]
looks like this one has another issue for me
```
2020-11-01 16:03:50 INFO     Check for new files using password stored in keyring...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, SocketTimeoutException sending request http://accountservice.p21.prod.me.com:80/api/get_account_by_appleid_password, Read timed out, timeoutMs: 3000
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    load_entry_point('icloudpd==1.7.0', 'console_scripts', 'icloudpd')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.0-py3.8.egg/icloudpd/base.py", line 255, in main
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.0-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('statusCode = UnknownServerError, SocketTimeoutException sending request http://accountservice.p21.prod.me.com:80/api/get_account_by_appleid_password, Read timed out, timeoutMs: 3000'))
2020-11-01 16:03:55 ERROR    Check failed - Exit code: 1
```

the version matches
```
2020-11-01 16:03:42 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2020-11-01 16:03:42 INFO     ***** /usr/local/bin/sync-icloud.sh script version: 2020/11/01_14:35 *****
2020-11-01 16:03:42 INFO     Alpine Linux v3.12
2020-11-01 16:03:42 INFO     Python version: 3.8.5
2020-11-01 16:03:42 INFO     icloudpd version: 1.7.0
2020-11-01 16:03:44 INFO     pyicloud-ipd version: 0.10.1
```

what do you mean by "upstream"?

**Comment by boredazfcuk** [comment]
There are two errors listed above:
```
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, SocketTimeoutException sending request http://accountservice.p21.prod.me.com:80/api/get_account_by_appleid_password, Read timed out, timeoutMs: 3000
```
and
```
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('statusCode = UnknownServerError, SocketTimeoutException sending request http://accountservice.p21.prod.me.com:80/api/get_account_by_appleid_password, Read timed out, timeoutMs: 3000'))
```
Both of these suggest a network issue is to blame. It seems it cannot connect to Apple as it cannot find  the server: accountservice.p21.prod.me.com

It's also saying that there's an e-mail/password issue (you've not changed your Apple ID password recently?) but that might just be due to the connectivity issue.

Presuming your container is named icloudpd, connect to it from a shell prompt like this:
`docker exec -it icloudpd /bin/sh`
and once inside the container run the follwing three commands:
```
nslookup www.google.com
nslookup accountservice.p21.prod.me.com
ping 8.8.8.8
```
and let me know what you get.

**Comment by boredazfcuk** [comment]
> what do you mean by "upstream"?

I'm not the maintainer of these two applications which are inside my container:
```
2020-11-01 16:03:42 INFO     icloudpd version: 1.7.0
2020-11-01 16:03:44 INFO     pyicloud-ipd version: 0.10.1
```
Sometimes issues occur in these two applications which I have no control over.

**Comment by eleaner** [comment]
I manage to make it work by downloading to empty location
I am not sure what was the problem but I am closing this issue

**Comment by boredazfcuk** [comment]
Odd.

The checking phase that is failing doesn't look at the specified download location. It's hard-coded to dump any output /dev/null as it's not needed.

I have logged an issue in the upstream app as a there is a bug with live photos. Once that if fixed, I should be able to rip out the entire checking phase as I only put it in as a workaround to the bug.
