### ISSUE TITLE
Can download with the album structure? 

### ISSUE THREAD

**Issue by jiaoting** [boredazfcuk/docker-icloudpd#360]
Can you follow the iPhone's photo library photo structure photo/A photo/B? After downloading, the structure is also/icloud/A/001.jpeg,/icloud/B/002.jpeg

folder_structure = album is not correct, I set photo_album=“all albums”
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/12553424/074203c4-3e1d-4b07-ae9a-a0f49fc95394)

log:
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Download destination directory: /iCloud
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Folder structure: {:%Y/%m/%d}
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Synchronisation interval: 86400
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Synchronisation delay (minutes): 0
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Set EXIF date/time: false
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Auto delete: true
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Delete after download: false
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Photo size: original
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Single pass mode: false
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Skip download check: false
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Skip live photos: false
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Number of most recently added photos to download: Download All Photos
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Downloading photos from album(s): all albums
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Live photo size: original
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Skip videos: false
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Convert HEIC to JPEG: false
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Downloading from: icloud.com.cn
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Authentication domain: cn
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Ignore Synology extended attribute directories: Disabled
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Check download directory mounted correctly...
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023-07-29 15:19:40 2023-07-29 15:19:40 INFO     Keyring file exists, continuing
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO     Albums available:
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - All Photos
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Time-lapse
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Videos
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Slo-mo
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Bursts
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Favorites
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Panoramas
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Screenshots
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Live
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Recently Deleted
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Hidden
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 金茂悦府
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - ❤
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 二手
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 课程
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 工作
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 收集
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 囍相册
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 错埠岭
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 中南1204
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - Photomator
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 今日水印相机
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 百度网盘
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO      - 小红书
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO     Sync user: user
2023-07-29 15:19:50 2023-07-29 15:19:50 INFO     Synchronisation starting at 15:19:50
2023-07-29 15:19:51 2023-07-29 15:19:51 INFO     Keyring file exists, continuing
2023-07-29 15:19:51 2023-07-29 15:19:51 INFO     Check download directory mounted correctly...
2023-07-29 15:19:51 2023-07-29 15:19:51 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023-07-29 15:19:51 2023-07-29 15:19:51 INFO     Check for new files using password stored in keyring file
2023-07-29 15:19:51 2023-07-29 15:19:51 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0631.HEIC
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0631_HEVC.MOV
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0630.HEIC
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0630_HEVC.MOV
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0629.HEIC
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0629_HEVC.MOV
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0628.HEIC
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0628_HEVC.MOV
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0627.HEIC
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0627_HEVC.MOV
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0626.PNG
2023-07-29 15:21:28 ash: out of range
2023-07-29 15:21:28 grep: /tmp/icloudpd/icloudpd_sync.log: No such file or directory
2023-07-29 15:21:28 grep: /tmp/icloudpd/icloudpd_sync.log: No such file or directory
2023-07-29 15:21:28 grep: /tmp/icloudpd/icloudpd_sync.log: No such file or directory
2023-07-29 15:21:28 grep: /tmp/icloudpd/icloudpd_sync.log: No such file or directory
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0625.PNG
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0624.HEIC
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0624_HEVC.MOV
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0623.PNG
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0622.PNG
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0621.PNG
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0620.PNG
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0619.PNG
2023-07-29 15:21:19 /iCloud/2023/07/29/IMG_0618.PNG
2023-07-29 15:21:19 2023-07-29 15:21:19 INFO     Check successful
2023-07-29 15:21:19 2023-07-29 15:21:19 INFO     New files detected: 20
2023-07-29 15:24:04 2023-07-29 15:24:04 INFO     Synchronisation complete for user
2023-07-29 15:24:04 2023-07-29 15:24:04 INFO     Web cookie expires: 2023-09-14 @ 07:42:33
2023-07-29 15:24:04 2023-07-29 15:24:04 INFO     Two factor authentication cookie expires: 2023-10-14 @ 07:42:42
2023-07-29 15:24:04 2023-07-29 15:24:04 INFO     Days remaining until expiration: 76
2023-07-29 15:24:04 2023-07-29 15:24:04 INFO     Synchronisation ended at 15:24:04
2023-07-29 15:24:04 2023-07-29 15:24:04 INFO     Total time taken: 00:04:14
2023-07-29 15:24:04 2023-07-29 15:24:04 INFO     Next synchronisation at 15:19:50

**Comment by jiaoting** [comment]
2023-07-30 00:16:54 /usr/local/bin/sync-icloud.sh: /config/icloudpd.conf: line 35: albums: not found
2023-07-30 00:16:54 
2023-07-30 00:16:54 2023-07-30 00:16:54 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.622 started *****
2023-07-30 00:16:54 2023-07-30 00:16:54 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-07-30 00:16:54 2023-07-30 00:16:54 INFO     Alpine Linux 3.18.2
2023-07-30 00:16:54 2023-07-30 00:16:54 INFO     Python version: 3.11.4
2023-07-30 00:16:54 2023-07-30 00:16:54 INFO     Loading configuration from: /config/icloudpd.conf
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Apple ID: jiaoting@126.com
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Authentication Type: MFA
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Cookie path: /config/jiaoting126com
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Cookie expiry notification period: 7
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Download destination directory: /iCloud
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Folder structure: {:%Y}
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Synchronisation interval: 86400
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Synchronisation delay (minutes): 0
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Set EXIF date/time: false
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Auto delete: true
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Delete after download: false
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Photo size: original
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Single pass mode: false
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Skip download check: true
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Skip live photos: false
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Number of most recently added photos to download: Download All Photos
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Downloading photos from album(s): "all albums"
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Live photo size: original
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Skip videos: false
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Convert HEIC to JPEG: false
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Downloading from: icloud.com.cn
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Authentication domain: cn
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Ignore Synology extended attribute directories: Disabled
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Check download directory mounted correctly...
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023-07-30 00:17:24 2023-07-30 00:17:24 INFO     Keyring file exists, continuing
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO     Albums available:
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - All Photos
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Time-lapse
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Videos
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Slo-mo
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Bursts
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Favorites
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Panoramas
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Screenshots
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Live
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Recently Deleted
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Hidden
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 金茂悦府
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - ❤
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 二手
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 课程
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 工作
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 收集
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 囍相册
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 错埠岭
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 中南1204
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - Photomator
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 今日水印相机
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 百度网盘
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO      - 小红书
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO     Sync user: user
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO     Synchronisation starting at 00:17:35
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO     Keyring file exists, continuing
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO     Check download directory mounted correctly...
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023-07-30 00:17:35 2023-07-30 00:17:35 INFO     Downloading album: "all albums"
2023-07-30 00:17:35 2023-07-30 00:17:35 DEBUG    Authenticating...
2023-07-30 00:17:47 2023-07-30 00:17:47 ERROR    Failed downloading album: "all albums"
2023-07-30 00:17:57 2023-07-30 00:17:57 ERROR    Failed to download new files
2023-07-30 00:17:57 2023-07-30 00:17:57 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-07-30 00:17:57 2023-07-30 00:17:57 ERROR    Error debugging info:
2023-07-30 00:17:57 2023-07-30 00:17:57 ERROR    Traceback (most recent call last):
2023-07-30 00:17:57   File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
2023-07-30 00:17:57     sys.exit(main())
2023-07-30 00:17:57              ^^^^^^
2023-07-30 00:17:57   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2023-07-30 00:17:57     return self.main(*args, **kwargs)
2023-07-30 00:17:57            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-30 00:17:57   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
2023-07-30 00:17:57     rv = self.invoke(ctx)
2023-07-30 00:17:57          ^^^^^^^^^^^^^^^^
2023-07-30 00:17:57   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2023-07-30 00:17:57     return ctx.invoke(self.callback, **ctx.params)
2023-07-30 00:17:57            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-30 00:17:57   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2023-07-30 00:17:57     return __callback(*args, **kwargs)
2023-07-30 00:17:57            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-30 00:17:57   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 285, in main
2023-07-30 00:17:57     core(
2023-07-30 00:17:57   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 696, in core
2023-07-30 00:17:57     photos = icloud.photos.albums[album]
2023-07-30 00:17:57              ~~~~~~~~~~~~~~~~~~~~^^^^^^^
2023-07-30 00:17:57 KeyError: '"all albums"'
2023-07-30 00:17:57 2023-07-30 00:17:57 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-07-30 00:17:57 2023-07-30 00:17:57 INFO     Web cookie expires: 2023-09-14 @ 07:42:33
2023-07-30 00:17:57 2023-07-30 00:17:57 INFO     Two factor authentication cookie expires: 2023-10-14 @ 07:42:42
2023-07-30 00:17:57 2023-07-30 00:17:57 INFO     Days remaining until expiration: 76
2023-07-30 00:17:57 2023-07-30 00:17:57 INFO     Synchronisation ended at 00:17:57
2023-07-30 00:17:57 2023-07-30 00:17:57 INFO     Total time taken: 00:00:22
2023-07-30 00:17:57 2023-07-30 00:17:57 INFO     Next synchronisation at 00:17:35

**Comment by boredazfcuk** [comment]
Unfortunately it's not possible to follow the iCloud photo structure. People have requested this feature upstream. If it gets implemented, I will add it to my container.
