### ISSUE TITLE
Error regenerating MFA cookies

### ISSUE THREAD

**Issue by H15teve** [boredazfcuk/docker-icloudpd#373]
I tried deleting keyring then --Initialise. I could receive 2FA authentication code on Apple device but the error had occured.
```
2023-08-19 18:13:33 INFO     Alpine Linux 3.13.5
2023-08-19 18:13:33 INFO     Python version: 3.8.10
2023-08-19 18:13:33 INFO     icloudpd version: 1.7.2
2023-08-19 18:13:34 INFO     pyicloud-ipd version: 0.10.1
2023-08-19 18:13:36 INFO     Running user id: 0
2023-08-19 18:13:36 INFO     Running group id: 0
2023-08-19 18:13:36 INFO     Local user: user:1000
2023-08-19 18:13:36 INFO     Local group: group:1000
2023-08-19 18:13:36 INFO     Force GID: False
2023-08-19 18:13:36 INFO     LAN IP Address: 172.17.0.4
2023-08-19 18:13:36 INFO     Default gateway: 172.17.0.1
2023-08-19 18:13:36 INFO     DNS server: 192.168.1.1
2023-08-19 18:13:36 INFO     DNS lookup for icloud.com.cn: 103.115.248.1
2023-08-19 18:13:51 INFO     Route check to icloud.com.cn successful
2023-08-19 18:13:51 INFO     Apple ID: ---
2023-08-19 18:13:51 INFO     Authentication Type: MFA
2023-08-19 18:13:51 INFO     Cookie path: /config/---
2023-08-19 18:13:51 INFO     Cookie expiry notification period: 7
2023-08-19 18:13:51 INFO     Download destination directory: /home/user/iCloud
2023-08-19 18:13:51 INFO     Folder structure: {:%Y/%m}
2023-08-19 18:13:51 INFO     Directory permissions: 777
2023-08-19 18:13:51 INFO     File permissions: 777
2023-08-19 18:13:51 INFO     Synchronisation interval: 86400
2023-08-19 18:13:51 INFO     Synchronisation delay (minutes): 0
2023-08-19 18:13:51 INFO     Time zone: Asia/Shanghai
2023-08-19 18:13:51 INFO     Set EXIF date/time: False
2023-08-19 18:13:51 INFO     Auto delete: False
2023-08-19 18:13:51 INFO     Photo size: original
2023-08-19 18:13:51 INFO     Skip download check: True
2023-08-19 18:13:51 INFO     Skip live photos: False
2023-08-19 18:13:51 INFO     Number of most recently added photos to download: Download All Photos
2023-08-19 18:13:51 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-08-19 18:13:51 INFO     Live photo size: original
2023-08-19 18:13:51 INFO     Skip videos: False
2023-08-19 18:13:51 INFO     Convert HEIC to JPEG: False
2023-08-19 18:13:51 INFO     JPEG conversion quality: 90
2023-08-19 18:13:51 INFO     Cleaned notification title: boredazfcukiCloudPD
2023-08-19 18:13:51 INFO     Telegram notifications enabled
2023-08-19 18:13:51 INFO     Telegram token: ---
2023-08-19 18:13:51 INFO     Telegram chat id: ---
2023-08-19 18:13:51 INFO     Telegram notification URL: https://api.telegram.org/---
2023-08-19 18:13:51 INFO     Notification period: 7
2023-08-19 18:13:51 INFO     Sending Telegram startup notification
2023-08-19 18:13:52 INFO     Telegram startup notification sent successfully
2023-08-19 18:13:52 INFO     Download notifications: Enabled
2023-08-19 18:13:52 INFO     Delete notifications: Enabled
2023-08-19 18:13:52 INFO     Downloading from: icloud.com.cn
2023-08-19 18:13:52 WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
2023-08-19 18:13:52 INFO     Script launch parameters: --Initialise
2023-08-19 18:13:52 INFO     Group, group:1000, already created
2023-08-19 18:13:52 INFO     User, user:1000, already created
2023-08-19 18:13:52 INFO     Set owner, user, on iCloud directory, if required
2023-08-19 18:13:52 INFO     Set group, group, on iCloud directory, if required
2023-08-19 18:13:53 INFO     Correct owner on icloudpd temp directory, if required
2023-08-19 18:13:53 INFO     Correct group on icloudpd temp directory, if required
2023-08-19 18:13:53 INFO     Correct owner on config directory, if required
2023-08-19 18:13:53 INFO     Correct group on config directory, if required
2023-08-19 18:13:53 INFO     Correct owner on keyring directory, if required
2023-08-19 18:13:53 INFO     Correct group on keyring directory, if required
2023-08-19 18:13:53 INFO     Set 777 permissions on iCloud directories, if required
2023-08-19 18:13:53 INFO     Set 777 permissions on iCloud files, if required
2023-08-19 18:13:53 INFO     Configure password
2023-08-19 18:13:53 INFO     Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for ---: 
Save password in keyring?  [y/N]: y
Two-step authentication required. Your trusted devices are:
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 216, in main
    devices = api.trusted_devices
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 249, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-08-19 18:14:10 INFO     Correct owner on config directory, if required
2023-08-19 18:14:10 INFO     Correct group on config directory, if required
2023-08-19 18:14:10 INFO     Generate 2FA cookie using password stored in keyring file.
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 47, in authenticate
    request_2sa(icloud, logger)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 53, in request_2sa
    devices = icloud.trusted_devices
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 249, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-08-19 18:14:13 INFO     Web cookie generated. Sync should now be successful.
```

**Comment by boredazfcuk** [comment]
Closed as duplicate.
