### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by raeying06** [boredazfcuk/docker-icloudpd#375]
Key in below, run, error occurred.
/ # sync-icloud.sh --Initialise

2023-08-20 21:05:28 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.622 started *****
2023-08-20 21:05:28 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-08-20 21:05:28 INFO     Alpine Linux 3.18.2
2023-08-20 21:05:28 INFO     Python version: 3.11.4
2023-08-20 21:05:28 INFO     Loading configuration from: /config/icloudpd.conf
2023-08-20 21:05:49 INFO     Apple ID: raeying@gmail.com
2023-08-20 21:05:49 INFO     Authentication Type: MFA
2023-08-20 21:05:49 INFO     Cookie path: /config/raeying06gmailcom
2023-08-20 21:05:49 INFO     Cookie expiry notification period: 7
2023-08-20 21:05:49 INFO     Download destination directory: /share/Photo/data/originals/iCloud/raeliu
2023-08-20 21:05:49 INFO     Folder structure: {:%Y/%m/%d}
2023-08-20 21:05:49 INFO     Synchronisation interval: 86400
2023-08-20 21:05:49 INFO     Synchronisation delay (minutes): 1
2023-08-20 21:05:49 INFO     Set EXIF date/time: false
2023-08-20 21:05:49 INFO     Auto delete: false
2023-08-20 21:05:49 INFO     Delete after download: false
2023-08-20 21:05:49 INFO     Photo size: original
2023-08-20 21:05:49 INFO     Single pass mode: false
2023-08-20 21:05:49 INFO     Skip download check: true
2023-08-20 21:05:49 INFO     Skip live photos: false
2023-08-20 21:05:49 INFO     Number of most recently added photos to download: Download All Photos
2023-08-20 21:05:49 INFO     Downloading photos from album: Download All Photos
2023-08-20 21:05:49 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-08-20 21:05:49 INFO     Live photo size: original
2023-08-20 21:05:49 INFO     Skip videos: false
2023-08-20 21:05:49 INFO     Convert HEIC to JPEG: false
2023-08-20 21:05:49 INFO     Downloading from: icloud.com.cn
2023-08-20 21:05:49 INFO     Authentication domain: cn
2023-08-20 21:05:49 INFO     Ignore Synology extended attribute directories: Disabled
2023-08-20 21:05:49 INFO     Script launch parameters: --Initialise
Traceback (most recent call last):
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 325, in authenticate
    self.session.post(
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 133, in request
    self._raise_error(response.status_code, response.reason)
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 189, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseException: Bad Gateway (502)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.7.2_china/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd===1.7.2-china-auth-fix', 'console_scripts', 'icloudpd')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/icloudpd-1.7.2_china_auth_fix-py3.11.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
             ^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/icloudpd-1.7.2_china_auth_fix-py3.11.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud.PyiCloudService(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 271, in __init__
    self.authenticate()
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 333, in authenticate
    raise PyiCloudFailedLoginException(msg, error) from error
pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('Bad Gateway (502)'))
2023-08-20 21:05:54 ERROR    Multi-factor authentication information missing from cookie. Authentication has failed
2023-08-20 21:05:54 ERROR     - Was the correct password entered?
2023-08-20 21:05:54 ERROR     - Was the multi-factor authentication code mistyped?
2023-08-20 21:05:54 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-08-20 21:05:54 ERROR     - Are you based in China? You will need to set the icloud_china variable

**Comment by boredazfcuk** [comment]
>pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.'

Check you're putting in the right password.

>PyiCloudAPIResponseException('Bad Gateway (502)'))

And also that you have Internet connectivity from within the container.
