### ISSUE TITLE
Still require 2FA after initialization.

### ISSUE THREAD

**Issue by BreakVoid** [boredazfcuk/docker-icloudpd#378]
Two weeks ago, it works well. However, when I start the service to sync my new photos, the issue occurs. It always want me to input the 2FA code. Even if I have reinitialize the cookies manaually.
```
icloudpd-songyu  | 2023-08-24 17:53:44 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.627 started *****
icloudpd-songyu  | 2023-08-24 17:53:44 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
icloudpd-songyu  | 2023-08-24 17:53:44 INFO     Alpine Linux 3.18.2
icloudpd-songyu  | 2023-08-24 17:53:44 INFO     Python version: 3.11.4
icloudpd-songyu  | 2023-08-24 17:53:44 INFO     Loading configuration from: /config/icloudpd.conf
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Apple ID: ********
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Authentication Type: MFA
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Cookie path: /config/********
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Cookie expiry notification period: 7
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Download destination directory: /iCloud
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Folder structure: {:%Y-%m}
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Synchronisation interval: 86400
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Synchronisation delay (minutes): 0
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Set EXIF date/time: false
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Auto delete: false
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Delete after download: false
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Photo size: original
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Single pass mode: false
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Skip download check: false
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Skip live photos: false
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Number of most recently added photos to download: Download All Photos
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Downloading photos from album: Download All Photos
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Stop downloading when prexisiting files count is: Download All Photos
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Live photo size: original
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Skip videos: false
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Convert HEIC to JPEG: false
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Downloading from: icloud.com.cn
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Authentication domain: cn
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Ignore Synology extended attribute directories: Disabled
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Directory is writable: /config/python_keyring/
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Directory is writable: /home/user/.local/share/
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Check download directory mounted correctly...
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Failsafe file /iCloud/.mounted exists, continuing
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Directory is writable: /config/python_keyring/
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Directory is writable: /home/user/.local/share/
icloudpd-songyu  | 2023-08-24 17:54:25 INFO     Keyring file exists, continuing
icloudpd-songyu  | Traceback (most recent call last):
icloudpd-songyu  |   File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
icloudpd-songyu  |     sys.exit(main())
icloudpd-songyu  |              ^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
icloudpd-songyu  |     return self.main(*args, **kwargs)
icloudpd-songyu  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
icloudpd-songyu  |     rv = self.invoke(ctx)
icloudpd-songyu  |          ^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
icloudpd-songyu  |     return ctx.invoke(self.callback, **ctx.params)
icloudpd-songyu  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
icloudpd-songyu  |     return __callback(*args, **kwargs)
icloudpd-songyu  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 285, in main
icloudpd-songyu  |     core(
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 665, in core
icloudpd-songyu  |     icloud = authenticator(domain)(
icloudpd-songyu  |              ^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 49, in authenticate_
icloudpd-songyu  |     request_2sa(icloud, logger)
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 56, in request_2sa
icloudpd-songyu  |     devices = icloud.trusted_devices
icloudpd-songyu  |               ^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 266, in trusted_devices
icloudpd-songyu  |     request = self.session.get(
icloudpd-songyu  |               ^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
icloudpd-songyu  |     return self.request("GET", url, **kwargs)
icloudpd-songyu  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
icloudpd-songyu  |     self._raise_error(code, reason)
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
icloudpd-songyu  |     raise api_error
icloudpd-songyu  | pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
icloudpd-songyu  | 2023-08-24 17:54:29 INFO     Albums available:
icloudpd-songyu  | 2023-08-24 17:54:29 INFO      - 2023-08-24 17:54:29 INFO     Two-step/two-factor authentication is required!
icloudpd-songyu  | 2023-08-24 17:54:29 INFO     Sync user: user
icloudpd-songyu  | 2023-08-24 17:54:29 INFO     Synchronisation starting at 17:54:29
icloudpd-songyu  | 2023-08-24 17:54:29 INFO     Keyring file exists, continuing
icloudpd-songyu  | 2023-08-24 17:54:29 INFO     Check download directory mounted correctly...
icloudpd-songyu  | 2023-08-24 17:54:29 INFO     Failsafe file /iCloud/.mounted exists, continuing
icloudpd-songyu  | 2023-08-24 17:54:29 INFO     Check for new files using password stored in keyring file
icloudpd-songyu  | 2023-08-24 17:54:29 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
icloudpd-songyu  | 2023-08-24 17:54:33 ERROR    Failed check for new files files
icloudpd-songyu  | 2023-08-24 17:54:33 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
icloudpd-songyu  | 2023-08-24 17:54:33 ERROR    Error debugging info:
icloudpd-songyu  | 2023-08-24 17:54:33 ERROR    Traceback (most recent call last):
icloudpd-songyu  |   File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
icloudpd-songyu  |     sys.exit(main())
icloudpd-songyu  |              ^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
icloudpd-songyu  |     return self.main(*args, **kwargs)
icloudpd-songyu  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
icloudpd-songyu  |     rv = self.invoke(ctx)
icloudpd-songyu  |          ^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
icloudpd-songyu  |     return ctx.invoke(self.callback, **ctx.params)
icloudpd-songyu  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
icloudpd-songyu  |     return __callback(*args, **kwargs)
icloudpd-songyu  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 285, in main
icloudpd-songyu  |     core(
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 665, in core
icloudpd-songyu  |     icloud = authenticator(domain)(
icloudpd-songyu  |              ^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 49, in authenticate_
icloudpd-songyu  |     request_2sa(icloud, logger)
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 56, in request_2sa
icloudpd-songyu  |     devices = icloud.trusted_devices
icloudpd-songyu  |               ^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 266, in trusted_devices
icloudpd-songyu  |     request = self.session.get(
icloudpd-songyu  |               ^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
icloudpd-songyu  |     return self.request("GET", url, **kwargs)
icloudpd-songyu  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
icloudpd-songyu  |     self._raise_error(code, reason)
icloudpd-songyu  |   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
icloudpd-songyu  |     raise api_error
icloudpd-songyu  | pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
icloudpd-songyu  | 2023-08-24 17:54:33 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
icloudpd-songyu  | 2023-08-24 17:54:33 INFO     Web cookie expires: 2023-10-23 @ 09:48:39
icloudpd-songyu  | 2023-08-24 17:54:33 INFO     Two factor authentication cookie expires: 2023-11-22 @ 09:48:58
icloudpd-songyu  | 2023-08-24 17:54:33 INFO     Days remaining until expiration: 89
icloudpd-songyu  | 2023-08-24 17:54:33 INFO     Synchronisation ended at 17:54:33
icloudpd-songyu  | 2023-08-24 17:54:33 INFO     Total time taken: 00:00:04
icloudpd-songyu  | 2023-08-24 17:54:33 INFO     Next synchronisation at 17:54:29
```

**Comment by jiaoting** [comment]
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Cookie path: /config/jiaoting126com
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Cookie expiry notification period: 7
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Download destination directory: /iCloud
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Folder structure: {:%Y}
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Synchronisation interval: 86400
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Synchronisation delay (minutes): 0
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Set EXIF date/time: false
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Auto delete: true
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Delete after download: false
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Photo size: original
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Single pass mode: false
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Skip download check: true
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Skip live photos: false
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Number of most recently added photos to download: Download All Photos
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Downloading photos from album: Download All Photos
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Live photo size: original
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Skip videos: false
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Convert HEIC to JPEG: false
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Downloading from: icloud.com.cn
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Authentication domain: cn
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Ignore Synology extended attribute directories: Disabled
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Directory is writable: /config/python_keyring/
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Directory is writable: /home/user/.local/share/
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Check download directory mounted correctly...
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Directory is writable: /config/python_keyring/
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Directory is writable: /home/user/.local/share/
2023-08-26 00:07:28 2023-08-26 00:07:28 INFO     Keyring file exists, continuing
2023-08-26 00:07:32 2023-08-26 00:07:32 INFO     Albums available:
2023-08-26 00:07:32 2023-08-26 00:07:32 INFO      - 2023-08-26 00:07:32 INFO     Two-step/two-factor authentication is required!
2023-08-26 00:07:32 2023-08-26 00:07:32 INFO     Sync user: user
2023-08-26 00:07:32 2023-08-26 00:07:32 INFO     Synchronisation starting at 00:07:32
2023-08-26 00:07:32 2023-08-26 00:07:32 INFO     Keyring file exists, continuing
2023-08-26 00:07:32 2023-08-26 00:07:32 INFO     Check download directory mounted correctly...
2023-08-26 00:07:32 2023-08-26 00:07:32 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023-08-26 00:07:33 2023-08-26 00:07:33 DEBUG    Authenticating...
2023-08-26 00:07:36 2023-08-26 00:07:36 INFO     Two-step/two-factor authentication is required!
2023-08-26 00:07:36 2023-08-26 00:07:36 ERROR    Failed to download new files
2023-08-26 00:07:36 2023-08-26 00:07:36 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-08-26 00:06:58 /usr/local/bin/sync-icloud.sh: /config/icloudpd.conf: line 35: albums: not found
2023-08-26 00:07:32 Traceback (most recent call last):
2023-08-26 00:07:32   File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
2023-08-26 00:07:32     sys.exit(main())
2023-08-26 00:07:32              ^^^^^^
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2023-08-26 00:07:32     return self.main(*args, **kwargs)
2023-08-26 00:07:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
2023-08-26 00:07:32     rv = self.invoke(ctx)
2023-08-26 00:07:32          ^^^^^^^^^^^^^^^^
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2023-08-26 00:07:32     return ctx.invoke(self.callback, **ctx.params)
2023-08-26 00:07:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2023-08-26 00:07:32     return __callback(*args, **kwargs)
2023-08-26 00:07:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 285, in main
2023-08-26 00:07:32     core(
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 665, in core
2023-08-26 00:07:32     icloud = authenticator(domain)(
2023-08-26 00:07:32              ^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 49, in authenticate_
2023-08-26 00:07:32     request_2sa(icloud, logger)
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 56, in request_2sa
2023-08-26 00:07:32     devices = icloud.trusted_devices
2023-08-26 00:07:32               ^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 266, in trusted_devices
2023-08-26 00:07:32     request = self.session.get(
2023-08-26 00:07:32               ^^^^^^^^^^^^^^^^^
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
2023-08-26 00:07:32     return self.request("GET", url, **kwargs)
2023-08-26 00:07:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
2023-08-26 00:07:32     self._raise_error(code, reason)
2023-08-26 00:07:32   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
2023-08-26 00:07:32     raise api_error
2023-08-26 00:07:32 pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-08-26 00:07:36 2023-08-26 00:07:36 ERROR    Error debugging info:
2023-08-26 00:07:36 2023-08-26 00:07:36 ERROR    Traceback (most recent call last):
2023-08-26 00:07:36   File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
2023-08-26 00:07:36     sys.exit(main())
2023-08-26 00:07:36              ^^^^^^
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2023-08-26 00:07:36     return self.main(*args, **kwargs)
2023-08-26 00:07:36            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
2023-08-26 00:07:36     rv = self.invoke(ctx)
2023-08-26 00:07:36          ^^^^^^^^^^^^^^^^
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2023-08-26 00:07:36     return ctx.invoke(self.callback, **ctx.params)
2023-08-26 00:07:36            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2023-08-26 00:07:36     return __callback(*args, **kwargs)
2023-08-26 00:07:36            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 285, in main
2023-08-26 00:07:36     core(
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 665, in core
2023-08-26 00:07:36     icloud = authenticator(domain)(
2023-08-26 00:07:36              ^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 49, in authenticate_
2023-08-26 00:07:36     request_2sa(icloud, logger)
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 56, in request_2sa
2023-08-26 00:07:36     devices = icloud.trusted_devices
2023-08-26 00:07:36               ^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 266, in trusted_devices
2023-08-26 00:07:36     request = self.session.get(
2023-08-26 00:07:36               ^^^^^^^^^^^^^^^^^
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
2023-08-26 00:07:36     return self.request("GET", url, **kwargs)
2023-08-26 00:07:36            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
2023-08-26 00:07:36     self._raise_error(code, reason)
2023-08-26 00:07:36   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
2023-08-26 00:07:36     raise api_error
2023-08-26 00:07:36 pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-08-26 00:07:36 2023-08-26 00:07:36 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-08-26 00:07:36 2023-08-26 00:07:36 INFO     Web cookie expires: 2023-10-22 @ 09:13:39
2023-08-26 00:07:36 2023-08-26 00:07:36 INFO     Two factor authentication cookie expires: 2023-11-21 @ 09:13:48
2023-08-26 00:07:36 2023-08-26 00:07:36 INFO     Days remaining until expiration: 87
2023-08-26 00:07:36 2023-08-26 00:07:36 INFO     Synchronisation ended at 00:07:36
2023-08-26 00:07:36 2023-08-26 00:07:36 INFO     Total time taken: 00:00:04
2023-08-26 00:07:36 2023-08-26 00:07:36 INFO     Next synchronisation at 00:07:32

**Comment by BreakVoid** [comment]
I have solved the issue. The reason is that icloud.com.cn has updated the terms of service, and it requires two confirmations from the user. Without the two confirmations, the cookie cannot be used by icloudpd.

**Comment by boredazfcuk** [comment]
> 2023-08-26 00:07:36 2023-08-26 00:07:36 ERROR - Can you log into icloud.com.cn without receiving pop-up notifications?

So you were getting pop-up notifications when logging onto iCloud?

**Comment by jiaoting** [comment]
> > 2023-08-26 00:07:36 2023-08-26 00:07:36 ERROR - Can you log into icloud.com.cn without receiving pop-up notifications?
> 
> So you were getting pop-up notifications when logging onto iCloud?

yes

**Comment by jiaoting** [comment]
> I have solved the issue. The reason is that icloud.com.cn has updated the terms of service, and it requires two confirmations from the user. Without the two confirmations, the cookie cannot be used by icloudpd.

怎么处理呢？

**Comment by BreakVoid** [comment]
1. Open the browser and login to [icloud.com.cn](https://icloud.com.cn) normally.
2. Confirm the two pop-up notifications, i.e., asking you to agree with the new terms of service.
3. Execute `sync-icloud.sh -Initialise` to regenerate the cookie.

With the three steps above, I can sync the photos again. I hope it would help you.

**Comment by laoshu133** [comment]
> 

It works for me

**Comment by laoshu133** [comment]
> 1. Open the browser and login to [icloud.com.cn](https://icloud.com.cn) normally.
> 2. Confirm the two pop-up notifications, i.e., asking you to agree with the new terms of service.
> 3. Execute `sync-icloud.sh -Initialise` to regenerate the cookie.
> 
> With the three steps above, I can sync the photos again. I hope it would help you.

It works for me

**Comment by jiaoting** [comment]
me too



At 2023-08-27 14:13:50, "米空格" ***@***.***> wrote:

Open the browser and login to icloud.com.cn normally.
Confirm the two pop-up notifications, i.e., asking you to agree with the new terms of service.
Execute sync-icloud.sh -Initialise to regenerate the cookie.

With the three steps above, I can sync the photos again. I hope it would help you.

It works for me

**Comment by jinnxu75** [comment]
> > 1. Open the browser and login to [icloud.com.cn](https://icloud.com.cn) normally.
> > 2. Confirm the two pop-up notifications, i.e., asking you to agree with the new terms of service.
> > 3. Execute `sync-icloud.sh -Initialise` to regenerate the cookie.
> > 
> > With the three steps above, I can sync the photos again. I hope it would help you.
> 
> It works for me



> > 1. Open the browser and login to [icloud.com.cn](https://icloud.com.cn) normally.
> > 2. Confirm the two pop-up notifications, i.e., asking you to agree with the new terms of service.
> > 3. Execute `sync-icloud.sh -Initialise` to regenerate the cookie.
> > 
> > With the three steps above, I can sync the photos again. I hope it would help you.
> 
> It works for me

me too. Thanks a lot
