### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by dragon7999** [boredazfcuk/docker-icloudpd#379]
2023-08-28 15:34:15 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.453 started *****
2023-08-28 15:34:15 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-08-28 15:34:15 INFO     Alpine Linux 3.17.3
2023-08-28 15:34:15 INFO     Python version: 3.10.11
2023-08-28 15:34:15 INFO     Loading configuration from: /config/icloudpd.conf
2023-08-28 15:34:36 INFO     Apple ID: ********@foxmail.com
2023-08-28 15:34:36 INFO     Authentication Type: 2FA
2023-08-28 15:34:36 INFO     Cookie path: /config/dragon719foxmailcom
2023-08-28 15:34:36 INFO     Cookie expiry notification period: 7
2023-08-28 15:34:36 INFO     Download destination directory: /icloud
2023-08-28 15:34:36 INFO     Folder structure: {:%Y/%m/%d}
2023-08-28 15:34:36 INFO     Synchronisation interval: 86400
2023-08-28 15:34:36 INFO     Synchronisation delay (minutes): 0
2023-08-28 15:34:36 INFO     Set EXIF date/time: false
2023-08-28 15:34:36 INFO     Auto delete: false
2023-08-28 15:34:36 INFO     Photo size: original
2023-08-28 15:34:36 INFO     Single pass mode: false
2023-08-28 15:34:36 INFO     Skip download check: true
2023-08-28 15:34:36 INFO     Skip live photos: false
2023-08-28 15:34:36 INFO     Number of most recently added photos to download: Download All Photos
2023-08-28 15:34:36 INFO     Downloading photos from album: Download All Photos
2023-08-28 15:34:36 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-08-28 15:34:36 INFO     Live photo size: original
2023-08-28 15:34:36 INFO     Skip videos: false
2023-08-28 15:34:36 INFO     Convert HEIC to JPEG: false
2023-08-28 15:34:36 INFO     Downloading from: icloud.com.cn
2023-08-28 15:34:36 INFO     Authentication domain: cn
2023-08-28 15:34:36 INFO     Check download directory mounted correctly...
2023-08-28 15:34:36 INFO     Failsafe file /icloud/.mounted exists, continuing
2023-08-28 15:34:42 INFO     Albums available:
2023-08-28 15:34:42 INFO      - All Photos
2023-08-28 15:34:42 INFO      - Time-lapse
2023-08-28 15:34:42 INFO      - Videos
2023-08-28 15:34:42 INFO      - Slo-mo
2023-08-28 15:34:42 INFO      - Bursts
2023-08-28 15:34:42 INFO      - Favorites
2023-08-28 15:34:42 INFO      - Panoramas
2023-08-28 15:34:42 INFO      - Screenshots
2023-08-28 15:34:42 INFO      - Live
2023-08-28 15:34:42 INFO      - Recently Deleted
2023-08-28 15:34:42 INFO      - Hidden
2023-08-28 15:34:42 INFO      - 证件
2023-08-28 15:34:42 INFO      - 车辆
2023-08-28 15:34:42 INFO     Sync user: user
2023-08-28 15:34:42 INFO     Synchronisation starting at 15:34:42
2023-08-28 15:34:42 INFO     Check download directory mounted correctly...
2023-08-28 15:34:42 INFO     Failsafe file /icloud/.mounted exists, continuing
2023-08-28 15:34:43 DEBUG    Authenticating...
2023-08-28 15:34:48 DEBUG    Looking up all photos and videos from album All Photos...
2023-08-28 15:34:48 INFO     Downloading 5051 original photos and videos to /icloud ...
2023-08-28 15:34:51 ERROR    Failed to download new files
2023-08-28 15:34:51 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-08-28 15:34:51 ERROR    Error debugging info:
2023-08-28 15:34:51 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/base.py", line 283, in main
    core(
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/base.py", line 727, in core
    if download_photo(
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/icloudpd/base.py", line 355, in download_photo_
    created_date = photo.created.astimezone(get_localzone())
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/tzlocal/unix.py", line 209, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/tzlocal/unix.py", line 167, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/opt/icloudpd_latest/lib/python3.10/site-packages/tzlocal/utils.py", line 124, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like CST-8. \nPlease use a timezone in the form of Continent/City'
2023-08-28 15:34:51 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-08-28 15:34:51 INFO     Web cookie expires: 2023-10-27 @ 07:17:40
2023-08-28 15:34:51 INFO     Two factor authentication cookie expires: 2023-11-26 @ 07:18:04
2023-08-28 15:34:51 INFO     Days remaining until expiration: 89
2023-08-28 15:34:51 INFO     Synchronisation ended at 15:34:51
2023-08-28 15:34:51 INFO     Total time taken: 00:00:09
2023-08-28 15:34:51 INFO     Next synchronisation at 15:34:42

**Comment by 2Jelly2** [comment]
you may refer to section 3 in this page #336 
e.g. using Asia/Shanghai instead of CST-8 as TZ

**Comment by dragon7999** [comment]
> you may refer to section 3 in this page #336 e.g. using Asia/Shanghai instead of CST-8 as TZ

Thank you very much for your advice!  Changing the time zone to Asia / Shanghai solved my problem!  The problem haunted me for three days, and finally the dust settled.
