### ISSUE TITLE
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, 

### ISSUE THREAD

**Issue by HuLuXi** [boredazfcuk/docker-icloudpd#383]
2023-08-29 23:38:18 INFO     Skip download check: true
2023-08-29 23:38:18 INFO     Skip live photos: false
2023-08-29 23:38:18 INFO     Number of most recently added photos to download: Download All Photos
2023-08-29 23:38:18 INFO     Downloading photos from album: Download All Photos
2023-08-29 23:38:18 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-08-29 23:38:18 INFO     Live photo size: original
2023-08-29 23:38:18 INFO     Skip videos: false
2023-08-29 23:38:18 INFO     Convert HEIC to JPEG: true
2023-08-29 23:38:18 INFO     Downloading from: icloud.com.cn
2023-08-29 23:38:18 INFO     Authentication domain: cn
2023-08-29 23:38:18 INFO     Ignore Synology extended attribute directories: Disabled
2023-08-29 23:38:18 INFO     Directory is writable: /config/python_keyring/
2023-08-29 23:38:18 INFO     Directory is writable: /home/cal/.local/share/
2023-08-29 23:38:18 ERROR    Keyring file /config/python_keyring/keyring_pass.cfg does not exist
2023-08-29 23:38:18 ERROR     - Please add the your password to the system keyring using the --Initialise script command line option
2023-08-29 23:38:18 ERROR     - Syntax: docker exec -it <container name> sync-icloud.sh --Initialise
2023-08-29 23:38:18 ERROR     - Example: docker exec -it icloudpd sync-icloud.sh --Initialise
2023-08-29 23:38:18 ERROR    Waiting for keyring file to be created...
2023-08-29 23:39:13 INFO     Check download directory mounted correctly...
2023-08-29 23:39:13 INFO     Failsafe file /photos/.mounted exists, continuing
2023-08-29 23:39:13 INFO     Directory is writable: /config/python_keyring/
2023-08-29 23:39:13 INFO     Directory is writable: /home/cal/.local/share/
2023-08-29 23:39:13 INFO     Keyring file exists, continuing
2023-08-29 23:39:13 ERROR    Multi-factor authentication cookie does not exist
2023-08-29 23:39:13 ERROR    Waiting for valid cookie file to be created...
2023-08-29 23:39:13 ERROR     - Please create your cookie using the --Initialise script command line option
2023-08-29 23:39:13 ERROR     - Syntax: docker exec -it <container name> sync-icloud.sh --Initialise
2023-08-29 23:39:13 ERROR     - Example: docker exec -it icloudpd sync-icloud.sh --Initialise
Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 285, in main

(
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 665, in core
    icloud = authenticator(domain)(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 49, in authenticate_
    request_2sa(icloud, logger)
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 56, in request_2sa
    devices = icloud.trusted_devices
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 266, in trusted_devices
    request = self.session.get(
              ^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-08-29 23:40:04 INFO     Albums available:
2023-08-29 23:40:04 INFO      - 2023-08-29 23:40:03 INFO     Two-step/two-factor authentication is required!
2023-08-29 23:40:04 INFO     Sync user: cal
2023-08-29 23:40:04 INFO     Synchronisation starting at 23:40:04
2023-08-29 23:40:04 INFO     Keyring file exists, continuing
2023-08-29 23:40:04 INFO     Check download directory mounted correctly...
2023-08-29 23:40:04 INFO     Failsafe file /photos/.mounted exists, continuing
2023-08-29 23:40:06 DEBUG    Authenticating...
2023-08-29 23:40:09 INFO     Two-step/two-factor authentication is required!
2023-08-29 23:40:09 ERROR    Failed to download new files
2023-08-29 23:40:09 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-08-29 23:40:10 ERROR    Error debugging info:
2023-08-29 23:40:10 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 285, in main

(
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 665, in core
    icloud = authenticator(domain)(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 49, in authenticate_
    request_2sa(icloud, logger)
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 56, in request_2sa
    devices = icloud.trusted_devices
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 266, in trusted_devices
    request = self.session.get(
              ^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-08-29 23:40:10 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-08-29 23:40:10 INFO     Web cookie expires: 2023-10-28 @ 15:39:37
2023-08-29 23:40:10 INFO     Two factor authentication cookie expires: 2023-11-27 @ 15:39:47
2023-08-29 23:40:10 INFO     Days remaining until expiration: 89
2023-08-29 23:40:10 INFO     Synchronisation ended at 23:40:10
2023-08-29 23:40:10 INFO     Total time taken: 00:00:06
2023-08-29 23:40:10 INFO     Next synchronisation at 23:40:04

**Comment by boredazfcuk** [comment]
Closed. No fault found. iCloud.com issue

**Comment by Qwenjin** [comment]
>> docker exec -it icloudpd sync-icloud.sh --Initialise
...
...

2023-09-03 17:45:22 INFO     Generate 2FA cookie using password stored in keyring file.
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 47, in authenticate
    request_2sa(icloud, logger)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 53, in request_2sa
    devices = icloud.trusted_devices
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 249, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-09-03 17:45:27 INFO     Two factor authentication cookie generated. Sync should now be successful.

---

run log:

2023-09-03 17:49:38 2023-09-03 17:49:38 INFO     Cookie exists, check expiry date
2023-09-03 17:49:38 2023-09-03 17:49:38 ERROR    Cookie is not 2FA capable, authentication type may have changed.
2023-09-03 17:49:38 2023-09-03 17:49:38 INFO      - Please recreate your cookie using the --Initialise script command line option.
2023-09-03 17:49:38 2023-09-03 17:49:38 INFO      - Syntax: docker exec -it <container name> sync-icloud.sh --Initialise
2023-09-03 17:49:38 2023-09-03 17:49:38 INFO      - Example: docker exec -it icloudpd sync-icloud.sh --Initialise
2023-09-03 17:49:38 2023-09-03 17:49:38 INFO     Restarting in 5 minutes...
