### ISSUE TITLE
init fail,  UnknownServerError

### ISSUE THREAD

**Issue by Qwenjin** [boredazfcuk/docker-icloudpd#385]
docker exec -it icloudpd sync-icloud.sh --Initialise

...
...

2023-09-03 17:45:22 INFO     Generate 2FA cookie using password stored in keyring file.
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 47, in authenticate
    request_2sa(icloud, logger)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 53, in request_2sa
    devices = icloud.trusted_devices
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 249, in trusted_devices
    request = self.session.get(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-09-03 17:45:27 INFO     Two factor authentication cookie generated. Sync should now be successful.

---

run log:

2023-09-03 17:49:38 2023-09-03 17:49:38 INFO     Cookie exists, check expiry date
2023-09-03 17:49:38 2023-09-03 17:49:38 ERROR    Cookie is not 2FA capable, authentication type may have changed.
2023-09-03 17:49:38 2023-09-03 17:49:38 INFO      - Please recreate your cookie using the --Initialise script command line option.
2023-09-03 17:49:38 2023-09-03 17:49:38 INFO      - Syntax: docker exec -it <container name> sync-icloud.sh --Initialise
2023-09-03 17:49:38 2023-09-03 17:49:38 INFO      - Example: docker exec -it icloudpd sync-icloud.sh --Initialise
2023-09-03 17:49:38 2023-09-03 17:49:38 INFO     Restarting in 5 minutes...

---
version info:

2023-09-03 17:51:12 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2023-09-03 17:51:12 INFO     ***** https://github.com/boredazfcuk/docker-icloudpd *****
2023-09-03 17:51:12 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/12/13_07:53 *****
2023-09-03 17:51:12 INFO     ***** /usr/local/bin/sync-icloud.sh hash: 74dfafa177492086fb3c777f518fbb55 *****
2023-09-03 17:51:12 INFO     Alpine Linux 3.13.5
2023-09-03 17:51:12 INFO     Python version: 3.8.10
WARNING: You are using pip version 21.3.1; however, version 23.2.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2023-09-03 17:51:12 INFO     icloudpd version: 1.7.2
WARNING: You are using pip version 21.3.1; however, version 23.2.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2023-09-03 17:51:13 INFO     pyicloud-ipd version: 0.10.1
2023-09-03 17:51:13 INFO     Running user id: 0
2023-09-03 17:51:13 INFO     Running group id: 0
2023-09-03 17:51:13 INFO     Local user: user:1000
2023-09-03 17:51:13 INFO     Local group: group:1000
2023-09-03 17:51:13 INFO     Force GID: False
2023-09-03 17:51:13 INFO     LAN IP Address: 192.168.115.1
2023-09-03 17:51:13 INFO     Default gateway: 192.168.115.254
2023-09-03 17:51:13 INFO     DNS server: 127.0.0.11
2023-09-03 17:51:13 INFO     DNS lookup for icloud.com.cn: 103.115.248.1
2023-09-03 17:51:41 INFO     Route check to icloud.com.cn successful

_Originally posted by @Qwenjin in https://github.com/boredazfcuk/docker-icloudpd/issues/383#issuecomment-1704073625_

**Comment by HuLuXi** [comment]
我那底下他说没问题，直接关闭了，还以为是个例，这也不知道咋解决

**Comment by boredazfcuk** [comment]
Duplicate

**Comment by Qwenjin** [comment]
> 我那底下他说没问题，直接关闭了，还以为是个例，这也不知道咋解决

他意思好像是icloud.com本身的问题，和代码没关系。可能要自己改代码来处理了

**Comment by Qwenjin** [comment]
> 我那底下他说没问题，直接关闭了，还以为是个例，这也不知道咋解决

参考解决方案：https://github.com/boredazfcuk/docker-icloudpd/issues/378
参考docker：docker pull pjoc/docker-icloudpd:master
大致就是用这个镜像进行MFA鉴权和获取cookie，然后再切回原镜像同步iCloud的图片。
这个镜像的配置和挂载目录都和原镜像一致。

**Comment by HuLuXi** [comment]
> 

不用先用那个镜像，就是云上贵州协议更新了，需要网页登上icloud同意那个协议，然后就能用了,你提供的378那个评论里有解决方案，就是我说的这个，现在已经成功下载了。但是我现在不能用bark不知道为啥，就很离谱，一个问题解决了，另一个问题又来了

**Comment by Qwenjin** [comment]
> > 
> 
> 不用先用那个镜像，就是云上贵州协议更新了，需要网页登上icloud同意那个协议，然后就能用了,你提供的378那个评论里有解决方案，就是我说的这个，现在已经成功下载了。但是我现在不能用bark不知道为啥，就很离谱，一个问题解决了，另一个问题又来了

sorry，我实际用的方法不是378那个，而是294评论下面的：https://github.com/boredazfcuk/docker-icloudpd/issues/294

**Comment by HuLuXi** [comment]
解决了就行，老哥用的啥通知渠道
