### ISSUE TITLE
ERROR    Keyring file does not exist. Please try again.

### ISSUE THREAD

**Issue by gygy** [boredazfcuk/docker-icloudpd#403]
配置如下:
version: "3.7"
services:
  icloudpd:
    image: boredazfcuk/icloudpd:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - user=root
      - user_id=0
      - group=root
      - group_id=0
      - apple_id=+861803xxxxx
      - authentication_type=2FA
      - synchronisation_interval=43200
      - config_dir=/config
      - XDG_DATA_HOME=/config
      - download_path=/app/icloudpd/icloud
      - folder_structure={:%Y/%m}
    volumes:
      - /app/icloudpd/config:/config

初始化:

root@vdocker:~# docker exec -it icloudpd-icloudpd-1  sync-icloud.sh --Initialise

2023-10-05 09:17:21 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.662 started *****
2023-10-05 09:17:21 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-10-05 09:17:21 INFO     Alpine Linux 3.18.3
2023-10-05 09:17:21 INFO     Python version: 3.11.5
2023-10-05 09:17:22 INFO     Loading configuration from: /config/icloudpd.conf
ERROR    Keyring file does not exist. Please try again.2023-10-05 09:17:51 INFO     Apple ID: +86180380xxxxx
2023-10-05 09:17:51 INFO     Authentication Type: MFA
2023-10-05 09:17:51 INFO     Cookie path: /config/8618038xxxxxx
2023-10-05 09:17:51 INFO     Cookie expiry notification period: 7
2023-10-05 09:17:51 INFO     Download destination directory: /app/icloudpd/icloud
2023-10-05 09:17:51 INFO     Folder structure: {:%Y/%m}
2023-10-05 09:17:51 INFO     Synchronisation interval: 43200
2023-10-05 09:17:51 INFO     Synchronisation delay (minutes): 0
2023-10-05 09:17:51 INFO     Set EXIF date/time: false
2023-10-05 09:17:51 INFO     Auto delete: false
2023-10-05 09:17:51 INFO     Delete after download: false
2023-10-05 09:17:51 INFO     Photo size: original
2023-10-05 09:17:51 INFO     Single pass mode: false
2023-10-05 09:17:51 INFO     Skip download check: false
2023-10-05 09:17:51 INFO     Skip live photos: false
2023-10-05 09:17:51 INFO     Number of most recently added photos to download: Download All Photos
2023-10-05 09:17:51 INFO     Downloading photos from: Download All Photos
2023-10-05 09:17:51 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-10-05 09:17:51 INFO     Live photo size: original
2023-10-05 09:17:51 INFO     Skip videos: false
2023-10-05 09:17:51 INFO     Convert HEIC to JPEG: false
2023-10-05 09:17:51 INFO     Downloading from: icloud.com
2023-10-05 09:17:51 INFO     Authentication domain: com
2023-10-05 09:17:51 INFO     Ignore Synology extended attribute directories: Disabled
2023-10-05 09:17:51 INFO     Script launch parameters: --Initialise
Enter iCloud password for +8618038xxxxxx:
Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloud", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    api = pyicloud_ipd.PyiCloudService(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 234, in authenticate
    raise PyiCloudConnectionException(msg)
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter
2023-10-05 09:18:00 ERROR    Keyring file does not exist. Please try again.

**Comment by gygy** [comment]
- user=root
- user_id=0
- group=root
- group_id=0    ----以上四行,修改成其他也不行

**Comment by boredazfcuk** [comment]
>- TZ=Asia/Shanghai

>pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter

You have not configured your container correctly. There are two variables needed to make it download and authenticate against Chinese servers.
