### ISSUE TITLE
Cannot Initialize icloudpd

### ISSUE THREAD

**Issue by askalee2000** [boredazfcuk/docker-icloudpd#410]
After I enter my icloud password，The following prompt appears，don't know how to do next（It hasn't appeared before）。

2023-10-11 14:13:39 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.679 started *****
2023-10-11 14:13:39 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-10-11 14:13:39 INFO     Alpine Linux 3.18.3
2023-10-11 14:13:39 INFO     Python version: 3.11.5
2023-10-11 14:13:41 INFO     Loading configuration from: /config/icloudpd.conf
2023-10-11 14:14:08 INFO     Apple ID: xxxxxxxx@gmail.com
2023-10-11 14:14:08 INFO     Authentication Type: MFA
2023-10-11 14:14:08 INFO     Cookie path: /config/stoneleelileigmailcom
2023-10-11 14:14:08 INFO     Cookie expiry notification period: 7
2023-10-11 14:14:08 INFO     Download destination directory: /iCloud
2023-10-11 14:14:08 INFO     Folder structure: {:%Y/%m}
2023-10-11 14:14:08 INFO     Synchronisation interval: 86400
2023-10-11 14:14:08 INFO     Synchronisation delay (minutes): 0
2023-10-11 14:14:08 INFO     Set EXIF date/time: false
2023-10-11 14:14:08 INFO     Auto delete: false
2023-10-11 14:14:08 INFO     Delete after download: false
2023-10-11 14:14:08 INFO     Photo size: original
2023-10-11 14:14:08 INFO     Single pass mode: false
2023-10-11 14:14:08 INFO     Skip download check: false
2023-10-11 14:14:08 INFO     Skip live photos: false
2023-10-11 14:14:08 INFO     Number of most recently added photos to download: Download All Photos
2023-10-11 14:14:08 INFO     Downloading photos from: Download All Photos
2023-10-11 14:14:08 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-10-11 14:14:08 INFO     Live photo size: original
2023-10-11 14:14:08 INFO     Skip videos: false
2023-10-11 14:14:08 INFO     Convert HEIC to JPEG: false
2023-10-11 14:14:08 INFO     Downloading from: icloud.com.cn
2023-10-11 14:14:08 INFO     Authentication domain: cn
2023-10-11 14:14:08 INFO     Ignore Synology extended attribute directories: Disabled
2023-10-11 14:14:08 INFO     Script launch parameters: --Initialise
Enter iCloud password for xxxxxxx@gmail.com: 
Traceback (most recent call last):
  File "/opt/icloudpd_v1.7.2_china/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud==1.0.0', 'console_scripts', 'icloud')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/cmdline.py", line 191, in main
    api = PyiCloudService(username.strip(), password.strip())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_v1.7.2_china/lib/python3.11/site-packages/pyicloud/base.py", line 233, in __init__
    topdir = path.join(gettempdir(), "pyicloud")
                       ^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 299, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 292, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 223, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
2023-10-11 14:14:32 ERROR    Keyring file does not exist. Please try again.

**Comment by askalee2000** [comment]
sorry ，after update my nas docker version，prompt disappear
