### ISSUE TITLE
Can't sync photos

### ISSUE THREAD

**Issue by 32ethers** [boredazfcuk/docker-icloudpd#412]
after init, sync failed, error log

```
2023-10-12 16:20:19 2023-10-12 16:20:19 INFO     Two-step/two-factor authentication is required
2023-10-12 16:20:20 2023-10-12 16:20:20 ERROR    statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-10-12 16:20:20 2023-10-12 16:20:20 ERROR    Failed to download new files
2023-10-12 16:20:20 2023-10-12 16:20:20 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-10-12 16:20:20 2023-10-12 16:20:20 ERROR    Error debugging info:
2023-10-12 16:20:20 2023-10-12 16:20:20 ERROR    Traceback (most recent call last):
2023-10-12 16:20:20   File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
2023-10-12 16:20:20     sys.exit(main())
2023-10-12 16:20:20              ^^^^^^
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2023-10-12 16:20:20     return self.main(*args, **kwargs)
2023-10-12 16:20:20            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
2023-10-12 16:20:20     rv = self.invoke(ctx)
2023-10-12 16:20:20          ^^^^^^^^^^^^^^^^
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2023-10-12 16:20:20     return ctx.invoke(self.callback, **ctx.params)
2023-10-12 16:20:20            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2023-10-12 16:20:20     return __callback(*args, **kwargs)
2023-10-12 16:20:20            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
2023-10-12 16:20:20     core(
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
2023-10-12 16:20:20     icloud = authenticator(logger, domain)(
2023-10-12 16:20:20              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 48, in authenticate_
2023-10-12 16:20:20     request_2sa(icloud, logger)
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 55, in request_2sa
2023-10-12 16:20:20     devices = icloud.trusted_devices
2023-10-12 16:20:20               ^^^^^^^^^^^^^^^^^^^^^^
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 266, in trusted_devices
2023-10-12 16:20:20     request = self.session.get(
2023-10-12 16:20:20               ^^^^^^^^^^^^^^^^^
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
2023-10-12 16:20:20     return self.request("GET", url, **kwargs)
2023-10-12 16:20:20            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
2023-10-12 16:20:20     self._raise_error(code, reason)
2023-10-12 16:20:20   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
2023-10-12 16:20:20     raise api_error
2023-10-12 16:20:20 pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
2023-10-12 16:20:20 2023-10-12 16:20:20 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-10-12 16:20:20 2023-10-12 16:20:20 INFO     Web cookie expires: 2023-12-11 @ 08:15:30
2023-10-12 16:20:20 2023-10-12 16:20:20 INFO     Multifactor authentication cookie expires: 2024-01-10 @ 08:15:45
2023-10-12 16:20:20 2023-10-12 16:20:20 INFO     Days remaining until expiration: 89
2023-10-12 16:20:20 2023-10-12 16:20:20 INFO     Synchronisation ended at 16:20:20
2023-10-12 16:20:20 2023-10-12 16:20:20 INFO     Total time taken: 00:00:03
2023-10-12 16:20:20 2023-10-12 16:20:20 INFO     Next synchronisation at 16:20:17
```

config: 

```
agentid=
albums_with_dates=false
apple_id=xxxxxx
auth_china=true
authentication_type=MFA
auto_delete=false
bark_device_key=
bark_server=
content_source_url=
convert_heic_to_jpeg=false
debug_logging=false
delete_accompanying=false
delete_after_download=false
delete_notifications=true
dingtalk_token=
directory_permissions=750
discord_id=
discord_token=
download_notifications=true
download_path=/iCloud
file_permissions=640
folder_structure={:%Y/%m/%d}
gotify_app_token=
group=group
group_id=1000
icloud_china=true
iyuu_token=
jpeg_path=
jpeg_quality=90
libraries_with_dates=false
media_id_delete=
media_id_download=
media_id_expiration=
media_id_startup=
media_id_warning=
nextcloud_delete=false
nextcloud_password=
nextcloud_upload=false
nextcloud_url=
nextcloud_username=
notification_days=7
notification_type=
photo_album=
photo_library=
photo_size=original
prowl_api_key=
pushover_sound=
pushover_token=
pushover_user=
recent_only=
set_exif_datetime=false
single_pass=false
skip_album=
skip_check=true
skip_download=false
skip_library=
skip_live_photos=false
skip_videos=false
synchronisation_delay=0
synchronisation_interval=86400
synology_ignore_path=false
telegram_chat_id=
telegram_polling=true
telegram_server=
telegram_silent_file_notifications=
telegram_token=
touser=
trigger_nextlcoudcli_synchronisation=
until_found=
user_id=1000
webhook_https=false
webhook_id=
webhook_path=/api/webhook/
webhook_port=8123
webhook_server=
wecom_id=
wecom_proxy=
wecom_secret=

```

compare to default conf, following is changed

skip_check=true
auth_china=true
icloud_china=true

docker image version is latest

and I create a new container.  and /usr/local/bin/sync-icloud.sh --Initialise is successful

**Comment by 32ethers** [comment]
tried again, and it worked
