### ISSUE TITLE
Login not pulled any longer for keyring. need to login every time

### ISSUE THREAD

**Issue by dotnjet** [boredazfcuk/docker-icloudpd#416]
Since the last Update, my login credentials are not pulled any longer from the keyring. Also when triggering the download from Telegram with "user" it requests a password:
2023-10-20 22:58:20 INFO     Monitoring Telegram for remote wake command: user
2023-10-20 23:01:21 INFO     Sending Telegram remotesync notification
2023-10-20 23:01:21 INFO     Synchronisation starting at 23:01:21
2023-10-20 23:01:21 INFO     Keyring file exists, continuing
2023-10-20 23:01:21 INFO     Check download directory mounted correctly...
2023-10-20 23:01:21 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023-10-20 23:01:22 DEBUG    Authenticating...
iCloud Password:

**Comment by maplexu1994** [comment]
same issue

**Comment by dotnjet** [comment]
here some more error log:
2023-10-25 21:24:13 ERROR    Unknown reason                                      
2023-10-25 21:24:13 ERROR    Failed to download new files                        
2023-10-25 21:24:13 ERROR     - Can you log into icloud.com without receiving pop
-up notifications?                                                               
2023-10-25 21:24:13 ERROR    Error debugging info:                               
2023-10-25 21:24:13 ERROR    Traceback (most recent call last):                  
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", 
line 220, in authenticate                                                        
    req = self.session.post(                                                     
          ^^^^^^^^^^^^^^^^^^                                                     
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", 
line 637, in post                                                                
    return self.request("POST", url, data=data, json=json, **kwargs)             
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^             
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", 
line 105, in request                                                             
    self._raise_error(code, reason)                                              
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", 
line 127, in _raise_error                                                        
    raise api_error                                                              
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason                 
                                                                                 
During handling of the above exception, another exception occurred:              
                                                                                    
Traceback (most recent call last):                                               
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>                  
    sys.exit(main())                                                             
             ^^^^^^                                                              
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 11
57, in __call__                                                                  
    return self.main(*args, **kwargs)                                            
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                            
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 10
78, in main                                                                      
    rv = self.invoke(ctx)                                                        
         ^^^^^^^^^^^^^^^^                                                        
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 14
34, in invoke                                                                    
    return ctx.invoke(self.callback, **ctx.params)                               
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                               
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 78
3, in invoke                                                                     
    return __callback(*args, **kwargs)                                           
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line
 317, in main                                                                    
    core(                                                                        
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line
 744, in core                                                                    
    icloud = authenticator(logger, domain)(                                      
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                      
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication
.py", line 31, in authenticate_                                                  
    icloud = pyicloud_ipd.PyiCloudService(                                       
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", 
line 204, in __init__                                                            
    self.authenticate()                                                          
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", 
line 228, in authenticate                                                        
    raise PyiCloudFailedLoginException(msg, error)                               
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password co
mbination.', PyiCloudAPIResponseError('Unknown reason'))                         
2023-10-25 21:24:13 ERROR    ***** Please report problems here: https://github.co
m/boredazfcuk/docker-icloudpd/issues *****

**Comment by dannycpw** [comment]
Same issue & also "Generating list of files in iCloud" take forever!

Problem resolved by remove & rebuild the current container with removing all contents in /config but keep all downloaded in /iCloud.

**Comment by maplexu1994** [comment]
My issue solved by using "reset" in container manager

**Comment by boredazfcuk** [comment]
> My issue solved by using "reset" in container manager

Thanks for posting the resolution.
