### ISSUE TITLE
Failed to synchronize photos

### ISSUE THREAD

**Issue by Zzzzson** [boredazfcuk/docker-icloudpd#420]
2023-10-31 22:51:38 INFO     Synchronisation starting at 22:51:38
2023-10-31 22:51:39 INFO     Keyring file exists, continuing
2023-10-31 22:51:39 INFO     Check download directory mounted correctly...
2023-10-31 22:51:39 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023-10-31 22:51:39 INFO     Check for new files using password stored in keyring file
2023-10-31 22:51:39 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-10-31 22:51:47 ERROR    Failed check for new files files
2023-10-31 22:51:47 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-10-31 22:51:47 ERROR    Error debugging info:
2023-10-31 22:51:47 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
    core(
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
    icloud = authenticator(logger, domain)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
    icloud = pyicloud_ipd.PyiCloudService(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 234, in authenticate
    raise PyiCloudConnectionException(msg)
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter
2023-10-31 22:51:47 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by Zzzzson** [comment]
auth_china=true
icloud_china=true
