### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by docterry** [boredazfcuk/docker-icloudpd#441]
Today, docker-icloudpd has not been able to connect and sync. I restarted the containers and still get the same error. I can login to icloud.com without any problem. Logs attached below.

Thanks!

```
2023-12-06 14:49:37 INFO     Synchronisation starting at 14:49:37
2023-12-06 14:49:37 INFO     Keyring file exists, continuing
2023-12-06 14:49:37 INFO     Check download directory mounted correctly...
2023-12-06 14:49:37 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-12-06 14:49:37 INFO     Check for new files using password stored in keyring file
2023-12-06 14:49:37 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-12-06 14:49:38 ERROR    Unknown reason
2023-12-06 14:49:38 ERROR    Failed check for new files files
2023-12-06 14:49:38 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2023-12-06 14:49:38 ERROR    Error debugging info:
2023-12-06 14:49:38 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 220, in authenticate
    req = self.session.post(
          ^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main

(
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
    icloud = authenticator(logger, domain)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
    icloud = pyicloud_ipd.PyiCloudService(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 228, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2023-12-06 14:49:38 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
ash: out of range
2023-12-06 14:49:38 INFO     Web cookie expires: 2024-01-23 @ 22:49:55
2023-12-06 14:49:38 INFO     Multifactor authentication cookie expires: 2023-12-24 @ 02:22:47
2023-12-06 14:49:38 INFO     Days remaining until expiration: 17
2023-12-06 14:49:38 INFO     Synchronisation ended at 14:49:38
2023-12-06 14:49:38 INFO     Total time taken: 00:00:01
2023-12-06 14:49:38 INFO     Next synchronisation at 14:49:37
```

**Comment by MatthewLuky** [comment]
Same problem, it was still normal yesterday

**Comment by justindotcloud** [comment]
Same problem as well since this morning. Seems like an authentication issue of some sorts maybe?

**Comment by THX723** [comment]
Same.

**Comment by robflate** [comment]
Same

**Comment by Designator-Ol** [comment]
Same here. 

I tried deleting the session cookie and account data but the error persist.
Seems like it´s a change apple made.

**Comment by gdtms247** [comment]
Same

**Comment by gunner007cd** [comment]
https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/729

**Comment by ifei-ting** [comment]
Same today. I was normal yesterday.

**Comment by jmaliakal** [comment]
getting the same thing here too, somewhat relieved to see there's some underlying issue/change triggering this...

**Comment by gadlou** [comment]
same

**Comment by adoramon** [comment]
same issue, waiting for auther fix it ASAP.

**Comment by edward8e** [comment]
same

**Comment by boredazfcuk** [comment]
Latest version should work for icloud.com users and hopefully icloud.com.cn users too, but this is untested.

**Comment by boredazfcuk** [comment]
Closed as no response in over a month
