### ISSUE TITLE
Service Unavailable (503)

### ISSUE THREAD

**Issue by ms100** [boredazfcuk/docker-icloudpd#455]
From the first time I use it, I will encounter Service Unavailable (503) after running for a few minutes each time. Then the program will run from the beginning again after the interval I set. Sometimes I will encounter Service Unavailable (503) again before I start downloading new photos. I have more than 10,000 photos. How can I set them to download quickly?
![截屏2023-12-19 17 37 22](https://github.com/boredazfcuk/docker-icloudpd/assets/13431945/989bfc13-4a9d-4ed7-aee0-ffcacc72cfb4)

**Comment by S474N** [comment]
Same problem:

```
2023-12-20 18:56:20 INFO     Directory is writable: /config/python_keyring/
2023-12-20 18:56:20 INFO     Starting container initialisation
2023-12-20 18:56:23 ERROR    Unknown reason
Traceback (most recent call last):
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 220, in authenticate
    req = self.session.post(
          ^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
    core(
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
    icloud = authenticator(logger, domain)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
    icloud = pyicloud_ipd.PyiCloudService(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 228, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
grep: /config/xxxxxxxxxxxxx: No such file or directory
ash: out of range
2023-12-20 18:56:23 ERROR    Multifactor authentication information missing from cookie. Authentication has failed
2023-12-20 18:56:23 ERROR     - Was the correct password entered?
2023-12-20 18:56:23 ERROR     - Was the multifactor authentication code mistyped?
2023-12-20 18:56:23 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2023-12-20 18:56:23 INFO     Container initialisation complete

```

**Comment by S474N** [comment]
Newest version works perfectly!

**Comment by boredazfcuk** [comment]
Latest version should fix this issue for icloud.com and icloud.com.cn users.
