### ISSUE TITLE
Authentication required for Account. (421) ?

### ISSUE THREAD

**Issue by jaronsoft** [boredazfcuk/docker-icloudpd#468]
2024-01-01 01:46:55 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.700 started *****

2024-01-01 01:46:55 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****

2024-01-01 01:46:55 INFO     Alpine Linux 3.19.0

2024-01-01 01:46:55 INFO     Python version: 3.11.6

2024-01-01 01:46:55 INFO     Loading configuration from: /config/icloudpd.conf

2024-01-01 01:47:25 INFO     Apple ID: xxxxxx@qq.com

2024-01-01 01:47:25 INFO     Authentication Type: MFA

2024-01-01 01:47:25 INFO     Cookie path: /config/xxxxx

2024-01-01 01:47:25 INFO     Cookie expiry notification period: 7

2024-01-01 01:47:25 INFO     Download destination directory: /iCloud

2024-01-01 01:47:25 INFO     Folder structure: {:%Y/%m}

2024-01-01 01:47:25 INFO     Synchronisation interval: 86400

2024-01-01 01:47:25 INFO     Synchronisation delay (minutes): 0

2024-01-01 01:47:25 INFO     Set EXIF date/time: false

2024-01-01 01:47:25 INFO     Auto delete: false

2024-01-01 01:47:25 INFO     Delete after download: false

2024-01-01 01:47:25 INFO     Photo size: original

2024-01-01 01:47:25 INFO     Single pass mode: false

2024-01-01 01:47:25 INFO     Skip download check: false

2024-01-01 01:47:25 INFO     Skip live photos: false

2024-01-01 01:47:25 INFO     Number of most recently added photos to download: 200

2024-01-01 01:47:25 INFO     Downloading photos from: Download All Photos

2024-01-01 01:47:25 INFO     Stop downloading when prexisiting files count is: 200

2024-01-01 01:47:25 INFO     Live photo size: original

2024-01-01 01:47:25 INFO     Skip videos: false

2024-01-01 01:47:25 INFO     Convert HEIC to JPEG: false

2024-01-01 01:47:25 INFO     Downloading from: icloud.com.cn

2024-01-01 01:47:25 WARNING  You have the icloud_china variable set, but auth_china is false. Are you sure this is correct?

2024-01-01 01:47:25 INFO     Authentication domain: com

2024-01-01 01:47:25 INFO     Ignore Synology extended attribute directories: Disabled

2024-01-01 01:47:25 INFO     Directory is writable: /config/python_keyring/

2024-01-01 01:47:25 INFO     Check download directory mounted correctly...

2024-01-01 01:47:25 INFO     Failsafe file /iCloud/.mounted exists, continuing

2024-01-01 01:47:25 INFO     Directory is writable: /config/python_keyring/

2024-01-01 01:47:25 INFO     Keyring file exists, continuing

2024-01-01 01:47:25 INFO     Sync user: user

2024-01-01 01:47:25 INFO     Synchronisation starting at 01:47:25

2024-01-01 01:47:25 INFO     Keyring file exists, continuing

2024-01-01 01:47:25 INFO     Check download directory mounted correctly...

2024-01-01 01:47:25 INFO     Failsafe file /iCloud/.mounted exists, continuing

2024-01-01 01:47:25 INFO     Check for new files using password stored in keyring file

2024-01-01 01:47:25 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time

2024-01-01 01:47:26 ERROR    Authentication required for Account. (421)

2024-01-01 01:47:29 ERROR    Failed check for new files files

2024-01-01 01:47:29 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?

2024-01-01 01:47:29 ERROR    Error debugging info:

2024-01-01 01:47:29 ERROR    Traceback (most recent call last):

  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>

    sys.exit(main())

             ^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__

    return self.main(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main

    rv = self.invoke(ctx)

         ^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke

    return ctx.invoke(self.callback, **ctx.params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke

    return __callback(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 328, in main


(

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 760, in core

    icloud = authenticator(logger, domain)(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_

    icloud = pyicloud_ipd.PyiCloudService(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 305, in __init__

    self.authenticate()

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 367, in authenticate

    self._authenticate_with_token()

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 399, in _authenticate_with_token

    raise PyiCloudConnectionException(msg)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^

NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?

**Comment by boredazfcuk** [comment]
Latest version should hopefully now work for icloud.com and icloud.com.cn.

**Comment by jaronsoft** [comment]
Using version 1.0.705, the problem still persists.

`
2024-01-05 22:30:28 ERROR    Traceback (most recent call last):

  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>

    sys.exit(main())

             ^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__

    return self.main(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main

    rv = self.invoke(ctx)

         ^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke

    return ctx.invoke(self.callback, **ctx.params)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke

    return __callback(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 328, in main


(

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 760, in core

    icloud = authenticator(logger, domain)(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_

    icloud = pyicloud_ipd.PyiCloudService(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 305, in __init__

    self.authenticate()

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 367, in authenticate

    self._authenticate_with_token()

  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 399, in _authenticate_with_token

    raise PyiCloudConnectionException(msg)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^

NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?

2024-01-05 22:30:28 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****`

**Comment by jaronsoft** [comment]
The translation into English is: "I have a total of five accounts, all using the same version boredazfcuk/icloudpd:stable. One is in the US region, and four are in the China region, among which three of the China region accounts have issues."

**Comment by Bernd-Walter** [comment]
I'm seeing the same error with one of our accounts. Region is germany in this case.

**Comment by boredazfcuk** [comment]
Authentication required just means it needs reinitialising, no?

I had this when the fix was first applied. IIRC, I just removed the keying and then reinitialised the container.

I think my other half's container is doing the same. Has been for a few days. I'll check and test when I get home.

**Comment by Bernd-Walter** [comment]
yeah, I thought so, as well, and re-initialized. Unfortunately without any
change.

boredazfcuk ***@***.***> schrieb am Fr. 12. Jan. 2024 um
18:47:

**Comment by boredazfcuk** [comment]
Did you remove the keying first?

**Comment by boredazfcuk** [comment]
I just ran `sync-icloud.sh --init` and it was all OK:

```
2024-01-12 18:50:15 DEBUG    Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2024-01-12 18:50:15 INFO     Starting container initialisation
2024-01-12 18:50:15 DEBUG    2024-01-12 18:50:15 INFO     Correct owner on config directory, if required
2024-01-12 18:50:15 DEBUG    2024-01-12 18:50:15 INFO     Correct group on config directory, if required
2024-01-12 18:50:15 DEBUG    Generate Web cookie using password stored in keyring file
2024-01-12 18:50:16 ERROR    Authentication required for Account. (421)
Please enter two-factor authentication code: 123456
2024-01-12 18:50:45 WARNING  Failed to parse response with JSON mimetype
2024-01-12 18:50:51 DEBUG    Web cookie generated. Sync should now be successful
2024-01-12 18:50:51 INFO     Container initialisation complete
```

Restarted the container and it downloaded everything fine.

Just checked the logs and my error was just:
```
2024-01-09 23:16:23 DEBUG    Authenticating...
2024-01-09 23:16:23 INFO     Two-step/two-factor authentication is required (2fa)
Please enter two-factor authentication code: 2024-01-09 23:16:23 ERROR    Failed to download new files
```

**Comment by jaronsoft** [comment]
I used the latest version of boredazfcuk/icloudpd:1.0.714, and tried deleting all files under /config, then reinitialized with sync-icloud.sh --init, but the problem persists, IOS 17.3 (21D5044a).

`
/ # sync-icloud.sh --init

2024-01-13 14:20:09 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.714 started *****
2024-01-13 14:20:09 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-01-13 14:20:09 INFO     Alpine Linux 3.19.0
2024-01-13 14:20:09 INFO     Python version: 3.11.6
2024-01-13 14:20:09 INFO     Loading configuration from: /config/icloudpd.conf
2024-01-13 14:20:53 INFO     Apple ID: xxx@qq.com
2024-01-13 14:20:53 INFO     Authentication Type: MFA
2024-01-13 14:20:53 INFO     Cookie path: /config/xxxxqqcom
2024-01-13 14:20:53 INFO     Cookie expiry notification period: 7
2024-01-13 14:20:53 INFO     Download destination directory: /iCloud
2024-01-13 14:20:53 INFO     Folder structure: {:%Y/%m}
2024-01-13 14:20:53 INFO     Synchronisation interval: 86400
2024-01-13 14:20:53 INFO     Synchronisation delay (minutes): 0
2024-01-13 14:20:53 INFO     Set EXIF date/time: false
2024-01-13 14:20:53 INFO     Auto delete: false
2024-01-13 14:20:53 INFO     Delete after download: false
2024-01-13 14:20:53 INFO     Photo size: original
2024-01-13 14:20:53 INFO     Single pass mode: false
2024-01-13 14:20:53 INFO     Skip download check: false
2024-01-13 14:20:53 INFO     Skip live photos: false
2024-01-13 14:20:53 INFO     Number of most recently added photos to download: 200
2024-01-13 14:20:53 INFO     Downloading photos from: Download All Photos
2024-01-13 14:20:53 INFO     Stop downloading when prexisiting files count is: 200
2024-01-13 14:20:53 INFO     Live photo size: original
2024-01-13 14:20:53 INFO     Skip videos: false
2024-01-13 14:20:53 INFO     Convert HEIC to JPEG: false
2024-01-13 14:20:53 INFO     Downloading from: icloud.com.cn
2024-01-13 14:20:53 WARNING  You have the icloud_china variable set, but auth_china is false. Are you sure this is correct?
2024-01-13 14:20:53 INFO     Authentication domain: com
2024-01-13 14:20:53 INFO     Ignore Synology extended attribute directories: Disabled
2024-01-13 14:20:56 INFO     Script launch parameters: --init
Enter iCloud password for xxxx@qq.com: 
Traceback (most recent call last):
  File "starters/icloud.py", line 5, in <module>
  File "pyicloud_ipd/cmdline.py", line 200, in main
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 367, in authenticate
  File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?
[18138] Failed to execute script 'icloud' due to unhandled exception!
2024-01-13 14:21:13 ERROR    Keyring file does not exist. Please try again.
`

**Comment by rambolee** [comment]
> I used the latest version of boredazfcuk/icloudpd:1.0.714, and tried deleting all files under /config, then reinitialized with sync-icloud.sh --init, but the problem persists, IOS 17.3 (21D5044a).
> 
> ` / # sync-icloud.sh --init
> 
> 2024-01-13 14:20:09 INFO ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.714 started ***** 2024-01-13 14:20:09 INFO ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd ***** 2024-01-13 14:20:09 INFO Alpine Linux 3.19.0 2024-01-13 14:20:09 INFO Python version: 3.11.6 2024-01-13 14:20:09 INFO Loading configuration from: /config/icloudpd.conf 2024-01-13 14:20:53 INFO Apple ID: [xxx@qq.com](mailto:xxx@qq.com) 2024-01-13 14:20:53 INFO Authentication Type: MFA 2024-01-13 14:20:53 INFO Cookie path: /config/xxxxqqcom 2024-01-13 14:20:53 INFO Cookie expiry notification period: 7 2024-01-13 14:20:53 INFO Download destination directory: /iCloud 2024-01-13 14:20:53 INFO Folder structure: {:%Y/%m} 2024-01-13 14:20:53 INFO Synchronisation interval: 86400 2024-01-13 14:20:53 INFO Synchronisation delay (minutes): 0 2024-01-13 14:20:53 INFO Set EXIF date/time: false 2024-01-13 14:20:53 INFO Auto delete: false 2024-01-13 14:20:53 INFO Delete after download: false 2024-01-13 14:20:53 INFO Photo size: original 2024-01-13 14:20:53 INFO Single pass mode: false 2024-01-13 14:20:53 INFO Skip download check: false 2024-01-13 14:20:53 INFO Skip live photos: false 2024-01-13 14:20:53 INFO Number of most recently added photos to download: 200 2024-01-13 14:20:53 INFO Downloading photos from: Download All Photos 2024-01-13 14:20:53 INFO Stop downloading when prexisiting files count is: 200 2024-01-13 14:20:53 INFO Live photo size: original 2024-01-13 14:20:53 INFO Skip videos: false 2024-01-13 14:20:53 INFO Convert HEIC to JPEG: false 2024-01-13 14:20:53 INFO Downloading from: icloud.com.cn 2024-01-13 14:20:53 WARNING You have the icloud_china variable set, but auth_china is false. Are you sure this is correct? 2024-01-13 14:20:53 INFO Authentication domain: com 2024-01-13 14:20:53 INFO Ignore Synology extended attribute directories: Disabled 2024-01-13 14:20:56 INFO Script launch parameters: --init Enter iCloud password for [xxxx@qq.com](mailto:xxxx@qq.com): Traceback (most recent call last): File "starters/icloud.py", line 5, in File "pyicloud_ipd/cmdline.py", line 200, in main File "pyicloud_ipd/base.py", line 305, in **init** File "pyicloud_ipd/base.py", line 367, in authenticate File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'? [18138] Failed to execute script 'icloud' due to unhandled exception! 2024-01-13 14:21:13 ERROR Keyring file does not exist. Please try again. `

I have same questions, with latest version of boredazfcuk/icloudpd:1.0.714

**Comment by boredazfcuk** [comment]
I notice both of you have set the container to download from the Chinese iCloud, but are authenticating against the global servers.

What happens when you authenticate against Chinese iCloud servers?

**Comment by Bernd-Walter** [comment]
> Did you remove the keying first?

no, didn't do that. I'm giving it a try, right now.

**Comment by Bernd-Walter** [comment]
Fixed it, is now syncing. But only pulls arround 250 items

**Comment by jaronsoft** [comment]
After entering the correct password, a verification code pops up on the phone, and before I can fill it in, the following error occurs
`
Traceback (most recent call last):
File "starters/icloud.py", line 5, in
File "pyicloud_ipd/cmdline.py", line 200, in main
File "pyicloud_ipd/base.py", line 305, in init
File "pyicloud_ipd/base.py", line 367, in authenticate
File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?
[18138] Failed to execute script 'icloud' due to unhandled exception!
2024-01-13 14:21:13 ERROR Keyring file does not exist. Please try again.
`
My other account, which is also a China region account, works normally with the boredazfcuk/icloudpd:stable version. The version of my phone is 17.2.1. I tried using the account with the above error message with the boredazfcuk/icloudpd:stable version, and the error occurred just like the first message I described.

thx..

**Comment by JafeChang** [comment]
I got the same failure.
<img width="909" alt="image" src="https://github.com/boredazfcuk/docker-icloudpd/assets/7353792/abf603c5-ad60-47f5-83c0-dd749f3d6013">

**Comment by iSwfe** [comment]
> After entering the correct password, a verification code pops up on the phone, and before I can fill it in, the following error occurs `Traceback (most recent call last): File "starters/icloud.py", line 5, in File "pyicloud_ipd/cmdline.py", line 200, in main File "pyicloud_ipd/base.py", line 305, in init File "pyicloud_ipd/base.py", line 367, in authenticate File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'? [18138] Failed to execute script 'icloud' due to unhandled exception! 2024-01-13 14:21:13 ERROR Keyring file does not exist. Please try again.` My other account, which is also a China region account, works normally with the boredazfcuk/icloudpd:stable version. The version of my phone is 17.2.1. I tried using the account with the above error message with the boredazfcuk/icloudpd:stable version, and the error occurred just like the first message I described.
> 
> thx..
> 
> ![WX20240113-214220](https://private-user-images.githubusercontent.com/32379785/296498547-49e0174a-c082-415c-bdb3-05c894c8d1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODkxNDYsIm5iZiI6MTcwNTI4ODg0NiwicGF0aCI6Ii8zMjM3OTc4NS8yOTY0OTg1NDctNDllMDE3NGEtYzA4Mi00MTVjLWJkYjMtMDVjODk0YzhkMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAzMjA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZDJmOGU4YjdmMTJkZmU3YjM3NmE5MDZjNTRiNTMyMWI1YTQxYzhkY2I0YzUyNTE0YmUyYmY1MzA1YzlhMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NQqGAD_qEX-iinF8kwdIG6wSxvGft2lCBAzfu25Ydp0)

Me too! ! I encountered the same problem. It should be that there are some problems with the python code (the relevant exception module PyiCloudConnectionException cannot be found), resulting in the actual exception information not being printed.

This is the log of my initialization command execution
```
/ # sync-icloud.sh --init

2024-01-15 11:35:00 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.714 started *****
2024-01-15 11:35:00 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-01-15 11:35:00 INFO     Alpine Linux 3.19.0
2024-01-15 11:35:00 INFO     Python version: 3.11.6
2024-01-15 11:35:00 INFO     Loading configuration from: /config/icloudpd.conf
2024-01-15 11:35:00 DEBUG    Running user id: 0
2024-01-15 11:35:00 DEBUG    Running group id: 0
2024-01-15 11:35:00 DEBUG    Local user: xxxxx:1026
2024-01-15 11:35:00 DEBUG    Local group: users:100
2024-01-15 11:35:00 DEBUG    Force GID: true
2024-01-15 11:35:00 DEBUG    LAN IP Address: 172.18.0.2
2024-01-15 11:35:00 DEBUG    Default gateway: 172.18.0.1
2024-01-15 11:35:00 DEBUG    DNS server: 127.0.0.11
2024-01-15 11:35:00 DEBUG    IP address for icloud.com.cn: 103.115.248.1
2024-01-15 11:35:24 DEBUG    Route check to icloud.com.cn successful
2024-01-15 11:35:24 DEBUG    Apple ID: (hidden)
2024-01-15 11:35:24 INFO     Authentication Type: MFA
2024-01-15 11:35:24 DEBUG    Cookie path: /config/(hidden)
2024-01-15 11:35:24 INFO     Cookie expiry notification period: 7
2024-01-15 11:35:24 INFO     Download destination directory: /iCloud
2024-01-15 11:35:24 INFO     Folder structure: {:%Y/%m/%d}
2024-01-15 11:35:24 DEBUG    Directory permissions: 750
2024-01-15 11:35:24 DEBUG    File permissions: 640
2024-01-15 11:35:24 INFO     Synchronisation interval: 86400
2024-01-15 11:35:24 INFO     Synchronisation delay (minutes): 0
2024-01-15 11:35:24 INFO     Set EXIF date/time: false
2024-01-15 11:35:24 INFO     Auto delete: false
2024-01-15 11:35:24 INFO     Delete after download: false
2024-01-15 11:35:24 INFO     Photo size: original
2024-01-15 11:35:24 INFO     Single pass mode: false
2024-01-15 11:35:24 INFO     Skip download check: true
2024-01-15 11:35:24 INFO     Skip live photos: false
2024-01-15 11:35:24 INFO     Number of most recently added photos to download: Download All Photos
2024-01-15 11:35:24 INFO     Downloading photos from: Download All Photos
2024-01-15 11:35:24 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-01-15 11:35:24 INFO     Live photo size: original
2024-01-15 11:35:24 INFO     Skip videos: false
2024-01-15 11:35:24 INFO     Convert HEIC to JPEG: false
2024-01-15 11:35:24 INFO     Downloading from: icloud.com.cn
2024-01-15 11:35:24 INFO     Authentication domain: cn
2024-01-15 11:35:24 DEBUG    Nextcloud synchronisation trigger: Disabled
2024-01-15 11:35:24 DEBUG    Nextcloud upload: Disabled
2024-01-15 11:35:24 INFO     Ignore Synology extended attribute directories: Enabled
2024-01-15 11:35:26 DEBUG    Activated Python virtual environment for icloudpd: 1.17.3
2024-01-15 11:35:26 INFO     Script launch parameters: --init
2024-01-15 11:35:26 DEBUG    Group, users:100, already created
2024-01-15 11:35:26 DEBUG    User, xxxxx:1026, already created
2024-01-15 11:35:26 DEBUG    Set owner and group on icloudpd temp directory
2024-01-15 11:35:26 DEBUG    Set owner and group on config directory
2024-01-15 11:35:26 DEBUG    Configure password
2024-01-15 11:35:26 DEBUG    Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for yyyyy: 
Traceback (most recent call last):
  File "starters/icloud.py", line 5, in <module>
  File "pyicloud_ipd/cmdline.py", line 200, in main
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 367, in authenticate
  File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?
[594] Failed to execute script 'icloud' due to unhandled exception!
2024-01-15 11:37:04 ERROR    Keyring file does not exist. Please try again.
```

This is my .env environment parameter to run docker-compose
```
user=xxxxx
group=users
user_id=1026
group_id=100
force_gid=true
icloudpd_config=/volume1/docker/icloudpd
photos_icloud=/volume1/homes/${user}/Photos/iCloud
TZ=Asia/Shanghai
download_path=/iCloud
apple_id=yyyyy
auth_china=true
icloud_china=true
debug_logging=true
skip_check=true
synology_photos_app_fix=true
synology_ignore_path=true
```

**Comment by msn1983aa** [comment]
same error info with the latest docker image.

**Comment by vongoethe** [comment]
Same error in TrueNAS Scale App deployment.
