### ISSUE TITLE
Python Issue?

### ISSUE THREAD

**Issue by Jholmgren5** [boredazfcuk/docker-icloudpd#469]
Just updated Synology DSM to latest, along with all packages and icloudpd docker container.  Each time I go to terminal and try to use this, I get the error below.  I cannot figure out why.  

2024-01-01 03:52:52 DEBUG    Authenticating...                                   
iCloud Password:                                                                 
Traceback (most recent call last):                                               
  File "pyicloud_ipd/base.py", line 220, in authenticate                         
  File "requests/sessions.py", line 635, in post                                 
  File "pyicloud_ipd/base.py", line 105, in request                              
  File "pyicloud_ipd/base.py", line 127, in _raise_error                         
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason                 
                                                                                 
During handling of the above exception, another exception occurred:              
                                                                                 
Traceback (most recent call last):                                               
  File "icloudpd.py", line 5, in <module>                                        
  File "click/core.py", line 1130, in __call__                                   
  File "click/core.py", line 1055, in main                                       
  File "click/core.py", line 1404, in invoke                                     
  File "click/core.py", line 760, in invoke                                      
  File "icloudpd/base.py", line 275, in main                                     
  File "icloudpd/authentication.py", line 31, in authenticate_                   
  File "pyicloud_ipd/base.py", line 204, in __init__                             
  File "pyicloud_ipd/base.py", line 228, in authenticate                         
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password co
mbination.', PyiCloudAPIResponseError('Unknown reason'))                         
[7] Failed to execute script 'icloudpd' due to unhandled exception!              
/app #

**Comment by boredazfcuk** [comment]
The /app directory does not exist in my container. The sync-icloud.sh script and its various command line parameters are used to run the various functions.

I'm guessing you're using the container from the [icloud-photos-downloader](https://github.com/icloud-photos-downloader/icloud_photos_downloader) maintainers. This only provides the core functionality in my [container](https://hub.docker.com/repository/docker/boredazfcuk/icloudpd/general).

**Comment by jinnxu75** [comment]
same problem, Have you solved it?

**Comment by KayhanKaynar** [comment]
same problem..
