### ISSUE TITLE
Connection aborted - RemoteDisconnected

### ISSUE THREAD

**Issue by Boerni-tech** [boredazfcuk/docker-icloudpd#486]
Hi,
I've got a (kind of) working instance but frequently see this, after downloading some 150 Files. Seems like Apple drops my connection. It left the container of for > than 25hours, without any change to his behaviour:

`2024-01-12 17:33:19 ERROR    Failed to download new files
2024-01-12 17:33:19 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-01-12 17:33:19 ERROR    Error debugging info:
2024-01-12 17:33:19 ERROR    Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 714, in urlopen
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3/connectionpool.py", line 461, in _make_request
  File "http/client.py", line 1419, in getresponse
  File "http/client.py", line 331, in begin
  File "http/client.py", line 300, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 798, in urlopen
  File "urllib3/util/retry.py", line 550, in increment
  File "urllib3/packages/six.py", line 769, in reraise
  File "urllib3/connectionpool.py", line 714, in urlopen
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3/connectionpool.py", line 461, in _make_request
  File "http/client.py", line 1419, in getresponse
  File "http/client.py", line 331, in begin
  File "http/client.py", line 300, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 908, in core
  File "pyicloud_ipd/services/photos.py", line 357, in photos
  File "pyicloud_ipd/services/photos.py", line 337, in photos_request
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 77, in request
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[293] Failed to execute script 'icloudpd' due to unhandled exception!
2024-01-12 17:33:19 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024-01-12 17:33:19 INFO     Web cookie expires: 2024-03-09 @ 13:09:17
2024-01-12 17:33:19 INFO     Multifactor authentication cookie expires: 2024-04-08 @ 13:09:24
2024-01-12 17:33:19 INFO     Days remaining until expiration: 86
2024-01-12 17:33:19 INFO     Synchronisation ended at 17:33:19
2024-01-12 17:33:19 INFO     Total time taken: 00:22:40
2024-01-12 17:33:19 INFO     Next synchronisation at 17:10:39
`

**Comment by boredazfcuk** [comment]
Are network connections being proxied? Seems like a networking/firewall/routing issue.

**Comment by Boerni-tech** [comment]
No, plain network. Just the machine, switch and ubiquiti UXG-Lite. Nothing fancy in there.

**Comment by boredazfcuk** [comment]
I'd check networking of the host machine... network driver, GeoIP implementation, DNS server, IPv6 and the likes could be affecting it.
