### ISSUE TITLE
 'PyiCloudConnectionException' is not defined.

### ISSUE THREAD

**Issue by yizhitangtongxue** [boredazfcuk/docker-icloudpd#489]
执行`sync-cloud.sh --Initialise`后报错，之前还稳定跑了几个月
```bash
  File "pyicloud_ipd/cmdline.py", line 200, in main                              
Traceback (most recent call last):                                               
  File "starters/icloud.py", line 5, in <module>                                 
  File "pyicloud_ipd/base.py", line 305, in __init__                             
  File "pyicloud_ipd/base.py", line 367, in authenticate                         
  File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token             
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiC
loudFailedLoginException'?                                                       
[513] Failed to execute script 'icloud' due to unhandled exception!              
2024-01-16 00:20:46 ERROR    Keyring file does not exist. Please try again.  
```

**Comment by Nonac** [comment]
Same issue

**Comment by vongoethe** [comment]
Same here

**Comment by mikexfreeze** [comment]
> Use boredazfcuk/icloudpd:stable vision,don't use latest vision.

This project got this problem LOL. https://github.com/boredazfcuk/docker-icloudpd/issues/470

**Comment by vanyanyan** [comment]
Same here

**Comment by rambolee** [comment]
在initializing的时候还是报错。目前已经更新到最新版本的docker 。

**Comment by kingcarn** [comment]
same issue

**Comment by kingcarn** [comment]
> same issue
same issue with stable version
Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloud", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = PyiCloudService(
          ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 305, in __init__
    self.authenticate()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 367, in authenticate
    self._authenticate_with_token()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 399, in _authenticate_with_token
    raise PyiCloudConnectionException(msg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?
2024-02-25 15:18:57 ERROR    Keyring file does not exist. Please try again.

**Comment by Hao813** [comment]
> > Use boredazfcuk/icloudpd:stable vision,don't use latest vision.
> 
> This project got this problem LOL. #470

same issue, do you solve this?

**Comment by boredazfcuk** [comment]
I believe this was resolved upstream in latest release. I've now rolled that into the latest container.

**Comment by boredazfcuk** [comment]
Closed as stale
