### ISSUE TITLE
Failure to authenticate

### ISSUE THREAD

**Issue by syl779** [boredazfcuk/docker-icloudpd#513]
Had a similar issue several months ago that got fixed. Not authenticating. Trying to reinitialise also fails. Multiple accounts.

2024-02-22 22:46:43 INFO     Synchronisation starting at 22:46:43
2024-02-22 22:46:43 INFO     Keyring file exists, continuing
2024-02-22 22:46:43 INFO     Check download directory mounted correctly...
2024-02-22 22:46:43 INFO     Failsafe file /icloud/.mounted exists, continuing
2024-02-22 22:46:45 DEBUG    Authenticating...
2024-02-22 22:46:58 ERROR    Authentication required for Account. (421)
2024-02-22 22:47:22 ERROR    Authentication required for Account. (500)
2024-02-22 22:47:22 ERROR    Failed to download new files
2024-02-22 22:47:22 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-02-22 22:47:22 ERROR    Error debugging info:
2024-02-22 22:47:22 ERROR    Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 387, in _authenticate_with_token
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 132, in request
  File "pyicloud_ipd/base.py", line 134, in request
  File "pyicloud_ipd/base.py", line 207, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (500)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 760, in core
  File "icloudpd/authentication.py", line 31, in authenticate_
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 367, in authenticate
  File "pyicloud_ipd/base.py", line 393, in _authenticate_with_token
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Authentication required for Account. (500)'))
[280] Failed to execute script 'icloudpd' due to unhandled exception!
2024-02-22 22:47:22 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024-02-22 22:47:22 INFO     Web cookie expires: 2024-03-27 @ 16:42:02
2024-02-22 22:47:22 INFO     Multifactor authentication cookie expires: 2024-04-26 @ 16:42:12
2024-02-22 22:47:22 INFO     Days remaining until expiration: 63
2024-02-22 22:47:22 INFO     Synchronisation ended at 22:47:22
2024-02-22 22:47:22 INFO     Total time taken: 00:00:39
2024-02-22 22:47:22 INFO     Next synchronisation at 22:46:43

**Comment by syl779** [comment]
Seems to have started working again. Maybe it was a problem at the other end.
