### ISSUE TITLE
Premission Error with keyring_pass.cfg?

### ISSUE THREAD

**Issue by X-Track** [boredazfcuk/docker-icloudpd#523]
```
/ # sync-icloud.sh --Initialise

2024-03-15 17:55:57 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.718 started *****
2024-03-15 17:55:57 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-03-15 17:55:57 INFO     Alpine Linux 3.19.0
2024-03-15 17:55:57 INFO     Python version: 3.11.6
chmod: changing permissions of '/config/icloudpd.conf': Operation not permitted
2024-03-15 17:55:57 INFO     Loading configuration from: /config/icloudpd.conf
2024-03-15 17:55:57 INFO     Apple ID: xxxxxx@xxxxxxx
2024-03-15 17:55:57 INFO     Authentication Type: MFA
2024-03-15 17:55:57 INFO     Cookie path: /config/xxxxxxxxxxxxx
2024-03-15 17:55:57 INFO     Cookie expiry notification period: 7
2024-03-15 17:55:57 INFO     Download destination directory: /downloads
2024-03-15 17:55:57 INFO     Folder structure: {:%Y/%m/%d}
2024-03-15 17:55:57 INFO     Synchronisation interval: 86400
2024-03-15 17:55:57 INFO     Synchronisation delay (minutes): 0
2024-03-15 17:55:57 INFO     Set EXIF date/time: false
2024-03-15 17:55:57 INFO     Auto delete: false
2024-03-15 17:55:57 INFO     Delete after download: false
2024-03-15 17:55:57 INFO     Photo size: original
2024-03-15 17:55:57 INFO     Single pass mode: false
2024-03-15 17:55:57 INFO     Skip download check: false
2024-03-15 17:55:57 INFO     Skip live photos: false
2024-03-15 17:55:57 INFO     Number of most recently added photos to download: Download All Photos
2024-03-15 17:55:57 INFO     Downloading photos from: Download All Photos
2024-03-15 17:55:57 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-03-15 17:55:57 INFO     Live photo size: original
2024-03-15 17:55:57 INFO     Skip videos: false
2024-03-15 17:55:57 INFO     Convert HEIC to JPEG: false
2024-03-15 17:55:57 INFO     Downloading from: icloud.com
2024-03-15 17:55:57 INFO     Authentication domain: com
2024-03-15 17:55:57 INFO     Ignore Synology extended attribute directories: Disabled
2024-03-15 17:55:58 INFO     Script launch parameters: --Initialise
2024-03-15 17:55:58 INFO     Directory is writable: /config/python_keyring/
Enter iCloud password for xxxxxx@xxxxxxx: 
Save password in keyring? [y/N]: y
Traceback (most recent call last):
  File "starters/icloud.py", line 5, in <module>
  File "pyicloud_ipd/cmdline.py", line 210, in main
  File "pyicloud_ipd/utils.py", line 52, in store_password_in_keyring
  File "keyring/core.py", line 60, in set_password
  File "keyrings/alt/file_base.py", line 129, in set_password
  File "keyrings/alt/file_base.py", line 137, in _write_config_value
  File "keyrings/alt/file_base.py", line 169, in _ensure_file_path
PermissionError: [Errno 1] Operation not permitted: '/config/python_keyring/keyring_pass.cfg'
[833] Failed to execute script 'icloud' due to unhandled exception!
2024-03-15 17:56:10 INFO     Starting container initialisation
iCloud Password: 
2024-03-15 17:56:20 ERROR    Authentication required for Account. (421)
2024-03-15 17:56:25 INFO     Multifactor authentication cookie generated. Sync should now be successful
2024-03-15 17:56:25 INFO     Container initialisation complete
```

I got the app downloaded within truenas scale. permissions are set to apps with id 568.

how can i fix this?

**Comment by boredazfcuk** [comment]
```
chmod: changing permissions of '/config/icloudpd.conf': Operation not permitted
```

This command is run with the root account inside the container but still doesn't have permission to change files. I think you'll need to set the container to run in privileged mode.

**Comment by boredazfcuk** [comment]
Closed as stale
