### ISSUE TITLE
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))

### ISSUE THREAD

**Issue by shilongcheng10** [boredazfcuk/docker-icloudpd#527]
hoto_downloader v1.0.684 started *****
2024-03-20 18:21:17 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-03-20 18:21:17 INFO     Alpine Linux 3.18.3
2024-03-20 18:21:17 INFO     Python version: 3.11.5
2024-03-20 18:21:17 INFO     Loading configuration from: /config/icloudpd.conf
2024-03-20 18:21:44 INFO     Apple ID: 1344177736@qq.com
2024-03-20 18:21:44 INFO     Authentication Type: MFA
2024-03-20 18:21:44 INFO     Cookie path: /config/1344177736qqcom
2024-03-20 18:21:44 INFO     Cookie expiry notification period: 7
2024-03-20 18:21:44 INFO     Download destination directory: /icloud/yusei
2024-03-20 18:21:44 INFO     Folder structure: {:%Y/%m/%d}
2024-03-20 18:21:44 INFO     Synchronisation interval: 86400
2024-03-20 18:21:44 INFO     Synchronisation delay (minutes): 0
2024-03-20 18:21:44 INFO     Set EXIF date/time: false
2024-03-20 18:21:44 INFO     Auto delete: false
2024-03-20 18:21:44 INFO     Delete after download: false
2024-03-20 18:21:44 INFO     Photo size: original
2024-03-20 18:21:44 INFO     Single pass mode: false
2024-03-20 18:21:44 INFO     Skip download check: false
2024-03-20 18:21:44 INFO     Skip live photos: false
2024-03-20 18:21:44 INFO     Number of most recently added photos to download: Download All Photos
2024-03-20 18:21:44 INFO     Downloading photos from: Download All Photos
2024-03-20 18:21:44 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-03-20 18:21:44 INFO     Live photo size: original
2024-03-20 18:21:44 INFO     Skip videos: false
2024-03-20 18:21:44 INFO     Convert HEIC to JPEG: false
2024-03-20 18:21:44 INFO     Downloading from: icloud.com.cn
2024-03-20 18:21:44 INFO     Authentication domain: cn
2024-03-20 18:21:44 INFO     Ignore Synology extended attribute directories: Disabled
2024-03-20 18:21:44 INFO     Directory is writable: /config/python_keyring/
2024-03-20 18:21:44 INFO     Check download directory mounted correctly...
2024-03-20 18:21:44 INFO     Failsafe file /icloud/yusei/.mounted exists, continuing
2024-03-20 18:21:44 INFO     Directory is writable: /config/python_keyring/
2024-03-20 18:21:44 INFO     Keyring file exists, continuing
2024-03-20 18:21:44 INFO     Sync user: user
2024-03-20 18:21:44 INFO     Synchronisation starting at 18:21:44
2024-03-20 18:21:44 INFO     Keyring file exists, continuing
2024-03-20 18:21:44 INFO     Check download directory mounted correctly...
2024-03-20 18:21:44 INFO     Failsafe file /icloud/yusei/.mounted exists, continuing
2024-03-20 18:21:44 INFO     Check for new files using password stored in keyring file
2024-03-20 18:21:44 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2024-03-20 18:21:45 ERROR    Unknown reason
2024-03-20 18:21:45 ERROR    Failed check for new files files
2024-03-20 18:21:46 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2024-03-20 18:21:46 ERROR    Error debugging info:
2024-03-20 18:21:46 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 220, in authenticate
    req = self.session.post(
          ^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
    core(
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
    icloud = authenticator(logger, domain)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
    icloud = pyicloud_ipd.PyiCloudService(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 228, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2024-03-20 18:21:46 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
ash: out of range
2024-03-20 18:21:46 INFO     Web cookie expires: 2024-05-19 @ 09:47:43
2024-03-20 18:21:46 INFO     Multifactor authentication cookie expires: 2024-06-18 @ 09:47:41
2024-03-20 18:21:46 INFO     Days remaining until expiration: 89
2024-03-20 18:21:46 INFO     Synchronisation ended at 18:21:46
2024-03-20 18:21:46 INFO     Total time taken: 00:00:02
2024-03-20 18:21:46 INFO     Next synchronisation at 18:21:44

* it remind invalid mail/password, but my credientials is correct.

**Comment by JiangXL** [comment]
Here was same issue for me at icloud_photo_downloader v1.0.626. But latest one does work.

**Comment by boredazfcuk** [comment]
I think there was an update in the upstream application which addressed a password issue for users in China. Please update to latest version of the container and try again.

**Comment by boredazfcuk** [comment]
Closing as no response
