### ISSUE TITLE
An error is reported using reauth.sh

### ISSUE THREAD

**Issue by Arnold4869** [boredazfcuk/docker-icloudpd#536]
docker exec -it icloudpd reauth.sh
2024-03-31 11:32:02 DEBUG    Authenticating...
2024-03-31 11:32:05 ERROR    Authentication required for Account. (421)
Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 760, in core
  File "icloudpd/authentication.py", line 31, in authenticate_
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 367, in authenticate
  File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?
[1420] Failed to execute script 'icloudpd' due to unhandled exception!

**Comment by boredazfcuk** [comment]
Are you based in China? It's probably defaulting to global authentication servers, instead of Chinese ones.

**Comment by Arnold4869** [comment]
> Are you based in China? It's probably defaulting to global authentication servers, instead of Chinese ones.

yeah, i am a Chinese.It means i need to change the reauth.sh to make it OK？

**Comment by boredazfcuk** [comment]
I've updated the container so that reauth.sh should now correctly set the authorisation domain.

**Comment by Arnold4869** [comment]
> I've updated the container so that reauth.sh should now correctly set the authorisation domain.

thanks. It is great.
