### ISSUE TITLE
Errors on initialise ?  

### ISSUE THREAD

**Issue by vw-kombi** [boredazfcuk/docker-icloudpd#545]
Got the usual alert to re-auth.
reauth.sh did not seem to do the normal stuff.
Ran the initialise, and got some errors - 

/ # sync-icloud.sh --Initialise

2024-04-14 08:34:02 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.733 started *****
2024-04-14 08:34:02 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-04-14 08:34:02 INFO     Alpine Linux 3.19.1
2024-04-14 08:34:02 INFO     Python version: 3.11.8
2024-04-14 08:34:02 INFO     Loading configuration from: /config/icloudpd.conf
2024-04-14 08:34:03 INFO     Apple ID: xxxxxx
2024-04-14 08:34:03 INFO     Authentication Type: MFA
2024-04-14 08:34:03 INFO     Cookie path: /config/xxxxxx
2024-04-14 08:34:03 INFO     Cookie expiry notification period: 7
2024-04-14 08:34:03 INFO     Download destination directory: /home/user/iCloud
2024-04-14 08:34:03 INFO     Folder structure: {:%Y/%m}
2024-04-14 08:34:03 INFO     Synchronisation interval: 172800
2024-04-14 08:34:03 INFO     Synchronisation delay (minutes): 0
2024-04-14 08:34:03 INFO     Set EXIF date/time: false
2024-04-14 08:34:03 INFO     Auto delete: true
2024-04-14 08:34:03 INFO     Delete after download: false
2024-04-14 08:34:03 INFO     Photo size: original
2024-04-14 08:34:03 INFO     Single pass mode: false
2024-04-14 08:34:03 INFO     Skip download check: false
2024-04-14 08:34:03 INFO     Skip live photos: false
2024-04-14 08:34:03 INFO     Number of most recently added photos to download: Download All Photos
2024-04-14 08:34:03 INFO     Downloading photos from: Download All Photos
2024-04-14 08:34:03 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-04-14 08:34:03 INFO     Live photo size: original
2024-04-14 08:34:03 INFO     Skip videos: false
2024-04-14 08:34:03 INFO     Convert HEIC to JPEG: false
2024-04-14 08:34:03 INFO     Discord notifications enabled
2024-04-14 08:34:03 INFO     Discord Discord ID: xxxxxx
2024-04-14 08:34:03 INFO     Discord Discord token: xxxxxx
2024-04-14 08:34:03 INFO     Discord notification URL: https://discord.com/api/webhooks/xxxxxx
2024-04-14 08:34:03 INFO     Sending Discord startup notification
2024-04-14 08:34:04 INFO     Downloading from: icloud.com
2024-04-14 08:34:04 INFO     Authentication domain: com
2024-04-14 08:34:04 INFO     Ignore Synology extended attribute directories: Disabled
2024-04-14 08:34:06 INFO     Script launch parameters: --Initialise
2024-04-14 08:34:06 INFO     Directory is writable: /config/python_keyring/
2024-04-14 08:34:06 INFO     Starting container initialisation
2024-04-14 08:34:09 ERROR    Authentication required for Account. (421)
2024-04-14 08:34:10 ERROR    Authentication required for Account. (421)
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 387, in _authenticate_with_token
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 132, in request
  File "pyicloud_ipd/base.py", line 134, in request
  File "pyicloud_ipd/base.py", line 207, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (421)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 760, in core
  File "icloudpd/authentication.py", line 31, in authenticate_
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 367, in authenticate
  File "pyicloud_ipd/base.py", line 393, in _authenticate_with_token
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Authentication required for Account. (421)'))
[490] Failed to execute script 'icloudpd' due to unhandled exception!
2024-04-14 08:34:10 ERROR    Multifactor authentication information missing from cookie. Authentication has failed
2024-04-14 08:34:10 ERROR     - Was the correct password entered?
2024-04-14 08:34:10 ERROR     - Was the multifactor authentication code mistyped?
2024-04-14 08:34:10 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-04-14 08:34:10 INFO     Container initialisation complete
/ #

**Comment by vw-kombi** [comment]
This can be closed - it thought my password had been reset.  
I think in my sleep on the apple watch it came up with the code and change password or something.

**Comment by vw-kombi** [comment]
Maybe not close - same issue even after I can login on icloud.com fine.

**Comment by vw-kombi** [comment]
I deleted the container and the config in unraid, then re-set it all up and it is working now.
