### ISSUE TITLE
Failed check for new files files    Failed to execute script 'icloudpd' due to unhandled exception!

### ISSUE THREAD

**Issue by sunnyjackyang** [boredazfcuk/docker-icloudpd#548]
I configured the docker, and have run the --Initialise command. However, I got these error messages that I have marked in bold. I also received error messsages from Bark saying 'failed check for new files'. Can someone help me with it? Thanks!!

2024-04-17T00:14:22.489613778Z 
2024-04-17T00:14:22.511946673Z 2024-04-17 00:14:22 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.733 started *****
2024-04-17T00:14:22.515642977Z 2024-04-17 00:14:22 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-04-17T00:14:22.525047068Z 2024-04-17 00:14:22 INFO     Alpine Linux 3.19.1
2024-04-17T00:14:22.580634006Z 2024-04-17 00:14:22 INFO     Python version: 3.11.8
2024-04-17T00:14:22.714753242Z 2024-04-17 00:14:22 INFO     Loading configuration from: /config/icloudpd.conf
2024-04-17T00:14:22.751547306Z 2024-04-17 00:14:22 WARNING  The local group for synchronisation cannot be root
2024-04-17T00:14:22.973099292Z 2024-04-17 00:14:22 INFO     Apple ID: s**********@gmail.com
2024-04-17T00:14:22.976043604Z 2024-04-17 00:14:22 INFO     Authentication Type: MFA
2024-04-17T00:14:22.978380441Z 2024-04-17 00:14:22 INFO     Cookie path: /config/s********gmailcom
2024-04-17T00:14:22.980371607Z 2024-04-17 00:14:22 INFO     Cookie expiry notification period: 7
2024-04-17T00:14:22.982871690Z 2024-04-17 00:14:22 INFO     Download destination directory: /iCloud
2024-04-17T00:14:22.985031738Z 2024-04-17 00:14:22 INFO     Folder structure: {:%Y/%m/%d}
2024-04-17T00:14:22.986999640Z 2024-04-17 00:14:22 INFO     Synchronisation interval: 86400
2024-04-17T00:14:22.989037151Z 2024-04-17 00:14:22 INFO     Synchronisation delay (minutes): 0
2024-04-17T00:14:22.991121173Z 2024-04-17 00:14:22 INFO     Set EXIF date/time: false
2024-04-17T00:14:22.993252522Z 2024-04-17 00:14:22 INFO     Auto delete: false
2024-04-17T00:14:22.995082369Z 2024-04-17 00:14:22 INFO     Delete after download: false
2024-04-17T00:14:22.996970143Z 2024-04-17 00:14:22 INFO     Photo size: original
2024-04-17T00:14:22.998790902Z 2024-04-17 00:14:22 INFO     Single pass mode: false
2024-04-17T00:14:23.000564196Z 2024-04-17 00:14:23 INFO     Skip download check: false
2024-04-17T00:14:23.002357097Z 2024-04-17 00:14:23 INFO     Skip live photos: false
2024-04-17T00:14:23.004309768Z 2024-04-17 00:14:23 INFO     Number of most recently added photos to download: Download All Photos
2024-04-17T00:14:23.006351527Z 2024-04-17 00:14:23 INFO     Downloading photos from: Download All Photos
2024-04-17T00:14:23.008465753Z 2024-04-17 00:14:23 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-04-17T00:14:23.010465821Z 2024-04-17 00:14:23 INFO     Live photo size: original
2024-04-17T00:14:23.012488352Z 2024-04-17 00:14:23 INFO     Skip videos: false
2024-04-17T00:14:23.014577928Z 2024-04-17 00:14:23 INFO     Convert HEIC to JPEG: false
2024-04-17T00:14:23.016855685Z 2024-04-17 00:14:23 INFO     Bark notifications enabled
2024-04-17T00:14:23.018978340Z 2024-04-17 00:14:23 INFO     Bark device key: N5FQ4HrN5bHyerPsT2LENY
2024-04-17T00:14:23.021036780Z 2024-04-17 00:14:23 INFO     Bark server: api.day.app
2024-04-17T00:14:23.023326677Z 2024-04-17 00:14:23 INFO     Sending Bark startup notification
2024-04-17T00:14:23.275345407Z 2024-04-17 00:14:23 INFO     Downloading from: icloud.com
2024-04-17T00:14:23.277468864Z 2024-04-17 00:14:23 INFO     Authentication domain: com
2024-04-17T00:14:23.279712534Z 2024-04-17 00:14:23 INFO     Ignore Synology extended attribute directories: Disabled
2024-04-17T00:14:25.454443797Z 2024-04-17 00:14:25 INFO     Directory is writable: /config/python_keyring/
2024-04-17T00:14:25.468858826Z 2024-04-17 00:14:25 INFO     Check download directory mounted correctly...
2024-04-17T00:14:25.471942802Z 2024-04-17 00:14:25 INFO     Failsafe file /iCloud/.mounted exists, continuing
2024-04-17T00:14:25.485200068Z 2024-04-17 00:14:25 INFO     Directory is writable: /config/python_keyring/
2024-04-17T00:14:25.487324322Z 2024-04-17 00:14:25 INFO     Keyring file exists, continuing
2024-04-17T00:14:25.489205886Z 2024-04-17 00:14:25 INFO     Sync user: user
2024-04-17T00:14:25.494761447Z 2024-04-17 00:14:25 INFO     Synchronisation starting at 00:14:25
2024-04-17T00:14:25.501751863Z 2024-04-17 00:14:25 INFO     Keyring file exists, continuing
2024-04-17T00:14:25.529324396Z 2024-04-17 00:14:25 INFO     Check download directory mounted correctly...
2024-04-17T00:14:25.531574358Z 2024-04-17 00:14:25 INFO     Failsafe file /iCloud/.mounted exists, continuing
2024-04-17T00:14:25.533413852Z 2024-04-17 00:14:25 INFO     Check for new files using password stored in keyring file
2024-04-17T00:14:25.535187827Z 2024-04-17 00:14:25 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
**2024-04-17T00:14:27.332111066Z 2024-04-17 00:14:27 ERROR    Failed check for new files files
2024-04-17T00:14:27.333227662Z 2024-04-17 00:14:27 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-04-17T00:14:27.334322246Z 2024-04-17 00:14:27 ERROR    Error debugging info:
2024-04-17T00:14:27.336697787Z 2024-04-17 00:14:27 ERROR    Traceback (most recent call last):**
2024-04-17T00:14:27.336718131Z   File "starters/icloudpd.py", line 6, in <module>
2024-04-17T00:14:27.336723088Z   File "click/core.py", line 1157, in __call__
2024-04-17T00:14:27.336726873Z   File "click/core.py", line 1078, in main
2024-04-17T00:14:27.336730332Z   File "click/core.py", line 1434, in invoke
2024-04-17T00:14:27.336733678Z   File "click/core.py", line 783, in invoke
2024-04-17T00:14:27.336736698Z   File "icloudpd/base.py", line 328, in main
2024-04-17T00:14:27.336739727Z   File "icloudpd/base.py", line 760, in core
2024-04-17T00:14:27.336743088Z   File "icloudpd/authentication.py", line 31, in authenticate_
2024-04-17T00:14:27.336746487Z   File "pyicloud_ipd/base.py", line 226, in __init__
2024-04-17T00:14:27.336761673Z   File "pyicloud_ipd/utils.py", line 34, in get_password_from_keyring
2024-04-17T00:14:27.336766115Z   File "keyring/core.py", line 55, in get_password
2024-04-17T00:14:27.336769570Z   File "keyrings/alt/file_base.py", line 99, in get_password
2024-04-17T00:14:27.336773085Z   File "configparser.py", line 684, in read
2024-04-17T00:14:27.336776276Z   File "configparser.py", line 1063, in _read
2024-04-17T00:14:27.336779371Z configparser.MissingSectionHeaderError: File contains no section headers.
2024-04-17T00:14:27.336782723Z file: '/config/python_keyring/keyring_pass.cfg', line: 2
2024-04-17T00:14:27.336786059Z 'Set-Cookie3: dslang="US-EN"; path="/"; domain=".apple.com"; path_spec; secure; discard; HttpOnly=None; version=0\n'
2024-04-17T00:14:27.336789846Z [247] Failed to execute script 'icloudpd' due to unhandled exception!
2024-04-17T00:14:27.337959072Z 2024-04-17 00:14:27 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024-04-17T00:14:27.339098046Z 2024-04-17 00:14:27 INFO     Sending Bark failure notification
2024-04-17T00:14:27.597667241Z ash: out of range
2024-04-17T00:14:27.603786417Z 2024-04-17 00:14:27 INFO     Web cookie expires: 2024-06-16 @ 00:00:08
2024-04-17T00:14:27.605783267Z 2024-04-17 00:14:27 INFO     Multifactor authentication cookie expires: 2024-05-17 @ 00:00:20
2024-04-17T00:14:27.607687630Z 2024-04-17 00:14:27 INFO     Days remaining until expiration: 29
2024-04-17T00:14:27.612982578Z 2024-04-17 00:14:27 INFO     Synchronisation ended at 00:14:27
2024-04-17T00:14:27.617135681Z 2024-04-17 00:14:27 INFO     Total time taken: 00:00:02
2024-04-17T00:14:27.620774629Z 2024-04-17 00:14:27 INFO     Next synchronisation at 00:14:25

**Comment by boredazfcuk** [comment]
```
2024-04-17T00:14:27.336779371Z configparser.MissingSectionHeaderError: File contains no section headers.
2024-04-17T00:14:27.336782723Z file: '/config/python_keyring/keyring_pass.cfg', line: 2
2024-04-17T00:14:27.336786059Z 'Set-Cookie3: dslang="US-EN"; path="/"; domain=".apple.com"; path_spec; secure; discard; HttpOnly=None; version=0\n'
2024-04-17T00:14:27.336789846Z [247] Failed to execute script 'icloudpd' due to unhandled exception!
```

It looks like something is wrong with your password file. Delete this file `/config/python_keyring/keyring_pass.cfg` and then re-initialise.

**Comment by sunnyjackyang** [comment]
> ```
> 2024-04-17T00:14:27.336779371Z configparser.MissingSectionHeaderError: File contains no section headers.
> 2024-04-17T00:14:27.336782723Z file: '/config/python_keyring/keyring_pass.cfg', line: 2
> 2024-04-17T00:14:27.336786059Z 'Set-Cookie3: dslang="US-EN"; path="/"; domain=".apple.com"; path_spec; secure; discard; HttpOnly=None; version=0\n'
> 2024-04-17T00:14:27.336789846Z [247] Failed to execute script 'icloudpd' due to unhandled exception!
> ```
> 
> It looks like something is wrong with your password file. Delete this file `/config/python_keyring/keyring_pass.cfg` and then re-initialise.

Alright I will check it tonight. Thank you for the reply.

**Comment by boredazfcuk** [comment]
Closing as stale
