### ISSUE TITLE
These log messages indicate errors that occurred while attempting to log in to iCloud, including an invalid email/password combination, as well as the inability to find the stored password in the system's keychain. The fact is that the password is entirely correct, and the login attempts are being made in China. Despite numerous attempts, the issue remains unresolved.

### ISSUE THREAD

**Issue by jnxbk** [boredazfcuk/docker-icloudpd#565]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 249, in main
    raise RuntimeError(message)
RuntimeError: Bad username or password for pdas@qq.com
2024-05-19 22:14:13 INFO     Correct owner on config directory, if required
2024-05-19 22:14:13 INFO     Correct group on config directory, if required
2024-05-19 22:14:13 INFO     Generate 2FA cookie using password stored in keyring file.
iCloud Password: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for pdas@qq.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2024-05-19 22:14:21 INFO     Two factor authentication cookie generated. Sync should now be successful.

**Comment by jnxbk** [comment]
Please help me analyze the cause of the issue. Thank you.

**Comment by jnxbk** [comment]
These log messages indicate errors that occurred while attempting to log in to iCloud, including an invalid email/password combination, as well as the inability to find the stored password in the system's keychain. The fact is that the password is entirely correct, and the login attempts are being made in China. Despite numerous attempts, the issue remains unresolved.

**Comment by jnxbk** [comment]
2024-05-19 22:47:54 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2024-05-19 22:47:54 INFO     ***** https://github.com/boredazfcuk/docker-icloudpd *****
2024-05-19 22:47:54 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/12/13_07:53 *****
2024-05-19 22:47:54 INFO     ***** /usr/local/bin/sync-icloud.sh hash: 74dfafa177492086fb3c777f518fbb55 *****
2024-05-19 22:47:54 INFO     Alpine Linux 3.13.5
2024-05-19 22:47:54 INFO     Python version: 3.8.10
2024-05-19 22:47:54 INFO     icloudpd version: 1.7.2
2024-05-19 22:47:56 INFO     pyicloud-ipd version: 0.10.1
2024-05-19 22:47:59 INFO     Running user id: 0
2024-05-19 22:47:59 INFO     Running group id: 0
2024-05-19 22:47:59 INFO     Local user: user:1000
2024-05-19 22:47:59 INFO     Local group: group:1000
2024-05-19 22:47:59 INFO     Force GID: False
2024-05-19 22:47:59 INFO     LAN IP Address: 172.17.0.2
2024-05-19 22:47:59 INFO     Default gateway: 172.17.0.1
2024-05-19 22:47:59 INFO     DNS server: 8.8.8.8
2024-05-19 22:47:59 INFO     DNS lookup for icloud.com.cn: 103.115.248.1
2024-05-19 22:48:28 INFO     Route check to icloud.com.cn successful
2024-05-19 22:48:28 INFO     Apple ID: pdas@qq.com
2024-05-19 22:48:28 INFO     Authentication Type: 2FA
2024-05-19 22:48:28 INFO     Cookie path: /config/pdasqqcom
2024-05-19 22:48:28 INFO     Cookie expiry notification period: 7
2024-05-19 22:48:28 INFO     Download destination directory: /iCloud
2024-05-19 22:48:28 INFO     Folder structure: {:%Y/%m/%d}
2024-05-19 22:48:28 INFO     Directory permissions: 750
2024-05-19 22:48:28 INFO     File permissions: 640
2024-05-19 22:48:28 INFO     Synchronisation interval: 86400
2024-05-19 22:48:28 INFO     Synchronisation delay (minutes): 0
2024-05-19 22:48:28 INFO     Time zone: Asia/Shanghai
2024-05-19 22:48:28 INFO     Set EXIF date/time: False
2024-05-19 22:48:28 INFO     Auto delete: False
2024-05-19 22:48:28 INFO     Photo size: original
2024-05-19 22:48:28 INFO     Skip download check: False
2024-05-19 22:48:28 INFO     Skip live photos: False
2024-05-19 22:48:28 INFO     Number of most recently added photos to download: Download All Photos
2024-05-19 22:48:28 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-05-19 22:48:28 INFO     Live photo size: original
2024-05-19 22:48:28 INFO     Skip videos: False
2024-05-19 22:48:28 INFO     Convert HEIC to JPEG: False
2024-05-19 22:48:28 INFO     JPEG conversion quality: 90
2024-05-19 22:48:28 INFO     Downloading from: icloud.com.cn
2024-05-19 22:48:28 WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues
2024-05-19 22:48:30 INFO     Script launch parameters: --Initialise
2024-05-19 22:48:30 INFO     Group, group:1000, already created
2024-05-19 22:48:30 INFO     User, user:1000, already created
2024-05-19 22:48:30 INFO     Set owner, user, on iCloud directory, if required
2024-05-19 22:48:30 INFO     Set group, group, on iCloud directory, if required
2024-05-19 22:48:30 INFO     Correct owner on icloudpd temp directory, if required
2024-05-19 22:48:30 INFO     Correct group on icloudpd temp directory, if required
2024-05-19 22:48:30 INFO     Correct owner on config directory, if required
2024-05-19 22:48:30 INFO     Correct group on config directory, if required
2024-05-19 22:48:30 INFO     Correct owner on keyring directory, if required
2024-05-19 22:48:30 INFO     Correct group on keyring directory, if required
2024-05-19 22:48:30 INFO     Set 750 permissions on iCloud directories, if required
2024-05-19 22:48:30 INFO     Set 640 permissions on iCloud files, if required
2024-05-19 22:48:30 INFO     Configure password
2024-05-19 22:48:30 INFO     Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for pdas@qq.com: 
Bad username or password for pdas@qq.com
Enter iCloud password for pdas@qq.com: 
Bad username or password for pdas@qq.com
Enter iCloud password for pdas@qq.com: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 249, in main
    raise RuntimeError(message)
RuntimeError: Bad username or password for pdas@qq.com
2024-05-19 22:49:13 INFO     Correct owner on config directory, if required
2024-05-19 22:49:13 INFO     Correct group on config directory, if required
2024-05-19 22:49:13 INFO     Generate 2FA cookie using password stored in keyring file.
iCloud Password: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for pdas@qq.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2024-05-19 22:49:28 INFO     Two factor authentication cookie generated. Sync should now be successful.

**Comment by boredazfcuk** [comment]
>2024-05-19 22:47:54 INFO ***** /usr/local/bin/sync-icloud.sh date: 2021/12/13_07:53 *****
2024-05-19 22:47:54 INFO ***** /usr/local/bin/sync-icloud.sh hash: 74dfafa177492086fb3c777f518fbb55 *****
2024-05-19 22:47:54 INFO Alpine Linux 3.13.5
2024-05-19 22:47:54 INFO Python version: 3.8.10
2024-05-19 22:47:54 INFO icloudpd version: 1.7.2
2024-05-19 22:47:56 INFO pyicloud-ipd version: 0.10.1

Your version is over 3 years old.

**Comment by jnxbk** [comment]
> > 2024-05-19 22:47:54 信息 ***** /usr/local/bin/sync-icloud.sh 日期：2021/12/13_07:53 *****2024-05-19 22:47:54 INFO ***** /usr/local/bin/sync-icloud.sh hash: 74dfafa177492086fb3c777f518fbb55 *****2024-05-19 22:47:54 信息 Alpine Linux 3.13.52024-05-19 22:47:54 INFO Python版本：3.8.102024-05-19 22:47:54 INFO icloudpd版本：1.7.22024-05-19 22:47:56 INFO pyicloud-ipd 版本：0.10.1
> 
> 您的版本已超过3年。

thanks

**Comment by jnxbk** [comment]
> > 2024-05-19 22:47:54 INFO ***** /usr/local/bin/sync-icloud.sh date: 2021/12/13_07:53 *****
> > 2024-05-19 22:47:54 INFO ***** /usr/local/bin/sync-icloud.sh hash: 74dfafa177492086fb3c777f518fbb55 *****
> > 2024-05-19 22:47:54 INFO Alpine Linux 3.13.5
> > 2024-05-19 22:47:54 INFO Python version: 3.8.10
> > 2024-05-19 22:47:54 INFO icloudpd version: 1.7.2
> > 2024-05-19 22:47:56 INFO pyicloud-ipd version: 0.10.1
> 
> Your version is over 3 years old.

good  Thank you very much
