### ISSUE TITLE
Login failed The specific log is as follows

### ISSUE THREAD

**Issue by jnxbk** [boredazfcuk/docker-icloudpd#568]
Traceback (most recent call last):
  File "starters/icloud.py", line 5, in <module>
  File "pyicloud_ipd/cmdline.py", line 200, in main
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 367, in authenticate
  File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?
[513] Failed to execute script 'icloud' due to unhandled exception!
2024-05-25 13:42:49 ERROR    Keyring file does not exist. Please try again.

**Comment by jnxbk** [comment]
2024-05-25 13:41:53 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.825 started *****
2024-05-25 13:41:53 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-05-25 13:41:53 INFO     Alpine Linux 3.20.0
2024-05-25 13:41:53 INFO     Python version: 3.12.3
2024-05-25 13:41:53 INFO     Loading configuration from: /config/icloudpd.conf
2024-05-25 13:42:22 INFO     Apple ID: pdas@qq.com
2024-05-25 13:42:22 INFO     Authentication Type: MFA
2024-05-25 13:42:22 INFO     Cookie path: /config/pdasqqcom
2024-05-25 13:42:22 INFO     Cookie expiry notification period: 7
2024-05-25 13:42:22 INFO     Download destination directory: /iCloud
2024-05-25 13:42:22 INFO     Folder structure: {:%Y/%m/%d}
2024-05-25 13:42:22 INFO     Synchronisation interval: 86400
2024-05-25 13:42:22 INFO     Synchronisation delay (minutes): 0
2024-05-25 13:42:22 INFO     Set EXIF date/time: false
2024-05-25 13:42:22 INFO     Auto delete: false
2024-05-25 13:42:22 INFO     Delete after download: false
2024-05-25 13:42:22 INFO     Photo size: original
2024-05-25 13:42:22 INFO     Single pass mode: false
2024-05-25 13:42:22 INFO     Skip download check: false
2024-05-25 13:42:22 INFO     Skip live photos: false
2024-05-25 13:42:22 INFO     Number of most recently added photos to download: Download All Photos
2024-05-25 13:42:22 INFO     Downloading photos from: Download All Photos
2024-05-25 13:42:22 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-05-25 13:42:22 INFO     Live photo size: original
2024-05-25 13:42:22 INFO     Skip videos: false
2024-05-25 13:42:22 INFO     Convert HEIC to JPEG: false
2024-05-25 13:42:22 INFO     Downloading from: icloud.com.cn
2024-05-25 13:42:22 WARNING  You have the icloud_china variable set, but auth_china is false. Are you sure this is correct?
2024-05-25 13:42:22 INFO     Authentication domain: com
2024-05-25 13:42:22 INFO     Ignore Synology extended attribute directories: Disabled
2024-05-25 13:42:26 INFO     Script launch parameters: --Initialise

**Comment by boredazfcuk** [comment]
>WARNING You have the icloud_china variable set, but auth_china is false. Are you sure this is correct?

You've configured it authenticate against global servers, but download photos from China. This is probably why it's failing to authenticate.

**Comment by boredazfcuk** [comment]
Thanks for confirming the resolution.
