### ISSUE TITLE
docker initialize script doesn't prompt for interactivity

### ISSUE THREAD

**Issue by timrettop** [boredazfcuk/docker-icloudpd#570]
Hello, 

I noticed an issue starting a photo backup and checked on this tool.  I updated to the latest: 
2024-05-27 19:25:11 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.733 started *****

When i attempt to run the sync-icloud.sh --Initialise I am not being prompted when it reaches the username/password section, the script just continues executing and fails. 
I tried deleting my icloud username files in the config folder and reattempted and get the same result.

I'm running this in an unraid environment, anything you need to debug further? 

Here is the output of the command: 

```
root@Black:/mnt/disks/S6PNNS0T413198L/docker# docker exec -it icloudpd sync-icloud.sh --Initialise

2024-05-27 19:29:35 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.733 started *****
2024-05-27 19:29:35 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-05-27 19:29:35 INFO     Alpine Linux 3.19.1
2024-05-27 19:29:35 INFO     Python version: 3.11.8
2024-05-27 19:29:35 INFO     Loading configuration from: /config/icloudpd.conf
{config info redacted}
2024-05-27 19:29:43 INFO     Sending Telegram startup notification
2024-05-27 19:29:43 INFO     Downloading from: icloud.com
2024-05-27 19:29:43 INFO     Authentication domain: com
2024-05-27 19:29:43 INFO     Ignore Synology extended attribute directories: Disabled
2024-05-27 19:29:45 INFO     Script launch parameters: --Initialise
2024-05-27 19:29:45 INFO     Directory is writable: /config/python_keyring/
2024-05-27 19:29:45 INFO     Starting container initialisation
2024-05-27 19:29:46 ERROR    Invalid username/password combination. (401)
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 357, in authenticate
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 140, in request
  File "pyicloud_ipd/base.py", line 207, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Invalid username/password combination. (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 760, in core
  File "icloudpd/authentication.py", line 31, in authenticate_
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 365, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('Invalid username/password combination. (401)'))
[481] Failed to execute script 'icloudpd' due to unhandled exception!
2024-05-27 19:29:46 ERROR    Multifactor authentication information missing from cookie. Authentication has failed
2024-05-27 19:29:46 ERROR     - Was the correct password entered?
2024-05-27 19:29:46 ERROR     - Was the multifactor authentication code mistyped?
2024-05-27 19:29:46 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-05-27 19:29:46 INFO     Container initialisation complete
```

**Comment by timrettop** [comment]
Ahh, removing the python_keyring/keyring_pass.cfg file and restarting resolved this issue. Closing.
