### ISSUE TITLE
Couldn't Initialize: Couldn't generate the keyring

### ISSUE THREAD

**Issue by Junyu06** [boredazfcuk/docker-icloudpd#572]
### Overall:
Hi, thank you for maintaining the code.
I have been using iCloudPD for a year at Unraid, and it works fine.
I lost all my Docker images and data recently due to a drive failure. Luckily, Unraid remembered my iCloudPD setting, and I used it to perform a new iCloudPD.
Unfortunately, during the initialization, it keeps telling me that the "keyring file does not exist. please try again."

### Try:
1. I tried to enter my password multiple times to ensure I didn't enter the wrong one. (I also tried going to appleid.com to verify the correct password.)
2. I also thought that maybe the folder permission was wrong, so I changed the permission to wrx for all.

Both tries didn't work for me.
Also, in the Config folder, it seems it didn't generate anything.

I would be grateful if you could help me to find out where the issue is.

### Terminal:

> root@3cebf280b636:/> sync-icloud.sh --Initialise
>
>2024-05-28 23:51:02 INFO     ***** boredazfcuk/icloudpd container v1.0.831_28-05-2024 started *****
2024-05-28 23:51:02 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-05-28 23:51:02 INFO     Alpine Linux 3.20.0
2024-05-28 23:51:02 INFO     Python version: 3.12.3
2024-05-28 23:51:03 INFO     icloud-photos-downloader version: 1.18.0
2024-05-28 23:51:03 INFO     Loading configuration from: /config/icloudpd.conf
2024-05-28 23:51:04 INFO     Apple ID: _AppleID_
2024-05-28 23:51:04 INFO     Authentication Type: MFA
2024-05-28 23:51:04 INFO     Cookie path: /config/_AppleID_
2024-05-28 23:51:04 INFO     Cookie expiry notification period: 7
2024-05-28 23:51:04 INFO     Download destination directory: /home/user/iCloud
2024-05-28 23:51:04 INFO     Folder structure: {:%Y/%m/%d}
2024-05-28 23:51:04 INFO     Synchronisation interval: 86400
2024-05-28 23:51:04 INFO     Synchronisation delay (minutes): 0
2024-05-28 23:51:04 INFO     Set EXIF date/time: false
2024-05-28 23:51:04 INFO     Auto delete: false
2024-05-28 23:51:04 INFO     Delete after download: false
2024-05-28 23:51:04 INFO     Photo size: original
2024-05-28 23:51:04 INFO     Single pass mode: false
2024-05-28 23:51:04 INFO     Skip download check: false
2024-05-28 23:51:04 INFO     Skip live photos: false
2024-05-28 23:51:04 INFO     Number of most recently added photos to download: Download All Photos
2024-05-28 23:51:04 INFO     Downloading photos from: Download All Photos
2024-05-28 23:51:04 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-05-28 23:51:04 INFO     Live photo size: original
2024-05-28 23:51:04 INFO     Skip videos: false
2024-05-28 23:51:04 INFO     Convert HEIC to JPEG: false
2024-05-28 23:51:04 INFO     Telegram notifications enabled
2024-05-28 23:51:04 INFO     Telegram token: _TelegramToken_
2024-05-28 23:51:04 INFO     Telegram chat id: _TelegramChatID_
2024-05-28 23:51:04 INFO     Telegram polling: true
2024-05-28 23:51:04 INFO     Telegram notification URL: _TelegramURL_
2024-05-28 23:51:04 INFO     Check Telegram bot initialised...
2024-05-28 23:51:10 INFO      - Bot has been initialised.
2024-05-28 23:51:10 INFO     Latest update id: 0
2024-05-28 23:51:10 INFO     Sending Telegram startup notification
2024-05-28 23:51:10 INFO     Downloading from: icloud.com
2024-05-28 23:51:10 INFO     Authentication domain: com
2024-05-28 23:51:10 INFO     Ignore Synology extended attribute directories: Disabled
2024-05-28 23:51:11 INFO     Script launch parameters: --Initialise
Enter iCloud password for _AppleID_: 
Traceback (most recent call last):
  File "starters/icloud.py", line 5, in <module>
  File "pyicloud_ipd/cmdline.py", line 202, in main
  File "pyicloud_ipd/base.py", line 63, in __init__
  File "pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
pyicloud_ipd.exceptions.PyiCloudNoStoredPasswordAvailableException: No pyicloud password for _AppleIDPassword_ could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.
[585] Failed to execute script 'icloud' due to unhandled exception!
2024-05-28 23:51:19 ERROR    Keyring file does not exist. Please try again.

### Configuration:
![screencapture-bigteririnas-local-Docker-UpdateContainer-2024-05-29-00_13_39](https://github.com/boredazfcuk/docker-icloudpd/assets/70296613/9f6ceea4-3b78-4a6c-905a-064fd3d6bbd1)

### File Permission:
![20240529000704](https://github.com/boredazfcuk/docker-icloudpd/assets/70296613/3ea8eb73-f4a6-4c3e-8fe2-9bf6e54b3438)

**Comment by Junyu06** [comment]
The problem was solved by using version 1.0.816. But I still don't know why it doesn't work on the latest version.
