### ISSUE TITLE
Can not download photos

### ISSUE THREAD

**Issue by pandahuman** [boredazfcuk/docker-icloudpd#581]
2024/6/13 20:41:23  2024-06-13 20:41:23 ERROR    ***** Once you have captured this log file, please post it along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024/6/13 20:41:23  2024-06-13 20:41:23 ERROR    Please set debug_logging=true in your icloudpd.conf file then reproduce the error.
2024/6/13 20:41:23  [323] Failed to execute script 'icloudpd' due to unhandled exception!
2024/6/13 20:41:23  tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like CST-8. \nPlease use a timezone in the form of Continent/City'
2024/6/13 20:41:23    File "tzlocal/utils.py", line 124, in _tz_from_env
2024/6/13 20:41:23    File "tzlocal/unix.py", line 167, in _get_localzone
2024/6/13 20:41:23    File "tzlocal/unix.py", line 209, in get_localzone
2024/6/13 20:41:23    File "icloudpd/base.py", line 514, in download_photo_
2024/6/13 20:41:23    File "icloudpd/base.py", line 1019, in core
2024/6/13 20:41:23    File "icloudpd/base.py", line 422, in main
2024/6/13 20:41:23    File "click/core.py", line 783, in invoke
2024/6/13 20:41:23    File "click/core.py", line 1434, in invoke
2024/6/13 20:41:23    File "click/core.py", line 1078, in main
2024/6/13 20:41:23    File "click/core.py", line 1157, in __call__
2024/6/13 20:41:23    File "starters/icloudpd.py", line 6, in <module>
2024/6/13 20:41:23  2024-06-13 20:41:23 ERROR    Traceback (most recent call last):
2024/6/13 20:41:23  2024-06-13 20:41:23 ERROR    Error debugging info:
2024/6/13 20:41:23  2024-06-13 20:41:23 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2024/6/13 20:41:23  2024-06-13 20:41:23 ERROR    Failed check for new files files
2024/6/13 20:41:12  2024-06-13 20:41:12 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2024/6/13 20:41:12  2024-06-13 20:41:12 INFO     Check for new files using password stored in keyring file
![屏幕快照 2024-06-13 下午8 49 00](https://github.com/boredazfcuk/docker-icloudpd/assets/59038401/a4cf3308-52fc-41e8-b47b-aaa59bd41c9d)

what can I do

**Comment by pandahuman** [comment]
wrong time zone !it's ok now
