### ISSUE TITLE
Error downloading "Unhandled Exception" 

### ISSUE THREAD

**Issue by Jgams** [boredazfcuk/docker-icloudpd#613]
I've run iCloudpd a few times now and have managed to get most of my library. However each time it fails out after about 20-30 minutes. I get this error:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 645, in main
  File "icloudpd/base.py", line 1235, in core
  File "icloudpd/base.py", line 801, in download_photo_
KeyError: <AssetVersionSize.ORIGINAL: 'original'>
[466] Failed to execute script 'icloudpd' due to unhandled exception!

Anyone have any thoughts? Thanks!

**Comment by boredazfcuk** [comment]
Seems one of your photos may not have an 'original' size version in iCloud. 

Only think I can suggest is seeing if the log tells you which file it's attempting to download before the error. Set **debug_logging=true** in your icloudpd.conf file should help.

**Comment by Jgams** [comment]
Thanks! I ran it one more time as I saw you updated the app. Here's what I found: 

2024-07-26 15:24:35 DEBUG    /home/user/iCloud/2014/07/02/AdvyIJh67e5y+sv2jnMWSEMuTI5e.MOV already exists
2024-07-26 15:24:35 DEBUG    /home/user/iCloud/2014/07/02/ARG1dLtHnPQ+n2MibMqHKalg0PFh.MOV already exists
2024-07-26 15:24:35 ERROR    Failed to download new files
2024-07-26 15:24:35 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-07-26 15:24:35 ERROR    Error debugging info:
2024-07-26 15:24:35 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd/lib/python3.12/site-packages/icloudpd/base.py", line 696, in main
    result = core(
             ^^^^^
  File "/opt/icloudpd/lib/python3.12/site-packages/icloudpd/base.py", line 1286, in core
    if download_photo(consecutive_files_found, item) and delete_after_download:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd/lib/python3.12/site-packages/icloudpd/base.py", line 852, in download_photo_
    version = versions[download_size]
              ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: <AssetVersionSize.ORIGINAL: 'original'>
2024-07-26 15:24:35 ERROR    ***** Please post the above debug log, along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024-07-26 15:24:35 DEBUG    Web cookie exists
2024-07-26 15:24:35 INFO     Web cookie expires: 2024-09-09 @ 03:12:37
2024-07-26 15:24:35 INFO     Multifactor authentication cookie expires: 2024-08-25 @ 18:58:57
2024-07-26 15:24:35 INFO     Days remaining until expiration: 30
2024-07-26 15:24:35 DEBUG    iCloud login counter = 1
2024-07-26 15:24:35 INFO     Synchronisation ended at 15:24:35
2024-07-26 15:24:35 INFO     Total time taken: 00:12:03


It looks like it's stopping at the same file each time. I found the photos that are due to be imported after that, and I don't see any issue opening or downloading that particular file. 

The naming convention is a bit odd... so idk if characters are causing errors at all.

**Comment by boredazfcuk** [comment]
I believe this is due to it not being able to find the 'original' size version in icloud and has been fixed by an upstream change. Please try again and let me know if you have any more issues.
