### ISSUE TITLE
Can't authenticate after running --Initialise

### ISSUE THREAD

**Issue by crusey11** [boredazfcuk/docker-icloudpd#642]
I'm having an issue when i run sync-icloud.sh --Initialise it asks me for the pw to the icloud account and when i hit enter it just doesn't move forward. It moves to the next line and nothing. I've tried using an older release on recommendations found on github and reddit and no luck yet. 

:/> sync-icloud.sh --Initialise

2024-08-31 12:03:07 INFO     ***** boredazfcuk/icloudpd container v1.0.937_31-08-2024 started *****
2024-08-31 12:03:07 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-08-31 12:03:07 INFO     Alpine Linux 3.20.2
2024-08-31 12:03:07 INFO     Python version: 3.12.3
2024-08-31 12:03:08 INFO     icloud-photos-downloader version: 1.23.1
2024-08-31 12:03:08 INFO     Checking for updates...
2024-08-31 12:03:09 INFO      - Current version is up to date
2024-08-31 12:03:09 INFO     Loading configuration from: /config/icloudpd.conf
2024-08-31 12:03:12 INFO     Apple ID: xxxxx
2024-08-31 12:03:12 INFO     Authentication Type: MFA
2024-08-31 12:03:12 INFO     Cookie path: /config/xxxxx
2024-08-31 12:03:12 INFO     Cookie expiry notification period: 7
2024-08-31 12:03:12 INFO     Download destination directory: /home/user/iCloud
2024-08-31 12:03:12 INFO     Folder structure: {:%Y/%m/%d}
2024-08-31 12:03:12 INFO     Keep Unicode: false
2024-08-31 12:03:12 INFO     Live Photo MOV Filename Policy: suffix
2024-08-31 12:03:12 INFO     File Match Policy: name-size-dedup-with-suffix
2024-08-31 12:03:12 INFO     Synchronisation interval: 86400
2024-08-31 12:03:12 INFO     Synchronisation delay (minutes): 0
2024-08-31 12:03:12 INFO     Set EXIF date/time: false
2024-08-31 12:03:12 INFO     Auto delete: false
2024-08-31 12:03:12 INFO     Delete after download: false
2024-08-31 12:03:12 INFO     Delete empty directories: false
2024-08-31 12:03:12 INFO     Photo size: original
2024-08-31 12:03:12 INFO     Align RAW: as-is
2024-08-31 12:03:12 INFO     Single pass mode: false
2024-08-31 12:03:12 INFO     Skip download check: false
2024-08-31 12:03:12 INFO     Skip live photos: false
2024-08-31 12:03:12 INFO     Number of most recently added photos to download: Download All Photos
2024-08-31 12:03:12 INFO     Downloading photos from: Download All Photos
2024-08-31 12:03:12 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-08-31 12:03:12 INFO     Live photo size: original
2024-08-31 12:03:12 INFO     Skip videos: false
2024-08-31 12:03:12 INFO     Convert HEIC to JPEG: false
2024-08-31 12:03:12 INFO     Downloading from: icloud.com
2024-08-31 12:03:12 INFO     Fake user agent for curl: Disabled
2024-08-31 12:03:12 INFO     Authentication domain: com
2024-08-31 12:03:12 INFO     Ignore Synology extended attribute directories: Disabled
2024-08-31 12:03:12 INFO     Container initialisation complete
2024-08-31 12:03:12 INFO     Script launch parameters: --Initialise
Running in MAIN
Enter iCloud password for xxxxxxx: 

------

LOG

2024-08-31 11:53:17 INFO     ***** boredazfcuk/icloudpd container v1.0.937_31-08-2024 started *****
2024-08-31 11:53:17 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-08-31 11:53:17 INFO     Alpine Linux 3.20.2
2024-08-31 11:53:17 INFO     Python version: 3.12.3
2024-08-31 11:53:17 INFO     icloud-photos-downloader version: 1.23.1
2024-08-31 11:53:17 INFO     Checking for updates...
2024-08-31 11:53:18 INFO      - Current version is up to date
2024-08-31 11:53:18 INFO     Loading configuration from: /config/icloudpd.conf
2024-08-31 11:53:20 INFO     Apple ID: xxxxx
2024-08-31 11:53:20 INFO     Authentication Type: MFA
2024-08-31 11:53:20 INFO     Cookie path: /config/xxxxxx
2024-08-31 11:53:20 INFO     Cookie expiry notification period: 7
2024-08-31 11:53:20 INFO     Download destination directory: /home/user/iCloud
2024-08-31 11:53:20 INFO     Folder structure: {:%Y/%m/%d}
2024-08-31 11:53:20 INFO     Keep Unicode: false
2024-08-31 11:53:20 INFO     Live Photo MOV Filename Policy: suffix
2024-08-31 11:53:20 INFO     File Match Policy: name-size-dedup-with-suffix
2024-08-31 11:53:20 INFO     Synchronisation interval: 86400
2024-08-31 11:53:20 INFO     Synchronisation delay (minutes): 0
2024-08-31 11:53:20 INFO     Set EXIF date/time: false
2024-08-31 11:53:20 INFO     Auto delete: false
2024-08-31 11:53:20 INFO     Delete after download: false
2024-08-31 11:53:20 INFO     Delete empty directories: false
2024-08-31 11:53:20 INFO     Photo size: original
2024-08-31 11:53:20 INFO     Align RAW: as-is
2024-08-31 11:53:21 INFO     Single pass mode: false
2024-08-31 11:53:21 INFO     Skip download check: false
2024-08-31 11:53:21 INFO     Skip live photos: false
2024-08-31 11:53:21 INFO     Number of most recently added photos to download: Download All Photos
2024-08-31 11:53:21 INFO     Downloading photos from: Download All Photos
2024-08-31 11:53:21 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-08-31 11:53:21 INFO     Live photo size: original
2024-08-31 11:53:21 INFO     Skip videos: false
2024-08-31 11:53:21 INFO     Convert HEIC to JPEG: false
2024-08-31 11:53:21 INFO     Downloading from: icloud.com
2024-08-31 11:53:21 INFO     Fake user agent for curl: Disabled
2024-08-31 11:53:21 INFO     Authentication domain: com
2024-08-31 11:53:21 INFO     Ignore Synology extended attribute directories: Disabled
2024-08-31 11:53:21 INFO     Container initialisation complete
2024-08-31 11:53:21 ERROR    Keyring file /config/python_keyring/keyring_pass.cfg does not exist
2024-08-31 11:53:21 ERROR     - Please add the your password to the system keyring using the --Initialise script command line option
2024-08-31 11:53:21 ERROR     - Syntax: docker exec -it <container name> sync-icloud.sh --Initialise
2024-08-31 11:53:21 ERROR     - Example: docker exec -it icloudpd sync-icloud.sh --Initialise
2024-08-31 11:53:21 ERROR    Waiting for keyring file to be created...

**Comment by fanhuameng** [comment]
Try with in shell
docker exec -it {your docker ps}  sync-icloud.sh --Initialise

**Comment by crusey11** [comment]
the same thing happened when i ran it in my unraid terminal

**Comment by fanhuameng** [comment]
We haven't had any problems with this one;

**Comment by boredazfcuk** [comment]
```
Running in MAIN
```
I don't know why you're seeing this. it's not something my container would produce so I suspect something is interfering with the code input sequence.

**Comment by boredazfcuk** [comment]
> ```
> Running in MAIN
> ```
> 
> I don't know why you're seeing this. it's not something my container would produce so I suspect something is interfering with the code input sequence.

I actually changed my password the other day and saw this myself. This only appears when setting the password and not when renewing the multi-factor authentication cookie.

Guess the unraid terminal is affecting input somehow. Try running from a terminal prompt and using the docker command line.

**Comment by tquizzle** [comment]
Same title issue, slightly different output.

```
docker exec -it icloudpd sync-icloud.sh --Initialise

2024-10-08 16:39:51 INFO     ***** boredazfcuk/icloudpd container v1.0.980_17-09-2024 started *****
2024-10-08 16:39:51 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-10-08 16:39:51 INFO     Alpine Linux 3.20.3
2024-10-08 16:39:51 INFO     Python version: 3.12.6
2024-10-08 16:39:51 INFO     icloud-photos-downloader version: 1.23.4
2024-10-08 16:39:51 INFO     Checking for updates...
2024-10-08 16:39:52 INFO      - Current version is up to date
2024-10-08 16:39:52 INFO     Loading configuration from: /config/icloudpd.conf
2024-10-08 16:40:02 INFO     Apple ID: tquinnelly@gmail.com
2024-10-08 16:40:02 INFO     Authentication Type: MFA
2024-10-08 16:40:02 INFO     Cookie path: /config/tquinnellygmailcom
2024-10-08 16:40:02 INFO     Cookie expiry notification period: 7
2024-10-08 16:40:02 INFO     Download destination directory: /home/user/iCloud
2024-10-08 16:40:02 INFO     Folder structure: {:%Y/%m/%d}
2024-10-08 16:40:02 INFO     Keep Unicode: false
2024-10-08 16:40:02 INFO     Live Photo MOV Filename Policy: suffix
2024-10-08 16:40:02 INFO     File Match Policy: name-size-dedup-with-suffix
2024-10-08 16:40:02 INFO     Synchronisation interval: 86400
2024-10-08 16:40:02 INFO     Synchronisation delay (minutes): 0
2024-10-08 16:40:02 INFO     Set EXIF date/time: false
2024-10-08 16:40:02 INFO     Auto delete: false
2024-10-08 16:40:02 INFO     Delete after download: false
2024-10-08 16:40:02 INFO     Delete empty directories: false
2024-10-08 16:40:02 INFO     Photo size: original
2024-10-08 16:40:02 INFO     Align RAW: as-is
2024-10-08 16:40:02 INFO     Single pass mode: false
2024-10-08 16:40:02 INFO     Skip download check: false
2024-10-08 16:40:02 INFO     Skip live photos: false
2024-10-08 16:40:02 INFO     Number of most recently added photos to download: Download All Photos
2024-10-08 16:40:02 INFO     Downloading photos from: Download All Photos
2024-10-08 16:40:02 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-10-08 16:40:02 INFO     Live photo size: original
2024-10-08 16:40:02 INFO     Skip videos: false
2024-10-08 16:40:02 INFO     Convert HEIC to JPEG: false
2024-10-08 16:40:03 INFO     Downloading from: icloud.com
2024-10-08 16:40:03 INFO     Fake user agent for curl: Disabled
2024-10-08 16:40:03 INFO     Authentication domain: com
2024-10-08 16:40:03 INFO     Ignore Synology extended attribute directories: Disabled
2024-10-08 16:40:03 INFO     Container initialisation complete
2024-10-08 16:40:03 INFO     Script launch parameters: --Initialise
2024-10-08 16:40:04 INFO     Directory is writable: /config/python_keyring/
2024-10-08 16:40:04 INFO     Starting container initialisation
2024-10-08 16:40:04 DEBUG    Authenticating...

```

And that's where it hangs. No other output. After a while, the container dies.

**Comment by boredazfcuk** [comment]
> And that's where it hangs. No other output. After a while, the container dies.

Enable debug logging for further information.

**Comment by DeltaEchoFour** [comment]
I'm also having this issue setting up icloudpd on Unraid. I've tried using the Unraid web terminal and sshing into the Unraid server from MacOS Terminal.

I get the password prompt, but when entering the correct password, I'm getting a Bad username or password error.

I will say, I was able to get this working a few revisions of the container ago, but it's all been failing using newer versions.

**Comment by apriliars3** [comment]
I have this issue

`2024-11-16 00:10:48 INFO     Container initialisation complete
2024-11-16 00:10:48 INFO     Script launch parameters: --Initialise
2024-11-16 00:10:48 INFO     Directory is writable: /config/python_keyring/
2024-11-16 00:10:48 INFO     Starting container initialisation
2024-11-16 00:10:53 DEBUG    Authenticating...
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 270, in authenticate
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: {
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
} (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1183, in core
  File "icloudpd/authentication.py", line 53, in authenticate_
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 280, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[824] Failed to execute script 'icloudpd' due to unhandled exception!
2024-11-16 00:10:55 ERROR    Multifactor authentication information missing from cookie. Authentication has failed
2024-11-16 00:10:55 ERROR     - Was the correct password entered?
2024-11-16 00:10:55 ERROR     - Was the multifactor authentication code mistyped?
2024-11-16 00:10:55 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-11-16 00:10:55 INFO     Container initialisation complete
`
