### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by wyhghost** [boredazfcuk/docker-icloudpd#651]
2024-09-14 02:13:29 INFO     ***** boredazfcuk/icloudpd container v1.0.977_11-09-2024 started *****
2024-09-14 02:13:29 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-09-14 02:13:29 INFO     Alpine Linux 3.20.3
2024-09-14 02:13:29 INFO     Python version: 3.12.3
2024-09-14 02:13:30 INFO     icloud-photos-downloader version: 1.23.4
2024-09-14 02:13:30 INFO     Checking for updates...
2024-09-14 02:13:31 INFO      - Current version is up to date
2024-09-14 02:13:31 INFO     Loading configuration from: /config/icloudpd.conf
2024-09-14 02:13:31 DEBUG    Running user id: 0
2024-09-14 02:13:31 DEBUG    Running group id: 0
2024-09-14 02:13:31 DEBUG    Local user: user:1000
2024-09-14 02:13:31 DEBUG    Local group: group:1000
2024-09-14 02:13:31 DEBUG    Force GID: false
2024-09-14 02:13:31 DEBUG    LAN IP Address: 172.17.0.8
2024-09-14 02:13:31 DEBUG    Default gateway: 172.17.0.1
2024-09-14 02:13:31 DEBUG    DNS server: 192.168.31.1
8.8.8.8
2024-09-14 02:13:31 DEBUG    IP address for icloud.com.cn: 103.115.248.1
2024-09-14 02:14:03 DEBUG    Route check to icloud.com.cn successful
2024-09-14 02:14:03 DEBUG    Apple ID: (hidden)
2024-09-14 02:14:03 INFO     Authentication Type: MFA
2024-09-14 02:14:03 DEBUG    Cookie path: /config/(hidden)
2024-09-14 02:14:03 INFO     Cookie expiry notification period: 7
2024-09-14 02:14:03 INFO     Download destination directory: /home/user/iCloud
2024-09-14 02:14:03 INFO     Folder structure: {:%Y/%m/%d}
2024-09-14 02:14:03 DEBUG    Directory permissions: 750
2024-09-14 02:14:03 DEBUG    File permissions: 640
2024-09-14 02:14:03 INFO     Keep Unicode: false
2024-09-14 02:14:03 INFO     Live Photo MOV Filename Policy: suffix
2024-09-14 02:14:03 INFO     File Match Policy: name-size-dedup-with-suffix
2024-09-14 02:14:03 INFO     Synchronisation interval: 86400
2024-09-14 02:14:03 INFO     Synchronisation delay (minutes): 0
2024-09-14 02:14:03 INFO     Set EXIF date/time: false
2024-09-14 02:14:03 INFO     Auto delete: true
2024-09-14 02:14:03 INFO     Delete after download: false
2024-09-14 02:14:03 INFO     Delete empty directories: false
2024-09-14 02:14:03 INFO     Photo size: original
2024-09-14 02:14:03 INFO     Align RAW: as-is
2024-09-14 02:14:03 INFO     Single pass mode: false
2024-09-14 02:14:03 INFO     Skip download check: false
2024-09-14 02:14:03 INFO     Skip live photos: false
2024-09-14 02:14:03 INFO     Number of most recently added photos to download: Download All Photos
2024-09-14 02:14:03 INFO     Downloading photos from: Download All Photos
2024-09-14 02:14:03 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-09-14 02:14:03 INFO     Live photo size: original
2024-09-14 02:14:03 INFO     Skip videos: false
2024-09-14 02:14:03 INFO     Convert HEIC to JPEG: false
2024-09-14 02:14:03 INFO     Downloading from: icloud.com.cn
2024-09-14 02:14:03 INFO     Fake user agent for curl: Disabled
2024-09-14 02:14:03 INFO     Authentication domain: cn
2024-09-14 02:14:03 DEBUG    Nextcloud upload: Disabled
2024-09-14 02:14:03 INFO     Ignore Synology extended attribute directories: Disabled
2024-09-14 02:14:03 DEBUG    Activated Python virtual environment for icloudpd
2024-09-14 02:14:03 INFO     Container initialisation complete
2024-09-14 02:14:03 DEBUG    Group, group:1000, already created
2024-09-14 02:14:03 DEBUG    User, user:1000, already created
2024-09-14 02:14:03 DEBUG    Set owner and group on icloudpd temp directory
2024-09-14 02:14:03 DEBUG    Set owner and group on config directory
2024-09-14 02:14:03 INFO     Directory is writable: /config/python_keyring/
2024-09-14 02:14:03 DEBUG    Configure password
2024-09-14 02:14:03 DEBUG    Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2024-09-14 02:14:03 INFO     Check download directory mounted correctly...
2024-09-14 02:14:03 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2024-09-14 02:14:03 DEBUG    Set owner and group on icloudpd temp directory
2024-09-14 02:14:03 DEBUG    Set owner and group on config directory
2024-09-14 02:14:03 INFO     Directory is writable: /config/python_keyring/
2024-09-14 02:14:03 INFO     Keyring file exists, continuing
2024-09-14 02:14:03 INFO     Sync user: user
2024-09-14 02:14:03 INFO     Synchronisation starting at 02:14:03
2024-09-14 02:14:03 INFO     Keyring file exists, continuing
2024-09-14 02:14:03 DEBUG    Check MFA Cookie
2024-09-14 02:14:03 DEBUG    Multifactor authentication cookie exists
2024-09-14 02:14:03 DEBUG    Valid multifactor authentication cookie found. Days until expiration: 29
2024-09-14 02:14:03 INFO     Check download directory mounted correctly...
2024-09-14 02:14:03 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2024-09-14 02:14:03 INFO     Check for new files using password stored in keyring file
2024-09-14 02:14:03 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2024-09-14 02:14:03 DEBUG    Launch command: /opt/icloudpd/bin/icloudpd --directory /home/user/iCloud --cookie-directory /config --username wyhghost@outlook.com --domain cn --folder-structure {:%Y/%m/%d} --only-print-filenames
2024-09-14 02:14:04 ERROR    Authentication required for Account. (421)
2024-09-14 02:14:10 ERROR    Please log into https://icloud.com/ to manually finish setting up your iCloud service (AUTHENTICATION_FAILED)
2024-09-14 02:14:10 ERROR    Failed check for new files files
2024-09-14 02:14:10 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2024-09-14 02:14:10 ERROR    Error debugging info:
2024-09-14 02:14:10 ERROR    Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1218, in core
  File "pyicloud_ipd/base.py", line 549, in photos
  File "pyicloud_ipd/services/photos.py", line 281, in __init__
  File "pyicloud_ipd/services/photos.py", line 168, in __init__
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/session.py", line 167, in request
  File "pyicloud_ipd/session.py", line 185, in _raise_error
pyicloud_ipd.exceptions.PyiCloudServiceNotActivatedException: Please log into https://icloud.com/ to manually finish setting up your iCloud service (AUTHENTICATION_FAILED)
[448] Failed to execute script 'icloudpd' due to unhandled exception!
2024-09-14 02:14:10 ERROR    ***** Please post the above debug log, along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
ash: out of range
2024-09-14 02:14:10 DEBUG    Web cookie exists
2024-09-14 02:14:10 INFO     Web cookie expires: 2024-11-10 @ 15:34:37
2024-09-14 02:14:10 INFO     Multifactor authentication cookie expires: 2024-10-13 @ 18:10:25
2024-09-14 02:14:10 INFO     Days remaining until expiration: 29
2024-09-14 02:14:11 DEBUG    iCloud login counter = 1
2024-09-14 02:14:11 INFO     Synchronisation ended at 02:14:11
2024-09-14 02:14:11 INFO     Total time taken: 00:00:08
2024-09-14 02:14:11 INFO     Next synchronisation at Sun Sep 15 02:14:03 2024

**Comment by ivlboa** [comment]
i have the same issues

**Comment by boredazfcuk** [comment]
Issue template not used.
