### ISSUE TITLE
Unable to refresh 2FA cookie using keyring in Unraid docker

### ISSUE THREAD

**Issue by haigneyc** [boredazfcuk/docker-icloudpd#66]
With docker running in version 6.9.2 of Unraid server I ran another instance of the docker using the command 

`docker exec -it icloudpd /usr/local/bin/sync-icloud.sh`

Everything starts up correctly, then I'm asked to input a password

```
2021-05-19 11:46:03 INFO     Group, group:1000, already created
2021-05-19 11:46:03 INFO     User, user:1000, already created
2021-05-19 11:46:03 INFO     Correct owner on config directory, if required
2021-05-19 11:46:03 INFO     Correct group on config directory, if required
2021-05-19 11:46:03 INFO     Using password stored in keyring
2021-05-19 11:46:03 INFO     Correct owner on config directory, if required
2021-05-19 11:46:03 INFO     Correct group on config directory, if required
2021-05-19 11:46:03 INFO     Generate 2FA cookie with password: usekeyring
2021-05-19 11:46:03 INFO     Check for new files using password stored in keyring...
iCloud Password: 
```

That fails with the following error

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for email@email.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
```

But the script seems to believe everything worked as expected

`2021-05-19 11:46:12 INFO     Two factor authentication cookie generated. Sync should now be successful.`

After restarting the docker container, as expected, I'm still seeing this error

`2021-05-19 11:50:26 ERROR Cookie does not exist. Please run container interactively to generate - Retry in 5 minutes`

Versions (from log):

```
2021-05-19 11:45:00 INFO ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2021-05-19 11:45:00 INFO ***** /usr/local/bin/sync-icloud.sh script version: 2021/03/22_17:23 *****

2021-05-19 11:45:00 INFO Alpine Linux v3.13
2021-05-19 11:45:00 INFO Python version: 3.8.8
2021-05-19 11:45:00 INFO icloudpd version: 1.7.2
2021-05-19 11:45:04 INFO pyicloud-ipd version: 0.10.1
```

I've attached the entire interactive session log. [icloudpd interactive session log.txt](https://github.com/boredazfcuk/docker-icloudpd/files/6510166/icloudpd.interactive.session.log.txt)

Tangentially related: I just configured a new docker with my wife's apple id/password with the 'usekeyring' option and everything worked flawlessly.

**Comment by boredazfcuk** [comment]
Hi,

Can you upgrade to the latest version and try again?

I think you must have an empty credentials file, so I've changed the code to remove it if detected.

Thanks.

**Comment by haigneyc** [comment]
Looks like that did the trick! Thanks!

**Comment by boredazfcuk** [comment]
Awesome. Thanks for letting me know that it worked.

**Comment by boredazfcuk** [comment]
Oh, you may want to remove the gist, as I noticed it has your e-mail address in it and bots will scrape that and add it to spam lists.
