### ISSUE TITLE
 ERROR    Keyring file does not exist. Please try again

### ISSUE THREAD

**Issue by Jaccyshaw** [boredazfcuk/docker-icloudpd#669]
sync-icloud.sh --Initialise this command let me input the icloud password, there is the following error, I check the previous problem report, still can not solve

Log:
2024-10-17 00:27:14 INFO     ***** boredazfcuk/icloudpd container v1.0.984_15-10-
2024 started *****                                                               
2024-10-17 00:27:14 INFO     ***** For support, please go here: https://github.co
m/boredazfcuk/docker-icloudpd *****                                              
2024-10-17 00:27:14 INFO     Alpine Linux 3.20.3                                 
2024-10-17 00:27:14 INFO     Python version: 3.12.6                              
2024-10-17 00:27:15 INFO     icloud-photos-downloader version: 1.23.4            
2024-10-17 00:27:15 INFO     Checking for updates...                             
2024-10-17 00:27:16 INFO      - Current version is up to date                    
2024-10-17 00:27:16 INFO     Loading configuration from: /config/icloudpd.conf
2024-10-17 00:27:44 INFO     Debug logging: Disabledarting co                    
2024-10-17 00:27:44 INFO     Apple ID:  (hidden)                     
2024-10-17 00:27:44 INFO     Authentication Type: MFA                            
2024-10-17 00:27:44 INFO     Cookie path: /config/ (hidden)            
2024-10-17 00:27:44 INFO     Cookie expiry notification period: 7                
2024-10-17 00:27:44 INFO     Download destination directory: /icloud             
2024-10-17 00:27:44 INFO     Folder structure: {:%Y/%m/%d}                       
2024-10-17 00:27:44 INFO     Keep Unicode: false                                 
2024-10-17 00:27:44 INFO     Live Photo MOV Filename Policy: suffix              
2024-10-17 00:27:44 INFO     File Match Policy: name-size-dedup-with-suffix      
2024-10-17 00:27:44 INFO     Synchronisation interval: 86400                     
2024-10-17 00:27:44 INFO     Synchronisation delay (minutes): 0                  
2024-10-17 00:27:44 INFO     Set EXIF date/time: false                           
2024-10-17 00:27:44 INFO     Auto delete: false                                  
2024-10-17 00:27:44 INFO     Delete after download: false                        
2024-10-17 00:27:44 INFO     Delete empty directories: false                     
2024-10-17 00:27:44 INFO     Photo size: original                                
2024-10-17 00:27:44 INFO     Align RAW: as-is                                    
2024-10-17 00:27:44 INFO     Single pass mode: false                             
2024-10-17 00:27:44 INFO     Skip download check: ture                           
2024-10-17 00:27:44 INFO     Skip live photos: false                             
2024-10-17 00:27:44 INFO     Number of most recently added photos to download: Do
wnload All Photos                                    2024-10-17 00:27:44 INFO     Downloading photos from: Download All Photos        
2024-10-17 00:27:44 INFO     Stop downloading when prexisiting files count is: Do
wnload All Photos                                                                
2024-10-17 00:27:44 INFO     Live photo size: original                           
2024-10-17 00:27:44 INFO     Skip videos: false                                  
2024-10-17 00:27:44 INFO     Convert HEIC to JPEG: false                         
2024-10-17 00:27:44 INFO     Downloading from: icloud.com                        
2024-10-17 00:27:44 INFO     Fake user agent for curl: Disabled                  
2024-10-17 00:27:44 INFO     Authentication domain: com                          
2024-10-17 00:27:44 INFO     Ignore Synology extended attribute directories: Disa
bled                                                                             
2024-10-17 00:27:44 INFO     Container initialisation complete                   
2024-10-17 00:27:44 INFO     Script launch parameters: --initialise              
Running in MAIN                                                                  
Enter iCloud password for (hidden):         
Traceback (most recent call last):                                               
  File "starters/icloud.py", line 5, in <module>                                 
  File "click/core.py", line 1157, in __call__                                   
  File "click/core.py", line 1078, in main                                       
  File "click/core.py", line 1434, in invoke                                     
  File "click/core.py", line 783, in invoke                                      
  File "pyicloud_ipd/cmdline.py", line 81, in main                               
  File "pyicloud_ipd/cmdline.py", line 257, in main_aux                          
  File "pyicloud_ipd/base.py", line 157, in __init__                             
  File "pyicloud_ipd/base.py", line 221, in authenticate                         
  File "pyicloud_ipd/base.py", line 253, in _authenticate_with_token             
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iClou
d.com.cn for your request. Please use --domain parameter                         
[786] Failed to execute script 'icloud' due to unhandled exception!              
2024-10-17 00:30:18 ERROR    Keyring file does not exist. Please try again

**Comment by Jaccyshaw** [comment]
There was another problem. I had set icloud_china and auth_china as ture in the config file, but the download address displayed in the log was still icloud.com instead of icloud.com.cn

Authentication domain: com
Downloading from: icloud.com

**Comment by boredazfcuk** [comment]
`icloud_china and auth_china as ture`

Is that a typo? you mean true?

```
2024-10-17 00:27:44 INFO Debug logging: Disabledarting co
2024-10-17 00:27:44 INFO Apple ID: (hidden)
2024-10-17 00:27:44 INFO Authentication Type: MFA
2024-10-17 00:27:44 INFO Cookie path: /config/ (hidden)
```

This bit is really strange. Ignoring the strange text that's somehow been introduced: "arting co" it tells me that debug logging is disabled, yet the format of `Apple ID: (hidden)` is only displayed when debug logging is enabled.

Also, if `debug_logging=true` was set in the config file, then the bit:
```
2024-10-17 00:27:44 INFO Folder structure: {:%Y/%m/%d}
2024-10-17 00:27:44 INFO Keep Unicode: false
```
should have entries for "Directory permissions:" and "File permissions:" between them.



```
2024-10-17 00:27:44 INFO Skip download check: ture
````
I'm guessing `ture` isn't actually a typo and you need to correct your config file.

**Comment by Jaccyshaw** [comment]
Thank you,issue has been resloved,rookie mistake
