### ISSUE TITLE
Check failed - Exit code: 1, and suspended

### ISSUE THREAD

**Issue by latel** [boredazfcuk/docker-icloudpd#67]
when this error throws, it hang up there, and nothing will happen again.

```
icloudpd    | /home/user/iCloud/2018/05/02/IMG_1938.PNG
icloudpd    | /home/user/iCloud/2018/05/02/IMG_1937.PNG
icloudpd    | /home/user/iCloud/2018/05/02/IMG_1936.PNG
icloudpd    | /home/user/iCloud/2018/05/02/IMG_1935.PNG
icloudpd    | /home/user/iCloud/2018/05/02/IMG_1934.PNG
icloudpd    | /home/user/iCloud/2018/05/02/IMG_1933.PNG
icloudpd    | /home/user/iCloud/2018/05/02/IMG_1932.JPG
icloudpd    | /home/user/iCloud/2018/05/02/IMG_1931.PNG
icloudpd    | /home/user/iCloud/2018/05/01/IMG_1930.PNG
icloudpd    | /home/user/iCloud/2018/05/01/IMG_1929.PNG
icloudpd    | /home/user/iCloud/2018/05/01/IMG_1928.JPG
icloudpd    | /home/user/iCloud/2018/05/01/IMG_1924.JPG
icloudpd    | /home/user/iCloud/2018/05/01/IMG_1919.JPG
icloudpd    | /home/user/iCloud/2018/05/01/IMG_1918.JPG
icloudpd    | /home/user/iCloud/2018/04/30/IMG_1917.PNG
icloudpd    | /home/user/iCloud/2018/04/30/IMG_1916.JPG
icloudpd    | /home/user/iCloud/2018/04/30/IMG_1915.JPG
icloudpd    | /home/user/iCloud/2018/04/30/IMG_1914.PNG
icloudpd    | /home/user/iCloud/2018/04/30/IMG_1913.JPG
icloudpd    | /home/user/iCloud/2018/04/30/IMG_1907.JPG
icloudpd    | Traceback (most recent call last):
icloudpd    |   File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 438, in _error_catcher
icloudpd    |     yield
icloudpd    |   File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 767, in read_chunked
icloudpd    |     chunk = self._handle_chunk(amt)
icloudpd    |   File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 711, in _handle_chunk
icloudpd    |     value = self._fp._safe_read(amt)
icloudpd    |   File "/usr/lib/python3.8/http/client.py", line 611, in _safe_read
icloudpd    |     raise IncompleteRead(data, amt-len(data))
icloudpd    | http.client.IncompleteRead: IncompleteRead(2028 bytes read, 8212 more expected)
icloudpd    |
icloudpd    | During handling of the above exception, another exception occurred:
icloudpd    |
icloudpd    | Traceback (most recent call last):
icloudpd    |   File "/usr/lib/python3.8/site-packages/requests/models.py", line 753, in generate
icloudpd    |     for chunk in self.raw.stream(chunk_size, decode_content=True):
icloudpd    |   File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 572, in stream
icloudpd    |     for line in self.read_chunked(amt, decode_content=decode_content):
icloudpd    |   File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 793, in read_chunked
icloudpd    |     self._original_response.close()
icloudpd    |   File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
icloudpd    |     self.gen.throw(type, value, traceback)
icloudpd    |   File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 455, in _error_catcher
icloudpd    |     raise ProtocolError("Connection broken: %r" % e, e)
icloudpd    | urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(2028 bytes read, 8212 more expected)', IncompleteRead(2028 bytes read, 8212 more expected))
icloudpd    |
icloudpd    | During handling of the above exception, another exception occurred:
icloudpd    |
icloudpd    | Traceback (most recent call last):
icloudpd    |   File "/usr/bin/icloudpd", line 33, in <module>
icloudpd    |     sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
icloudpd    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
icloudpd    |     return self.main(*args, **kwargs)
icloudpd    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
icloudpd    |     rv = self.invoke(ctx)
icloudpd    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
icloudpd    |     return ctx.invoke(self.callback, **ctx.params)
icloudpd    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
icloudpd    |     return callback(*args, **kwargs)
icloudpd    |   File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 561, in main
icloudpd    |     item = next(photos_iterator)
icloudpd    |   File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 295, in photos
icloudpd    |     request = self.photos_request(offset)
icloudpd    |   File "/usr/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 276, in photos_request
icloudpd    |     return self.service.session.post(
icloudpd    |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
icloudpd    |     return self.request('POST', url, data=data, json=json, **kwargs)
icloudpd    |   File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 68, in request
icloudpd    |     response = super(PyiCloudSession, self).request(*args, **kwargs)
icloudpd    |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
icloudpd    |     resp = self.send(prep, **send_kwargs)
icloudpd    |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
icloudpd    |     r.content
icloudpd    |   File "/usr/lib/python3.8/site-packages/requests/models.py", line 831, in content
icloudpd    |     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
icloudpd    |   File "/usr/lib/python3.8/site-packages/requests/models.py", line 756, in generate
icloudpd    |     raise ChunkedEncodingError(e)
icloudpd    | requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(2028 bytes read, 8212 more expected)', IncompleteRead(2028 bytes read, 8212 more expected))
icloudpd    | 2021-05-21 17:00:17 ERROR    Check failed - Exit code: 1
icloudpd    | 2021-05-21 17:00:17 INFO     Web cookie expires: 2021-07-20 @ 02:29:41
icloudpd    | 2021-05-21 17:00:17 INFO     Two factor authentication cookie expires: 2021-08-19 @ 02:29:53
icloudpd    | 2021-05-21 17:00:17 INFO     iCloud login counter = 1
icloudpd    | 2021-05-21 17:00:17 INFO     Next synchronisation at 17:00
```

![image](https://user-images.githubusercontent.com/5621862/119114249-9125e400-ba58-11eb-90e9-51d04dc9eb3b.png)

**Comment by boredazfcuk** [comment]
This looks like your internet connection has been interrupted during a download run.

The script shouldn't just hang, but attempt to download again the following day at 17:00 (assuming you have it set to sync every 24hrs).

An exit code of 1 should put the container into an unhealthy state. You can use this container: https://hub.docker.com/r/willfarrell/autoheal to automatically restart any unhealthy containers.

Does it do this every time you attempt to download? If it does, then it may be an issue with a file you have located in the cloud.

**Comment by boredazfcuk** [comment]
Just closing this off as it appears to be a system issue, rather than a script issue, and I've had no response for over 3 weeks.
