### ISSUE TITLE
Can't Autthenticate

### ISSUE THREAD

**Issue by flaflaflufla** [boredazfcuk/docker-icloudpd#672]
When I complete the Initialise command, I get to where I need to enter my password but I can no longer type anything. Not sure how to proceed....

root@5a2ccd2d9425:/> sync-icloud.sh --Initialise

2024-10-22 23:35:57 INFO     ***** boredazfcuk/icloudpd container v1.0.985_16-10-2024 started *****
2024-10-22 23:35:57 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-10-22 23:35:57 INFO     Alpine Linux 3.20.3
2024-10-22 23:35:57 INFO     Python version: 3.12.6
2024-10-22 23:35:58 INFO     icloud-photos-downloader version: 1.23.4
2024-10-22 23:35:58 INFO     Checking for updates...
2024-10-22 23:35:58 INFO      - Current version is up to date
2024-10-22 23:35:58 INFO     Loading configuration from: /config/icloudpd.conf
2024-10-22 23:36:01 INFO     Debug logging: Disabled
2024-10-22 23:36:01 INFO     Apple ID: *********@icloud:
2024-10-22 23:36:01 INFO     Cookie path: /config/crblack6495gmailcom
2024-10-22 23:36:01 INFO     Cookie expiry notification period: 7
2024-10-22 23:36:01 INFO     Download destination directory: /home/user/iCloud
2024-10-22 23:36:01 INFO     Folder structure: {:%Y/%m/%d}
2024-10-22 23:36:01 INFO     Keep Unicode: false
2024-10-22 23:36:01 INFO     Live Photo MOV Filename Policy: suffix
2024-10-22 23:36:01 INFO     File Match Policy: name-size-dedup-with-suffix
2024-10-22 23:36:01 INFO     Synchronisation interval: 86400
2024-10-22 23:36:01 INFO     Synchronisation delay (minutes): 0
2024-10-22 23:36:01 INFO     Set EXIF date/time: false
2024-10-22 23:36:01 INFO     Auto delete: false
2024-10-22 23:36:01 INFO     Delete after download: false
2024-10-22 23:36:01 INFO     Delete empty directories: false
2024-10-22 23:36:01 INFO     Photo size: original
2024-10-22 23:36:01 INFO     Align RAW: as-is
2024-10-22 23:36:01 INFO     Single pass mode: false
2024-10-22 23:36:01 INFO     Skip download check: false
2024-10-22 23:36:01 INFO     Skip live photos: false
2024-10-22 23:36:01 INFO     Number of most recently added photos to download: Download All Photos
2024-10-22 23:36:01 INFO     Downloading photos from: Download All Photos
2024-10-22 23:36:01 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-10-22 23:36:01 INFO     Live photo size: original
2024-10-22 23:36:01 INFO     Skip videos: false
2024-10-22 23:36:01 INFO     Convert HEIC to JPEG: false
2024-10-22 23:36:01 INFO     Downloading from: icloud.com
2024-10-22 23:36:01 INFO     Fake user agent for curl: Disabled
2024-10-22 23:36:01 INFO     Authentication domain: com
2024-10-22 23:36:01 INFO     Ignore Synology extended attribute directories: Disabled
2024-10-22 23:36:01 INFO     Container initialisation complete
2024-10-22 23:36:01 INFO     Script launch parameters: --Initialise
Running in MAIN
Enter iCloud password for *********@icloud: 
Bad username or password for *********@icloud:
Enter iCloud password for *********@icloud: 
usage: icloud [-h] [--username USERNAME] [--password PASSWORD] [-n] [--delete-from-keyring] [--list] [--llist] [--locate] [--device DEVICE_ID]
              [--sound] [--message MESSAGE] [--silentmessage SILENTMESSAGE] [--lostmode] [--lostphone LOST_PHONE] [--lostpassword LOST_PASSWORD]
              [--lostmessage LOST_MESSAGE] [--outputfile] [--domain DOMAIN]
icloud: error: No password supplied
2024-10-22 23:36:34 ERROR    Keyring file does not exist. Please try again

**Comment by bf13ld5on** [comment]
same exact issue here

**Comment by boredazfcuk** [comment]
Duplicate

**Comment by boredazfcuk** [comment]
My guess you have special characters in your password that interfere with the password capture process.

**Comment by ajkuftic** [comment]
I'm having a similar issue and I have a special character in my password, but I know my password has worked with icloudpd in the past. I confirmed my password works through iCloud.com, so I'm not sure what changed

**Comment by ajkuftic** [comment]
Rolled back to the v980/17-09-2024 image and it works without issue. Haven't tried anything newer.

**Comment by MrEcstaz** [comment]
I have the same problem, the password does not contain special characters, only letters and numbers.

root@icloud_sync:/> sync-icloud.sh --Initialize
2024-11-27 20:36:51 INFO     ***** boredazfcuk/icloudpd container v1.0.1014_24-11-2024 started *****
2024-11-27 20:36:51 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-11-27 20:36:51 INFO     Alpine Linux 3.20.3
2024-11-27 20:36:51 INFO     Python version: 3.12.7
2024-11-27 20:36:52 INFO     icloud-photos-downloader version: 1.24.4
2024-11-27 20:36:52 INFO     Checking for updates...
2024-11-27 20:36:52 INFO      - Current version is up to date
2024-11-27 20:36:52 INFO     Loading configuration from: /config/icloudpd.conf
2024-11-27 20:37:03 INFO     Debug logging: Disabled
2024-11-27 20:37:03 INFO     Apple ID: ***
2024-11-27 20:37:03 INFO     Cookie path: /config/***
2024-11-27 20:37:03 INFO     Cookie expiry notification period: 7
2024-11-27 20:37:03 INFO     Download destination directory: /home/valera/iCloud
2024-11-27 20:37:03 INFO     Folder structure: {:%Y/%m/%d}
2024-11-27 20:37:03 INFO     Keep Unicode: false
2024-11-27 20:37:03 INFO     Live Photo MOV Filename Policy: suffix
2024-11-27 20:37:03 INFO     File Match Policy: name-size-dedup-with-suffix
2024-11-27 20:37:03 INFO     Synchronisation interval: 86400
2024-11-27 20:37:03 INFO     Synchronisation delay (minutes): 0
2024-11-27 20:37:03 INFO     Set EXIF date/time: false
2024-11-27 20:37:03 INFO     Auto delete: false
2024-11-27 20:37:03 INFO     Delete after download: false
2024-11-27 20:37:03 INFO     Delete empty directories: false
2024-11-27 20:37:03 INFO     Photo size: original
2024-11-27 20:37:03 INFO     Align RAW: as-is
2024-11-27 20:37:03 INFO     Single pass mode: false
2024-11-27 20:37:03 INFO     Skip download check: true
2024-11-27 20:37:03 INFO     Skip live photos: false
2024-11-27 20:37:03 INFO     Number of most recently added photos to download: Download All Photos
2024-11-27 20:37:03 INFO     Downloading photos from: Download All Photos
2024-11-27 20:37:03 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-11-27 20:37:03 INFO     Live photo size: original
2024-11-27 20:37:03 INFO     Skip videos: false
2024-11-27 20:37:03 INFO     Convert HEIC to JPEG: true
2024-11-27 20:37:03 INFO     Telegram notifications enabled
2024-11-27 20:37:03 INFO     Telegram token: ***
2024-11-27 20:37:03 INFO     Telegram chat id: ***
2024-11-27 20:37:03 INFO     Telegram polling: true
2024-11-27 20:37:03 INFO     Telegram uses HTTP: 
2024-11-27 20:37:03 INFO     Telegram base URL: ***
2024-11-27 20:37:03 INFO     Telegram notification URL: ***
2024-11-27 20:37:03 INFO     Sending Telegram startup notification
2024-11-27 20:37:03 INFO     Downloading from: icloud.com
2024-11-27 20:37:03 INFO     Fake user agent for curl: Disabled
2024-11-27 20:37:03 INFO     Authentication domain: com
2024-11-27 20:37:03 INFO     Ignore Synology extended attribute directories: Disabled
2024-11-27 20:37:03 INFO     Container initialisation complete
2024-11-27 20:37:03 INFO     Script launch parameters: --Initialize
Running in MAIN
Enter iCloud password for ***: 
Bad username or password for ***
Enter iCloud password for ***: 
Bad username or password for ***
Enter iCloud password for ***: 
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 270, in authenticate
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: {
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
} (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyicloud_ipd/cmdline.py", line 258, in main_aux
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 280, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloud.py", line 5, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "pyicloud_ipd/cmdline.py", line 82, in main
  File "pyicloud_ipd/cmdline.py", line 337, in main_aux
RuntimeError: Bad username or password for ***
[568] Failed to execute script 'icloud' due to unhandled exception!
2024-11-27 20:39:21 ERROR    Keyring file does not exist. Please try again
root@icloud_sync:/>

**Comment by RICwang** [comment]
Bad username or password for ***

I also encountered this situation.

**Comment by quadratmuede** [comment]
I have encountered the same problem. Using the same password I can log into icloud website, but got the "bad username or password" in docker. My password contains special characters.

**Comment by boredazfcuk** [comment]
Apple changed the authentication process a while back. It means that anyone who hasn't changed their password for a long time can't authenticate. It's possible it could be that as many people have resolved similar issues by resetting their icloud password.

**Comment by MrEcstaz** [comment]
I changed my Apple password, but it didn't help - the error still appears. Note that I don't enter any passwords - I just run the initialization and immediately get the error.

If the problem was in the changed authentication mechanisms of Apple, then in this situation, rolling back to the old version of the application would not have any effect.

root@icloud_sync:/> sync-icloud.sh --Initialize
2024-12-31 20:28:07 INFO     ***** boredazfcuk/icloudpd container v1.0.1070_29-12-2024 started *****
2024-12-31 20:28:07 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-12-31 20:28:07 INFO     Alpine Linux 3.21.0
2024-12-31 20:28:07 INFO     Python version: 3.12.7
2024-12-31 20:28:08 INFO     icloud-photos-downloader version: 1.25.0
2024-12-31 20:28:08 INFO     Checking for updates...
2024-12-31 20:28:09 INFO      - Current version is up to date
2024-12-31 20:28:09 INFO     Loading configuration from: /config/icloudpd.conf
2024-12-31 20:28:19 INFO     Debug logging: Disabled
2024-12-31 20:28:19 INFO     Apple ID: _"it contains my apple_id email"_
2024-12-31 20:28:19 INFO     Cookie path: /config/valerareshetnikovru
2024-12-31 20:28:19 INFO     Cookie expiry notification period: 7
2024-12-31 20:28:19 INFO     Download destination directory: /home/valera/iCloud
2024-12-31 20:28:19 INFO     Folder structure: {:%Y/%m/%d}
2024-12-31 20:28:19 INFO     Keep Unicode: false
2024-12-31 20:28:19 INFO     Live Photo MOV Filename Policy: suffix
2024-12-31 20:28:19 INFO     File Match Policy: name-size-dedup-with-suffix
2024-12-31 20:28:19 INFO     Synchronisation interval: 43200
2024-12-31 20:28:19 INFO     Synchronisation delay (minutes): 0
2024-12-31 20:28:19 INFO     Set EXIF date/time: false
2024-12-31 20:28:19 INFO     Auto delete: false
2024-12-31 20:28:19 INFO     Delete after download: false
2024-12-31 20:28:19 INFO     Delete empty directories: false
2024-12-31 20:28:19 INFO     Photo size: original
2024-12-31 20:28:19 INFO     Align RAW: as-is
2024-12-31 20:28:19 INFO     Single pass mode: false
2024-12-31 20:28:19 INFO     Skip download check: true
2024-12-31 20:28:19 INFO     Skip live photos: false
2024-12-31 20:28:19 INFO     Number of most recently added photos to download: Download All Photos
2024-12-31 20:28:19 INFO     Downloading photos from: Download All Photos
2024-12-31 20:28:19 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-12-31 20:28:19 INFO     Live photo size: original
2024-12-31 20:28:19 INFO     Skip videos: false
2024-12-31 20:28:19 INFO     Convert HEIC to JPEG: true
2024-12-31 20:28:19 INFO     Downloading from: icloud.com
2024-12-31 20:28:19 INFO     Fake user agent for curl: Disabled
2024-12-31 20:28:19 INFO     Authentication domain: com
2024-12-31 20:28:19 INFO     Ignore Synology extended attribute directories: Disabled
2024-12-31 20:28:19 INFO     Container initialisation complete
2024-12-31 20:28:19 INFO     Script launch parameters: --Initialise
2024-12-31 20:28:19 INFO     Directory is writable: /config/python_keyring/
2024-12-31 20:28:19 INFO     Starting container initialisation
2024-12-31 20:28:20 DEBUG    Authenticating...
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 278, in authenticate
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: {
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
} (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 753, in main
  File "icloudpd/base.py", line 1196, in core
  File "icloudpd/authentication.py", line 53, in authenticate_
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 281, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[586] Failed to execute script 'icloudpd' due to unhandled exception!
2024-12-31 20:28:22 INFO     Container initialisation complete

**Comment by MrEcstaz** [comment]
**UPDATE**: After I deleted all the files in the /config folder, I ran the initialization again and entered the password + 2fa - the initialization was successful.

However, it is still unclear why old versions of the container continue to work with the old keychain.

**Comment by boredazfcuk** [comment]
Closing as issue appears to have been resolved by re-authenticating after removing keyring
