### ISSUE TITLE
'Service Temporarily Unavailable (503)'

### ISSUE THREAD

**Issue by makhlouta** [boredazfcuk/docker-icloudpd#675]
**Describe the bug**
It doesn't work anymore for both containers/accounts that I have. I tried to initialize and reauth, both are showing the same issue. I don't receive a notification for OTP. iCloud web is working fine.

**System (The following information must be entered or the issue will be closed):**
 - OS: Debian Bookworm
 - Version latest docker container

**Debug log file**
`2024-10-28 10:20:18 DEBUG    Generate MFA cookie using password stored in keyring file
2024-10-28 10:20:19 ERROR    Authentication required for Account. (421)
2024-10-28 10:20:20 ERROR    Service Temporarily Unavailable (503)
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 357, in authenticate
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 134, in request
  File "pyicloud_ipd/base.py", line 207, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Service Temporarily Unavailable (503)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 760, in core
  File "icloudpd/authentication.py", line 31, in authenticate_
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 365, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('Service Temporarily Unavailable (503)'))
[508] Failed to execute script 'icloudpd' due to unhandled exception!
2024-10-28 10:20:20 ERROR    Multifactor authentication information missing from cookie. Authentication has failed
2024-10-28 10:20:20 ERROR     - Was the correct password entered?
2024-10-28 10:20:20 ERROR     - Was the multifactor authentication code mistyped?
2024-10-28 10:20:20 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-10-28 10:20:20 INFO     Container initialisation complete
michel@DockerVM:~$ docker exec -it icloudpd-michel reauth.sh
2024-10-28 10:21:04 DEBUG    Authenticating...
2024-10-28 10:21:04 ERROR    Service Temporarily Unavailable (503)
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 357, in authenticate
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 134, in request
  File "pyicloud_ipd/base.py", line 207, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Service Temporarily Unavailable (503)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 760, in core
  File "icloudpd/authentication.py", line 31, in authenticate_
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 365, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('Service Temporarily Unavailable (503)'))
[544] Failed to execute script 'icloudpd' due to unhandled exception!
michel@DockerVM:~$ docker exec -it icloudpd-michel reauth.sh
2024-10-28 10:22:36 DEBUG    Authenticating...
2024-10-28 10:22:37 ERROR    Service Temporarily Unavailable (503)
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 357, in authenticate
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 134, in request
  File "pyicloud_ipd/base.py", line 207, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Service Temporarily Unavailable (503)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 760, in core
  File "icloudpd/authentication.py", line 31, in authenticate_
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 365, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('Service Temporarily Unavailable (503)'))
[598] Failed to execute script 'icloudpd' due to unhandled exception!
`

**Comment by boredazfcuk** [comment]
This can be resolved with a password change. Maybe not the first password change, but a password change.

It seems that there may be an upstream but regarding storing passwords that results in a 1 in 10, or maybe 1 in 16 chance of it not processing passwords correctly. Changing your password may get you going again.
