### ISSUE TITLE
Authentication error - Invalid email/password combination

### ISSUE THREAD

**Issue by docwisdom** [boredazfcuk/docker-icloudpd#676]
**Describe the bug**
I have had this container running just fine for a couple years. I found it stopped today so I assumed I just needed to enter my 2FA agin. When I ran the initialise command, I received an authentication error. Nothing has changed regarding the Apple credentials and I can access iCloud via the web just fine. See log output.

**Expected behaviour**
Request 2FA code

**Actual behaviour**
Receive authentication error 

**System (The following information must be entered or the issue will be closed):**
 - Docker on Unraid 6.12.13
 - Alpine Linux 3.20.3
 - icloud-photos-downloader version: 1.24.1

**Debug log file**
root@7de2300131c4:/> sync-icloud.sh --Initialise

2024-10-28 15:29:18 INFO     ***** boredazfcuk/icloudpd container v1.0.989_28-10-2024 started *****
2024-10-28 15:29:18 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-10-28 15:29:18 INFO     Alpine Linux 3.20.3
2024-10-28 15:29:18 INFO     Python version: 3.12.7
2024-10-28 15:29:20 INFO     icloud-photos-downloader version: 1.24.1
2024-10-28 15:29:20 INFO     Checking for updates...
2024-10-28 15:29:20 INFO      - Current version is up to date
2024-10-28 15:29:20 INFO     Loading configuration from: /config/icloudpd.conf
2024-10-28 15:29:21 INFO     Debug logging: Disabled
2024-10-28 15:29:21 INFO     Apple ID: fl----@gmail.com
2024-10-28 15:29:21 INFO     Cookie path: /config/fl----gmailcom
2024-10-28 15:29:21 INFO     Cookie expiry notification period: 7
2024-10-28 15:29:21 INFO     Download destination directory: /home/user/iCloud
2024-10-28 15:29:21 INFO     Folder structure: {:%Y/%m/%d}
2024-10-28 15:29:21 INFO     Keep Unicode: false
2024-10-28 15:29:21 INFO     Live Photo MOV Filename Policy: suffix
2024-10-28 15:29:21 INFO     File Match Policy: name-size-dedup-with-suffix
2024-10-28 15:29:21 INFO     Synchronisation interval: 86400
2024-10-28 15:29:21 INFO     Synchronisation delay (minutes): 0
2024-10-28 15:29:21 INFO     Set EXIF date/time: false
2024-10-28 15:29:21 INFO     Auto delete: false
2024-10-28 15:29:21 INFO     Delete after download: false
2024-10-28 15:29:21 INFO     Delete empty directories: false
2024-10-28 15:29:21 INFO     Photo size: original
2024-10-28 15:29:21 INFO     Align RAW: as-is
2024-10-28 15:29:21 INFO     Single pass mode: false
2024-10-28 15:29:21 INFO     Skip download check: false
2024-10-28 15:29:21 INFO     Skip live photos: false
2024-10-28 15:29:21 INFO     Number of most recently added photos to download: Download All Photos
2024-10-28 15:29:21 INFO     Downloading photos from: Download All Photos
2024-10-28 15:29:21 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-10-28 15:29:21 INFO     Live photo size: original
2024-10-28 15:29:21 INFO     Skip videos: false
2024-10-28 15:29:21 INFO     Convert HEIC to JPEG: false
2024-10-28 15:29:21 INFO     Downloading from: icloud.com
2024-10-28 15:29:21 INFO     Fake user agent for curl: Disabled
2024-10-28 15:29:21 INFO     Authentication domain: com
2024-10-28 15:29:21 INFO     Ignore Synology extended attribute directories: Disabled
2024-10-28 15:29:21 INFO     Container initialisation complete
2024-10-28 15:29:21 INFO     Script launch parameters: --Initialise
2024-10-28 15:29:21 INFO     Directory is writable: /config/python_keyring/
2024-10-28 15:29:21 INFO     Starting container initialisation
2024-10-28 15:29:23 DEBUG    Authenticating...
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 270, in authenticate
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: {
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
} (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1183, in core
  File "icloudpd/authentication.py", line 53, in authenticate_
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 280, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[785] Failed to execute script 'icloudpd' due to unhandled exception!
2024-10-28 15:29:24 ERROR    Multifactor authentication information missing from cookie. Authentication has failed
2024-10-28 15:29:24 ERROR     - Was the correct password entered?
2024-10-28 15:29:24 ERROR     - Was the multifactor authentication code mistyped?
2024-10-28 15:29:24 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-10-28 15:29:24 INFO     Container initialisation complete
root@7de2300131c4:/>

**Comment by alientim** [comment]
i can confirm same for me but with appleid in config

**Comment by NLZ** [comment]
As others said it in #670 resetting your password works

**Comment by dherzhau** [comment]
Is there any solution to this problem? In my case changing the password and deleting and reinstalling the icloud service does not help.

File "/usr/local/lib/python3.13/site-packages/pyicloud/services/findmyiphone.py", line 64, in refresh_client_with_reauth
    self._refresh_client(locate=True)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/services/findmyiphone.py", line 132, in _refresh_client
    req: Response = self.session.post(
                    ~~~~~~~~~~~~~~~~~^
        url=self._fmip_refresh_url if self._server_ctx else self._fmip_init_url,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        params=self.params,
        ^^^^^^^^^^^^^^^^^^^
        json=req_json,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 147, in request
    return self._request(
           ~~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<14 lines>...
        json=json,
        ^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 201, in _request
    return self._handle_request_error(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        status_code=status_code,
        ^^^^^^^^^^^^^^^^^^^^^^^^
        response=response,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 239, in _handle_request_error
    raise PyiCloudAuthRequiredException(
    ...<2 lines>...
    )
pyicloud.exceptions.PyiCloudAuthRequiredException: Re-authentication required for account: xxxx@yyyy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyicloud/base.py", line 373, in _authenticate_with_token
    resp: Response = self.session.post(
                     ~~~~~~~~~~~~~~~~~^
        f"{self._setup_endpoint}/accountLogin", json=login_data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 147, in request
    return self._request(
           ~~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<14 lines>...
        json=json,
        ^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 201, in _request
    return self._handle_request_error(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        status_code=status_code,
        ^^^^^^^^^^^^^^^^^^^^^^^^
        response=response,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 244, in _handle_request_error
    self._raise_error(status_code, response.reason)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 296, in _raise_error
    raise PyiCloudAPIResponseException(reason, code)
pyicloud.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (421)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyicloud/base.py", line 278, in _authenticate
    self._authenticate_with_token()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/base.py", line 386, in _authenticate_with_token
    raise PyiCloudFailedLoginException(msg, error) from error
pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Authentication required for Account. (421)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyicloud/base.py", line 345, in _srp_authentication
    self.session.post(
    ~~~~~~~~~~~~~~~~~^
        f"{self._auth_endpoint}/signin/complete",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        headers=headers,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 147, in request
    return self._request(
           ~~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<14 lines>...
        json=json,
        ^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 201, in _request
    return self._handle_request_error(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        status_code=status_code,
        ^^^^^^^^^^^^^^^^^^^^^^^^
        response=response,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 244, in _handle_request_error
    self._raise_error(status_code, response.reason)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/session.py", line 296, in _raise_error
    raise PyiCloudAPIResponseException(reason, code)
pyicloud.exceptions.PyiCloudAPIResponseException:  (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/icloud/__init__.py", line 61, in async_setup_entry
    await hass.async_add_executor_job(account.setup)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/icloud/account.py", line 130, in setup
    user_info = self.api.devices.user_info
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/base.py", line 752, in devices
    self._devices = FindMyiPhoneServiceManager(
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        service_root=service_root,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        with_family=self._with_family,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/services/findmyiphone.py", line 55, in __init__
    self.refresh_client_with_reauth()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/services/findmyiphone.py", line 71, in refresh_client_with_reauth
    self.session.service.authenticate(force_refresh=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/base.py", line 220, in authenticate
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/base.py", line 282, in _authenticate
    self._srp_authentication(headers)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyicloud/base.py", line 358, in _srp_authentication
    raise PyiCloudFailedLoginException(msg) from error
pyicloud.exceptions.PyiCloudFailedLoginException: Invalid email/password combination.

**Comment by Lyrebird-BBS** [comment]
I encountered the same problem. I have done the following to resolve it:
1. change the passwords for apple id at iapple website. 
2. remove the keyring file under your docker's sub folder python_keyring
3. re-initialise

**Comment by raintiliang** [comment]
I still met the bug now , just rechange the passwords for apple id at apple phone. the way invalid.
