### ISSUE TITLE
Unknown ItemType?

### ISSUE THREAD

**Issue by johnny2678** [boredazfcuk/docker-icloudpd#684]
**Describe the bug**
I've been running the container successfully for a few different iCloud accounts in my house for months now.  Over the weekend, after the re-auth issue was fixed upstream, all containers started running again, except for one of them.  It keeps giving a `Unknown ItemType` error and failing.  The logs below specifically state to post the issue here so that what i'm doing 😁

In the error output below, it asks if I can log into iCloud.  The answer is yes, I can successfully log into icloud.com using the same creds the container is using.

Happy to provide any other information necessary to troubleshoot. Thanks for looking into it.

**Expected behaviour**
Container completes sync as expected

**Actual behaviour**
Container repeatedly errors out with the error below

**System (The following information must be entered or the issue will be closed):**
- OS: Unraid 6.latest

**Debug log file**
```
2024-11-01 04:26:14 DEBUG    /home/user/iCloud/2021/07/11/IMG_7884-205632.JPG already exists
2024-11-01 04:26:14 DEBUG    /home/user/iCloud/2021/07/11/IMG_7883-660453.JPG deduplicated
2024-11-01 04:26:14 DEBUG    /home/user/iCloud/2021/07/11/IMG_7883-660453.JPG already exists
2024-11-01 04:26:14 DEBUG    /home/user/iCloud/2021/07/11/IMG_7883.JPG already exists
2024-11-01 04:26:14 DEBUG    /home/user/iCloud/2021/07/11/IMG_7882.JPG already exists
2024-11-01 04:26:14 DEBUG    /home/user/iCloud/2021/07/11/IMG_7882.JPG already exists
2024-11-01 04:26:14 ERROR    Failed to download new files
2024-11-01 04:26:14 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-11-01 04:26:14 ERROR    Error debugging info:
2024-11-01 04:26:14 ERROR    Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1344, in core
  File "icloudpd/base.py", line 860, in download_photo_
  File "pyicloud_ipd/services/photos.py", line 734, in versions
  File "pyicloud_ipd/services/photos.py", line 711, in item_type
ValueError: Unknown ItemType
[12346] Failed to execute script 'icloudpd' due to unhandled exception!
2024-11-01 04:26:14 ERROR    ***** Please post the above debug log, along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024-11-01 04:26:14 INFO     Sending Pushover failure notification
2024-11-01 04:26:15 DEBUG    Pushover failure notification sent successfully
2024-11-01 04:26:15 DEBUG    Web cookie exists
2024-11-01 04:26:15 INFO     Web cookie expires: 2024-12-28 @ 20:13:08
2024-11-01 04:26:15 INFO     Multifactor authentication cookie expires: 2024-11-28 @ 20:13:08
2024-11-01 04:26:15 INFO     Days remaining until expiration: 27
2024-11-01 04:26:15 DEBUG    iCloud login counter = 3
2024-11-01 04:26:15 INFO     Synchronisation ended at 04:26:15
2024-11-01 04:26:15 INFO     Total time taken: 00:13:11
2024-11-01 04:26:15 INFO     Next synchronisation at 16:13:04
```

**Comment by johnny2678** [comment]
sorry, this looks to be the same as #680 .  I will close this as a dupe/

**Comment by johnny2678** [comment]
dupe of 680
