### ISSUE TITLE
Issue downloading new files

### ISSUE THREAD

**Issue by Tiger770** [boredazfcuk/docker-icloudpd#685]
I've got an issue with my container not pulling any file after a certain point.  At first it was bombing out with Unknown ItemType after the IMG_1105.jpg file, but I was able to skip the check and download files by setting SKIP CHECK to True.  While it was able to download after setting skip check, it still seems to be failing at this point.  Any suggestions on how to correct this would be appreciated.  Thank you!

2024-11-01 12:34:59 DEBUG    /home/user/iCloud/2018/08/17/IMG_1117.JPG already exists
2024-11-01 12:34:59 DEBUG    /home/user/iCloud/2018/08/17/IMG_1116.JPG already exists
2024-11-01 12:34:59 DEBUG    /home/user/iCloud/2018/08/17/IMG_1115.JPG already exists
2024-11-01 12:34:59 DEBUG    /home/user/iCloud/2018/08/16/2AE12715-8646-49EC-BBD6-4DCA49692429.JPG already exists
2024-11-01 12:34:59 DEBUG    /home/user/iCloud/2018/08/15/IMG_1108.JPG already exists
2024-11-01 12:34:59 DEBUG    /home/user/iCloud/2018/08/13/IMG_1105.JPG already exists
2024-11-01 12:35:00 ERROR    Failed to download new files
2024-11-01 12:35:00 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-11-01 12:35:00 ERROR    Error debugging info:
2024-11-01 12:35:00 ERROR    Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1344, in core
  File "icloudpd/base.py", line 860, in download_photo_
  File "pyicloud_ipd/services/photos.py", line 734, in versions
  File "pyicloud_ipd/services/photos.py", line 711, in item_type
ValueError: Unknown ItemType
[14694] Failed to execute script 'icloudpd' due to unhandled exception!
2024-11-01 12:35:00 ERROR    ***** Please post the above debug log, along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024-11-01 12:35:00 DEBUG    Web cookie exists
2024-11-01 12:35:00 INFO     Web cookie expires: 2024-12-30 @ 16:25:10
2024-11-01 12:35:00 INFO     Multifactor authentication cookie expires: 2024-11-30 @ 16:25:23
2024-11-01 12:35:00 INFO     Days remaining until expiration: 29
2024-11-01 12:35:00 DEBUG    iCloud login counter = 2
2024-11-01 12:35:00 INFO     Synchronisation ended at 12:35:00
2024-11-01 12:35:00 INFO     Total time taken: 00:05:35
2024-11-01 12:35:00 INFO     Next synchronisation at Sat Nov  2 12:29:25 2024

**Comment by AndreyNikiforov** [comment]
same as #680 ?

**Comment by Tiger770** [comment]
Closing issue, duplicate of #680 and fixed with the release of [icloudpd 1.24.3](https://github.com/icloud-photos-downloader/icloud_photos_downloader/releases/tag/v1.24.3)

**Comment by Tiger770** [comment]
Closing issue.  Duplicate of issue #680 and resolved with the update to [icloudpd 1.24.3](https://github.com/icloud-photos-downloader/icloud_photos_downloader/releases/tag/v1.24.3)****
