### ISSUE TITLE
Authentication error listing files before sync, but auth works

### ISSUE THREAD

**Issue by saghul** [boredazfcuk/docker-icloudpd#687]
**Describe the bug**

I'm getting an auth exception when the container starts and lists the files, but auth works since some files are listed.

**Expected behaviour**

No error.

**Actual behaviour**

```
2024-11-04 14:09:50 INFO     ***** boredazfcuk/icloudpd container v1.0.993_03-11-2024 started *****
2024-11-04 14:09:50 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-11-04 14:09:50 INFO     Alpine Linux 3.20.3
2024-11-04 14:09:50 INFO     Python version: 3.12.7
2024-11-04 14:09:51 INFO     icloud-photos-downloader version: 1.24.3
2024-11-04 14:09:51 INFO     Checking for updates...
2024-11-04 14:09:51 INFO      - Current version is up to date
2024-11-04 14:09:51 INFO     Loading configuration from: /config/icloudpd.conf
2024-11-04 14:10:15 INFO     Debug logging: Disabled
2024-11-04 14:10:15 INFO     Apple ID: saghul@gmail.com
2024-11-04 14:10:15 INFO     Cookie path: /config/saghulgmailcom
2024-11-04 14:10:15 INFO     Cookie expiry notification period: 7
2024-11-04 14:10:15 INFO     Download destination directory: /home/user/iCloud
2024-11-04 14:10:15 INFO     Folder structure: {:%Y/%m}
2024-11-04 14:10:15 INFO     Keep Unicode: false
2024-11-04 14:10:15 INFO     Live Photo MOV Filename Policy: suffix
2024-11-04 14:10:15 INFO     File Match Policy: name-size-dedup-with-suffix
2024-11-04 14:10:15 INFO     Synchronisation interval: 86400
2024-11-04 14:10:15 INFO     Synchronisation delay (minutes): 0
2024-11-04 14:10:15 INFO     Set EXIF date/time: false
2024-11-04 14:10:15 INFO     Auto delete: false
2024-11-04 14:10:15 INFO     Delete after download: false
2024-11-04 14:10:15 INFO     Delete empty directories: false
2024-11-04 14:10:15 INFO     Photo size: original
2024-11-04 14:10:15 INFO     Align RAW: as-is
2024-11-04 14:10:15 INFO     Single pass mode: false
2024-11-04 14:10:15 INFO     Skip download check: false
2024-11-04 14:10:15 INFO     Skip live photos: false
2024-11-04 14:10:15 INFO     Number of most recently added photos to download: Download All Photos
2024-11-04 14:10:15 INFO     Downloading photos from: Download All Photos
2024-11-04 14:10:15 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-11-04 14:10:15 INFO     Live photo size: original
2024-11-04 14:10:15 INFO     Skip videos: false
2024-11-04 14:10:15 INFO     Convert HEIC to JPEG: false
2024-11-04 14:10:15 INFO     Pushover notifications enabled
2024-11-04 14:10:15 INFO     Pushover user: udtnhxesnqejj16mts7xv5hktifut1
2024-11-04 14:10:15 INFO     Pushover token: are9jncri99trmj3i8j7aqcw8ix7u4
2024-11-04 14:10:15 INFO     Sending Pushover startup notification
2024-11-04 14:10:16 INFO     Downloading from: icloud.com
2024-11-04 14:10:16 INFO     Fake user agent for curl: Disabled
2024-11-04 14:10:16 INFO     Authentication domain: com
2024-11-04 14:10:16 INFO     Ignore Synology extended attribute directories: Disabled
2024-11-04 14:10:16 INFO     Container initialisation complete
2024-11-04 14:10:16 INFO     Directory is writable: /config/python_keyring/
2024-11-04 14:10:16 INFO     Check download directory mounted correctly...
2024-11-04 14:10:16 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2024-11-04 14:10:16 INFO     Directory is writable: /config/python_keyring/
2024-11-04 14:10:16 INFO     Keyring file exists, continuing
2024-11-04 14:10:16 INFO     Sync user: user
2024-11-04 14:10:16 INFO     Synchronisation starting at 14:10:16
2024-11-04 14:10:16 INFO     Keyring file exists, continuing
2024-11-04 14:10:16 INFO     Check download directory mounted correctly...
2024-11-04 14:10:16 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2024-11-04 14:10:16 INFO     Check for new files using password stored in keyring file
2024-11-04 14:10:16 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
/home/user/iCloud/2024/11/IMG_1642.HEIC
[snip, a bunch of files are listed here]
2024-11-04 14:11:57 ERROR    Authentication required for Account. (421)
2024-11-04 14:11:58 ERROR    Authentication required for Account. (421)
2024-11-04 14:11:58 ERROR    Authentication required for Account. (421)
2024-11-04 14:11:58 ERROR    Authentication required for Account. (421)
2024-11-04 14:11:59 ERROR    Authentication required for Account. (421)
2024-11-04 14:11:59 ERROR    Authentication required for Account. (421)
2024-11-04 14:11:59 ERROR    Failed check for new files files
2024-11-04 14:11:59 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-11-04 14:11:59 ERROR    Error debugging info:
2024-11-04 14:11:59 ERROR    Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1343, in core
  File "pyicloud_ipd/services/photos.py", line 387, in photos
  File "pyicloud_ipd/services/photos.py", line 367, in photos_request
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/session.py", line 120, in request
  File "pyicloud_ipd/session.py", line 122, in request
  File "pyicloud_ipd/session.py", line 196, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (421)
[435] Failed to execute script 'icloudpd' due to unhandled exception!
2024-11-04 14:11:59 ERROR    Please set debug_logging=true in your icloudpd.conf file then reproduce the error
2024-11-04 14:11:59 ERROR    ***** Once you have captured this log file, please post it along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024-11-04 14:11:59 INFO     Sending Pushover failure notification
ash: out of range
2024-11-04 14:12:00 INFO     Web cookie expires: 2024-12-25 @ 21:34:04
2024-11-04 14:12:00 INFO     Multifactor authentication cookie expires: 2024-12-04 @ 02:27:43
2024-11-04 14:12:00 INFO     Days remaining until expiration: 29
2024-11-04 14:12:00 INFO     Synchronisation ended at 14:12:00
2024-11-04 14:12:00 INFO     Total time taken: 00:01:44
2024-11-04 14:12:00 INFO     Next synchronisation at Tue Nov  5 14:10:16 2024
```

**System (The following information must be entered or the issue will be closed):**
 - OS:  unRAID
 - Version: 6.11

**Debug log file**
Please add a the output of a debug log file which shows the error and all configured variables. You will need to set **debug_log=true** in your /config/icloudpd.conf file and re-generate a log file. Please feel free to remove all of the irrelevant lines, such as the filenames of the downloaded files and anything that contains personally identifiable information.

**Comment by boredazfcuk** [comment]
Try setting *skip_check=true* in your icloudpd.conf file.

**Comment by saghul** [comment]
I'll give it a try, thanks!

**Comment by saghul** [comment]
That worked! 🎉

**Comment by saghul** [comment]
Spoke too soon I guess. It did run for a couple of days, but I now get this:

```
[long list of file here]
2024-12-02 16:34:12 DEBUG    /home/user/iCloud/2023/11/IMG_8885.HEIC already exists
2024-12-02 16:34:13 ERROR    Authentication required for Account. (421)
2024-12-02 16:34:13 ERROR    Authentication required for Account. (421)
2024-12-02 16:34:14 ERROR    Authentication required for Account. (421)
2024-12-02 16:34:14 ERROR    Authentication required for Account. (421)
2024-12-02 16:34:14 ERROR    Authentication required for Account. (421)
2024-12-02 16:34:15 ERROR    Authentication required for Account. (421)
2024-12-02 16:34:15 ERROR    Failed to download new files
2024-12-02 16:34:15 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-12-02 16:34:15 ERROR    Error debugging info:
2024-12-02 16:34:15 ERROR    Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1343, in core
  File "pyicloud_ipd/services/photos.py", line 387, in photos
  File "pyicloud_ipd/services/photos.py", line 367, in photos_request
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/session.py", line 120, in request
  File "pyicloud_ipd/session.py", line 122, in request
  File "pyicloud_ipd/session.py", line 196, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (421)
[471] Failed to execute script 'icloudpd' due to unhandled exception!
2024-12-02 16:34:15 ERROR    ***** Please post the above debug log, along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024-12-02 16:34:15 INFO     Sending Pushover failure notification
2024-12-02 16:34:15 DEBUG    Pushover failure notification sent successfully
2024-12-02 16:34:15 DEBUG    Web cookie exists
2024-12-02 16:34:15 INFO     Web cookie expires: 2025-01-29 @ 08:49:01
2024-12-02 16:34:15 INFO     Multifactor authentication cookie expires: 2024-12-30 @ 08:49:16
2024-12-02 16:34:15 INFO     Days remaining until expiration: 27
2024-12-02 16:34:15 DEBUG    iCloud login counter = 1
2024-12-02 16:34:15 INFO     Synchronisation ended at 16:34:15
2024-12-02 16:34:15 INFO     Total time taken: 00:01:26
2024-12-02 16:34:15 INFO     Next synchronisation at Tue Dec  3 16:32:49 2024
```

I recently refreshed auth, but is started to fail before that.

**Comment by boredazfcuk** [comment]
>pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (421)

I believe that this is due to a password issue and a new authentication method introduced by Apple. Changing the Apple ID password resolved it for most people.

**Comment by saghul** [comment]
I'll give that a try, thanks!
