### ISSUE TITLE
Unable to "sync-icloud.sh --Initialise" due to Bad username or password error

### ISSUE THREAD

**Issue by syl779** [boredazfcuk/docker-icloudpd#699]
**Describe the bug**
I have 3 instances of icloudpd for three people and have been using it for over a year now, thanks.

My MFA has expired as it does every month and the cookie needs recreating.

Two accounts have worked fine. One of them is failing to reauthorise despite login for that account via the icloud website working fine (so the password is OK). The other two accounts don't even ask for the password, just the 6 digit MFA code.

EDIT - It first failed with the same error messages without asking for the password, then it asked for password manually when I deleted the keyring_pass.cfg file but still gives an error. See very bottom of this page.

**I have checked the password on icloud.com and on my apple account.**

**Expected behaviour**
Get asked for MFA and enter code from phone

**Actual behaviour**

Get asked for account password
Refuses with bad username / password

I can login to icloud account via the web page using that account and password

**System (The following information must be entered or the issue will be closed):**
 - OS: Ubuntu 22.04.5 LTS
 - Version: 22.04.5 LTS
 Using Docker version 27.3.1, build ce12230

**Debug log file**
:/> sync-icloud.sh --Initialise
2024-11-15 12:30:28 INFO     ***** boredazfcuk/icloudpd container v1.0.1005_11-11-2024 started *****
2024-11-15 12:30:28 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-11-15 12:30:28 INFO     Alpine Linux 3.20.3
2024-11-15 12:30:28 INFO     Python version: 3.12.7
2024-11-15 12:30:29 INFO     icloud-photos-downloader version: 1.24.3
2024-11-15 12:30:29 INFO     Checking for updates...
2024-11-15 12:30:29 INFO      - Current version is up to date
2024-11-15 12:30:29 INFO     Loading configuration from: /config/icloudpd.conf
2024-11-15 12:30:29 DEBUG    Running user id: 0
2024-11-15 12:30:29 DEBUG    Running group id: 0
2024-11-15 12:30:29 DEBUG    Local user: sxxxxx:1027
2024-11-15 12:30:29 DEBUG    Local group: users:100
2024-11-15 12:30:29 DEBUG    Force GID: false
2024-11-15 12:30:29 DEBUG    LAN IP Address: 127.0.0.1
2024-11-15 12:30:29 DEBUG    Default gateway: 192.168.61.1
2024-11-15 12:30:29 DEBUG    DNS server: 192.168.61.1
192.168.61.1
2024-11-15 12:30:29 DEBUG    IP address for icloud.com: 17.253.144.10
2024-11-15 12:30:29 DEBUG    Route check to icloud.com successful
2024-11-15 12:30:29 INFO     Debug logging: Enabled
2024-11-15 12:30:29 INFO     Apple ID: (hidden)
2024-11-15 12:30:29 INFO     Cookie path: /config/(hidden)
2024-11-15 12:30:29 INFO     Cookie expiry notification period: 7
2024-11-15 12:30:29 INFO     Download destination directory: /icloud
2024-11-15 12:30:29 INFO     Folder structure: {:%Y/%m}
2024-11-15 12:30:29 DEBUG    Directory permissions: 750
2024-11-15 12:30:29 DEBUG    File permissions: 640
2024-11-15 12:30:29 INFO     Keep Unicode: false
2024-11-15 12:30:29 INFO     Live Photo MOV Filename Policy: suffix
2024-11-15 12:30:29 INFO     File Match Policy: name-size-dedup-with-suffix
2024-11-15 12:30:29 INFO     Synchronisation interval: 86400
2024-11-15 12:30:29 INFO     Synchronisation delay (minutes): 1
2024-11-15 12:30:29 INFO     Set EXIF date/time: false
2024-11-15 12:30:29 INFO     Auto delete: true
2024-11-15 12:30:29 INFO     Delete after download: false
2024-11-15 12:30:29 INFO     Delete empty directories: false
2024-11-15 12:30:29 INFO     Photo size: original
2024-11-15 12:30:29 INFO     Align RAW: as-is
2024-11-15 12:30:29 INFO     Single pass mode: false
2024-11-15 12:30:29 INFO     Skip download check: true
2024-11-15 12:30:29 INFO     Skip live photos: false
2024-11-15 12:30:29 INFO     Number of most recently added photos to download: Download All Photos
2024-11-15 12:30:29 INFO     Downloading photos from: Download All Photos
2024-11-15 12:30:29 INFO     Stop downloading when prexisiting files count is: 10000
2024-11-15 12:30:29 INFO     Live photo size: original
2024-11-15 12:30:29 INFO     Skip videos: false
2024-11-15 12:30:29 INFO     Convert HEIC to JPEG: true
2024-11-15 12:30:29 DEBUG    JPEG conversion quality: 90
2024-11-15 12:30:29 INFO     Delete accompanying files (.JPG/.HEIC.MOV)
2024-11-15 12:30:29 WARNING   - This feature deletes files from your local disk. Please use with caution. I am not responsible for any data loss
2024-11-15 12:30:29 WARNING   - This feature cannot be used if the 'folder_structure' variable is set to 'none' and also, 'set_exif_datetime' must be 'False'
2024-11-15 12:30:29 WARNING   - These two settings will increase the chances of de-duplication happening, which could result in the wrong files being removed. Continuing in 2 minutes
2024-11-15 12:32:29 INFO     Downloading from: icloud.com
2024-11-15 12:32:29 INFO     Fake user agent for curl: Disabled
2024-11-15 12:32:29 INFO     Authentication domain: com
2024-11-15 12:32:29 DEBUG    Nextcloud upload: Disabled
2024-11-15 12:32:29 INFO     Ignore Synology extended attribute directories: Disabled
2024-11-15 12:32:29 DEBUG    Activated Python virtual environment for icloudpd
2024-11-15 12:32:29 INFO     Container initialisation complete
2024-11-15 12:32:29 INFO     Script launch parameters: --Initialise
2024-11-15 12:32:29 DEBUG    Group, users:100, already created
2024-11-15 12:32:29 DEBUG    User, sxxxxx:1027, already created
2024-11-15 12:32:29 DEBUG    Set owner and group on icloudpd temp directory
2024-11-15 12:32:29 DEBUG    Set owner and group on config directory
2024-11-15 12:32:29 INFO     Directory is writable: /config/python_keyring/
2024-11-15 12:32:29 DEBUG    Configure password
2024-11-15 12:32:29 DEBUG    Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Running in MAIN
Enter iCloud password for sxxxxx@axxxxx.co.uk: 
Bad username or password for sxxxxx@axxxxx.co.uk
Enter iCloud password for sxxxxx@axxxxx.co.uk: 
Bad username or password for sxxxxx@axxxxx.co.uk
Enter iCloud password for sxxxxx@axxxxx.co.uk: 
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 270, in authenticate
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: {
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
} (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyicloud_ipd/cmdline.py", line 258, in main_aux
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 280, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloud.py", line 5, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "pyicloud_ipd/cmdline.py", line 82, in main
  File "pyicloud_ipd/cmdline.py", line 337, in main_aux
RuntimeError: Bad username or password for sxxxxx@axxxxx.co.uk
[661] Failed to execute script 'icloud' due to unhandled exception!
2024-11-15 12:35:29 ERROR    Keyring file does not exist. Please try again

EDIT:

Before deleting (or after reinstating) the keyring file

2024-11-15 13:09:33 DEBUG    Generate MFA cookie using password stored in keyring file
2024-11-15 13:09:33 DEBUG    Authenticating...
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 270, in authenticate
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: {
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
} (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1183, in core
  File "icloudpd/authentication.py", line 53, in authenticate_
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 280, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[800] Failed to execute script 'icloudpd' due to unhandled exception!
2024-11-15 13:09:35 ERROR    Multifactor authentication information missing from cookie. Authentication has failed
2024-11-15 13:09:35 ERROR     - Was the correct password entered?
2024-11-15 13:09:35 ERROR     - Was the multifactor authentication code mistyped?
2024-11-15 13:09:35 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-11-15 13:09:35 INFO     Container initialisation complete

**Comment by syl779** [comment]
I have just recreated the container on a second NAS. I get the same error with the username/password

I have recreated it on he second NAS with one of the other users and I can enter the password fine and save it to file.

**Comment by syl779** [comment]
I got bored and changed the password. Now it works. I don't know what the problem was and likely will never find out. Just have to wait a year before I can change it back again now.
