### ISSUE TITLE
Files not getting downloaded

### ISSUE THREAD

**Issue by gregbert42** [boredazfcuk/docker-icloudpd#7]
Weird situation where it continues to recognize that there are files to download, but never seems to download anything. the directories get created, but no files appear. This had been working fine for a long time.
icloudpd, version 1.4.4

2020-02-09 08:33:51 INFO     Web cookie expires: 2020-02-28 @ 14:37:14
2020-02-09 08:33:51 INFO     Two factor authentication cookie expires: 2020-03-29 @ 14:37:37
2020-02-09 08:33:51 INFO     Syncronisation complete for usernamehere
2020-02-09 08:33:51 INFO     Next syncronisation at 14:33
2020-02-09 14:33:51 INFO     Check 2FA Cookie
2020-02-09 14:33:51 INFO     Cookie exists, check expiry date
2020-02-09 14:33:51 INFO     Valid two factor authentication cookie found. Days until expiration: 48
2020-02-09 14:33:51 INFO     Check download directory mounted correctly
2020-02-09 14:33:51 INFO     Check for new files...
2020-02-09 14:45:41 INFO     Check successful
2020-02-09 14:45:41 INFO     Check detected 72 files requiring download. Verifying list accuracy
2020-02-09 14:45:41 INFO     Ignoring 28 files which have already been downloaded
2020-02-09 14:45:41 INFO     New files detected: 44
2020-02-09 14:45:41 INFO     Starting download of 44 new files for user: usernamehere
2020-02-09 14:45:42 DEBUG    Authenticating...
2020-02-09 14:50:00 INFO     Web cookie expires: 2020-02-28 @ 14:37:14
2020-02-09 14:50:00 INFO     Two factor authentication cookie expires: 2020-03-29 @ 14:37:37
2020-02-09 14:50:00 INFO     Syncronisation complete for usernamehere
2020-02-09 14:50:00 INFO     Next syncronisation at 20:50
2020-02-09 20:50:00 INFO     Check 2FA Cookie
2020-02-09 20:50:00 INFO     Cookie exists, check expiry date
2020-02-09 20:50:00 INFO     Valid two factor authentication cookie found. Days until expiration: 48
2020-02-09 20:50:00 INFO     Check download directory mounted correctly
2020-02-09 20:50:00 INFO     Check for new files...
2020-02-09 21:01:47 INFO     Check successful
2020-02-09 21:01:47 INFO     Check detected 72 files requiring download. Verifying list accuracy
2020-02-09 21:01:47 INFO     Ignoring 28 files which have already been downloaded
2020-02-09 21:01:47 INFO     New files detected: 44
2020-02-09 21:01:47 INFO     Starting download of 44 new files for user: usernamehere
2020-02-09 21:01:48 DEBUG    Authenticating...
2020-02-09 21:06:07 INFO     Web cookie expires: 2020-02-28 @ 14:37:14
2020-02-09 21:06:07 INFO     Two factor authentication cookie expires: 2020-03-29 @ 14:37:37
2020-02-09 21:06:07 INFO     Syncronisation complete for usernamehere
2020-02-09 21:06:07 INFO     Next syncronisation at 03:06

**Comment by boredazfcuk** [comment]
Can you check to see if your container has a /tmp/icloudpd/icloudpd_sync_error.log log file?

This should contain any errors that are thrown by the icloudpd application.

**Comment by gregbert42** [comment]
Thanks. I didnt know about these. Yes it does. Looks like some file permission issue. will look into it simultaneously

check_exit_code  download_exit_code  icloudpd_check.log  icloudpd_check_error.log  icloudpd_sync.log  icloudpd_sync_error.log
/tmp/icloudpd # cat icloudpd_sync_error.log
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    load_entry_point('icloudpd==1.4.4', 'console_scripts', 'icloudpd')()
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.4.4-py3.8.egg/icloudpd/base.py", line 238, in main
  File "/usr/lib/python3.8/site-packages/icloudpd-1.4.4-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 223, in authenticate
    self.session.cookies.save()
  File "/usr/lib/python3.8/http/cookiejar.py", line 1890, in save
    with open(filename, "w") as f:
PermissionError: [Errno 13] Permission denied: '/config/usernamegmailcom'

**Comment by gregbert42** [comment]
ps. this file has permissions -rw-r--r--   not sure why its trying to write to it??

**Comment by boredazfcuk** [comment]
Pretty sure that's same as what I was seeing... Does the cookie file have the correct owner?

What about the /config directory it lives in?

**Comment by gregbert42** [comment]
remind me what the 'correct' owner is?
ive tried setting the file to 666 to see if that files it.

**Comment by boredazfcuk** [comment]
Well, my /config directory was owned by root, but I don't think that's correct.

Looking at the function that generates the 2FA cookie, it sets the owner of the /config directory, and any files in it to ${user}:${group}

These will be displayed in the logs as:
```
Local user: <your user here>
Local group: <your group here>
```

This means that it only confirms permissions at the point when the cookie is created/updated. I've added the /config directory to the function in the script which sets the owner and permissions at launch. I've also added a chown at the start of the sync, just to make sure.

I'm not sure why that file would suddenly change owner. It may be something on the host that affected it, or something in my launch script that changes it to root, but either way, it should be a bit more reliable now.

I've pushed the latest version of my iCloudPD container to here, which should trigger a DockerHub build... But my script which pushes to GitHub also pushes the latest versions of all my containers. DockeHub can take quite a while to build them all, so depending on the order it processes them, it could be a few hours before you can just docker pull boredazfcuk/icloudpd to get the new version.

Thanks.

**Comment by gregbert42** [comment]
Changing the permissions worked. And i think when i converted to the new update, i didnt change the ownership of the file to reflect the 'user' variable.. thank you

**Comment by boredazfcuk** [comment]
> Changing the permissions worked. And i think when i converted to the new update, i didnt change the ownership of the file to reflect the 'user' variable.. thank you

Changing the permissions worked, or the owner?

All but about 3 or 4 command in my script runs as root, so there shouldn't be any permissions issues for the most part.

It does run the sync process as the user specified in the $user variable, but if this account is set as the owner for everything in /config and /home/<user>/, then that shouldn't run into permissions errors either.

Are you sure it didn't start working because after you upgraded to the latest version, it set the owner on /config correctly? I've just changed my /config directory permissions to 700 and the file perms to 600 and it's pulled down 5 new photos fine.
