### ISSUE TITLE
"@" in password doesn´t work?

### ISSUE THREAD

**Issue by Bytechanger** [boredazfcuk/docker-icloudpd#719]
Hi,

I´m running this container for 2 icloud-accounts

First without an"@" in password runs well.
But on my second account with "@" in password, i get  this error:

`docker exec -it icloudpd_XX reauth.sh
2024-12-24 12:45:31 DEBUG    Authenticating...
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 278, in authenticate
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: {
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
} (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 753, in main
  File "icloudpd/base.py", line 1196, in core
  File "icloudpd/authentication.py", line 53, in authenticate_
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 281, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseExce                                         ption('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and passw                                         ord for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[744] Failed to execute script 'icloudpd' due to unhandled exception!
`

**Comment by boredazfcuk** [comment]
This is likely an issue with an upstream package would be be best to log here: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues
