### ISSUE TITLE
Cannot initialize - missing latest builds for amd64?

### ISSUE THREAD

**Issue by ZarK** [boredazfcuk/docker-icloudpd#87]
I'm having trouble getting through iCloud 2FA during Initialize. It seems like other have had similar issue recently and that the solution has been for them to update to latest.

However, to my knowledge, I'm on latest. This is the first time I'm trying icloudpd, so I downloaded boredazfcuk/icloudpd:latest from Docker Hub today. I cannot find the sha256 of the image I got on https://registry.hub.docker.com/r/boredazfcuk/icloudpd/tags?page=1&ordering=last_updated though, so not sure what's going on.

When running Initialize, I enter the apple password, then gets prompted for verification on my iPhone, and enter the number code.  However, there are exceptions in the log and 2FA is not actually setup or working.

Docker Inspect:
```
docker container inspect icloudpd
[
    {
        "Id": "4f5035887b52da03c0f8b87b6e86742db2a8e93dfad1a6300e431df49bb155f5",
        "Created": "2021-08-12T18:02:24.683069085Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "/usr/local/bin/sync-icloud.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 6677,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-08-12T19:02:10.616711379Z",
            "FinishedAt": "2021-08-12T19:02:10.008489436Z",
            "Health": {
                "Status": "starting",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2021-08-12T20:58:08.479958001+02:00",
                        "End": "2021-08-12T20:58:08.521405195+02:00",
                        "ExitCode": 1,
                        "Output": "Error: Cookie does not exist. Please generate new cookie\n"
                    },
                    {
                        "Start": "2021-08-12T20:59:08.771239487+02:00",
                        "End": "2021-08-12T20:59:08.803468727+02:00",
                        "ExitCode": 1,
                        "Output": "Error: Cookie does not exist. Please generate new cookie\n"
                    },
                    {
                        "Start": "2021-08-12T21:00:08.826512747+02:00",
                        "End": "2021-08-12T21:00:08.859684519+02:00",
                        "ExitCode": 1,
                        "Output": "Error: Cookie does not exist. Please generate new cookie\n"
                    },
                    {
                        "Start": "2021-08-12T21:01:08.929215541+02:00",
                        "End": "2021-08-12T21:01:08.966761624+02:00",
                        "ExitCode": 1,
                        "Output": "Error: Cookie does not exist. Please generate new cookie\n"
                    },
                    {
                        "Start": "2021-08-12T21:02:08.984096711+02:00",
                        "End": "2021-08-12T21:02:09.021234316+02:00",
                        "ExitCode": 1,
                        "Output": "Error: Cookie does not exist. Please generate new cookie\n"
                    }
                ]
            },
            "StartedTs": 1628794930,
            "FinishedTs": 1628794930
        },
        "Image": "sha256:05b1cd7f915c9023c82fe6f43fc7d2215431e1975dc8a04ec992cf6a4887f368",
        "ResolvConfPath": "/volume1/@docker/containers/4f5035887b52da03c0f8b87b6e86742db2a8e93dfad1a6300e431df49bb155f5/resolv.conf",
        "HostnamePath": "/volume1/@docker/containers/4f5035887b52da03c0f8b87b6e86742db2a8e93dfad1a6300e431df49bb155f5/hostname",
        "HostsPath": "/volume1/@docker/containers/4f5035887b52da03c0f8b87b6e86742db2a8e93dfad1a6300e431df49bb155f5/hosts",
        "LogPath": "/volume1/@docker/containers/4f5035887b52da03c0f8b87b6e86742db2a8e93dfad1a6300e431df49bb155f5/log.db",
        "Name": "/icloudpd",
        "RestartCount": 3,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
```

Docker Version:
```
docker version
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        b35e731
 Built:             Fri Jun 18 08:25:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.6
  Git commit:       e7f7c95
  Built:            Fri Jun 18 08:26:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        b1dc45ec561bd867c4805eee786caab7cc83acae
 runc:
  Version:          v1.0.0-rc93
  GitCommit:        89783e1862a2cc04647ab15b6e88a0af3d66fac3
 docker-init:
  Version:          0.19.0
  GitCommit:        12b6a20

```

Docker user:
```
ps -ef | grep dockerd
root     22228     1  0 Aug09 ?        00:08:24 /var/packages/Docker/target/usr/bin/dockerd --config-file /var/packages/Docker/etc/dockerd.json
root     27392 26386  0 20:54 pts/17   00:00:00 grep --color=auto dockerd
```

Log:
```
/ # /usr/local/bin/sync-icloud.sh --Initialise

2021-08-12 18:51:06 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2021-08-12 18:51:06 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/08/05_13:40 *****
2021-08-12 18:51:06 INFO     ***** /usr/local/bin/sync-icloud.sh hash: 88908a8613c3c14df5da9ade016ebd51 *****
2021-08-12 18:51:06 INFO     Alpine Linux 3.13.5
2021-08-12 18:51:06 INFO     Python version: 3.8.10
2021-08-12 18:51:06 INFO     icloudpd version: 1.7.2
2021-08-12 18:51:07 INFO     pyicloud-ipd version: 0.10.1
2021-08-12 18:51:07 INFO     Local user: ****man:1026
2021-08-12 18:51:07 INFO     Local group: admin****:101
2021-08-12 18:51:07 INFO     Force GID: False
2021-08-12 18:51:07 INFO     LAN IP Address: ***.***.0.3
2021-08-12 18:51:07 INFO     Apple ID: ****@****.com
2021-08-12 18:51:07 INFO     Authentication Type: 2FA
2021-08-12 18:51:07 INFO     Cookie path: /config/********com
2021-08-12 18:51:07 INFO     Cookie expiry notification period: 7
2021-08-12 18:51:07 INFO     Download destination directory: /iCloud
2021-08-12 18:51:07 INFO     Folder structure: {:%Y/%m}
2021-08-12 18:51:07 INFO     Directory permissions: 750
2021-08-12 18:51:07 INFO     File permissions: 640
2021-08-12 18:51:07 INFO     Synchronisation interval: 86400
2021-08-12 18:51:07 INFO     Synchronisation delay (minutes): 0
2021-08-12 18:51:07 INFO     Time zone: CEST
2021-08-12 18:51:07 INFO     Set EXIF date/time: False
2021-08-12 18:51:07 INFO     Auto delete: False
2021-08-12 18:51:07 INFO     Photo size: original
2021-08-12 18:51:07 INFO     Skip download check: False
2021-08-12 18:51:07 INFO     Skip live photos: False
2021-08-12 18:51:07 INFO     Number of most recently added photos to download: Download All Photos
2021-08-12 18:51:07 INFO     Stop downloading when prexisiting files count is: Download All Photos
2021-08-12 18:51:07 INFO     Live photo size: original
2021-08-12 18:51:07 INFO     Skip videos: False
2021-08-12 18:51:07 INFO     Convert HEIC to JPEG: False
2021-08-12 18:51:07 INFO     Script launch parameters: --Initialise
2021-08-12 18:51:07 INFO     Group, admin****:101, already created
2021-08-12 18:51:07 INFO     User, ****man:1026, already created
2021-08-12 18:51:07 INFO     Correct owner on config directory, if required
2021-08-12 18:51:07 INFO     Correct group on config directory, if required
2021-08-12 18:51:07 INFO     Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for ****@****.com:
Save password in keyring?  [y/N]: y
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3.8/site-packages/keyrings/alt/file_base.py", line 93, in set_password
    self._ensure_file_path()
  File "/usr/lib/python3.8/site-packages/keyrings/alt/file_base.py", line 115, in _ensure_file_path
    os.makedirs(storage_root)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/****man/.local/share/python_keyring'
2021-08-12 18:51:42 INFO     Correct owner on config directory, if required
2021-08-12 18:51:42 INFO     Correct group on config directory, if required
2021-08-12 18:51:42 INFO     Generate 2FA cookie with password:
2021-08-12 18:51:42 INFO     Check for new files using password stored in keyring file.
iCloud Password:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for ****@****.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2021-08-12 18:51:46 INFO     Two factor authentication cookie generated. Sync should now be successful.
```

**Comment by boredazfcuk** [comment]
Sorry, I won’t be able to investigate this thoroughly as I won’t have access to a laptop for another week or so.

There is an error in your logs though:
`FileExistsError: [Errno 17] File exists: '/home/****man/.local/share/python_keyring'`
Can you just delete that file and try again. It seems that it doesn’t like it if that file already exists. I’ll have to look into this more when I get time next week.

Thanks.

**Comment by ZarK** [comment]
Hi,

No worries, I'm just updating here meanwhile :) I've tried deleting the file, changing permissions, and run the script as the user. None of them works.

The file is a symbolic link to /config:
```
/ # ls -la /home/****man/.local/share/
total 4
drwxr-xr-x 1 root root 28 Aug 12 18:14 .
drwxr-xr-x 1 root root 10 Aug 12 18:14 ..
lrwxrwxrwx 1 root root 23 Aug 12 18:14 python_keyring -> /config/python_keyring/

/ # ls -la /config/
total 0
d--------- 1 ****man admin****  28 Aug 12 18:14 .
drwxr-xr-x 1 root     root           158 Aug 12 18:13 ..
d--------- 1 ****man admin****   0 Aug 12 18:14 python_keyring
```

I've tried deleting them and run, with the same error.
I also tried `su ****man` and ran the script, so ****man was the owner:
```
/ # ls -la /home/****man/.local/share/
total 4
drwxr-sr-x 1 ****man admin**** 28 Aug 20 09:43 .
drwxr-sr-x 1 ****man admin**** 10 Aug 20 09:43 ..
lrwxrwxrwx 1 ****man admin**** 23 Aug 20 09:43 python_keyring -> /config/python_keyring/

/ # ls -la /config/
total 0
d--------- 1 ****man admin****  28 Aug 20 09:44 .
drwxr-xr-x 1 root     root           158 Aug 12 18:13 ..
d--------- 1 ****man admin****   0 Aug 20 09:44 python_keyring
```

As far as I can see, I still get the same issue. Posting a new log here just in case:
```
/ # /usr/local/bin/sync-icloud.sh --Initialise

2021-08-20 09:14:16 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2021-08-20 09:14:16 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/08/05_13:40 *****
2021-08-20 09:14:16 INFO     ***** /usr/local/bin/sync-icloud.sh hash: 88908a8613c3c14df5da9ade016ebd51 *****
2021-08-20 09:14:16 INFO     Alpine Linux 3.13.5
2021-08-20 09:14:16 INFO     Python version: 3.8.10
2021-08-20 09:14:16 INFO     icloudpd version: 1.7.2
2021-08-20 09:14:16 INFO     pyicloud-ipd version: 0.10.1
2021-08-20 09:14:17 INFO     Local user: ****man:1026
2021-08-20 09:14:17 INFO     Local group: admin****:101
2021-08-20 09:14:17 INFO     Force GID: False
2021-08-20 09:14:17 INFO     LAN IP Address: 172.17.0.10
2021-08-20 09:14:17 INFO     Apple ID: ****@****.com
2021-08-20 09:14:17 INFO     Authentication Type: 2FA
2021-08-20 09:14:17 INFO     Cookie path: /config/********com
2021-08-20 09:14:17 INFO     Cookie expiry notification period: 7
2021-08-20 09:14:17 INFO     Download destination directory: /iCloud
2021-08-20 09:14:17 INFO     Folder structure: {:%Y/%m}
2021-08-20 09:14:17 INFO     Directory permissions: 750
2021-08-20 09:14:17 INFO     File permissions: 640
2021-08-20 09:14:17 INFO     Synchronisation interval: 86400
2021-08-20 09:14:17 INFO     Synchronisation delay (minutes): 0
2021-08-20 09:14:17 INFO     Time zone: CEST
2021-08-20 09:14:17 INFO     Set EXIF date/time: False
2021-08-20 09:14:17 INFO     Auto delete: False
2021-08-20 09:14:17 INFO     Photo size: original
2021-08-20 09:14:17 INFO     Skip download check: False
2021-08-20 09:14:17 INFO     Skip live photos: False
2021-08-20 09:14:17 INFO     Number of most recently added photos to download: Download All Photos
2021-08-20 09:14:17 INFO     Stop downloading when prexisiting files count is: Download All Photos
2021-08-20 09:14:17 INFO     Live photo size: original
2021-08-20 09:14:17 INFO     Skip videos: False
2021-08-20 09:14:17 INFO     Convert HEIC to JPEG: False
2021-08-20 09:14:17 INFO     Script launch parameters: --Initialise
2021-08-20 09:14:17 INFO     Group, admin****:101, already created
2021-08-20 09:14:17 INFO     User, ****man:1026, already created
2021-08-20 09:14:17 INFO     Correct owner on config directory, if required
2021-08-20 09:14:17 INFO     Correct group on config directory, if required
2021-08-20 09:14:17 INFO     Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for ****@****.com:
Save password in keyring?  [y/N]: y
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3.8/site-packages/keyrings/alt/file_base.py", line 93, in set_password
    self._ensure_file_path()
  File "/usr/lib/python3.8/site-packages/keyrings/alt/file_base.py", line 115, in _ensure_file_path
    os.makedirs(storage_root)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/****man/.local/share/python_keyring'
2021-08-20 09:14:57 INFO     Correct owner on config directory, if required
2021-08-20 09:14:57 INFO     Correct group on config directory, if required
2021-08-20 09:14:57 INFO     Generate 2FA cookie with password:
2021-08-20 09:14:57 INFO     Check for new files using password stored in keyring file.
iCloud Password:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for ****@****.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 33, in <module>
    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2021-08-20 09:15:07 INFO     Two factor authentication cookie generated. Sync should now be successful.
```

**Comment by boredazfcuk** [comment]
Sorry, it’s this file you need to remove:
`/config/python_keyring/keyring_pass.cfg`

This error does remind me of one that was logged a while back. For some reason, the underlying dependency won’t let you overwrite a pre-existing keyring file. It has to be removed before attempting to save the password again. I’ll need to check that the `--Initialise` command does this, when I return.

**Comment by ZarK** [comment]
I've never seen a file inside they` python_keyring `folder, and I also tried deleting the whole folder, so neither the folder nor the file existed before running Initialize. 

Is there some other file permission issue that could be in the /config folder I mapped to? It does seem correct to me - when I run `id` on the` python_keyring` folder from my nas, I get this, with matches with my config:

```
sh-4.3$ id
uid=1026(****man) gid=100(users) groups=100(users),101(admin****)
```

**Comment by boredazfcuk** [comment]
The script sets the owner and group on the `/config` directory (and it’s subdirectories) right before it attempts to add the password to the keyring.

Your UID being 1026 and GID being 101 gives you owner and admin group, which should be highest they can be.

Can you fire up the container, connect into it and just `chmod 777 -R /config /home/*****man/.local/share/python_keyring` then see what happens? If it works, then there’s defo a permissions issue that needs fixing.

**Comment by boredazfcuk** [comment]
The script sets the owner and group on the `/config` directory (and it’s subdirectories) right before it attempts to add the password to the keyring.

Your UID being 1026 and GID being 101 gives you owner and admin group, which should be highest they can be.

Can you fire up the container, connect into it and just `chmod 777 -R /config /home/*****man/.local/share/python_keyring` then see what happens? If it works, then there’s defo a permissions issue that needs fixing.

**Comment by ZarK** [comment]
Hurray, that worked :)

**Comment by boredazfcuk** [comment]
That’s not a good thing though. 777 permissions are bad as they give all other user accounts read/write permissions, don’t want that with a keyring file.

IIRC it will reset the permissions at some point too… It might be on the next sync, or the next restart, can’t remember which, off the top of my head.

I’ll have a proper look at it when I get back off holiday.

Thanks.

**Comment by boredazfcuk** [comment]
P.S. Your first sync can take a long time if you have a lot of photos. Just forget about it until the morning, or until it sends you a notification after it finishes downloading everything (if you have notifications enabled).

**Comment by ZarK** [comment]
Thanks so much for the help, really appreciate it. Took only an hour or so to get ready with 100k images, well on the way of downloading already. It will be a relief to finally have control and some extra backups of the iCloud photos.

**Comment by boredazfcuk** [comment]
No worries. I’m going to re-open this though, as a reminder to look at it when I get back off holiday next week.

I’m thinking there must be a UID/GID mismatch happening somewhere. Might be better if I just run everything as the native account in the container (instead of using `su` to change the user) then fix up permissions after the download with a `find/chown`

**Comment by boredazfcuk** [comment]
Can you connect to your container and run `ps` and post what you get?

You should see the script running as root, like this:
```
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 {sync-icloud.sh} /bin/ash /usr/local/bin/sync-icloud.sh
13194 root      0:00 sleep 43163
17156 root      0:00 /bin/ash
17164 root      0:00 ps
```
But if your Docker app is running containers non-privileged by default, you may see a different user like this:
```
/ $ ps
PID   USER     TIME  COMMAND
    1 1011      0:00 {sync-icloud.sh} /bin/ash /usr/local/bin/sync-icloud.sh
13194 1011      0:00 sleep 43163
17156 1011      0:00 /bin/ash
17164 1011      0:00 ps
```

If that user is mismatched with the **user_id** variable, then it could be responsible for the errors your seeing.

**Comment by boredazfcuk** [comment]
Hi,

I've had a look at the code which handles this and I've made a change so that the owner/permissions setting function runs prior to setting the password. I've added this in for good meansure, hopefully that should fix the permissions issue you were running into.

I'm guessing it was a permissions issue at some point in the path `/home/${user}/.local/share/python_keyring` which was preventing it from accessing the `kerying_pass.cfg` file which is linked from that previous directory, to `/config/python_keyring`.

Any more issues, just re-open the ticket. Thanks.

**Comment by ZarK** [comment]
Hi!

I'm back _shrug_

This run perfectly for a long while. As expected, cookie expired, but now I'm stuck again trying to authenticate.

icloudpd says coockie expired and to run script with --Initialize, just like the Readme also says. However, when I run script with --Initialize it says it is ignoring the argument and to please not run the script with --Initialize.

I've tried to make sure I'm on latest version, tried the chmod 777 etc. Tried both with docker exec and by running it from inside the docker container.

**Comment by ZarK** [comment]
It seems my problem may be that docker for some reason refuse to pull the latest image. This is what I get.

```
ash-4.4# docker pull boredazfcuk/icloudpd:latest
latest: Pulling from boredazfcuk/icloudpd
Digest: sha256:d153f02a62ea8a1c4563b6a57ab23c60df607cf33d240bd06967190aef824eb1
Status: Image is up to date for boredazfcuk/icloudpd:latest
docker.io/boredazfcuk/icloudpd:latest
```

**Comment by boredazfcuk** [comment]
> icloudpd says coockie expired and to run script with --Initialize, just like the Readme also says. However, when I run script with --Initialize it says it is ignoring the argument and to please not run the script with --Initialize.

Not quite, it says to run the script with `--Initialise` and it's ignoring your parameter because it doesn't recognise your spelling. 

>It seems my problem may be that docker for some reason refuse to pull the latest image. This is what I get.

It does say that it's up to date, but I'm not sure what the latest digest it... It doesn't help that I've just pushed a new version to Dockerhub either.

One of my containers has started notifying me every five minutes that it only has 6 days remaining before the 2FA cookie expired. My auto-heal container was restarting it because an expiry date less than 7 days away changes the health status to `unhealthy`.

**Comment by ZarK** [comment]
> > icloudpd says coockie expired and to run script with --Initialize, just like the Readme also says. However, when I run script with --Initialize it says it is ignoring the argument and to please not run the script with --Initialize.
> 
> Not quite, it says to run the script with `--Initialise` and it's ignoring your parameter because it doesn't recognise your spelling.
> 
Oh lol that is just funny, I could have sworn I copied the command from either my previous time (copied from above in this thread) or from the output example in the script. I had tried it with both s and z, and with and without capital... of the z variant. Of course work as a charm with both correct capitalization and British spelling.

**Comment by boredazfcuk** [comment]
I'm guessing you'll not be the only person to be caught out by it, so I've just pushed a new version which removes the capitalisation requirements. I've actually been thinking about that one for a while to be honest, as it reduces potential problems. I've also changed it so it accepts initialise spelled with a "z", while I was at it.
